"""Task 021 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('e0', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('rm1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIC/AAAAAAAAgD8AAABAAABAQAAAgEAAAKBAAADAQAAA4EAAAABBAAAQQQAAIEEAADBBAABAQQAAUEEAAGBBAABwQQAAgEEAAIhBAACQQQAAmEEAAKBBAACoQQAAsEEAALhBAADAQQAAyEEAANBBAADYQQAA4EE=')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'e0', 'e0'], ['bg'], equation='bchw,h,w->bc'),
        helper.make_node('Einsum', ['input', 'e0'], ['ht'], equation='bchw,w->b'),
        helper.make_node('Einsum', ['input', 'bg', 'e0'], ['hb'], equation='bchw,bc,w->b'),
        helper.make_node('Sub', ['ht', 'hb'], ['nh']),
        helper.make_node('Einsum', ['input', 'e0'], ['wt'], equation='bchw,h->b'),
        helper.make_node('Einsum', ['input', 'bg', 'e0'], ['wb'], equation='bchw,bc,h->b'),
        helper.make_node('Sub', ['wt', 'wb'], ['nv']),
        helper.make_node('Less', ['rm1', 'nh'], ['rl']),
        helper.make_node('Less', ['rm1', 'nv'], ['cl']),
        helper.make_node('Cast', ['rl'], ['rf'], to=10),
        helper.make_node('Cast', ['cl'], ['cf'], to=10),
        helper.make_node('Cast', ['bg'], ['bh'], to=10),
        helper.make_node('Einsum', ['bh', 'rf', 'cf'], ['output'], equation='bc,r,s->bcrs'),
    ]
    value_infos = [
    ]
    return model('task021_live_exact', nodes, inits, output_dtype=10, opset=13, value_infos=value_infos)
