"""Task 184 — exact source reconstruction of current live graph.

Generated by tools/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, node, tensor


def build(task):
    inits = [
        tensor('channel_mask', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/')),
        tensor('occ_scale', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA7')),
        tensor('occ_zp', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAr/')),
        tensor('basis_zp', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('axis_prefix_q', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsIDEsIDI0KSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('target_basis', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsIDMwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAADAAABAwAAAgL8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIA/AACAPwAAgD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('selector_cycle', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsIDIpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAKDAAABQwQAAQEAAAOBA')),
    ]
    nodes = [
        node('Einsum', ['input', 'channel_mask'], ['row_count'], attrs=[('equation', 'nchw,ac->nah')]),
        node('QuantizeLinear', ['row_count', 'occ_scale'], ['row_u8']),
        node('QLinearConv', ['row_u8', 'occ_scale', 'occ_zp', 'axis_prefix_q', 'occ_scale', 'basis_zp', 'occ_scale', 'basis_zp'], ['row_basis_u8'], attrs=[('kernel_shape', [24]), ('pads', [23, 0])]),
        node('Einsum', ['input', 'channel_mask'], ['col_count'], attrs=[('equation', 'nchw,ac->naw')]),
        node('QuantizeLinear', ['col_count', 'occ_scale'], ['col_u8']),
        node('QLinearConv', ['col_u8', 'occ_scale', 'occ_zp', 'axis_prefix_q', 'occ_scale', 'basis_zp', 'occ_scale', 'basis_zp'], ['col_basis_u8'], attrs=[('kernel_shape', [24]), ('pads', [23, 0])]),
        node('Cast', ['col_basis_u8'], ['col_basis'], attrs=[('to', 1)]),
        node('Cast', ['row_basis_u8'], ['row_basis'], attrs=[('to', 1)]),
        node('Einsum', ['input', 'channel_mask', 'row_basis', 'row_basis', 'col_basis', 'col_basis', 'target_basis', 'selector_cycle', 'target_basis', 'target_basis', 'selector_cycle', 'target_basis'], ['output'], attrs=[('equation', 'nchw,qc,nrh,nsh,nkw,nlw,rf,st,tf,kz,lu,uz->ncfz')]),
    ]
    value_infos = [
        helper.make_tensor_value_info('row_count', 1, [1, 1, 30]),
        helper.make_tensor_value_info('col_count', 1, [1, 1, 30]),
        helper.make_tensor_value_info('row_u8', 2, [1, 1, 30]),
        helper.make_tensor_value_info('col_u8', 2, [1, 1, 30]),
        helper.make_tensor_value_info('row_basis_u8', 2, [1, 2, 30]),
        helper.make_tensor_value_info('col_basis_u8', 2, [1, 2, 30]),
        helper.make_tensor_value_info('row_basis', 1, [1, 2, 30]),
        helper.make_tensor_value_info('col_basis', 1, [1, 2, 30]),
    ]
    return model('task184', nodes, inits, output_dtype=1, opset=18, value_infos=value_infos, ir_version=10)
