"""Task 381 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
import numpy as np
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('red8_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAA=')),
        tensor('red8_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAAkAAAAAAAAACgAAAAAAAAA=')),
        tensor('axes_chw', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAA=')),
        tensor('pads_output', np.array([1, 0, 21, 20], dtype=np.int64)),
        tensor('pad_axes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAMAAAAAAAAA')),
        tensor('maroon9', np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=np.float32).reshape(1, 10, 1, 1)),
        tensor('powers_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AAAAQAAAgEAAAABBAACAQQAAAEIAAIBCAAAAQwAAgEMAAABE')),
        tensor('powers_u16', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPHUyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDEwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAIABAAIABAAIABAAIAAAAEAAg==')),
        tensor('next_powers_u16', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPHUyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDEwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAQACAAQACAAQACAAAABAAIABA==')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'red8_starts', 'red8_ends', 'axes_chw'], ['red8_f']),
        helper.make_node('MatMul', ['red8_f', 'powers_f'], ['code_f']),
        helper.make_node('Cast', ['code_f'], ['code'], to=4),
        helper.make_node('GreaterOrEqual', ['code', 'powers_u16'], ['right_seen']),
        helper.make_node('Mod', ['code', 'next_powers_u16'], ['lower_bits']),
        helper.make_node('Cast', ['lower_bits'], ['left_seen'], to=9),
        helper.make_node('Cast', ['red8_f'], ['red8'], to=9),
        helper.make_node('And', ['left_seen', 'right_seen'], ['span']),
        helper.make_node('Not', ['red8'], ['not_red8']),
        helper.make_node('And', ['span', 'not_red8'], ['maroon8']),
        helper.make_node('Pad', ['maroon8', 'pads_output', '', 'pad_axes'], ['maroon30'], mode='constant'),
        helper.make_node('Where', ['maroon30', 'maroon9', 'input'], ['output']),
    ]
    value_infos = [
        helper.make_tensor_value_info('red8_f', 1, [1, 1, 8, 10]),
        helper.make_tensor_value_info('code_f', 1, [1, 1, 8, 1]),
        helper.make_tensor_value_info('code', 4, [1, 1, 8, 1]),
        helper.make_tensor_value_info('right_seen', 9, [1, 1, 8, 10]),
        helper.make_tensor_value_info('lower_bits', 4, [1, 1, 8, 10]),
        helper.make_tensor_value_info('left_seen', 9, [1, 1, 8, 10]),
        helper.make_tensor_value_info('red8', 9, [1, 1, 8, 10]),
        helper.make_tensor_value_info('span', 9, [1, 1, 8, 10]),
        helper.make_tensor_value_info('not_red8', 9, [1, 1, 8, 10]),
        helper.make_tensor_value_info('maroon8', 9, [1, 1, 8, 10]),
        helper.make_tensor_value_info('maroon30', 9, [1, 1, 30, 30]),
    ]
    return model('task381_live_exact', nodes, inits, output_dtype=1, opset=18, value_infos=value_infos)
