"""Task 245 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('axes3', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAA=')),
        tensor('s_black', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('e_black', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAoAAAAAAAAACgAAAAAAAAA=')),
        tensor('s_red', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('e_red', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAAoAAAAAAAAACgAAAAAAAAA=')),
        tensor('s_green', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('e_green', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoEAAAAAAAAAAoAAAAAAAAACgAAAAAAAAA=')),
        tensor('vec_m1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAr/////AAAAAAEAAAACAAAAAwAAAAQAAAAFAAAABgAAAAcAAAAIAAAA')),
        tensor('false', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEwLCAxMCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA')),
        tensor('pad_pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAUAAAAAAAAABQAAAAAAAAA')),
        tensor('ax2', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAA==')),
        tensor('ax3', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAA==')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 's_black', 'e_black', 'axes3'], ['black_f']),
        helper.make_node('Slice', ['input', 's_red', 'e_red', 'axes3'], ['red_f']),
        helper.make_node('Slice', ['input', 's_green', 'e_green', 'axes3'], ['green_f']),
        helper.make_node('Cast', ['black_f'], ['black_u'], to=2),
        helper.make_node('Cast', ['red_f'], ['red_u'], to=2),
        helper.make_node('Cast', ['green_f'], ['green_u'], to=2),
        helper.make_node('ReduceMax', ['red_u', 'ax3'], ['red_rows'], keepdims=0),
        helper.make_node('ReduceMax', ['red_u', 'ax2'], ['red_cols'], keepdims=0),
        helper.make_node('ReduceMax', ['green_u', 'ax3'], ['green_rows'], keepdims=0),
        helper.make_node('ReduceMax', ['green_u', 'ax2'], ['green_cols'], keepdims=0),
        helper.make_node('ArgMax', ['red_rows'], ['rr'], axis=2, keepdims=0),
        helper.make_node('ArgMax', ['red_cols'], ['rc'], axis=2, keepdims=0),
        helper.make_node('ArgMax', ['green_rows'], ['gr'], axis=2, keepdims=0),
        helper.make_node('ArgMax', ['green_cols'], ['gc'], axis=2, keepdims=0),
        helper.make_node('Sub', ['gr', 'rr'], ['dr0']),
        helper.make_node('Sub', ['gc', 'rc'], ['dc0']),
        helper.make_node('Cast', ['dr0'], ['dr0i'], to=6),
        helper.make_node('Cast', ['dc0'], ['dc0i'], to=6),
        helper.make_node('Squeeze', ['dr0i'], ['dr0s']),
        helper.make_node('Squeeze', ['dc0i'], ['dc0s']),
        helper.make_node('Sub', ['vec_m1', 'dr0s'], ['src_r']),
        helper.make_node('Sub', ['vec_m1', 'dc0s'], ['src_c']),
        helper.make_node('Gather', ['red_u', 'src_r'], ['red_rs'], axis=2),
        helper.make_node('Gather', ['red_rs', 'src_c'], ['red_new'], axis=3),
        helper.make_node('BitwiseOr', ['black_u', 'red_u'], ['old_occ']),
        helper.make_node('BitwiseXor', ['old_occ', 'red_new'], ['black_out']),
        helper.make_node('Concat', ['black_out', 'false', 'red_new', 'green_u'], ['out4'], axis=1),
        helper.make_node('Pad', ['out4', 'pad_pads'], ['output'], mode='constant'),
    ]
    value_infos = [
    ]
    return model('task245_live_exact', nodes, inits, output_dtype=2, opset=18, value_infos=value_infos)
