"""task209 candidate — plane-collapse rebuild of the live stamp/vote solver.

Same algorithm as src/custom/task209.py (exact on all generator-reachable
inputs), but with the grader-counted intermediate planes collapsed:
  - all row/col bounds (yellow bbox, key extent, template anchors) come from
    multi-operand Einsum contractions against the FREE 'input' (walk-einsum /
    free-input-operand mechanism): only [30] f32 profiles are counted.
  - S (magnification) detection via spread = max + (9 - min) with sentinel
    Where-masking and a global MaxPool, killing min/uniform/valid/fp16 planes.
  - the magnified stamp source is a separable per-row/per-col two-stage Gather
    (kills the [20,20] int32 flat-index plane).
  - per-axis Where masking replaces several [20,20] And planes.
"""
import numpy as np
from onnx import TensorProto, helper
from ._exact import model, tensor


def build(task):
    i32 = np.int32
    i64 = np.int64
    u8 = np.uint8
    f32 = np.float32

    sel4 = np.zeros((1, 10), dtype=f32); sel4[0, 4] = 1.0
    selo = np.zeros((1, 10), dtype=f32)
    for c in (1, 2, 3, 8):
        selo[0, c] = 1.0
    # 11x11 crop-read kernel: out[y,x] = sum_c c*input[c,y,x], valid conv
    # 30->20 (kernel anchored at (0,0)); reads label directly at 20x20.
    w11 = np.zeros((1, 10, 11, 11), dtype=f32)
    w11[0, :, 0, 0] = np.arange(10, dtype=f32)

    inits = [
        tensor('W11', w11),
        tensor('SEL4', sel4),
        tensor('SELO', selo),
        tensor('IOTA', np.arange(30, dtype=i32)),
        tensor('ROW', np.arange(20, dtype=i32).reshape(1, 1, 20, 1)),
        tensor('COL', np.arange(20, dtype=i32).reshape(1, 1, 1, 20)),
        tensor('ROW_EQ0', (np.arange(20) == 0).reshape(1, 1, 20, 1)),
        tensor('COL_EQ0', (np.arange(20) == 0).reshape(1, 1, 1, 20)),
        tensor('DR', np.arange(3, dtype=i32).reshape(1, 1, 3, 1)),
        tensor('DC', np.arange(5, dtype=i32).reshape(1, 1, 1, 5)),
        tensor('KSCORE', np.arange(15, dtype=i32).reshape(1, 1, 3, 5)),
        tensor('LAB10', np.arange(10, dtype=u8).reshape(1, 10, 1, 1)),
        tensor('BIG', np.asarray(9999, dtype=i32)),
        tensor('M1I', np.asarray(-1, dtype=i32)),
        tensor('Z_I', np.asarray(0, dtype=i32)),
        tensor('ONE_I', np.asarray(1, dtype=i32)),
        tensor('TWO_I', np.asarray(2, dtype=i32)),
        tensor('THREE_I', np.asarray(3, dtype=i32)),
        tensor('FOUR_I', np.asarray(4, dtype=i32)),
        tensor('C19', np.asarray(19, dtype=i32)),
        tensor('S20', np.asarray(20, dtype=i32)),
        tensor('HALF', np.asarray(0.5, dtype=f32)),
        tensor('Z_U8', np.asarray(0, dtype=u8)),
        tensor('FOUR_U8', np.asarray(4, dtype=u8)),
        tensor('NINE_U8', np.asarray(9, dtype=u8)),
        tensor('NEG_U8', np.asarray(255, dtype=u8)),
        tensor('QS', np.asarray(1.0, dtype=f32)),
        tensor('BIAS1', np.asarray([1], dtype=i32)),
        tensor('PADU', np.asarray([0, 0, 1, 0, 0, 0, -1, 0], dtype=i64)),
        tensor('PADL', np.asarray([0, 0, 0, 1, 0, 0, 0, -1], dtype=i64)),
        tensor('PADF', np.asarray([0, 0, 0, 0, 0, 0, 10, 10], dtype=i64)),
        tensor('SH3', np.asarray([3], dtype=i64)),
        tensor('SH5', np.asarray([5], dtype=i64)),
        tensor('SH15', np.asarray([15], dtype=i64)),
        tensor('SH20', np.asarray([20], dtype=i64)),
        tensor('SH400', np.asarray([400], dtype=i64)),
    ]

    nodes = [
        # ---- label read (valid 11x11 conv crops 30->20 in the op) ----
        helper.make_node('Conv', ['input', 'W11'], ['lab_f32']),
        helper.make_node('Cast', ['lab_f32'], ['lab'], to=TensorProto.UINT8),
        # ---- yellow bbox from free-input einsum profiles ----
        helper.make_node('Einsum', ['input', 'SEL4'], ['p4r'], equation='bchw,bc->h'),
        helper.make_node('Einsum', ['input', 'SEL4'], ['p4c'], equation='bchw,bc->w'),
        helper.make_node('Greater', ['p4r', 'HALF'], ['has4r']),
        helper.make_node('Greater', ['p4c', 'HALF'], ['has4c']),
        helper.make_node('Where', ['has4r', 'IOTA', 'BIG'], ['w4r1']),
        helper.make_node('ReduceMin', ['w4r1'], ['r_top'], keepdims=0),
        helper.make_node('Where', ['has4r', 'IOTA', 'M1I'], ['w4r2']),
        helper.make_node('ReduceMax', ['w4r2'], ['r_bot'], keepdims=0),
        helper.make_node('Where', ['has4c', 'IOTA', 'BIG'], ['w4c1']),
        helper.make_node('ReduceMin', ['w4c1'], ['c_left'], keepdims=0),
        helper.make_node('Where', ['has4c', 'IOTA', 'M1I'], ['w4c2']),
        helper.make_node('ReduceMax', ['w4c2'], ['c_right'], keepdims=0),
        helper.make_node('Sub', ['r_bot', 'r_top'], ['OHm1']),
        helper.make_node('Sub', ['c_right', 'c_left'], ['OWm1']),
        # ---- in-bbox indicator vectors (30-long f32 for einsum) ----
        helper.make_node('GreaterOrEqual', ['IOTA', 'r_top'], ['ger']),
        helper.make_node('LessOrEqual', ['IOTA', 'r_bot'], ['ler']),
        helper.make_node('And', ['ger', 'ler'], ['inr_b']),
        helper.make_node('Cast', ['inr_b'], ['inr_f'], to=TensorProto.FLOAT),
        helper.make_node('GreaterOrEqual', ['IOTA', 'c_left'], ['gec']),
        helper.make_node('LessOrEqual', ['IOTA', 'c_right'], ['lec']),
        helper.make_node('And', ['gec', 'lec'], ['inc_b']),
        helper.make_node('Cast', ['inc_b'], ['inc_f'], to=TensorProto.FLOAT),
        # 20-grid strict-interior plane (for S-detect masking; shown blocks
        # are provably strictly interior: irow,icol >= 1, end <= tall-2)
        helper.make_node('Greater', ['ROW', 'r_top'], ['rge']),
        helper.make_node('Less', ['ROW', 'r_bot'], ['rle']),
        helper.make_node('And', ['rge', 'rle'], ['row_in']),
        helper.make_node('Greater', ['COL', 'c_left'], ['cge']),
        helper.make_node('Less', ['COL', 'c_right'], ['cle']),
        helper.make_node('And', ['cge', 'cle'], ['col_in']),
        helper.make_node('And', ['row_in', 'col_in'], ['inside_b']),
        # ---- sprite/key + template bounds from einsum profiles ----
        helper.make_node('Einsum', ['input', 'SELO'], ['por'], equation='bchw,bc->h'),
        helper.make_node('Einsum', ['input', 'SELO'], ['poc'], equation='bchw,bc->w'),
        helper.make_node('Einsum', ['input', 'SELO', 'inc_f'], ['poir'], equation='bchw,bc,w->h'),
        helper.make_node('Einsum', ['input', 'SELO', 'inr_f'], ['poic'], equation='bchw,bc,h->w'),
        helper.make_node('Mul', ['inr_f', 'poir'], ['tmplr']),
        helper.make_node('Mul', ['inc_f', 'poic'], ['tmplc']),
        helper.make_node('Sub', ['por', 'tmplr'], ['keyr']),
        helper.make_node('Sub', ['poc', 'tmplc'], ['keyc']),
        helper.make_node('Greater', ['tmplr', 'HALF'], ['hastr']),
        helper.make_node('Where', ['hastr', 'IOTA', 'BIG'], ['wtr']),
        helper.make_node('ReduceMin', ['wtr'], ['tr_anchor'], keepdims=0),
        helper.make_node('Greater', ['tmplc', 'HALF'], ['hastc']),
        helper.make_node('Where', ['hastc', 'IOTA', 'BIG'], ['wtc']),
        helper.make_node('ReduceMin', ['wtc'], ['tc_anchor'], keepdims=0),
        helper.make_node('Greater', ['keyr', 'HALF'], ['haskr']),
        helper.make_node('Where', ['haskr', 'IOTA', 'BIG'], ['wkr1']),
        helper.make_node('ReduceMin', ['wkr1'], ['kr_top'], keepdims=0),
        helper.make_node('Where', ['haskr', 'IOTA', 'M1I'], ['wkr2']),
        helper.make_node('ReduceMax', ['wkr2'], ['kr_bot'], keepdims=0),
        helper.make_node('Greater', ['keyc', 'HALF'], ['haskc']),
        helper.make_node('Where', ['haskc', 'IOTA', 'BIG'], ['wkc1']),
        helper.make_node('ReduceMin', ['wkc1'], ['kc_left'], keepdims=0),
        helper.make_node('Where', ['haskc', 'IOTA', 'M1I'], ['wkc2']),
        helper.make_node('ReduceMax', ['wkc2'], ['kc_right'], keepdims=0),
        # ---- S (magnification) detection: spread + sentinel masking ----
        helper.make_node('Sub', ['NINE_U8', 'lab'], ['inv']),
        helper.make_node('MaxPool', ['lab'], ['mx3'], kernel_shape=[3, 3], pads=[0, 0, 2, 2], strides=[1, 1]),
        helper.make_node('MaxPool', ['inv'], ['imn3'], kernel_shape=[3, 3], pads=[0, 0, 2, 2], strides=[1, 1]),
        helper.make_node('Add', ['mx3', 'imn3'], ['sum3']),
        helper.make_node('MaxPool', ['lab'], ['mx4'], kernel_shape=[4, 4], pads=[0, 0, 3, 3], strides=[1, 1]),
        helper.make_node('MaxPool', ['inv'], ['imn4'], kernel_shape=[4, 4], pads=[0, 0, 3, 3], strides=[1, 1]),
        helper.make_node('Add', ['mx4', 'imn4'], ['sum4']),
        helper.make_node('Pad', ['lab', 'PADU', 'NEG_U8'], ['lab_up']),
        helper.make_node('Pad', ['lab', 'PADL', 'NEG_U8'], ['lab_left']),
        helper.make_node('Equal', ['lab', 'lab_up'], ['equp']),
        helper.make_node('Equal', ['lab', 'lab_left'], ['eqlf']),
        helper.make_node('Or', ['equp', 'eqlf'], ['eqany']),
        helper.make_node('Equal', ['lab', 'Z_U8'], ['is0']),
        helper.make_node('Or', ['eqany', 'is0'], ['bad']),
        helper.make_node('Where', ['bad', 'NINE_U8', 'sum3'], ['m3a']),
        helper.make_node('Where', ['inside_b', 'm3a', 'NINE_U8'], ['m3']),
        helper.make_node('MaxPool', ['m3'], ['mm3'], kernel_shape=[20, 20], strides=[1, 1]),
        helper.make_node('Equal', ['mm3', 'NINE_U8'], ['s_ok_s3']),
        helper.make_node('Where', ['bad', 'NINE_U8', 'sum4'], ['m4a']),
        helper.make_node('Where', ['inside_b', 'm4a', 'NINE_U8'], ['m4']),
        helper.make_node('MaxPool', ['m4'], ['mm4'], kernel_shape=[20, 20], strides=[1, 1]),
        helper.make_node('Equal', ['mm4', 'NINE_U8'], ['s_ok_s4']),
        helper.make_node('Where', ['s_ok_s3', 'THREE_I', 'TWO_I'], ['s_pre']),
        helper.make_node('Where', ['s_ok_s4', 'FOUR_I', 's_pre'], ['S']),
        # ---- kernel (native-sprite) sample via separable gathers ----
        helper.make_node('Mul', ['S', 'DR'], ['s_dr']),
        helper.make_node('Mul', ['S', 'DC'], ['s_dc']),
        helper.make_node('Add', ['tr_anchor', 's_dr'], ['ksr']),
        helper.make_node('Add', ['tc_anchor', 's_dc'], ['ksc']),
        helper.make_node('Clip', ['ksr', 'Z_I', 'C19'], ['ksr_cl']),
        helper.make_node('Clip', ['ksc', 'Z_I', 'C19'], ['ksc_cl']),
        helper.make_node('Reshape', ['ksr_cl', 'SH3'], ['ksr1']),
        helper.make_node('Reshape', ['ksc_cl', 'SH5'], ['ksc1']),
        helper.make_node('Gather', ['lab', 'ksr1'], ['gk1'], axis=2),
        helper.make_node('Gather', ['gk1', 'ksc1'], ['kern_label'], axis=3),
        # kern_tmpl recomputed from clipped coords + gathered labels
        helper.make_node('GreaterOrEqual', ['ksr_cl', 'r_top'], ['ktr1']),
        helper.make_node('LessOrEqual', ['ksr_cl', 'r_bot'], ['ktr2']),
        helper.make_node('And', ['ktr1', 'ktr2'], ['kin_r']),
        helper.make_node('GreaterOrEqual', ['ksc_cl', 'c_left'], ['ktc1']),
        helper.make_node('LessOrEqual', ['ksc_cl', 'c_right'], ['ktc2']),
        helper.make_node('And', ['ktc1', 'ktc2'], ['kin_c']),
        helper.make_node('And', ['kin_r', 'kin_c'], ['kin']),
        helper.make_node('Equal', ['kern_label', 'Z_U8'], ['k0']),
        helper.make_node('Equal', ['kern_label', 'FOUR_U8'], ['k4']),
        helper.make_node('Or', ['k0', 'k4'], ['k04']),
        helper.make_node('Not', ['k04'], ['knz']),
        helper.make_node('And', ['kin', 'knz'], ['kern_tmpl_b']),
        helper.make_node('Where', ['kern_tmpl_b', 'KSCORE', 'BIG'], ['kern_score_v']),
        helper.make_node('ReduceMin', ['kern_score_v'], ['k_pick_idx'], axes=[2, 3], keepdims=0),
        helper.make_node('Reshape', ['kern_label', 'SH15'], ['kernlab_flat']),
        helper.make_node('Gather', ['kernlab_flat', 'k_pick_idx'], ['k_anchor'], axis=0),
        # ---- vote conv ----
        helper.make_node('Equal', ['lab', 'k_anchor'], ['ind_b']),
        helper.make_node('Cast', ['ind_b'], ['ind_u8'], to=TensorProto.UINT8),
        helper.make_node('Equal', ['kern_label', 'k_anchor'], ['kern_eq_anchor_b']),
        helper.make_node('And', ['kern_eq_anchor_b', 'kern_tmpl_b'], ['kernel_b']),
        helper.make_node('Cast', ['kernel_b'], ['kernel_u8'], to=TensorProto.UINT8),
        helper.make_node('QLinearConv', ['ind_u8', 'QS', 'Z_U8', 'kernel_u8', 'QS', 'Z_U8', 'QS', 'Z_U8', 'BIAS1'],
                         ['votep1'], kernel_shape=[3, 5], pads=[0, 0, 2, 4], strides=[1, 1]),
        # ---- alignment window mask (per-axis) ----
        helper.make_node('Sub', ['ROW', 'kr_top'], ['ki_rel_g']),
        helper.make_node('Sub', ['COL', 'kc_left'], ['kj_rel_g']),
        helper.make_node('Sub', ['kr_bot', 'kr_top'], ['khm1']),
        helper.make_node('Add', ['khm1', 'ONE_I'], ['kh']),
        helper.make_node('Sub', ['kc_right', 'kc_left'], ['kwm1']),
        helper.make_node('Add', ['kwm1', 'ONE_I'], ['kw']),
        helper.make_node('Mul', ['kh', 'S'], ['s_kh']),
        helper.make_node('Mul', ['kw', 'S'], ['s_kw']),
        helper.make_node('Sub', ['tr_anchor', 'r_top'], ['tra_rel']),
        helper.make_node('Sub', ['tc_anchor', 'c_left'], ['tca_rel']),
        helper.make_node('Div', ['tra_rel', 'S'], ['ki_rel_max']),
        helper.make_node('Div', ['tca_rel', 'S'], ['kj_rel_max']),
        helper.make_node('GreaterOrEqual', ['ki_rel_g', 'Z_I'], ['ki_ge']),
        helper.make_node('LessOrEqual', ['ki_rel_g', 'ki_rel_max'], ['ki_le']),
        helper.make_node('And', ['ki_ge', 'ki_le'], ['ki_fit']),
        helper.make_node('GreaterOrEqual', ['kj_rel_g', 'Z_I'], ['kj_ge']),
        helper.make_node('LessOrEqual', ['kj_rel_g', 'kj_rel_max'], ['kj_le']),
        helper.make_node('And', ['kj_ge', 'kj_le'], ['kj_fit']),
        helper.make_node('Where', ['ki_fit', 'votep1', 'Z_U8'], ['vm1']),
        helper.make_node('Where', ['kj_fit', 'vm1', 'Z_U8'], ['vote_m']),
        helper.make_node('Reshape', ['vote_m', 'SH400'], ['vote_flat']),
        helper.make_node('ArgMax', ['vote_flat'], ['bi64'], axis=0, keepdims=0),
        helper.make_node('Cast', ['bi64'], ['bi'], to=TensorProto.INT32),
        helper.make_node('Div', ['bi', 'S20'], ['ki_star']),
        helper.make_node('Mul', ['ki_star', 'S20'], ['ki_x20']),
        helper.make_node('Sub', ['bi', 'ki_x20'], ['kj_star']),
        helper.make_node('Sub', ['ki_star', 'kr_top'], ['ki_rel_s']),
        helper.make_node('Sub', ['kj_star', 'kc_left'], ['kj_rel_s']),
        helper.make_node('Mul', ['S', 'ki_rel_s'], ['s_ki_rel_s']),
        helper.make_node('Mul', ['S', 'kj_rel_s'], ['s_kj_rel_s']),
        helper.make_node('Sub', ['tr_anchor', 's_ki_rel_s'], ['trm']),
        helper.make_node('Sub', ['tc_anchor', 's_kj_rel_s'], ['tcm']),
        helper.make_node('Sub', ['trm', 'r_top'], ['KOR']),
        helper.make_node('Sub', ['tcm', 'c_left'], ['KOC']),
        # ---- stamp via separable gathers ----
        helper.make_node('Sub', ['ROW', 'KOR'], ['fkr']),
        helper.make_node('Sub', ['COL', 'KOC'], ['fkc']),
        helper.make_node('Max', ['fkr', 'Z_I'], ['fkrp']),
        helper.make_node('Max', ['fkc', 'Z_I'], ['fkcp']),
        helper.make_node('Div', ['fkrp', 'S'], ['fsr_rel']),
        helper.make_node('Div', ['fkcp', 'S'], ['fsc_rel']),
        helper.make_node('Add', ['fsr_rel', 'kr_top'], ['fsr']),
        helper.make_node('Add', ['fsc_rel', 'kc_left'], ['fsc']),
        helper.make_node('Clip', ['fsr', 'Z_I', 'C19'], ['fsr_cl']),
        helper.make_node('Clip', ['fsc', 'Z_I', 'C19'], ['fsc_cl']),
        helper.make_node('Reshape', ['fsr_cl', 'SH20'], ['fri']),
        helper.make_node('Reshape', ['fsc_cl', 'SH20'], ['fci']),
        helper.make_node('Gather', ['lab', 'fri'], ['g1'], axis=2),
        helper.make_node('Gather', ['g1', 'fci'], ['fstamp'], axis=3),
        helper.make_node('Less', ['fkr', 's_kh'], ['fkr_lt']),
        helper.make_node('Less', ['fkc', 's_kw'], ['fkc_lt']),
        helper.make_node('GreaterOrEqual', ['fkr', 'Z_I'], ['fkr_ge0']),
        helper.make_node('GreaterOrEqual', ['fkc', 'Z_I'], ['fkc_ge0']),
        helper.make_node('And', ['fkr_ge0', 'fkr_lt'], ['fkr_v']),
        helper.make_node('And', ['fkc_ge0', 'fkc_lt'], ['fkc_v']),
        helper.make_node('Where', ['fkr_v', 'fstamp', 'Z_U8'], ['st1']),
        helper.make_node('Where', ['fkc_v', 'st1', 'Z_U8'], ['stampc']),
        # ---- compose output ----
        helper.make_node('Equal', ['ROW', 'OHm1'], ['row_eqhm1']),
        helper.make_node('Equal', ['COL', 'OWm1'], ['col_eqwm1']),
        helper.make_node('Or', ['ROW_EQ0', 'row_eqhm1'], ['row_edge']),
        helper.make_node('Or', ['COL_EQ0', 'col_eqwm1'], ['col_edge']),
        helper.make_node('And', ['row_edge', 'col_edge'], ['is_corner']),
        helper.make_node('Where', ['is_corner', 'FOUR_U8', 'stampc'], ['cst']),
        helper.make_node('LessOrEqual', ['ROW', 'OHm1'], ['row_in_out']),
        helper.make_node('LessOrEqual', ['COL', 'OWm1'], ['col_in_out']),
        helper.make_node('Where', ['row_in_out', 'cst', 'NEG_U8'], ['o1']),
        helper.make_node('Where', ['col_in_out', 'o1', 'NEG_U8'], ['out_label']),
        helper.make_node('Pad', ['out_label', 'PADF', 'NEG_U8'], ['out30'], mode='constant'),
        helper.make_node('Equal', ['out30', 'LAB10'], ['output']),
    ]
    return model('task209_cand', nodes, inits, output_dtype=TensorProto.BOOL, opset=17)
