"""Task 250 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('s_red', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAA=')),
        tensor('e_red', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAAgAAAAAAAAACAAAAAAAAAA=')),
        tensor('s_gray', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('e_gray', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoGAAAAAAAAAAoAAAAAAAAACgAAAAAAAAA=')),
        tensor('ax_chw', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAA=')),
        tensor('ax_w', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAA==')),
        tensor('ax_h', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAA==')),
        tensor('row_idx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAQAAAAIAAAADAAAABAAAAAUAAAAGAAAABwAAAAgAAAAJAAAA')),
        tensor('one', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAA')),
        tensor('two', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAA')),
        tensor('seven', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoHAAAA')),
        tensor('zero', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAA')),
        tensor('three', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAA')),
        tensor('depth4', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoEAAAA')),
        tensor('oh_vals', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAA8')),
        tensor('false_s', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGIxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('shape1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
        tensor('z1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAA==')),
        tensor('pad_red', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAA')),
        tensor('pad_out', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAUAAAAAAAAABQAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 's_red', 'e_red', 'ax_chw'], ['red6']),
        helper.make_node('Cast', ['red6'], ['red_mask6'], to=9),
        helper.make_node('Pad', ['red_mask6', 'pad_red', 'false_s'], ['red_mask'], mode='constant'),
        helper.make_node('ReduceSum', ['red6', 'ax_w'], ['row_cnt'], keepdims=1),
        helper.make_node('ArgMax', ['row_cnt'], ['brl_i64'], axis=2, keepdims=1),
        helper.make_node('Squeeze', ['brl_i64'], ['brl_s']),
        helper.make_node('Cast', ['brl_s'], ['brl'], to=6),
        helper.make_node('Add', ['brl', 'two'], ['boxrow']),
        helper.make_node('Sub', ['boxrow', 'one'], ['rmin']),
        helper.make_node('Sub', ['row_idx', 'rmin'], ['shr']),
        helper.make_node('Clip', ['shr', 'zero', 'three'], ['band_r']),
        helper.make_node('OneHot', ['band_r', 'depth4', 'oh_vals'], ['Rr'], axis=0),
        helper.make_node('Slice', ['input', 's_gray', 'e_gray', 'ax_chw'], ['gray_f32']),
        helper.make_node('Cast', ['gray_f32'], ['gray_h'], to=10),
        helper.make_node('ReduceSum', ['red6', 'ax_h'], ['col_cnt'], keepdims=1),
        helper.make_node('ArgMax', ['col_cnt'], ['bcl_i64'], axis=3, keepdims=1),
        helper.make_node('Squeeze', ['bcl_i64'], ['bcl_s']),
        helper.make_node('Cast', ['bcl_s'], ['bcl'], to=6),
        helper.make_node('Add', ['bcl', 'two'], ['boxcol']),
        helper.make_node('Sub', ['boxcol', 'one'], ['cmin']),
        helper.make_node('Sub', ['row_idx', 'cmin'], ['shc']),
        helper.make_node('Clip', ['shc', 'zero', 'three'], ['band_c']),
        helper.make_node('OneHot', ['band_c', 'depth4', 'oh_vals'], ['Rc'], axis=0),
        helper.make_node('Einsum', ['Rr', 'gray_h', 'Rc'], ['G4'], equation='ir,uvrc,jc->uvij'),
        helper.make_node('Cast', ['G4'], ['G4_b'], to=9),
        helper.make_node('Cast', ['rmin'], ['pbH1_64'], to=7),
        helper.make_node('Reshape', ['pbH1_64', 'shape1'], ['pbH1']),
        helper.make_node('Cast', ['cmin'], ['pbW1_64'], to=7),
        helper.make_node('Reshape', ['pbW1_64', 'shape1'], ['pbW1']),
        helper.make_node('Sub', ['seven', 'boxrow'], ['peH']),
        helper.make_node('Cast', ['peH'], ['peH1_64'], to=7),
        helper.make_node('Reshape', ['peH1_64', 'shape1'], ['peH1']),
        helper.make_node('Sub', ['seven', 'boxcol'], ['peW']),
        helper.make_node('Cast', ['peW'], ['peW1_64'], to=7),
        helper.make_node('Reshape', ['peW1_64', 'shape1'], ['peW1']),
        helper.make_node('Concat', ['z1', 'z1', 'pbH1', 'pbW1', 'z1', 'z1', 'peH1', 'peW1'], ['pads_dyn'], axis=0),
        helper.make_node('Pad', ['G4_b', 'pads_dyn', 'false_s'], ['newgray_b'], mode='constant'),
        helper.make_node('Or', ['red_mask', 'newgray_b'], ['occupied']),
        helper.make_node('Not', ['occupied'], ['bg']),
        helper.make_node('And', ['red_mask', 'false_s'], ['falsep']),
        helper.make_node('Concat', ['bg', 'falsep', 'red_mask', 'falsep', 'falsep', 'newgray_b'], ['onehot6'], axis=1),
        helper.make_node('Pad', ['onehot6', 'pad_out', 'false_s'], ['output'], mode='constant'),
    ]
    value_infos = [
        helper.make_tensor_value_info('newgray_b', 9, [1, 1, 10, 10]),
    ]
    return model('task250_live_exact', nodes, inits, output_dtype=9, opset=18, value_infos=value_infos)
