"""Task 293 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('slice_start', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==')),
        tensor('left_end', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAEAAAAAAAAAEAAAAAAAAAABAAAAAAAAAA==')),
        tensor('top_end', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAPAAAAAAAAAA==')),
        tensor('one_i64', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
        tensor('two_i64', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAA==')),
        tensor('one_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/')),
        tensor('row_offsets_u', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDMsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAEAAAAAAAAAAgAAAAAAAAA=')),
        tensor('col_offsets_u', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDIsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAEAAAAAAAAA')),
        tensor('shape_1_10_1_1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAoAAAAAAAAAAQAAAAAAAAABAAAAAAAAAA==')),
        tensor('true111', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGIxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('grid_shape4', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAMAAAAAAAAAAgAAAAAAAAABAAAAAAAAAA==')),
        tensor('batch_zero_grid4', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsIDMsIDIsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'slice_start', 'left_end'], ['left_slice']),
        helper.make_node('Slice', ['input', 'slice_start', 'top_end'], ['top_slice']),
        helper.make_node('ArgMin', ['left_slice'], ['row0_k'], axis=2, keepdims=0),
        helper.make_node('ArgMin', ['top_slice'], ['col0_k'], axis=3, keepdims=0),
        helper.make_node('Squeeze', ['row0_k'], ['row0'], axes=[0, 1, 2]),
        helper.make_node('Squeeze', ['col0_k'], ['col0'], axes=[0, 1, 2]),
        helper.make_node('Add', ['row0', 'one_i64'], ['row1']),
        helper.make_node('Add', ['row0', 'two_i64'], ['row2']),
        helper.make_node('Add', ['col0', 'one_i64'], ['col1']),
        helper.make_node('Add', ['row0', 'row_offsets_u'], ['rows_u']),
        helper.make_node('Add', ['col0', 'col_offsets_u'], ['cols_u']),
        helper.make_node('Cast', ['row0'], ['row0_i32'], to=6),
        helper.make_node('Cast', ['col0'], ['col0_i32'], to=6),
        helper.make_node('Expand', ['row0_i32', 'shape_1_10_1_1'], ['h_gather_idx']),
        helper.make_node('GatherElements', ['input', 'h_gather_idx'], ['h_vec4'], axis=2),
        helper.make_node('ArgMax', ['h_vec4'], ['h_color_u'], axis=1, keepdims=1),
        helper.make_node('Expand', ['col0_i32', 'shape_1_10_1_1'], ['v_gather_idx']),
        helper.make_node('GatherElements', ['input', 'v_gather_idx'], ['v_vec4'], axis=3),
        helper.make_node('ArgMax', ['v_vec4'], ['v_color_u'], axis=1, keepdims=1),
        helper.make_node('Gather', ['left_slice', 'row1'], ['left_r1'], axis=2),
        helper.make_node('Gather', ['left_slice', 'row2'], ['left_r2'], axis=2),
        helper.make_node('Less', ['left_r1', 'one_f'], ['row1_valid_k']),
        helper.make_node('Less', ['left_r2', 'one_f'], ['row2_candidate_k']),
        helper.make_node('And', ['row1_valid_k', 'row2_candidate_k'], ['row2_valid_k']),
        helper.make_node('Concat', ['true111', 'row1_valid_k', 'row2_valid_k'], ['row_valid_k'], axis=2),
        helper.make_node('Squeeze', ['row_valid_k'], ['row_valid'], axes=[0, 1]),
        helper.make_node('Gather', ['top_slice', 'col1'], ['top_c1'], axis=3),
        helper.make_node('Less', ['top_c1', 'one_f'], ['col1_valid_k']),
        helper.make_node('Concat', ['true111', 'col1_valid_k'], ['col_valid_k'], axis=2),
        helper.make_node('Squeeze', ['col_valid_k'], ['col_valid'], axes=[0, 1]),
        helper.make_node('Concat', ['h_color_u', 'v_color_u'], ['colors_u'], axis=0),
        helper.make_node('Expand', ['colors_u', 'grid_shape4'], ['color_grid4']),
        helper.make_node('Expand', ['rows_u', 'grid_shape4'], ['row_grid4']),
        helper.make_node('Expand', ['cols_u', 'grid_shape4'], ['col_grid4']),
        helper.make_node('Concat', ['batch_zero_grid4', 'color_grid4', 'row_grid4', 'col_grid4'], ['scatter_idx'], axis=3),
        helper.make_node('GatherND', ['input', 'scatter_idx'], ['orig']),
        helper.make_node('Equal', ['orig', 'one_f'], ['orig_b']),
        helper.make_node('Unsqueeze', ['row_valid'], ['row_valid_u'], axes=[1]),
        helper.make_node('And', ['row_valid_u', 'col_valid'], ['valid']),
        helper.make_node('Xor', ['orig_b', 'valid'], ['updates_b']),
        helper.make_node('Cast', ['updates_b'], ['updates'], to=1),
        helper.make_node('ScatterND', ['input', 'scatter_idx', 'updates'], ['output']),
    ]
    value_infos = [
    ]
    return model('task293_live_exact', nodes, inits, output_dtype=1, opset=11, value_infos=value_infos)
