"""Task 135 — exact source reconstruction of compact live graph.

Generated from inspected graph structure; does not load networks/task135.onnx.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor

def build(task):
    inits = [
        tensor('W', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCAxMCwgMiwgMSksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIC/AACAPwAAgL8AAAAAAACAvwAAAAAAAIC/AAAAAAAAgL8AAAAAAACAvwAAAAAAAIC/AAAAAAAAgL8AAAAAAACAvwAAAAAAAIC/AAAAAAAAgL8AAAAAAACAvwAAgD8AAIC/AAAAAAAAgL8AAAAAAACAvwAAAAAAAIC/AAAAAAAAgL8AAAAAAACAvwAAAAAAAIC/AAAAAAAAgL8AAAAAAACAvwAAAAAAAIC/AAAAAAAAgL8AAIA/AACAvwAAAAAAAIC/AAAAAAAAgL8AAAAAAACAvwAAAAAAAIC/AAAAAAAAgL8AAAAAAACAvwAAAAAAAIC/AAAAAAAAgL8AAAAAAACAvwAAAAAAAIC/AACAPwAAgL8AAAAAAACAvwAAAAAAAIC/AAAAAAAAgL8AAAAAAACAvwAAAAAAAIC/AAAAAAAAgL8AAAAAAACAvwAAAAAAAIC/AAAAAAAAgL8AAAAAAACAvwAAgD8AAIC/AAAAAAAAgL8AAAAAAACAvwAAAAAAAIC/AAAAAAAAgL8AAAAAAACAvwAAAAAAAIC/AAAAAAAAgL8AAAAAAACAvwAAAAAAAIC/AAAAAAAAgL8AAIA/AACAvwAAAAAAAIC/AAAAAAAAgL8AAAAAAACAvwAAAAAAAIC/AAAAAAAAgL8AAAAAAACAvwAAAAAAAIC/AAAAAAAAgL8AAAAAAACAvwAAAAAAAIC/AACAPwAAgL8AAAAAAACAvwAAAAAAAIC/AAAAAAAAgL8AAAAAAACAvwAAAAAAAIC/AAAAAAAAgL8AAAAAAACAvwAAAAAAAIC/AAAAAAAAgL8AAAAAAACAvwAAgD8AAIC/AAAAAAAAgL8AAAAAAACAvwAAAAAAAIC/AAAAAAAAgL8AAAAAAACAvwAAAAAAAIC/AAAAAAAAgL8AAAAAAACAvwAAAAAAAIC/AAAAAAAAgL8AAIA/AACAvwAAAAAAAIC/AAAAAAAAgL8AAAAAAACAvwAAAAAAAIC/AAAAAAAAgL8AAAAAAACAvwAAAAAAAIC/AAAAAAAAgL8AAAAAAACAvwAAAAAAAIC/AACAPw==')),
    ]
    nodes = [
        helper.make_node('Conv', ['input', 'W'], ['output'], dilations=[3, 1], kernel_shape=[2, 1], pads=[3, -6, 0, 6]),
    ]
    return model("task135", nodes, inits, output_dtype=TensorProto.FLOAT, opset=11)
