"""Task 145 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('scale_f16', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAPA==')),
        tensor('zero_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('one_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('two_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoC')),
        tensor('eight_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoI')),
        tensor('ten_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoK')),
        tensor('twenty_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoU')),
        tensor('z_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==')),
        tensor('z_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAEAAAAAAAAAFAAAAAAAAAAUAAAAAAAAAA==')),
        tensor('axes_hw', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAMAAAAAAAAA')),
        tensor('core_pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAACgAAAAAAAAAKAAAAAAAAAA==')),
        tensor('pos_left', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDIwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAgMEBQYHCAkKCwwNDg8QERITFA==')),
        tensor('pos_right', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDIwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoUExIREA8ODQwLCgkIBwYFBAMCAQ==')),
        tensor('pos_up', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDIwLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAgMEBQYHCAkKCwwNDg8QERITFA==')),
        tensor('pos_down', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDIwLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoUExIREA8ODQwLCgkIBwYFBAMCAQ==')),
        tensor('channel_ids_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJ')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'z_starts', 'z_ends'], ['z_f32']),
        helper.make_node('Cast', ['z_f32'], ['z_bool'], to=9),
        helper.make_node('Where', ['z_bool', 'zero_u8', 'pos_left'], ['left_src']),
        helper.make_node('Where', ['z_bool', 'zero_u8', 'pos_right'], ['right_src']),
        helper.make_node('Where', ['z_bool', 'zero_u8', 'pos_up'], ['up_src']),
        helper.make_node('Where', ['z_bool', 'zero_u8', 'pos_down'], ['down_src']),
        helper.make_node('MaxPool', ['left_src'], ['left_marker'], kernel_shape=[1, 20], pads=[0, 19, 0, 0], strides=[1, 1]),
        helper.make_node('MaxPool', ['right_src'], ['right_marker'], kernel_shape=[1, 20], pads=[0, 0, 0, 19], strides=[1, 1]),
        helper.make_node('MaxPool', ['up_src'], ['up_marker'], kernel_shape=[20, 1], pads=[19, 0, 0, 0], strides=[1, 1]),
        helper.make_node('MaxPool', ['down_src'], ['down_marker'], kernel_shape=[20, 1], pads=[0, 0, 19, 0], strides=[1, 1]),
        helper.make_node('Add', ['left_marker', 'right_marker'], ['lr_sum_u8']),
        helper.make_node('Add', ['up_marker', 'down_marker'], ['ud_sum_u8']),
        helper.make_node('DequantizeLinear', ['lr_sum_u8', 'scale_f16', 'twenty_u8'], ['neg_width']),
        helper.make_node('DequantizeLinear', ['ud_sum_u8', 'scale_f16', 'twenty_u8'], ['neg_height']),
        helper.make_node('Mul', ['neg_width', 'neg_height'], ['area']),
        helper.make_node('ReduceMax', ['area', 'axes_hw'], ['max_area'], keepdims=1),
        helper.make_node('Where', ['z_bool', 'area', 'max_area'], ['area_for_min']),
        helper.make_node('ReduceMin', ['area_for_min', 'axes_hw'], ['min_area'], keepdims=1),
        helper.make_node('Equal', ['area', 'max_area'], ['max_mask']),
        helper.make_node('Equal', ['area_for_min', 'min_area'], ['min_mask']),
        helper.make_node('MaxPool', ['z_f32'], ['row_inside_f'], kernel_shape=[20, 20], pads=[0, 0, 19, 0], strides=[1, 1]),
        helper.make_node('MaxPool', ['z_f32'], ['col_inside_f'], kernel_shape=[20, 20], pads=[0, 0, 0, 19], strides=[1, 1]),
        helper.make_node('Cast', ['row_inside_f'], ['row_inside'], to=9),
        helper.make_node('Cast', ['col_inside_f'], ['col_inside'], to=9),
        helper.make_node('And', ['row_inside', 'col_inside'], ['inside']),
        helper.make_node('Where', ['z_bool', 'zero_u8', 'two_u8'], ['color0']),
        helper.make_node('Where', ['inside', 'color0', 'ten_u8'], ['color1']),
        helper.make_node('Where', ['max_mask', 'one_u8', 'color1'], ['color2']),
        helper.make_node('Where', ['min_mask', 'eight_u8', 'color2'], ['color_core']),
        helper.make_node('Pad', ['color_core', 'core_pads', 'ten_u8', 'axes_hw'], ['color30'], mode='constant'),
        helper.make_node('Equal', ['color30', 'channel_ids_u8'], ['output']),
    ]
    value_infos = [
    ]
    return model('task145_live_exact', nodes, inits, output_dtype=9, opset=19, value_infos=value_infos)
