"""Task 354 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('safe_name_0', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoFAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAA=')),
        tensor('safe_name_1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoGAAAAAAAAAAoAAAAAAAAACgAAAAAAAAA=')),
        tensor('safe_name_2', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAA=')),
        tensor('safe_name_3', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAMAAAAAAAAA')),
        tensor('safe_name_4', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAA')),
        tensor('safe_name_5', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAMAAAAAAAAA')),
        tensor('safe_name_6', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAQAAAAAAAAA')),
        tensor('safe_name_7', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAYAAAAAAAAA')),
        tensor('safe_name_8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAcAAAAAAAAA')),
        tensor('safe_name_9', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAoAAAAAAAAA')),
        tensor('safe_name_10', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAA==')),
        tensor('safe_name_11', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAA==')),
        tensor('safe_name_12', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoEAAAAAAAAAA==')),
        tensor('safe_name_13', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoGAAAAAAAAAA==')),
        tensor('safe_name_14', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUAAAAAAAAABQAAAAAAAAA')),
        tensor('safe_name_15', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAA')),
        tensor('safe_name_16', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('safe_name_17', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoL')),
        tensor('safe_name_18', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('safe_name_19', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDgsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAQEBAQEBAQ==')),
        tensor('safe_name_20', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBB')),
        tensor('safe_name_21', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJ')),
        tensor('safe_name_22', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDEwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'safe_name_4', 'safe_name_5', 'safe_name_3'], ['safe_name_23']),
        helper.make_node('Conv', ['safe_name_23', 'safe_name_20'], ['safe_name_24']),
        helper.make_node('Cast', ['safe_name_24'], ['safe_name_25'], to=2),
        helper.make_node('Slice', ['input', 'safe_name_6', 'safe_name_7', 'safe_name_3'], ['safe_name_26']),
        helper.make_node('Conv', ['safe_name_26', 'safe_name_20'], ['safe_name_27']),
        helper.make_node('Cast', ['safe_name_27'], ['safe_name_28'], to=2),
        helper.make_node('Slice', ['input', 'safe_name_8', 'safe_name_9', 'safe_name_3'], ['safe_name_29']),
        helper.make_node('Conv', ['safe_name_29', 'safe_name_20'], ['safe_name_30']),
        helper.make_node('Cast', ['safe_name_30'], ['safe_name_31'], to=2),
        helper.make_node('Concat', ['safe_name_25', 'safe_name_18', 'safe_name_28', 'safe_name_18', 'safe_name_31'], ['safe_name_32'], axis=3),
        helper.make_node('Slice', ['input', 'safe_name_0', 'safe_name_1', 'safe_name_2'], ['safe_name_33']),
        helper.make_node('Equal', ['safe_name_33', 'safe_name_15'], ['safe_name_34']),
        helper.make_node('Split', ['safe_name_34'], ['safe_name_35', 'safe_name_36', 'safe_name_37', 'safe_name_38', 'safe_name_39', 'safe_name_40', 'safe_name_41', 'safe_name_42', 'safe_name_43', 'safe_name_44'], axis=3, num_outputs=10),
        helper.make_node('Cast', ['safe_name_36'], ['safe_name_45'], to=2),
        helper.make_node('Add', ['safe_name_19', 'safe_name_45'], ['safe_name_46']),
        helper.make_node('Cast', ['safe_name_37'], ['safe_name_47'], to=2),
        helper.make_node('Add', ['safe_name_46', 'safe_name_47'], ['safe_name_48']),
        helper.make_node('Cast', ['safe_name_38'], ['safe_name_49'], to=2),
        helper.make_node('Add', ['safe_name_48', 'safe_name_49'], ['safe_name_50']),
        helper.make_node('Cast', ['safe_name_39'], ['safe_name_51'], to=2),
        helper.make_node('Add', ['safe_name_50', 'safe_name_51'], ['safe_name_52']),
        helper.make_node('Cast', ['safe_name_40'], ['safe_name_53'], to=2),
        helper.make_node('Add', ['safe_name_52', 'safe_name_53'], ['safe_name_54']),
        helper.make_node('Cast', ['safe_name_41'], ['safe_name_55'], to=2),
        helper.make_node('Add', ['safe_name_54', 'safe_name_55'], ['safe_name_56']),
        helper.make_node('Cast', ['safe_name_42'], ['safe_name_57'], to=2),
        helper.make_node('Add', ['safe_name_56', 'safe_name_57'], ['safe_name_58']),
        helper.make_node('Concat', ['safe_name_19', 'safe_name_46', 'safe_name_48', 'safe_name_50', 'safe_name_52', 'safe_name_54', 'safe_name_56', 'safe_name_58', 'safe_name_58', 'safe_name_58'], ['safe_name_59'], axis=3),
        helper.make_node('Where', ['safe_name_34', 'safe_name_17', 'safe_name_59'], ['safe_name_60']),
        helper.make_node('ReduceMax', ['safe_name_31', 'safe_name_10'], ['safe_name_61'], keepdims=1),
        helper.make_node('Where', ['safe_name_34', 'safe_name_16', 'safe_name_61'], ['safe_name_62']),
        helper.make_node('ReduceMax', ['safe_name_25', 'safe_name_10'], ['safe_name_63'], keepdims=1),
        helper.make_node('Slice', ['safe_name_60', 'safe_name_11', 'safe_name_10', 'safe_name_10'], ['safe_name_64']),
        helper.make_node('ReduceMin', ['safe_name_64', 'safe_name_10'], ['safe_name_65'], keepdims=1),
        helper.make_node('Mod', ['safe_name_65', 'safe_name_17'], ['safe_name_66']),
        helper.make_node('Equal', ['safe_name_60', 'safe_name_66'], ['safe_name_67']),
        helper.make_node('Where', ['safe_name_67', 'safe_name_63', 'safe_name_62'], ['safe_name_68']),
        helper.make_node('ReduceMax', ['safe_name_28', 'safe_name_10'], ['safe_name_69'], keepdims=1),
        helper.make_node('Cast', ['safe_name_28'], ['safe_name_70'], to=9),
        helper.make_node('Slice', ['safe_name_60', 'safe_name_12', 'safe_name_13', 'safe_name_10'], ['safe_name_71']),
        helper.make_node('Where', ['safe_name_70', 'safe_name_71', 'safe_name_17'], ['safe_name_72']),
        helper.make_node('ReduceMin', ['safe_name_72', 'safe_name_10'], ['safe_name_73'], keepdims=1),
        helper.make_node('Mod', ['safe_name_73', 'safe_name_17'], ['safe_name_74']),
        helper.make_node('Equal', ['safe_name_60', 'safe_name_74'], ['safe_name_75']),
        helper.make_node('Where', ['safe_name_75', 'safe_name_69', 'safe_name_68'], ['safe_name_76']),
        helper.make_node('Concat', ['safe_name_32', 'safe_name_22', 'safe_name_76'], ['safe_name_77'], axis=2),
        helper.make_node('Pad', ['safe_name_77', 'safe_name_14', 'safe_name_17'], ['safe_name_78']),
        helper.make_node('Equal', ['safe_name_78', 'safe_name_21'], ['output']),
    ]
    value_infos = [
    ]
    return model('task354_live_exact', nodes, inits, output_dtype=9, opset=18, value_infos=value_infos)
