"""Task 161 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('rowsel0', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('ones30', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8=')),
        tensor('arange10i', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAEAAAAAAAAAAgAAAAAAAAADAAAAAAAAAAQAAAAAAAAABQAAAAAAAAAGAAAAAAAAAAcAAAAAAAAACAAAAAAAAAAJAAAAAAAAAA==')),
        tensor('arange10f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBB')),
        tensor('zf', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAA')),
        tensor('arange30r', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDMwLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBBAAAgQQAAMEEAAEBBAABQQQAAYEEAAHBBAACAQQAAiEEAAJBBAACYQQAAoEEAAKhBAACwQQAAuEEAAMBBAADIQQAA0EEAANhBAADgQQAA6EE=')),
        tensor('arange30c', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDMwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBBAAAgQQAAMEEAAEBBAABQQQAAYEEAAHBBAACAQQAAiEEAAJBBAACYQQAAoEEAAKhBAACwQQAAuEEAAMBBAADIQQAA0EEAANhBAADgQQAA6EE=')),
        tensor('f45', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAJBA')),
        tensor('f15', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAMA/')),
        tensor('u255', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAr/')),
        tensor('levels', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJ')),
        tensor('sh4d_r', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAEAAAAAAAAAHgAAAAAAAAABAAAAAAAAAA==')),
        tensor('sh4d_c', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAeAAAAAAAAAA==')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input'], ['total'], equation='bchw->bc'),
        helper.make_node('Einsum', ['input', 'rowsel0', 'ones30'], ['colcount'], equation='bchw,h,w->bc'),
        helper.make_node('Einsum', ['input', 'ones30', 'rowsel0'], ['rowcount'], equation='bchw,h,w->bc'),
        helper.make_node('Add', ['colcount', 'rowcount'], ['near']),
        helper.make_node('Greater', ['near', 'f15'], ['nearok']),
        helper.make_node('Less', ['total', 'f45'], ['l45']),
        helper.make_node('And', ['l45', 'nearok'], ['mk']),
        helper.make_node('Cast', ['mk'], ['mki'], to=2),
        helper.make_node('ArgMax', ['mki'], ['Marg'], axis=1, keepdims=0),
        helper.make_node('Equal', ['arange10i', 'Marg'], ['oMb']),
        helper.make_node('Where', ['oMb', 'arange10f', 'zf'], ['wc']),
        helper.make_node('Einsum', ['input', 'wc', 'rowsel0'], ['Rvalf'], equation='bchw,c,w->bh'),
        helper.make_node('Einsum', ['input', 'wc', 'rowsel0'], ['Cvalf'], equation='bchw,c,h->bw'),
        helper.make_node('Cast', ['Rvalf'], ['Rvalu'], to=2),
        helper.make_node('Cast', ['Cvalf'], ['Cvalu'], to=2),
        helper.make_node('Reshape', ['Rvalu', 'sh4d_r'], ['Rval']),
        helper.make_node('Reshape', ['Cvalu', 'sh4d_c'], ['Cval']),
        helper.make_node('Einsum', ['input', 'rowsel0'], ['Wsc'], equation='bchw,h->b'),
        helper.make_node('Einsum', ['input', 'rowsel0'], ['Hsc'], equation='bchw,w->b'),
        helper.make_node('Less', ['arange30r', 'Hsc'], ['rowok']),
        helper.make_node('Less', ['arange30c', 'Wsc'], ['colok']),
        helper.make_node('Where', ['rowok', 'Rval', 'u255'], ['Rv']),
        helper.make_node('Where', ['colok', 'Cval', 'u255'], ['Cv']),
        helper.make_node('Max', ['Rv', 'Cv'], ['code']),
        helper.make_node('Equal', ['code', 'levels'], ['output']),
    ]
    value_infos = [
        helper.make_tensor_value_info('total', 1, [1, 10]),
        helper.make_tensor_value_info('colcount', 1, [1, 10]),
        helper.make_tensor_value_info('rowcount', 1, [1, 10]),
        helper.make_tensor_value_info('near', 1, [1, 10]),
        helper.make_tensor_value_info('nearok', 9, [1, 10]),
        helper.make_tensor_value_info('l45', 9, [1, 10]),
        helper.make_tensor_value_info('mk', 9, [1, 10]),
        helper.make_tensor_value_info('mki', 2, [1, 10]),
        helper.make_tensor_value_info('Marg', 7, [1]),
        helper.make_tensor_value_info('oMb', 9, [10]),
        helper.make_tensor_value_info('wc', 1, [10]),
        helper.make_tensor_value_info('Rvalf', 1, [1, 30]),
        helper.make_tensor_value_info('Cvalf', 1, [1, 30]),
        helper.make_tensor_value_info('Rvalu', 2, [1, 30]),
        helper.make_tensor_value_info('Cvalu', 2, [1, 30]),
        helper.make_tensor_value_info('Rval', 2, [1, 1, 30, 1]),
        helper.make_tensor_value_info('Cval', 2, [1, 1, 1, 30]),
        helper.make_tensor_value_info('Wsc', 1, [1]),
        helper.make_tensor_value_info('Hsc', 1, [1]),
        helper.make_tensor_value_info('rowok', 9, [1, 1, 30, 1]),
        helper.make_tensor_value_info('colok', 9, [1, 1, 1, 30]),
        helper.make_tensor_value_info('Rv', 2, [1, 1, 30, 1]),
        helper.make_tensor_value_info('Cv', 2, [1, 1, 1, 30]),
        helper.make_tensor_value_info('code', 2, [1, 1, 30, 30]),
    ]
    return model('task161_live_exact', nodes, inits, output_dtype=9, opset=13, value_infos=value_infos)
