"""Task 325 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('slice_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==')),
        tensor('slice_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAkAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAA==')),
        tensor('w_anchor', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDUsIDUpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA//////8BAAAA/wAAAAD/AAAAAP8AAAAA')),
        tensor('w_sum_h', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDQpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAQEB')),
        tensor('w_sum_v', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDQsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAQEB')),
        tensor('q_scale', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/')),
        tensor('u8_zp', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('i8_zp', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('one_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('pix8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAg9')),
        tensor('pix20', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAKQ9')),
        tensor('miss_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAA==')),
        tensor('miss_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAEAAAAAAAAAAwAAAAAAAAAKAAAAAAAAAA==')),
        tensor('w_miss', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDMsIDQpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAr8/Pz8/Pz8AQAAAQA=')),
        tensor('row_ids', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDYsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAA8AEAAQgBEAEU=')),
        tensor('col_ids', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDYpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAA8AEAAQgBEAEU=')),
        tensor('zero6', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGIxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDYsIDYpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAYAAAAAAAAABgAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'slice_starts', 'slice_ends'], ['occ']),
        helper.make_node('GlobalAveragePool', ['occ'], ['pix_avg']),
        helper.make_node('Cast', ['occ'], ['occ_u8'], to=2),
        helper.make_node('QLinearConv', ['occ_u8', 'q_scale', 'u8_zp', 'w_anchor', 'q_scale', 'i8_zp', 'q_scale', 'u8_zp'], ['anchor_u8'], pads=[1, 1, 1, 1]),
        helper.make_node('MaxPool', ['anchor_u8'], ['sum4x4'], ceil_mode=1, kernel_shape=[4, 4], strides=[4, 4]),
        helper.make_node('QLinearConv', ['sum4x4', 'q_scale', 'u8_zp', 'w_sum_h', 'q_scale', 'u8_zp', 'q_scale', 'u8_zp'], ['sum4x1']),
        helper.make_node('QLinearConv', ['sum4x1', 'q_scale', 'u8_zp', 'w_sum_v', 'q_scale', 'u8_zp', 'q_scale', 'u8_zp'], ['n0_u8']),
        helper.make_node('Cast', ['n0_u8'], ['n0'], to=10),
        helper.make_node('Equal', ['n0_u8', 'one_u8'], ['n_is1']),
        helper.make_node('Greater', ['pix_avg', 'pix8'], ['pix_gt8']),
        helper.make_node('Greater', ['pix_avg', 'pix20'], ['pix_gt20']),
        helper.make_node('And', ['n_is1', 'pix_gt8'], ['corr_a_b']),
        helper.make_node('And', ['n_is1', 'pix_gt20'], ['corr_b_b']),
        helper.make_node('Cast', ['corr_a_b'], ['corr_a'], to=10),
        helper.make_node('Cast', ['corr_b_b'], ['corr_b'], to=10),
        helper.make_node('Slice', ['occ_u8', 'miss_starts', 'miss_ends'], ['miss_patch']),
        helper.make_node('QLinearConv', ['miss_patch', 'q_scale', 'u8_zp', 'w_miss', 'q_scale', 'i8_zp', 'q_scale', 'u8_zp'], ['miss_score']),
        helper.make_node('Greater', ['miss_score', 'one_u8'], ['test_corr_b']),
        helper.make_node('Cast', ['test_corr_b'], ['test_corr'], to=10),
        helper.make_node('Sum', ['n0', 'corr_a', 'corr_a', 'corr_b', 'test_corr', 'test_corr'], ['n']),
        helper.make_node('Less', ['row_ids', 'n'], ['rowin']),
        helper.make_node('Less', ['col_ids', 'n'], ['colin']),
        helper.make_node('And', ['rowin', 'colin'], ['inside']),
        helper.make_node('Equal', ['row_ids', 'col_ids'], ['diagfull']),
        helper.make_node('And', ['inside', 'diagfull'], ['diag']),
        helper.make_node('Xor', ['inside', 'diag'], ['bg']),
        helper.make_node('Concat', ['bg', 'zero6', 'zero6', 'zero6', 'zero6', 'zero6', 'zero6', 'zero6', 'diag'], ['compact'], axis=1),
        helper.make_node('Pad', ['compact', 'pads'], ['output'], mode='constant'),
    ]
    value_infos = [
    ]
    return model('task325_live_exact', nodes, inits, output_dtype=9, opset=13, value_infos=value_infos)
