"""Task 274 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('gray_selector', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8AAAAAAAAAAAAAAAAAAAAA')),
        tensor('nonbg_selector', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8AAAAAAAAAAAAAAD8AAAAA')),
        tensor('row5_mask', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('one', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAPA==')),
        tensor('two', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAQA==')),
        tensor('four', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoARA==')),
        tensor('thresholds', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDMsIDMpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAOAA+AEHQY9BjAEPQY9Bj0GM=')),
        tensor('zero_small', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDMsIDMpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAA=')),
        tensor('one_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('pads_final', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAbAAAAAAAAABsAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'gray_selector'], ['gray_half'], equation='bchw,c->b'),
        helper.make_node('Cast', ['gray_half'], ['gray_half__h16'], to=10),
        helper.make_node('Einsum', ['input', 'nonbg_selector'], ['nonbg_half'], equation='bchw,c->b'),
        helper.make_node('Cast', ['nonbg_half'], ['nonbg_half__h16'], to=10),
        helper.make_node('Sub', ['nonbg_half__h16', 'gray_half__h16'], ['cyan_half']),
        helper.make_node('Einsum', ['input', 'nonbg_selector', 'row5_mask'], ['row5_half'], equation='bchw,c,h->b'),
        helper.make_node('Cast', ['row5_half'], ['row5_half__h16'], to=10),
        helper.make_node('Greater', ['row5_half__h16', 'one'], ['row5_is_base']),
        helper.make_node('Equal', ['row5_half__h16', 'one'], ['row5_is_empty']),
        helper.make_node('Where', ['row5_is_base', 'row5_half__h16', 'two'], ['base_half']),
        helper.make_node('Sub', ['gray_half__h16', 'base_half'], ['wall_height']),
        helper.make_node('Sub', ['base_half', 'one'], ['inner_half']),
        helper.make_node('Div', ['cyan_half', 'inner_half'], ['water_height']),
        helper.make_node('Sub', ['wall_height', 'water_height'], ['space_formula']),
        helper.make_node('Clip', ['space_formula', 'one', 'two'], ['space_row5_zero']),
        helper.make_node('Where', ['row5_is_empty', 'four', 'space_row5_zero'], ['space_nonbase']),
        helper.make_node('Where', ['row5_is_base', 'space_formula', 'space_nonbase'], ['space']),
        helper.make_node('Greater', ['space', 'thresholds'], ['out8_small_b']),
        helper.make_node('Cast', ['out8_small_b'], ['out8_small'], to=2),
        helper.make_node('Where', ['out8_small_b', 'zero_small', 'one_u8'], ['out0_small']),
        helper.make_node('Concat', ['out0_small', 'zero_small', 'zero_small', 'zero_small', 'zero_small', 'zero_small', 'zero_small', 'zero_small', 'out8_small'], ['small_output'], axis=1),
        helper.make_node('Pad', ['small_output', 'pads_final'], ['output'], mode='constant'),
    ]
    return model('task274_live_exact', nodes, inits, output_dtype=2, opset=12)
