"""Task 240 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('zero_cell', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('sentinel_tail', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDExKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoKCgoKCgoKCgoKCg==')),
        tensor('zero_row', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDMwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAACgoKCgoKCgoKCgo=')),
        tensor('sentinel_row', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDMwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgo=')),
        tensor('channel_ids', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJ')),
    ]
    nodes = [
        helper.make_node('MaxPool', ['input'], ['s0_pool'], dilations=[16, 16], kernel_shape=[2, 2], pads=[-1, -1, 0, 0], strides=[100, 100]),
        helper.make_node('ArgMax', ['s0_pool'], ['s0_color'], axis=1, keepdims=0, select_last_index=1),
        helper.make_node('Cast', ['s0_color'], ['s0_u8'], to=2),
        helper.make_node('MaxPool', ['input'], ['s1_pool'], dilations=[16, 12], kernel_shape=[2, 2], pads=[-1, -3, 0, 0], strides=[100, 100]),
        helper.make_node('ArgMax', ['s1_pool'], ['s1_color'], axis=1, keepdims=0, select_last_index=1),
        helper.make_node('Cast', ['s1_color'], ['s1_u8'], to=2),
        helper.make_node('MaxPool', ['input'], ['s2_pool'], dilations=[12, 12], kernel_shape=[2, 2], pads=[-3, -3, 0, 0], strides=[100, 100]),
        helper.make_node('ArgMax', ['s2_pool'], ['s2_color'], axis=1, keepdims=0, select_last_index=1),
        helper.make_node('Cast', ['s2_color'], ['s2_u8'], to=2),
        helper.make_node('MaxPool', ['input'], ['s3_pool'], dilations=[12, 8], kernel_shape=[2, 2], pads=[-3, -5, 0, 0], strides=[100, 100]),
        helper.make_node('ArgMax', ['s3_pool'], ['s3_color'], axis=1, keepdims=0, select_last_index=1),
        helper.make_node('Cast', ['s3_color'], ['s3_u8'], to=2),
        helper.make_node('MaxPool', ['input'], ['s4_pool'], dilations=[8, 8], kernel_shape=[2, 2], pads=[-5, -5, 0, 0], strides=[100, 100]),
        helper.make_node('ArgMax', ['s4_pool'], ['s4_color'], axis=1, keepdims=0, select_last_index=1),
        helper.make_node('Cast', ['s4_color'], ['s4_u8'], to=2),
        helper.make_node('MaxPool', ['input'], ['s5_pool'], dilations=[8, 4], kernel_shape=[2, 2], pads=[-5, -7, 0, 0], strides=[100, 100]),
        helper.make_node('ArgMax', ['s5_pool'], ['s5_color'], axis=1, keepdims=0, select_last_index=1),
        helper.make_node('Cast', ['s5_color'], ['s5_u8'], to=2),
        helper.make_node('MaxPool', ['input'], ['s6_pool'], dilations=[4, 4], kernel_shape=[2, 2], pads=[-7, -7, 0, 0], strides=[100, 100]),
        helper.make_node('ArgMax', ['s6_pool'], ['s6_color'], axis=1, keepdims=0, select_last_index=1),
        helper.make_node('Cast', ['s6_color'], ['s6_u8'], to=2),
        helper.make_node('Concat', ['zero_cell', 's0_u8', 'zero_cell', 's1_u8', 'zero_cell', 's1_u8', 'zero_cell', 's1_u8', 'zero_cell', 's1_u8', 'zero_cell', 's1_u8', 'zero_cell', 's1_u8', 'zero_cell', 's1_u8', 'zero_cell', 's0_u8', 'zero_cell', 'sentinel_tail'], ['row0'], axis=2),
        helper.make_node('Concat', ['zero_cell', 's1_u8', 'zero_cell', 's2_u8', 'zero_cell', 's3_u8', 'zero_cell', 's3_u8', 'zero_cell', 's3_u8', 'zero_cell', 's3_u8', 'zero_cell', 's3_u8', 'zero_cell', 's2_u8', 'zero_cell', 's1_u8', 'zero_cell', 'sentinel_tail'], ['row1'], axis=2),
        helper.make_node('Concat', ['zero_cell', 's1_u8', 'zero_cell', 's3_u8', 'zero_cell', 's4_u8', 'zero_cell', 's5_u8', 'zero_cell', 's5_u8', 'zero_cell', 's5_u8', 'zero_cell', 's4_u8', 'zero_cell', 's3_u8', 'zero_cell', 's1_u8', 'zero_cell', 'sentinel_tail'], ['row2'], axis=2),
        helper.make_node('Concat', ['zero_cell', 's1_u8', 'zero_cell', 's3_u8', 'zero_cell', 's5_u8', 'zero_cell', 's6_u8', 'zero_cell', 'zero_cell', 'zero_cell', 's6_u8', 'zero_cell', 's5_u8', 'zero_cell', 's3_u8', 'zero_cell', 's1_u8', 'zero_cell', 'sentinel_tail'], ['row3'], axis=2),
        helper.make_node('Concat', ['zero_cell', 's1_u8', 'zero_cell', 's3_u8', 'zero_cell', 's5_u8', 'zero_cell', 'zero_cell', 'zero_cell', 'zero_cell', 'zero_cell', 'zero_cell', 'zero_cell', 's5_u8', 'zero_cell', 's3_u8', 'zero_cell', 's1_u8', 'zero_cell', 'sentinel_tail'], ['row4'], axis=2),
        helper.make_node('Concat', ['zero_row', 'row0', 'zero_row', 'row1', 'zero_row', 'row2', 'zero_row', 'row3', 'zero_row', 'row4', 'zero_row', 'row3', 'zero_row', 'row2', 'zero_row', 'row1', 'zero_row', 'row0', 'zero_row', 'sentinel_row', 'sentinel_row', 'sentinel_row', 'sentinel_row', 'sentinel_row', 'sentinel_row', 'sentinel_row', 'sentinel_row', 'sentinel_row', 'sentinel_row', 'sentinel_row'], ['color_index_grid'], axis=1),
        helper.make_node('Equal', ['color_index_grid', 'channel_ids'], ['output']),
    ]
    value_infos = [
        helper.make_tensor_value_info('s0_pool', 1, [1, 10, 1, 1]),
        helper.make_tensor_value_info('s0_color', 7, [1, 1, 1]),
        helper.make_tensor_value_info('s0_u8', 2, [1, 1, 1]),
        helper.make_tensor_value_info('s1_pool', 1, [1, 10, 1, 1]),
        helper.make_tensor_value_info('s1_color', 7, [1, 1, 1]),
        helper.make_tensor_value_info('s1_u8', 2, [1, 1, 1]),
        helper.make_tensor_value_info('s2_pool', 1, [1, 10, 1, 1]),
        helper.make_tensor_value_info('s2_color', 7, [1, 1, 1]),
        helper.make_tensor_value_info('s2_u8', 2, [1, 1, 1]),
        helper.make_tensor_value_info('s3_pool', 1, [1, 10, 1, 1]),
        helper.make_tensor_value_info('s3_color', 7, [1, 1, 1]),
        helper.make_tensor_value_info('s3_u8', 2, [1, 1, 1]),
        helper.make_tensor_value_info('s4_pool', 1, [1, 10, 1, 1]),
        helper.make_tensor_value_info('s4_color', 7, [1, 1, 1]),
        helper.make_tensor_value_info('s4_u8', 2, [1, 1, 1]),
        helper.make_tensor_value_info('s5_pool', 1, [1, 10, 1, 1]),
        helper.make_tensor_value_info('s5_color', 7, [1, 1, 1]),
        helper.make_tensor_value_info('s5_u8', 2, [1, 1, 1]),
        helper.make_tensor_value_info('s6_pool', 1, [1, 10, 1, 1]),
        helper.make_tensor_value_info('s6_color', 7, [1, 1, 1]),
        helper.make_tensor_value_info('s6_u8', 2, [1, 1, 1]),
        helper.make_tensor_value_info('row0', 2, [1, 1, 30]),
        helper.make_tensor_value_info('row1', 2, [1, 1, 30]),
        helper.make_tensor_value_info('row2', 2, [1, 1, 30]),
        helper.make_tensor_value_info('row3', 2, [1, 1, 30]),
        helper.make_tensor_value_info('row4', 2, [1, 1, 30]),
        helper.make_tensor_value_info('color_index_grid', 2, [1, 30, 30]),
    ]
    return model('task240_live_exact', nodes, inits, output_dtype=9, opset=13, value_infos=value_infos)
