"""Task 357 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('ten_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoK')),
        tensor('one_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('two_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoC')),
        tensor('step_idx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEwLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoJCAcGBQQDAgEA')),
        tensor('col_idx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDEwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJ')),
        tensor('conv_w', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCAxLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQAAAAAAAP8A')),
    ]
    nodes = [
        helper.make_node('ReduceSum', ['input'], ['total_f'], keepdims=1),
        helper.make_node('Cast', ['total_f'], ['total_i'], to=2),
        helper.make_node('Div', ['total_i', 'ten_u8'], ['width_i']),
        helper.make_node('Sub', ['width_i', 'one_u8'], ['width_m1']),
        helper.make_node('Add', ['width_m1', 'width_m1'], ['period']),
        helper.make_node('Mod', ['step_idx', 'period'], ['phase'], fmod=0),
        helper.make_node('Sub', ['period', 'phase'], ['reflected_phase']),
        helper.make_node('Min', ['phase', 'reflected_phase'], ['path_col']),
        helper.make_node('Equal', ['col_idx', 'path_col'], ['path_b']),
        helper.make_node('Greater', ['col_idx', 'width_m1'], ['inactive_b']),
        helper.make_node('Cast', ['inactive_b'], ['inactive_code'], to=2),
        helper.make_node('Where', ['path_b', 'two_u8', 'inactive_code'], ['code']),
        helper.make_node('ConvInteger', ['code', 'conv_w', 'one_u8'], ['output'], kernel_shape=[1, 1], pads=[0, 0, 20, 20]),
    ]
    return model('task357_live_exact', nodes, inits, output_dtype=6, opset=14)
