"""Task 173 — exact source reconstruction of current live graph.

This builder owns the graph structure and constants in Python source and does
not load networks/task173.onnx at runtime.  The task is a documented
wall/complex heuristic, so this file preserves the verified live behavior as
source-controlled ONNX construction.
"""
from onnx import helper
from ._exact import arr_b64, model, tensor

def build(task):
    inits = [
        tensor('zero_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('one_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('two_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoC')),
        tensor('three_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoD')),
        tensor('four_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoE')),
        tensor('ten_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoK')),
        tensor('zero_f16', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAA==')),
        tensor('zero_f32', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAA')),
        tensor('width_i32', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoZAAAA')),
        tensor('four_i32', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoEAAAA')),
        tensor('shape_flat', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIApxAgAAAAAAAA==')),
        tensor('shape_pad_flat', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIApJAwAAAAAAAA==')),
        tensor('shape_pad_4d', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAEAAAAAAAAAHQAAAAAAAAAdAAAAAAAAAA==')),
        tensor('shape_outer_flat', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIApgAAAAAAAAAA==')),
        tensor('axes1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
        tensor('axes_hw', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAMAAAAAAAAA')),
        tensor('topk_pixels', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAozAAAAAAAAAA==')),
        tensor('topk_slots', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAA==')),
        tensor('topk_centers', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoMAAAAAAAAAA==')),
        tensor('class_ids', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJ')),
        tensor('zero_vec10', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAA')),
        tensor('crop_start', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAA')),
        tensor('crop_end', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoZAAAAAAAAABkAAAAAAAAA')),
        tensor('inner_start', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAIAAAAAAAAA')),
        tensor('inner_end', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAobAAAAAAAAABsAAAAAAAAA')),
        tensor('pad_2', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAA')),
        tensor('pad_to_30', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFAAAAAAAAAAUAAAAAAAAA')),
        tensor('outer_offsets', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDgpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoeAAAAIAAAAFgAAABaAAAAHwAAAFkAAAA7AAAAPQAAAA==')),
        tensor('outer_primary_family', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDgpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAQEBAgICAg==')),
        tensor('outer_secondary_family', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDgpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoJCQkJBAQDAw==')),
        tensor('c_u_offset', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAofAAAA')),
        tensor('c_d_offset', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIApZAAAA')),
        tensor('c_l_offset', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAo7AAAA')),
        tensor('c_r_offset', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAo9AAAA')),
        tensor('c_ul_offset', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoeAAAA')),
        tensor('c_ur_offset', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogAAAA')),
        tensor('c_dl_offset', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIApYAAAA')),
        tensor('c_dr_offset', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIApaAAAA')),
        tensor('pair_h_other_offset', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAo+AAAA')),
        tensor('pair_v_other_offset', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAp2AAAA')),
        tensor('pair_dr_other_offset', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAp4AAAA')),
        tensor('lv_amx_0', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBB')),
    ]
    nodes = [
        helper.make_node('Conv', ['input', 'lv_amx_0'], ['grid_i64'], kernel_shape=[1, 1]),
        helper.make_node('Cast', ['grid_i64'], ['grid_full'], to=2),
        helper.make_node('Slice', ['grid_full', 'crop_start', 'crop_end', 'axes_hw'], ['grid']),
        helper.make_node('Reshape', ['grid', 'shape_flat'], ['grid_flat']),
        helper.make_node('ReduceMax', ['input'], ['valid_rows_f'], axes=[1, 3], keepdims=1),
        helper.make_node('ReduceMax', ['input'], ['valid_cols_f'], axes=[1, 2], keepdims=1),
        helper.make_node('Greater', ['valid_rows_f', 'zero_f32'], ['valid_rows']),
        helper.make_node('Greater', ['valid_cols_f', 'zero_f32'], ['valid_cols']),
        helper.make_node('Slice', ['valid_rows', 'crop_start', 'crop_end', 'axes_hw'], ['valid_rows_crop']),
        helper.make_node('Slice', ['valid_cols', 'crop_start', 'crop_end', 'axes_hw'], ['valid_cols_crop']),
        helper.make_node('And', ['valid_rows_crop', 'valid_cols_crop'], ['valid_b_small']),
        helper.make_node('Cast', ['grid_flat'], ['grid_score'], to=10),
        helper.make_node('TopK', ['grid_score', 'topk_pixels'], ['pix_vals', 'pix_pos_i64'], axis=0, largest=1, sorted=1),
        helper.make_node('Cast', ['pix_pos_i64'], ['pix_pos'], to=6),
        helper.make_node('Cast', ['pix_vals'], ['pix_color'], to=2),
        helper.make_node('Cast', ['pix_color'], ['pix_color_i32'], to=6),
        helper.make_node('Pad', ['grid', 'pad_2', 'zero_u8'], ['grid_pad'], mode='constant'),
        helper.make_node('Reshape', ['grid_pad', 'shape_pad_flat'], ['grid_pad_flat']),
        helper.make_node('Div', ['pix_pos', 'width_i32'], ['pix_row']),
        helper.make_node('Mul', ['pix_row', 'four_i32'], ['pix_row4']),
        helper.make_node('Add', ['pix_pos', 'pix_row4'], ['pix_pad_tmp']),
        helper.make_node('Add', ['pix_pad_tmp', 'c_u_offset'], ['c_u_idx']),
        helper.make_node('Gather', ['grid_pad_flat', 'c_u_idx'], ['c_u'], axis=0),
        helper.make_node('Add', ['pix_pad_tmp', 'c_d_offset'], ['c_d_idx']),
        helper.make_node('Gather', ['grid_pad_flat', 'c_d_idx'], ['c_d'], axis=0),
        helper.make_node('Add', ['pix_pad_tmp', 'c_l_offset'], ['c_l_idx']),
        helper.make_node('Gather', ['grid_pad_flat', 'c_l_idx'], ['c_l'], axis=0),
        helper.make_node('Add', ['pix_pad_tmp', 'c_r_offset'], ['c_r_idx']),
        helper.make_node('Gather', ['grid_pad_flat', 'c_r_idx'], ['c_r'], axis=0),
        helper.make_node('Add', ['pix_pad_tmp', 'c_ul_offset'], ['c_ul_idx']),
        helper.make_node('Gather', ['grid_pad_flat', 'c_ul_idx'], ['c_ul'], axis=0),
        helper.make_node('Add', ['pix_pad_tmp', 'c_ur_offset'], ['c_ur_idx']),
        helper.make_node('Gather', ['grid_pad_flat', 'c_ur_idx'], ['c_ur'], axis=0),
        helper.make_node('Add', ['pix_pad_tmp', 'c_dl_offset'], ['c_dl_idx']),
        helper.make_node('Gather', ['grid_pad_flat', 'c_dl_idx'], ['c_dl'], axis=0),
        helper.make_node('Add', ['pix_pad_tmp', 'c_dr_offset'], ['c_dr_idx']),
        helper.make_node('Gather', ['grid_pad_flat', 'c_dr_idx'], ['c_dr'], axis=0),
        helper.make_node('Equal', ['c_l', 'c_r'], ['h_eq']),
        helper.make_node('Greater', ['c_l', 'zero_u8'], ['h_nz']),
        helper.make_node('And', ['h_eq', 'h_nz'], ['h_pat']),
        helper.make_node('Equal', ['c_u', 'c_d'], ['v_eq']),
        helper.make_node('Greater', ['c_u', 'zero_u8'], ['v_nz']),
        helper.make_node('And', ['v_eq', 'v_nz'], ['v_pat']),
        helper.make_node('Max', ['c_u', 'c_l', 'c_r', 'c_d'], ['p_max']),
        helper.make_node('Min', ['c_u', 'c_l', 'c_r', 'c_d'], ['p_min']),
        helper.make_node('Equal', ['p_max', 'p_min'], ['p_eq']),
        helper.make_node('Greater', ['p_max', 'zero_u8'], ['p_nz']),
        helper.make_node('And', ['p_eq', 'p_nz'], ['p_pat']),
        helper.make_node('Max', ['c_ul', 'c_ur', 'c_dl', 'c_dr'], ['x_max']),
        helper.make_node('Min', ['c_ul', 'c_ur', 'c_dl', 'c_dr'], ['x_min']),
        helper.make_node('Equal', ['x_max', 'x_min'], ['x_eq']),
        helper.make_node('Greater', ['x_max', 'zero_u8'], ['x_nz']),
        helper.make_node('And', ['x_eq', 'x_nz'], ['x_pat']),
        helper.make_node('Where', ['x_pat', 'one_u8', 'zero_u8'], ['fam_x']),
        helper.make_node('Where', ['h_pat', 'three_u8', 'fam_x'], ['fam_h']),
        helper.make_node('Where', ['v_pat', 'four_u8', 'fam_h'], ['fam_v']),
        helper.make_node('Where', ['p_pat', 'two_u8', 'fam_v'], ['family_code']),
        helper.make_node('Greater', ['family_code', 'zero_u8'], ['complete_any']),
        helper.make_node('Max', ['c_ul', 'c_u', 'c_l'], ['outer_color']),
        helper.make_node('Where', ['complete_any', 'pix_color', 'zero_u8'], ['proto_center']),
        helper.make_node('Cast', ['proto_center'], ['proto_center_f16'], to=10),
        helper.make_node('TopK', ['proto_center_f16', 'topk_slots'], ['slot_center_f16', 'slot_pos'], axis=0, largest=1, sorted=1),
        helper.make_node('Greater', ['slot_center_f16', 'zero_f16'], ['slot_present']),
        helper.make_node('Cast', ['slot_center_f16'], ['slot_center'], to=2),
        helper.make_node('Gather', ['outer_color', 'slot_pos'], ['slot_outer_raw'], axis=0),
        helper.make_node('Gather', ['family_code', 'slot_pos'], ['slot_family_raw'], axis=0),
        helper.make_node('Where', ['slot_present', 'slot_outer_raw', 'zero_u8'], ['slot_outer']),
        helper.make_node('Where', ['slot_present', 'slot_family_raw', 'zero_u8'], ['slot_family']),
        helper.make_node('Cast', ['slot_center'], ['slot_center_i32'], to=6),
        helper.make_node('Cast', ['slot_outer'], ['slot_outer_i32'], to=6),
        helper.make_node('ScatterElements', ['zero_vec10', 'slot_center_i32', 'slot_outer'], ['c2o'], axis=0, reduction='max'),
        helper.make_node('ScatterElements', ['zero_vec10', 'slot_center_i32', 'slot_family'], ['c2f'], axis=0, reduction='max'),
        helper.make_node('ScatterElements', ['zero_vec10', 'slot_outer_i32', 'slot_center'], ['o2c'], axis=0, reduction='max'),
        helper.make_node('ScatterElements', ['zero_vec10', 'slot_outer_i32', 'slot_family'], ['o2f'], axis=0, reduction='max'),
        helper.make_node('Gather', ['c2o', 'pix_color_i32'], ['point_outer'], axis=0),
        helper.make_node('Gather', ['c2f', 'pix_color_i32'], ['point_family'], axis=0),
        helper.make_node('Cast', ['point_outer'], ['point_outer_f16'], to=10),
        helper.make_node('TopK', ['point_outer_f16', 'topk_centers'], ['center_vals', 'center_sel'], axis=0, largest=1, sorted=1),
        helper.make_node('Greater', ['center_vals', 'zero_f16'], ['center_valid']),
        helper.make_node('Cast', ['center_vals'], ['sel_outer'], to=2),
        helper.make_node('Gather', ['pix_pad_tmp', 'center_sel'], ['sel_center_pad'], axis=0),
        helper.make_node('Gather', ['point_family', 'center_sel'], ['sel_family'], axis=0),
        helper.make_node('Unsqueeze', ['sel_center_pad', 'axes1'], ['sel_center_pad_col']),
        helper.make_node('Add', ['sel_center_pad_col', 'outer_offsets'], ['outer_dest']),
        helper.make_node('Unsqueeze', ['sel_family', 'axes1'], ['sel_family_col']),
        helper.make_node('Equal', ['sel_family_col', 'outer_primary_family'], ['outer_primary_match']),
        helper.make_node('Equal', ['sel_family_col', 'outer_secondary_family'], ['outer_secondary_match']),
        helper.make_node('Or', ['outer_primary_match', 'outer_secondary_match'], ['outer_family_match']),
        helper.make_node('Unsqueeze', ['center_valid', 'axes1'], ['center_valid_col']),
        helper.make_node('And', ['outer_family_match', 'center_valid_col'], ['outer_valid']),
        helper.make_node('Unsqueeze', ['sel_outer', 'axes1'], ['sel_outer_col']),
        helper.make_node('Where', ['outer_valid', 'sel_outer_col', 'zero_u8'], ['outer_updates']),
        helper.make_node('Reshape', ['outer_dest', 'shape_outer_flat'], ['outer_dest_flat']),
        helper.make_node('Reshape', ['outer_updates', 'shape_outer_flat'], ['outer_updates_flat']),
        helper.make_node('Gather', ['o2c', 'pix_color_i32'], ['point_center'], axis=0),
        helper.make_node('Gather', ['o2f', 'pix_color_i32'], ['point_outer_family'], axis=0),
        helper.make_node('Equal', ['point_outer_family', 'one_u8'], ['fam_x_ok']),
        helper.make_node('Equal', ['point_outer_family', 'two_u8'], ['fam_p_ok']),
        helper.make_node('Equal', ['point_outer_family', 'three_u8'], ['fam_h_ok']),
        helper.make_node('Equal', ['point_outer_family', 'four_u8'], ['fam_v_ok']),
        helper.make_node('Or', ['fam_p_ok', 'fam_h_ok'], ['fam_hp_ok']),
        helper.make_node('Add', ['pix_pad_tmp', 'pair_h_other_offset'], ['pair_h_other_idx']),
        helper.make_node('Gather', ['grid_pad_flat', 'pair_h_other_idx'], ['pair_h_other'], axis=0),
        helper.make_node('Equal', ['pair_h_other', 'pix_color'], ['pair_h_same']),
        helper.make_node('And', ['pair_h_same', 'fam_hp_ok'], ['pair_h_valid']),
        helper.make_node('Where', ['pair_h_valid', 'point_center', 'zero_u8'], ['pair_h_color']),
        helper.make_node('Add', ['pix_pad_tmp', 'pair_v_other_offset'], ['pair_v_other_idx']),
        helper.make_node('Gather', ['grid_pad_flat', 'pair_v_other_idx'], ['pair_v_other'], axis=0),
        helper.make_node('Equal', ['pair_v_other', 'pix_color'], ['pair_v_same']),
        helper.make_node('And', ['pair_v_same', 'fam_v_ok'], ['pair_v_valid']),
        helper.make_node('Where', ['pair_v_valid', 'point_center', 'zero_u8'], ['pair_v_color']),
        helper.make_node('Add', ['pix_pad_tmp', 'pair_dr_other_offset'], ['pair_dr_other_idx']),
        helper.make_node('Gather', ['grid_pad_flat', 'pair_dr_other_idx'], ['pair_dr_other'], axis=0),
        helper.make_node('Equal', ['pair_dr_other', 'pix_color'], ['pair_dr_same']),
        helper.make_node('And', ['pair_dr_same', 'fam_x_ok'], ['pair_dr_valid']),
        helper.make_node('Where', ['pair_dr_valid', 'point_center', 'zero_u8'], ['pair_dr_color']),
        helper.make_node('Concat', ['outer_dest_flat', 'c_r_idx', 'c_d_idx', 'c_dr_idx'], ['fill_dest'], axis=0),
        helper.make_node('Concat', ['outer_updates_flat', 'pair_h_color', 'pair_v_color', 'pair_dr_color'], ['fill_color'], axis=0),
        helper.make_node('ScatterElements', ['grid_pad_flat', 'fill_dest', 'fill_color'], ['out_pad_flat'], axis=0, reduction='max'),
        helper.make_node('Reshape', ['out_pad_flat', 'shape_pad_4d'], ['out_pad_grid']),
        helper.make_node('Slice', ['out_pad_grid', 'inner_start', 'inner_end', 'axes_hw'], ['out_grid_small']),
        helper.make_node('Where', ['valid_b_small', 'out_grid_small', 'ten_u8'], ['out_idx_small']),
        helper.make_node('Pad', ['out_idx_small', 'pad_to_30', 'ten_u8'], ['out_idx'], mode='constant'),
        helper.make_node('Equal', ['out_idx', 'class_ids'], ['output']),
    ]
    value_infos = [
        helper.make_tensor_value_info('grid_i64', 1, [1, 1, 30, 30]),
        helper.make_tensor_value_info('grid_full', 2, [1, 1, 30, 30]),
        helper.make_tensor_value_info('grid', 2, [1, 1, 25, 25]),
        helper.make_tensor_value_info('grid_flat', 2, [625]),
        helper.make_tensor_value_info('valid_rows_f', 1, [1, 1, 30, 1]),
        helper.make_tensor_value_info('valid_cols_f', 1, [1, 1, 1, 30]),
        helper.make_tensor_value_info('valid_rows', 9, [1, 1, 30, 1]),
        helper.make_tensor_value_info('valid_cols', 9, [1, 1, 1, 30]),
        helper.make_tensor_value_info('valid_rows_crop', 9, [1, 1, 25, 1]),
        helper.make_tensor_value_info('valid_cols_crop', 9, [1, 1, 1, 25]),
        helper.make_tensor_value_info('valid_b_small', 9, [1, 1, 25, 25]),
        helper.make_tensor_value_info('grid_score', 10, [625]),
        helper.make_tensor_value_info('pix_vals', 10, [51]),
        helper.make_tensor_value_info('pix_pos_i64', 7, [51]),
        helper.make_tensor_value_info('pix_pos', 6, [51]),
        helper.make_tensor_value_info('pix_color', 2, [51]),
        helper.make_tensor_value_info('pix_color_i32', 6, [51]),
        helper.make_tensor_value_info('grid_pad', 2, [1, 1, 29, 29]),
        helper.make_tensor_value_info('grid_pad_flat', 2, [841]),
        helper.make_tensor_value_info('pix_row', 6, [51]),
        helper.make_tensor_value_info('pix_row4', 6, [51]),
        helper.make_tensor_value_info('pix_pad_tmp', 6, [51]),
        helper.make_tensor_value_info('c_u_idx', 6, [51]),
        helper.make_tensor_value_info('c_u', 2, [51]),
        helper.make_tensor_value_info('c_d_idx', 6, [51]),
        helper.make_tensor_value_info('c_d', 2, [51]),
        helper.make_tensor_value_info('c_l_idx', 6, [51]),
        helper.make_tensor_value_info('c_l', 2, [51]),
        helper.make_tensor_value_info('c_r_idx', 6, [51]),
        helper.make_tensor_value_info('c_r', 2, [51]),
        helper.make_tensor_value_info('c_ul_idx', 6, [51]),
        helper.make_tensor_value_info('c_ul', 2, [51]),
        helper.make_tensor_value_info('c_ur_idx', 6, [51]),
        helper.make_tensor_value_info('c_ur', 2, [51]),
        helper.make_tensor_value_info('c_dl_idx', 6, [51]),
        helper.make_tensor_value_info('c_dl', 2, [51]),
        helper.make_tensor_value_info('c_dr_idx', 6, [51]),
        helper.make_tensor_value_info('c_dr', 2, [51]),
        helper.make_tensor_value_info('h_eq', 9, [51]),
        helper.make_tensor_value_info('h_nz', 9, [51]),
        helper.make_tensor_value_info('h_pat', 9, [51]),
        helper.make_tensor_value_info('v_eq', 9, [51]),
        helper.make_tensor_value_info('v_nz', 9, [51]),
        helper.make_tensor_value_info('v_pat', 9, [51]),
        helper.make_tensor_value_info('p_max', 2, [51]),
        helper.make_tensor_value_info('p_min', 2, [51]),
        helper.make_tensor_value_info('p_eq', 9, [51]),
        helper.make_tensor_value_info('p_nz', 9, [51]),
        helper.make_tensor_value_info('p_pat', 9, [51]),
        helper.make_tensor_value_info('x_max', 2, [51]),
        helper.make_tensor_value_info('x_min', 2, [51]),
        helper.make_tensor_value_info('x_eq', 9, [51]),
        helper.make_tensor_value_info('x_nz', 9, [51]),
        helper.make_tensor_value_info('x_pat', 9, [51]),
        helper.make_tensor_value_info('fam_x', 2, [51]),
        helper.make_tensor_value_info('fam_h', 2, [51]),
        helper.make_tensor_value_info('fam_v', 2, [51]),
        helper.make_tensor_value_info('family_code', 2, [51]),
        helper.make_tensor_value_info('complete_any', 9, [51]),
        helper.make_tensor_value_info('outer_color', 2, [51]),
        helper.make_tensor_value_info('proto_center', 2, [51]),
        helper.make_tensor_value_info('proto_center_f16', 10, [51]),
        helper.make_tensor_value_info('slot_center_f16', 10, [3]),
        helper.make_tensor_value_info('slot_pos', 7, [3]),
        helper.make_tensor_value_info('slot_present', 9, [3]),
        helper.make_tensor_value_info('slot_center', 2, [3]),
        helper.make_tensor_value_info('slot_outer_raw', 2, [3]),
        helper.make_tensor_value_info('slot_family_raw', 2, [3]),
        helper.make_tensor_value_info('slot_outer', 2, [3]),
        helper.make_tensor_value_info('slot_family', 2, [3]),
        helper.make_tensor_value_info('slot_center_i32', 6, [3]),
        helper.make_tensor_value_info('slot_outer_i32', 6, [3]),
        helper.make_tensor_value_info('c2o', 2, [10]),
        helper.make_tensor_value_info('c2f', 2, [10]),
        helper.make_tensor_value_info('o2c', 2, [10]),
        helper.make_tensor_value_info('o2f', 2, [10]),
        helper.make_tensor_value_info('point_outer', 2, [51]),
        helper.make_tensor_value_info('point_family', 2, [51]),
        helper.make_tensor_value_info('point_outer_f16', 10, [51]),
        helper.make_tensor_value_info('center_vals', 10, [12]),
        helper.make_tensor_value_info('center_sel', 7, [12]),
        helper.make_tensor_value_info('center_valid', 9, [12]),
        helper.make_tensor_value_info('sel_outer', 2, [12]),
        helper.make_tensor_value_info('sel_center_pad', 6, [12]),
        helper.make_tensor_value_info('sel_family', 2, [12]),
        helper.make_tensor_value_info('sel_center_pad_col', 6, [12, 1]),
        helper.make_tensor_value_info('outer_dest', 6, [12, 8]),
        helper.make_tensor_value_info('sel_family_col', 2, [12, 1]),
        helper.make_tensor_value_info('outer_primary_match', 9, [12, 8]),
        helper.make_tensor_value_info('outer_secondary_match', 9, [12, 8]),
        helper.make_tensor_value_info('outer_family_match', 9, [12, 8]),
        helper.make_tensor_value_info('center_valid_col', 9, [12, 1]),
        helper.make_tensor_value_info('outer_valid', 9, [12, 8]),
        helper.make_tensor_value_info('sel_outer_col', 2, [12, 1]),
        helper.make_tensor_value_info('outer_updates', 2, [12, 8]),
        helper.make_tensor_value_info('outer_dest_flat', 6, [96]),
        helper.make_tensor_value_info('outer_updates_flat', 2, [96]),
        helper.make_tensor_value_info('point_center', 2, [51]),
        helper.make_tensor_value_info('point_outer_family', 2, [51]),
        helper.make_tensor_value_info('fam_x_ok', 9, [51]),
        helper.make_tensor_value_info('fam_p_ok', 9, [51]),
        helper.make_tensor_value_info('fam_h_ok', 9, [51]),
        helper.make_tensor_value_info('fam_v_ok', 9, [51]),
        helper.make_tensor_value_info('fam_hp_ok', 9, [51]),
        helper.make_tensor_value_info('pair_h_other_idx', 6, [51]),
        helper.make_tensor_value_info('pair_h_other', 2, [51]),
        helper.make_tensor_value_info('pair_h_same', 9, [51]),
        helper.make_tensor_value_info('pair_h_valid', 9, [51]),
        helper.make_tensor_value_info('pair_h_color', 2, [51]),
        helper.make_tensor_value_info('pair_v_other_idx', 6, [51]),
        helper.make_tensor_value_info('pair_v_other', 2, [51]),
        helper.make_tensor_value_info('pair_v_same', 9, [51]),
        helper.make_tensor_value_info('pair_v_valid', 9, [51]),
        helper.make_tensor_value_info('pair_v_color', 2, [51]),
        helper.make_tensor_value_info('pair_dr_other_idx', 6, [51]),
        helper.make_tensor_value_info('pair_dr_other', 2, [51]),
        helper.make_tensor_value_info('pair_dr_same', 9, [51]),
        helper.make_tensor_value_info('pair_dr_valid', 9, [51]),
        helper.make_tensor_value_info('pair_dr_color', 2, [51]),
        helper.make_tensor_value_info('fill_dest', 6, [249]),
        helper.make_tensor_value_info('fill_color', 2, [249]),
        helper.make_tensor_value_info('out_pad_flat', 2, [841]),
        helper.make_tensor_value_info('out_pad_grid', 2, [1, 1, 29, 29]),
        helper.make_tensor_value_info('out_grid_small', 2, [1, 1, 25, 25]),
        helper.make_tensor_value_info('out_idx_small', 2, [1, 1, 25, 25]),
        helper.make_tensor_value_info('out_idx', 2, [1, 1, 30, 30]),
    ]
    return model('task173', nodes, inits, output_dtype=9, opset=16, value_infos=value_infos)
