"""Task 143 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('p1_30', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBBAAAgQQAAMEEAAEBBAABQQQAAYEEAAHBBAACAQQAAiEEAAJBBAACYQQAAoEEAAKhBAACwQQAAuEEAAMBBAADIQQAA0EEAANhBAADgQQAA6EE=')),
        tensor('p1_3', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAA8AEA=')),
        tensor('ref_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('ref_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAMAAAAAAAAAAwAAAAAAAAA=')),
        tensor('ref_axes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAA=')),
        tensor('one_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/')),
        tensor('selector_if_target', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPw==')),
        tensor('selector_if_other', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AAAAAA==')),
        tensor('channel_map', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsIDEwLCAxMCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAAAAAAAAAA==')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'ref_starts', 'ref_ends', 'ref_axes'], ['ref_bg']),
        helper.make_node('Less', ['ref_bg', 'one_f'], ['ref_occ']),
        helper.make_node('Cast', ['ref_occ'], ['ref_occ_h'], to=10),
        helper.make_node('Einsum', ['input', 'one_f'], ['count'], equation='bchw,z->bc'),
        helper.make_node('Einsum', ['input', 'p1_30'], ['row_m1'], equation='bchw,h->bc'),
        helper.make_node('Einsum', ['input', 'p1_30', 'p1_30'], ['row_m2'], equation='bchw,h,h->bc'),
        helper.make_node('Einsum', ['input', 'p1_30'], ['col_m1'], equation='bchw,w->bc'),
        helper.make_node('ReduceSum', ['ref_occ_h'], ['ref_count_h'], axes=[2, 3], keepdims=0),
        helper.make_node('Einsum', ['ref_occ_h', 'p1_3'], ['ref_row_m1_h'], equation='bchw,h->bc'),
        helper.make_node('Einsum', ['ref_occ_h', 'p1_3', 'p1_3'], ['ref_row_m2_h'], equation='bchw,h,h->bc'),
        helper.make_node('Einsum', ['ref_occ_h', 'p1_3'], ['ref_col_m1_h'], equation='bchw,w->bc'),
        helper.make_node('Cast', ['count'], ['count_h'], to=10),
        helper.make_node('Cast', ['row_m1'], ['r_m1'], to=10),
        helper.make_node('Cast', ['row_m2'], ['r_m2'], to=10),
        helper.make_node('Cast', ['col_m1'], ['c_m1'], to=10),
        helper.make_node('Mul', ['r_m1', 'r_m1'], ['r_m1_sq']),
        helper.make_node('Mul', ['count_h', 'r_m2'], ['r_n_m2']),
        helper.make_node('Sub', ['r_n_m2', 'r_m1_sq'], ['r_mu2']),
        helper.make_node('Mod', ['r_m1', 'count_h'], ['r_mod'], fmod=1),
        helper.make_node('Mod', ['c_m1', 'count_h'], ['c_mod'], fmod=1),
        helper.make_node('Mul', ['ref_row_m1_h', 'ref_row_m1_h'], ['rr_m1_sq']),
        helper.make_node('Mul', ['ref_count_h', 'ref_row_m2_h'], ['rr_n_m2']),
        helper.make_node('Sub', ['rr_n_m2', 'rr_m1_sq'], ['rr_mu2']),
        helper.make_node('Mod', ['ref_row_m1_h', 'ref_count_h'], ['rr_mod'], fmod=1),
        helper.make_node('Mod', ['ref_col_m1_h', 'ref_count_h'], ['rc_mod'], fmod=1),
        helper.make_node('Equal', ['r_mu2', 'rr_mu2'], ['r_mu2_eq']),
        helper.make_node('Equal', ['r_mod', 'rr_mod'], ['r_mod_eq']),
        helper.make_node('Equal', ['c_mod', 'rc_mod'], ['c_mod_eq']),
        helper.make_node('And', ['r_mu2_eq', 'r_mod_eq'], ['shape_match_1']),
        helper.make_node('And', ['shape_match_1', 'c_mod_eq'], ['shape_match_2']),
        helper.make_node('Greater', ['r_m1', 'ref_row_m1_h'], ['below_ref']),
        helper.make_node('Greater', ['c_m1', 'ref_col_m1_h'], ['right_ref']),
        helper.make_node('Or', ['below_ref', 'right_ref'], ['outside_ref']),
        helper.make_node('And', ['shape_match_2', 'outside_ref'], ['target_ch']),
        helper.make_node('Where', ['target_ch', 'selector_if_target', 'selector_if_other'], ['selector']),
        helper.make_node('Einsum', ['input', 'selector', 'channel_map'], ['output'], equation='bchw,sc,sco->bohw'),
    ]
    return model('task143_live_exact', nodes, inits, output_dtype=1, opset=12)
