"""Task 353 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('color_selector', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsIDEwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAvwAAgD8AAAAAAAAAAAAAAAAAAAAAAAAAAA==')),
        tensor('coord30', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBBAAAgQQAAMEEAAEBBAABQQQAAYEEAAHBBAACAQQAAiEEAAJBBAACYQQAAoEEAAKhBAACwQQAAuEEAAMBBAADIQQAA0EEAANhBAADgQQAA6EE=')),
        tensor('batch_col', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==')),
        tensor('channel_col', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAA==')),
        tensor('updates', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAAAAAIA/')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'color_selector', 'coord30'], ['row_desc'], equation='bchw,kc,h->bk'),
        helper.make_node('Einsum', ['input', 'color_selector', 'coord30'], ['col_desc'], equation='bchw,kc,w->bk'),
        helper.make_node('Split', ['row_desc'], ['row3', 'row_delta'], axis=1, split=[1, 1]),
        helper.make_node('Split', ['col_desc'], ['col3', 'col_delta'], axis=1, split=[1, 1]),
        helper.make_node('Sign', ['row_delta'], ['row_step']),
        helper.make_node('Sign', ['col_delta'], ['col_step']),
        helper.make_node('Add', ['row3', 'row_step'], ['new_row']),
        helper.make_node('Add', ['col3', 'col_step'], ['new_col']),
        helper.make_node('Concat', ['row3', 'row3', 'new_row', 'new_row'], ['rows_f'], axis=0),
        helper.make_node('Concat', ['col3', 'col3', 'new_col', 'new_col'], ['cols_f'], axis=0),
        helper.make_node('Cast', ['rows_f'], ['rows'], to=7),
        helper.make_node('Cast', ['cols_f'], ['cols'], to=7),
        helper.make_node('Concat', ['batch_col', 'channel_col', 'rows', 'cols'], ['indices'], axis=1),
        helper.make_node('ScatterND', ['input', 'indices', 'updates'], ['output']),
    ]
    return model('task353_live_exact', nodes, inits, output_dtype=1, opset=12)
