"""Task 206 — exact source reconstruction of current live graph.

Generated by tools/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('sel5', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgD8AAAAAAAAAAAAAAAAAAAAA')),
        tensor('selt', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAgD8AAIA/AACAPwAAAAAAAIA/AACAPwAAgD8AAIA/')),
        tensor('iota', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBBAAAgQQAAMEEAAEBBAABQQQAAYEEAAHBBAACAQQAAiEEAAJBBAACYQQAAoEEAAKhBAACwQQAAuEEAAMBBAADIQQAA0EEAANhBAADgQQAA6EE=')),
        tensor('c15', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAMA/')),
        tensor('base_hw', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDE4LCAyKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAr///////////////////////////////8AAAAAAAAAAP//////////AQAAAAAAAAAAAAAAAAAAAP//////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAP//////////AQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAD///////////////////////////////8AAAAAAAAAAP//////////AQAAAAAAAAAAAAAAAAAAAP//////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAP//////////AQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAA=')),
        tensor('clearc', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDksIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('bcol', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDE4LCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('upd', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDE4LCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8=')),
        tensor('shape91', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoJAAAAAAAAAAEAAAAAAAAA')),
        tensor('roibatch', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAA==')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'sel5', 'iota'], ['r5f'], equation='nchw,c,h->'),
        helper.make_node('Einsum', ['input', 'sel5', 'iota'], ['c5f'], equation='nchw,c,w->'),
        helper.make_node('Einsum', ['input', 'selt', 'iota'], ['tnr'], equation='nchw,c,h->'),
        helper.make_node('Einsum', ['input', 'selt', 'iota'], ['tnc'], equation='nchw,c,w->'),
        helper.make_node('Einsum', ['input', 'selt'], ['tden'], equation='nchw,c->'),
        helper.make_node('Div', ['tnr', 'tden'], ['cenR']),
        helper.make_node('Div', ['tnc', 'tden'], ['cenC']),
        helper.make_node('Round', ['cenR'], ['ctrR']),
        helper.make_node('Sub', ['cenC', 'c15'], ['x1']),
        helper.make_node('Sub', ['ctrR', 'c15'], ['y1']),
        helper.make_node('Add', ['cenC', 'c15'], ['x2']),
        helper.make_node('Add', ['ctrR', 'c15'], ['y2']),
        helper.make_node('Unsqueeze', ['x1'], ['x1u'], axes=[0]),
        helper.make_node('Unsqueeze', ['y1'], ['y1u'], axes=[0]),
        helper.make_node('Unsqueeze', ['x2'], ['x2u'], axes=[0]),
        helper.make_node('Unsqueeze', ['y2'], ['y2u'], axes=[0]),
        helper.make_node('Concat', ['x1u', 'y1u', 'x2u', 'y2u'], ['rois4'], axis=0),
        helper.make_node('Unsqueeze', ['rois4'], ['rois'], axes=[0]),
        helper.make_node('RoiAlign', ['input', 'rois', 'roibatch'], ['troi'], mode='avg', output_height=3, output_width=3, sampling_ratio=1, spatial_scale=1.0),
        helper.make_node('ArgMax', ['troi'], ['chg'], axis=1, keepdims=0),
        helper.make_node('Reshape', ['chg', 'shape91'], ['ch9']),
        helper.make_node('Unsqueeze', ['r5f'], ['r5i'], axes=[0, 1]),
        helper.make_node('Cast', ['r5i'], ['r5u'], name='r5u', to=7),
        helper.make_node('Unsqueeze', ['c5f'], ['c5i'], axes=[0, 1]),
        helper.make_node('Cast', ['c5i'], ['c5u'], name='c5u', to=7),
        helper.make_node('Concat', ['r5u', 'c5u'], ['rc'], axis=1),
        helper.make_node('Add', ['base_hw', 'rc'], ['hw']),
        helper.make_node('Concat', ['clearc', 'ch9'], ['ccol'], axis=0),
        helper.make_node('Concat', ['bcol', 'ccol', 'hw'], ['idx'], axis=1),
        helper.make_node('ScatterND', ['input', 'idx', 'upd'], ['output']),
    ]
    value_infos = [
        helper.make_tensor_value_info('r5f', 1, []),
        helper.make_tensor_value_info('c5f', 1, []),
        helper.make_tensor_value_info('tnr', 1, []),
        helper.make_tensor_value_info('tnc', 1, []),
        helper.make_tensor_value_info('tden', 1, []),
        helper.make_tensor_value_info('cenR', 1, []),
        helper.make_tensor_value_info('cenC', 1, []),
        helper.make_tensor_value_info('ctrR', 1, []),
        helper.make_tensor_value_info('x1', 1, []),
        helper.make_tensor_value_info('y1', 1, []),
        helper.make_tensor_value_info('x2', 1, []),
        helper.make_tensor_value_info('y2', 1, []),
        helper.make_tensor_value_info('x1u', 1, [1]),
        helper.make_tensor_value_info('y1u', 1, [1]),
        helper.make_tensor_value_info('x2u', 1, [1]),
        helper.make_tensor_value_info('y2u', 1, [1]),
        helper.make_tensor_value_info('rois4', 1, [4]),
        helper.make_tensor_value_info('rois', 1, [1, 4]),
        helper.make_tensor_value_info('troi', 1, [1, 10, 3, 3]),
        helper.make_tensor_value_info('chg', 7, [1, 3, 3]),
        helper.make_tensor_value_info('ch9', 7, [9, 1]),
        helper.make_tensor_value_info('r5i', 1, [1, 1]),
        helper.make_tensor_value_info('r5u', 7, [1, 1]),
        helper.make_tensor_value_info('c5i', 1, [1, 1]),
        helper.make_tensor_value_info('c5u', 7, [1, 1]),
        helper.make_tensor_value_info('rc', 7, [1, 2]),
        helper.make_tensor_value_info('hw', 7, [18, 2]),
        helper.make_tensor_value_info('ccol', 7, [18, 1]),
        helper.make_tensor_value_info('idx', 7, [18, 4]),
    ]
    return model('task206_live_exact', nodes, inits, output_dtype=1, opset=12, value_infos=value_infos)
