"""Task 029 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('minus_four_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIDA')),
        tensor('thirty_i32', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoeAAAA')),
        tensor('range1_30_i32', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAgAAAAMAAAAEAAAABQAAAAYAAAAHAAAACAAAAAkAAAAKAAAACwAAAAwAAAANAAAADgAAAA8AAAAQAAAAEQAAABIAAAATAAAAFAAAABUAAAAWAAAAFwAAABgAAAAZAAAAGgAAABsAAAAcAAAAHQAAAB4AAAA=')),
        tensor('onehot_values', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPw==')),
    ]
    nodes = [
        helper.make_node('ReduceSum', ['input'], ['row_counts'], axes=[3], keepdims=1),
        helper.make_node('ReduceSum', ['input'], ['col_counts'], axes=[2], keepdims=1),
        helper.make_node('ReduceSum', ['row_counts'], ['total_count'], axes=[2], keepdims=1),
        helper.make_node('ReduceMax', ['row_counts'], ['row_max'], axes=[2], keepdims=1),
        helper.make_node('ReduceMax', ['col_counts'], ['col_max'], axes=[3], keepdims=1),
        helper.make_node('Sum', ['row_max', 'row_max', 'col_max', 'col_max', 'minus_four_f'], ['perim_count']),
        helper.make_node('Equal', ['total_count', 'perim_count'], ['total_ok_b']),
        helper.make_node('ArgMax', ['row_counts'], ['row_first_by_color'], axis=2, keepdims=1),
        helper.make_node('ArgMax', ['row_counts'], ['row_last_by_color'], axis=2, keepdims=1, select_last_index=1),
        helper.make_node('ArgMax', ['col_counts'], ['col_first_by_color'], axis=3, keepdims=1),
        helper.make_node('ArgMax', ['col_counts'], ['col_last_by_color'], axis=3, keepdims=1, select_last_index=1),
        helper.make_node('Cast', ['total_ok_b'], ['valid_u8'], to=2),
        helper.make_node('ArgMax', ['valid_u8'], ['color_idx_3d'], axis=1, keepdims=0),
        helper.make_node('Gather', ['row_first_by_color', 'color_idx_3d'], ['row_start_3d'], axis=1),
        helper.make_node('Squeeze', ['row_start_3d'], ['row_start_idx'], axes=[0, 1, 2, 3, 4, 5]),
        helper.make_node('Gather', ['row_last_by_color', 'color_idx_3d'], ['row_end_3d'], axis=1),
        helper.make_node('Squeeze', ['row_end_3d'], ['row_end_idx'], axes=[0, 1, 2, 3, 4, 5]),
        helper.make_node('Gather', ['col_first_by_color', 'color_idx_3d'], ['col_start_3d'], axis=1),
        helper.make_node('Squeeze', ['col_start_3d'], ['col_start_idx'], axes=[0, 1, 2, 3, 4, 5]),
        helper.make_node('Gather', ['col_last_by_color', 'color_idx_3d'], ['col_end_3d'], axis=1),
        helper.make_node('Squeeze', ['col_end_3d'], ['col_end_idx'], axes=[0, 1, 2, 3, 4, 5]),
        helper.make_node('Cast', ['row_start_idx'], ['row_start_i32'], to=6),
        helper.make_node('Cast', ['row_end_idx'], ['row_end_i32'], to=6),
        helper.make_node('Cast', ['col_start_idx'], ['col_start_i32'], to=6),
        helper.make_node('Cast', ['col_end_idx'], ['col_end_i32'], to=6),
        helper.make_node('Sub', ['row_end_i32', 'row_start_i32'], ['row_span']),
        helper.make_node('Add', ['range1_30_i32', 'row_start_i32'], ['row_src_raw']),
        helper.make_node('Less', ['range1_30_i32', 'row_span'], ['row_src_valid_b']),
        helper.make_node('Where', ['row_src_valid_b', 'row_src_raw', 'thirty_i32'], ['row_src']),
        helper.make_node('OneHot', ['row_src', 'thirty_i32', 'onehot_values'], ['row_selector'], axis=-1),
        helper.make_node('Sub', ['col_end_i32', 'col_start_i32'], ['col_span']),
        helper.make_node('Add', ['range1_30_i32', 'col_start_i32'], ['col_src_raw']),
        helper.make_node('Less', ['range1_30_i32', 'col_span'], ['col_src_valid_b']),
        helper.make_node('Where', ['col_src_valid_b', 'col_src_raw', 'thirty_i32'], ['col_src']),
        helper.make_node('OneHot', ['col_src', 'thirty_i32', 'onehot_values'], ['col_selector'], axis=-1),
        helper.make_node('Einsum', ['input', 'row_selector', 'col_selector'], ['output'], equation='bcrs,ir,js->bcij'),
    ]
    value_infos = [
    ]
    return model('task029_live_exact', nodes, inits, output_dtype=1, opset=12, value_infos=value_infos)
