"""Task 260 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('slice5_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==')),
        tensor('slice5_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAYAAAAAAAAACgAAAAAAAAAKAAAAAAAAAA==')),
        tensor('endpoint_indices', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDExLCA0KSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFAAAAAAAAAAAAAAAAAAAA')),
        tensor('line_offset_f16', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoARA==')),
        tensor('sum_axes_hw', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAMAAAAAAAAA')),
        tensor('diag_idx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEwLCAxMCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoJCAcGBQQDAgEACgkIBwYFBAMCAQsKCQgHBgUEAwIMCwoJCAcGBQQDDQwLCgkIBwYFBA4NDAsKCQgHBgUPDg0MCwoJCAcGEA8ODQwLCgkIBxEQDw4NDAsKCQgSERAPDg0MCwoJ')),
        tensor('zero_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('off_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAr/')),
        tensor('diag_idx_i32', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEwLCAxMCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoJAAAACAAAAAcAAAAGAAAABQAAAAQAAAADAAAAAgAAAAEAAAAAAAAACgAAAAkAAAAIAAAABwAAAAYAAAAFAAAABAAAAAMAAAACAAAAAQAAAAsAAAAKAAAACQAAAAgAAAAHAAAABgAAAAUAAAAEAAAAAwAAAAIAAAAMAAAACwAAAAoAAAAJAAAACAAAAAcAAAAGAAAABQAAAAQAAAADAAAADQAAAAwAAAALAAAACgAAAAkAAAAIAAAABwAAAAYAAAAFAAAABAAAAA4AAAANAAAADAAAAAsAAAAKAAAACQAAAAgAAAAHAAAABgAAAAUAAAAPAAAADgAAAA0AAAAMAAAACwAAAAoAAAAJAAAACAAAAAcAAAAGAAAAEAAAAA8AAAAOAAAADQAAAAwAAAALAAAACgAAAAkAAAAIAAAABwAAABEAAAAQAAAADwAAAA4AAAANAAAADAAAAAsAAAAKAAAACQAAAAgAAAASAAAAEQAAABAAAAAPAAAADgAAAA0AAAAMAAAACwAAAAoAAAAJAAAA')),
        tensor('scatter_zero_vec', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDE5LCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAA')),
        tensor('shape3', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAA==')),
        tensor('zero_f16', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAA==')),
        tensor('one_f16', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAPA==')),
        tensor('step_f16', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAQA==')),
        tensor('half_f16', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAOA==')),
        tensor('eight_f16', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoASA==')),
        tensor('channel_idx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJ')),
        tensor('color_channel_idx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAAGBwgJ')),
        tensor('pad_out_pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUAAAAAAAAABQAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'slice5_starts', 'slice5_ends'], ['gray_f']),
        helper.make_node('GatherND', ['input', 'endpoint_indices'], ['endpoint_ch0']),
        helper.make_node('ArgMin', ['endpoint_ch0'], ['endpoint_arg'], axis=3, keepdims=1, select_last_index=0),
        helper.make_node('Cast', ['endpoint_arg'], ['endpoint_arg_f16'], to=10),
        helper.make_node('Add', ['endpoint_arg_f16', 'line_offset_f16'], ['line_idx_f16']),
        helper.make_node('Cast', ['line_idx_f16'], ['line_idx'], to=2),
        helper.make_node('ReduceMax', ['input'], ['present_f'], axes=[2, 3], keepdims=1),
        helper.make_node('Cast', ['present_f'], ['present_b'], to=9),
        helper.make_node('Cast', ['gray_f'], ['gray_geom'], to=9),
        helper.make_node('Where', ['gray_geom', 'diag_idx', 'zero_u8'], ['high_diag_grid']),
        helper.make_node('ReduceMax', ['high_diag_grid'], ['high_anchor_idx'], axes=[2, 3], keepdims=1),
        helper.make_node('Greater', ['high_anchor_idx', 'line_idx'], ['has_high']),
        helper.make_node('Cast', ['high_anchor_idx'], ['high_anchor_idx_f16'], to=10),
        helper.make_node('Sub', ['high_anchor_idx_f16', 'line_idx_f16'], ['high_k_raw_f16']),
        helper.make_node('Where', ['has_high', 'high_k_raw_f16', 'zero_f16'], ['high_k_f16']),
        helper.make_node('Add', ['high_k_f16', 'one_f16'], ['high_k_plus_one_f16']),
        helper.make_node('Mul', ['high_k_f16', 'high_k_plus_one_f16'], ['high_tri_double_f16']),
        helper.make_node('Mul', ['high_tri_double_f16', 'half_f16'], ['high_tri_f16']),
        helper.make_node('ReduceSum', ['gray_f', 'sum_axes_hw'], ['gray_count_f']),
        helper.make_node('Cast', ['gray_count_f'], ['gray_count_f16'], to=10),
        helper.make_node('Sub', ['gray_count_f16', 'high_tri_f16'], ['low_count_f16']),
        helper.make_node('Greater', ['low_count_f16', 'zero_f16'], ['has_low']),
        helper.make_node('Mul', ['low_count_f16', 'eight_f16'], ['low_sqrt_arg0_f16']),
        helper.make_node('Add', ['low_sqrt_arg0_f16', 'one_f16'], ['low_sqrt_arg_f16']),
        helper.make_node('Sqrt', ['low_sqrt_arg_f16'], ['low_sqrt_f16']),
        helper.make_node('Sub', ['low_sqrt_f16', 'one_f16'], ['low_k_double_f16']),
        helper.make_node('Mul', ['low_k_double_f16', 'half_f16'], ['low_k_f16']),
        helper.make_node('Add', ['high_anchor_idx_f16', 'step_f16'], ['high_out_f16']),
        helper.make_node('Sub', ['line_idx_f16', 'low_k_f16'], ['low_anchor_idx_f16']),
        helper.make_node('Sub', ['low_anchor_idx_f16', 'step_f16'], ['low_out_f16']),
        helper.make_node('Cast', ['high_out_f16'], ['high_candidate_idx'], to=2),
        helper.make_node('Cast', ['low_out_f16'], ['low_candidate_idx'], to=2),
        helper.make_node('Where', ['present_b', 'color_channel_idx', 'zero_u8'], ['active_idx_grid']),
        helper.make_node('ReduceMax', ['active_idx_grid'], ['color_idx'], axes=[1], keepdims=1),
        helper.make_node('Concat', ['line_idx', 'high_candidate_idx', 'low_candidate_idx'], ['candidate_idx_1113'], axis=1),
        helper.make_node('Reshape', ['candidate_idx_1113', 'shape3'], ['candidate_idx']),
        helper.make_node('Cast', ['candidate_idx'], ['candidate_idx_i32'], to=6),
        helper.make_node('Where', ['has_high', 'color_idx', 'zero_u8'], ['high_color_update']),
        helper.make_node('Where', ['has_low', 'color_idx', 'zero_u8'], ['low_color_update']),
        helper.make_node('Concat', ['color_idx', 'high_color_update', 'low_color_update'], ['candidate_update_1113'], axis=1),
        helper.make_node('Reshape', ['candidate_update_1113', 'shape3'], ['candidate_update']),
        helper.make_node('ScatterElements', ['scatter_zero_vec', 'candidate_idx_i32', 'candidate_update'], ['diag_target_vec'], axis=0),
        helper.make_node('Gather', ['diag_target_vec', 'diag_idx_i32'], ['target_idx'], axis=0),
        helper.make_node('Pad', ['target_idx', 'pad_out_pads', 'off_u8'], ['target_idx30'], mode='constant'),
        helper.make_node('Equal', ['channel_idx', 'target_idx30'], ['output']),
    ]
    value_infos = [
    ]
    return model('task260_live_exact', nodes, inits, output_dtype=9, opset=13, value_infos=value_infos)
