"""Task 184 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('channel_mask', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/')),
        tensor('ones30', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDMwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8=')),
        tensor('row_diff_kernel', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDIsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIC/AACAPw==')),
        tensor('col_diff_kernel', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDIpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIC/AACAPw==')),
        tensor('cumsum_row_axis', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAA==')),
        tensor('cumsum_col_axis', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAA==')),
        tensor('group_ids', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDMpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AAAAQAAAQEA=')),
        tensor('group_ids_col', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDMsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AAAAQAAAQEA=')),
        tensor('output_pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbAAAAAAAAABsAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'channel_mask', 'ones30'], ['row_count'], equation='nchw,ac,bw->nahb'),
        helper.make_node('Sign', ['row_count'], ['row_nonempty']),
        helper.make_node('Einsum', ['input', 'channel_mask', 'ones30'], ['col_count'], equation='nchw,ac,bh->nabw'),
        helper.make_node('Sign', ['col_count'], ['col_nonempty']),
        helper.make_node('Conv', ['row_nonempty', 'row_diff_kernel'], ['row_delta'], pads=[1, 0, 0, 0]),
        helper.make_node('Relu', ['row_delta'], ['row_start']),
        helper.make_node('CumSum', ['row_start', 'cumsum_row_axis'], ['row_group']),
        helper.make_node('Conv', ['col_nonempty', 'col_diff_kernel'], ['col_delta'], pads=[0, 1, 0, 0]),
        helper.make_node('Relu', ['col_delta'], ['col_start']),
        helper.make_node('CumSum', ['col_start', 'cumsum_col_axis'], ['col_group']),
        helper.make_node('Equal', ['col_group', 'group_ids_col'], ['col_onehot_bool']),
        helper.make_node('Cast', ['col_onehot_bool'], ['col_onehot'], to=1),
        helper.make_node('Equal', ['row_group', 'group_ids'], ['row_onehot_bool']),
        helper.make_node('Cast', ['row_onehot_bool'], ['row_onehot'], to=1),
        helper.make_node('Einsum', ['input', 'channel_mask', 'row_onehot', 'col_onehot'], ['counts_row_col'], equation='nchw,ac,nahr,nakw->ncrk'),
        helper.make_node('Pad', ['counts_row_col', 'output_pads'], ['output']),
    ]
    value_infos = [
        helper.make_tensor_value_info('row_count', 1, [1, 1, 30, 1]),
        helper.make_tensor_value_info('row_nonempty', 1, [1, 1, 30, 1]),
        helper.make_tensor_value_info('col_count', 1, [1, 1, 1, 30]),
        helper.make_tensor_value_info('col_nonempty', 1, [1, 1, 1, 30]),
        helper.make_tensor_value_info('row_delta', 1, [1, 1, 30, 1]),
        helper.make_tensor_value_info('row_start', 1, [1, 1, 30, 1]),
        helper.make_tensor_value_info('row_group', 1, [1, 1, 30, 1]),
        helper.make_tensor_value_info('col_delta', 1, [1, 1, 1, 30]),
        helper.make_tensor_value_info('col_start', 1, [1, 1, 1, 30]),
        helper.make_tensor_value_info('col_group', 1, [1, 1, 1, 30]),
        helper.make_tensor_value_info('col_onehot_bool', 9, [1, 1, 3, 30]),
        helper.make_tensor_value_info('col_onehot', 1, [1, 1, 3, 30]),
        helper.make_tensor_value_info('row_onehot_bool', 9, [1, 1, 30, 3]),
        helper.make_tensor_value_info('row_onehot', 1, [1, 1, 30, 3]),
        helper.make_tensor_value_info('counts_row_col', 1, [1, 10, 3, 3]),
    ]
    return model('task184_live_exact', nodes, inits, output_dtype=1, opset=13, value_infos=value_infos)
