"""Task 265 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('slice_gray_start', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==')),
        tensor('slice_gray_end', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAYAAAAAAAAAEgAAAAAAAAASAAAAAAAAAA==')),
        tensor('axes_hw', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAMAAAAAAAAA')),
        tensor('pad_to_30', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAMAAAAAAAAAA==')),
        tensor('anchor_pair_idx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDIsIDIpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoIAAAAAAAAAAoAAAAAAAAACAAAAAAAAAALAAAAAAAAAA==')),
        tensor('fix_anchor_idx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDQpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAALAAAAAAAAAA==')),
        tensor('one', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('color_clear', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoD')),
        tensor('channel_ids', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoABAIEBAEEBAQE')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'slice_gray_start', 'slice_gray_end'], ['gray18_f32']),
        helper.make_node('Cast', ['gray18_f32'], ['gray18_u8'], to=2),
        helper.make_node('MaxPool', ['gray18_u8'], ['gray_any_u8'], kernel_shape=[2, 2]),
        helper.make_node('Sub', ['one', 'gray_any_u8'], ['anchor_u8']),
        helper.make_node('Add', ['anchor_u8', 'anchor_u8'], ['anchor2_u8']),
        helper.make_node('GatherND', ['anchor_u8', 'anchor_pair_idx'], ['pair_vals'], batch_dims=2),
        helper.make_node('ReduceMin', ['pair_vals'], ['pair_flag'], keepdims=0),
        helper.make_node('Sub', ['one', 'pair_flag'], ['pair_keep']),
        helper.make_node('ScatterND', ['anchor2_u8', 'fix_anchor_idx', 'pair_keep'], ['anchor2_fixed_u8'], reduction='mul'),
        helper.make_node('MaxPool', ['anchor2_fixed_u8'], ['red18_u8'], kernel_shape=[2, 2], pads=[1, 1, 1, 1]),
        helper.make_node('Add', ['red18_u8', 'gray18_u8'], ['color18']),
        helper.make_node('Pad', ['color18', 'pad_to_30', 'color_clear', 'axes_hw'], ['color30'], mode='constant'),
        helper.make_node('Equal', ['color30', 'channel_ids'], ['output']),
    ]
    value_infos = [
    ]
    return model('task265_live_exact', nodes, inits, output_dtype=9, opset=18, value_infos=value_infos)
