"""Task 253 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('aw2', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBBAAAgQQAAMEEAAEBBAABQQQAAYEEAAHBBAACAQQAAiEEAAJBBAACYQQAAoEEAAKhBAACwQQAAuEEAAMBBAADIQQAA0EEAANhBAADgQQAA6EE=')),
        tensor('three', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoD')),
        tensor('c012', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDMpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAgA=')),
        tensor('U', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsIDMsIDQpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAPAA8AAAAAAAAAAAAPAA8AAAAPAA8AAAAAAA8AAAAAAAAAAAAPAAAAAAAAAAAAAA=')),
        tensor('V', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsIDMwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('G', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAPAC8')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'aw2'], ['rs'], equation='bchw,hx->bcx'),
        helper.make_node('Einsum', ['input', 'aw2'], ['cs'], equation='bchw,wx->bcx'),
        helper.make_node('Cast', ['rs'], ['rsf'], to=2),
        helper.make_node('Cast', ['cs'], ['csf'], to=2),
        helper.make_node('Mod', ['rsf', 'three'], ['rm']),
        helper.make_node('Mod', ['csf', 'three'], ['cm']),
        helper.make_node('Equal', ['rm', 'c012'], ['rv']),
        helper.make_node('Equal', ['cm', 'c012'], ['cv']),
        helper.make_node('Cast', ['rv'], ['rvf'], to=10),
        helper.make_node('Cast', ['cv'], ['cvf'], to=10),
        helper.make_node('Cast', ['rs'], ['prf'], to=10),
        helper.make_node('Einsum', ['rvf', 'cvf', 'prf', 'U', 'V', 'U', 'V', 'G'], ['output'], equation='bkp,bkq,bkx,spu,ur,sqv,vc,s->bkrc'),
    ]
    value_infos = [
        helper.make_tensor_value_info('rs', 1, [1, 10, 1]),
        helper.make_tensor_value_info('cs', 1, [1, 10, 1]),
        helper.make_tensor_value_info('rsf', 2, [1, 10, 1]),
        helper.make_tensor_value_info('csf', 2, [1, 10, 1]),
        helper.make_tensor_value_info('rm', 2, [1, 10, 1]),
        helper.make_tensor_value_info('cm', 2, [1, 10, 1]),
        helper.make_tensor_value_info('rv', 9, [1, 10, 3]),
        helper.make_tensor_value_info('cv', 9, [1, 10, 3]),
        helper.make_tensor_value_info('rvf', 10, [1, 10, 3]),
        helper.make_tensor_value_info('cvf', 10, [1, 10, 3]),
        helper.make_tensor_value_info('prf', 10, [1, 10, 1]),
    ]
    return model('task253_live_exact', nodes, inits, output_dtype=10, opset=17, value_infos=value_infos)
