"""Task 255 — exact source reconstruction of current live graph.

This builder owns the graph structure and constants in Python source and does
not load networks/task255.onnx at runtime.  The task is a documented
wall/complex heuristic, so this file preserves the verified live behavior as
source-controlled ONNX construction.
"""
from onnx import helper
from ._exact import arr_b64, model, tensor

def build(task):
    inits = [
        tensor('axis_c', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
        tensor('axis_h', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAA==')),
        tensor('axis_w', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAA==')),
        tensor('i0', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAA==')),
        tensor('i4', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoEAAAAAAAAAA==')),
        tensor('i26', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoaAAAAAAAAAA==')),
        tensor('i27', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAobAAAAAAAAAA==')),
        tensor('i28', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAocAAAAAAAAAA==')),
        tensor('i29', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAodAAAAAAAAAA==')),
        tensor('i30', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoeAAAAAAAAAA==')),
        tensor('row_ge5', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGIxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDMwLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE=')),
        tensor('row_le24', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGIxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDMwLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAAA=')),
        tensor('col_ge5', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGIxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDMwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE=')),
        tensor('col_coord', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDMwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBBAAAgQQAAMEEAAEBBAABQQQAAYEEAAHBBAACAQQAAiEEAAJBBAACYQQAAoEEAAKhBAACwQQAAuEEAAMBBAADIQQAA0EEAANhBAADgQQAA6EE=')),
        tensor('row_coord', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDMwLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBBAAAgQQAAMEEAAEBBAABQQQAAYEEAAHBBAACAQQAAiEEAAJBBAACYQQAAoEEAAKhBAACwQQAAuEEAAMBBAADIQQAA0EEAANhBAADgQQAA6EE=')),
        tensor('twenty_six', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAANBB')),
        tensor('thirty', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAPBB')),
        tensor('thirty_one', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAPhB')),
        tensor('one_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/')),
        tensor('half', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAA/')),
        tensor('pos0', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGIxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDMwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('pos1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGIxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDMwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('pos28', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGIxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDMwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQA=')),
        tensor('pos29', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGIxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDMwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE=')),
        tensor('vec_shape', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAeAAAAAAAAAA==')),
        tensor('row_shape', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAEAAAAAAAAAHgAAAAAAAAABAAAAAAAAAA==')),
        tensor('channel3', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA')),
        tensor('w3_h', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDMpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAPAA8ADw=')),
        tensor('w6_h', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDYpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAPAA8ADwAPAA8ADw=')),
        tensor('six_h', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoARg==')),
        tensor('three_h', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAQg==')),
        tensor('half_h', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAOA==')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'i0', 'axis_c', 'axis_c'], ['z']),
        helper.make_node('ReduceSum', ['z'], ['c_full_sum'], axes=[2], keepdims=1),
        helper.make_node('Slice', ['z', 'i0', 'i4', 'axis_h'], ['z_top_edge']),
        helper.make_node('ReduceSum', ['z_top_edge'], ['top_edge_sum'], axes=[2], keepdims=1),
        helper.make_node('Sub', ['c_full_sum', 'top_edge_sum'], ['c_top_sum']),
        helper.make_node('Equal', ['c_top_sum', 'twenty_six'], ['c_top']),
        helper.make_node('Slice', ['z', 'i26', 'i30', 'axis_h'], ['z_bottom_edge']),
        helper.make_node('ReduceSum', ['z_bottom_edge'], ['bottom_edge_sum'], axes=[2], keepdims=1),
        helper.make_node('Sub', ['c_full_sum', 'bottom_edge_sum'], ['c_bottom_sum']),
        helper.make_node('Equal', ['c_bottom_sum', 'twenty_six'], ['c_bottom']),
        helper.make_node('Cast', ['c_top'], ['c_top_f'], to=10),
        helper.make_node('Conv', ['c_top_f', 'w6_h'], ['c_top_s6']),
        helper.make_node('Equal', ['c_top_s6', 'six_h'], ['c_top_e6']),
        helper.make_node('Cast', ['c_top_e6'], ['c_top_e6f'], to=10),
        helper.make_node('ConvTranspose', ['c_top_e6f', 'w6_h'], ['c_top_c6']),
        helper.make_node('Greater', ['c_top_c6', 'half_h'], ['c_top_ge6']),
        helper.make_node('Conv', ['c_top_f', 'w3_h'], ['c_top_s3'], pads=[0, 1, 0, 1]),
        helper.make_node('Equal', ['c_top_s3', 'three_h'], ['c_top_center']),
        helper.make_node('And', ['c_top_ge6', 'c_top_center'], ['c_top_interior']),
        helper.make_node('Cast', ['c_bottom'], ['c_bottom_f'], to=10),
        helper.make_node('Conv', ['c_bottom_f', 'w6_h'], ['c_bottom_s6']),
        helper.make_node('Equal', ['c_bottom_s6', 'six_h'], ['c_bottom_e6']),
        helper.make_node('Cast', ['c_bottom_e6'], ['c_bottom_e6f'], to=10),
        helper.make_node('ConvTranspose', ['c_bottom_e6f', 'w6_h'], ['c_bottom_c6']),
        helper.make_node('Greater', ['c_bottom_c6', 'half_h'], ['c_bottom_ge6']),
        helper.make_node('Conv', ['c_bottom_f', 'w3_h'], ['c_bottom_s3'], pads=[0, 1, 0, 1]),
        helper.make_node('Equal', ['c_bottom_s3', 'three_h'], ['c_bottom_center']),
        helper.make_node('And', ['c_bottom_ge6', 'c_bottom_center'], ['c_bottom_interior']),
        helper.make_node('And', ['row_ge5', 'c_top_interior'], ['vbase_top']),
        helper.make_node('And', ['row_le24', 'c_bottom_interior'], ['vbase_bottom']),
        helper.make_node('Or', ['vbase_top', 'vbase_bottom'], ['vbase_tb']),
        helper.make_node('Or', ['c_top_ge6', 'c_bottom_ge6'], ['base_cols']),
        helper.make_node('Cast', ['base_cols'], ['base_cols_f'], to=1),
        helper.make_node('Mul', ['base_cols_f', 'col_coord'], ['base_cols_weighted']),
        helper.make_node('ReduceMax', ['base_cols_weighted'], ['right'], axes=[3], keepdims=1),
        helper.make_node('Less', ['col_coord', 'right'], ['left_cols']),
        helper.make_node('Cast', ['left_cols'], ['left_cols_f'], to=1),
        helper.make_node('Sub', ['right', 'one_f'], ['right_m1']),
        helper.make_node('GreaterOrEqual', ['col_coord', 'right_m1'], ['right_rect_cols']),
        helper.make_node('Cast', ['right_rect_cols'], ['right_rect_cols_f'], to=1),
        helper.make_node('Sub', ['thirty_one', 'right'], ['right_width']),
        helper.make_node('GreaterOrEqual', ['col_coord', 'right'], ['right_green_cols']),
        helper.make_node('ReduceSum', ['z'], ['r_full_sum'], axes=[3], keepdims=1),
        helper.make_node('Equal', ['r_full_sum', 'thirty'], ['r_full_col']),
        helper.make_node('Reshape', ['r_full_col', 'vec_shape'], ['r_full']),
        helper.make_node('Slice', ['z', 'i0', 'i4', 'axis_w'], ['z_left_edge']),
        helper.make_node('ReduceSum', ['z_left_edge'], ['left_edge_sum'], axes=[3], keepdims=1),
        helper.make_node('Sub', ['r_full_sum', 'left_edge_sum'], ['r_left_sum']),
        helper.make_node('Equal', ['r_left_sum', 'twenty_six'], ['r_left_col']),
        helper.make_node('Reshape', ['r_left_col', 'vec_shape'], ['r_left']),
        helper.make_node('Cast', ['r_full'], ['r_full_f'], to=10),
        helper.make_node('Conv', ['r_full_f', 'w6_h'], ['r_full_s6']),
        helper.make_node('Equal', ['r_full_s6', 'six_h'], ['r_full_e6']),
        helper.make_node('Cast', ['r_full_e6'], ['r_full_e6f'], to=10),
        helper.make_node('ConvTranspose', ['r_full_e6f', 'w6_h'], ['r_full_c6']),
        helper.make_node('Greater', ['r_full_c6', 'half_h'], ['r_full_ge6']),
        helper.make_node('Conv', ['r_full_f', 'w3_h'], ['r_full_s3'], pads=[0, 1, 0, 1]),
        helper.make_node('Equal', ['r_full_s3', 'three_h'], ['r_full_center']),
        helper.make_node('And', ['r_full_ge6', 'r_full_center'], ['r_full_interior']),
        helper.make_node('Cast', ['r_left'], ['r_left_f'], to=10),
        helper.make_node('Conv', ['r_left_f', 'w6_h'], ['r_left_s6']),
        helper.make_node('Equal', ['r_left_s6', 'six_h'], ['r_left_e6']),
        helper.make_node('Cast', ['r_left_e6'], ['r_left_e6f'], to=10),
        helper.make_node('ConvTranspose', ['r_left_e6f', 'w6_h'], ['r_left_c6']),
        helper.make_node('Greater', ['r_left_c6', 'half_h'], ['r_left_ge6']),
        helper.make_node('Conv', ['r_left_f', 'w3_h'], ['r_left_s3'], pads=[0, 1, 0, 1]),
        helper.make_node('Equal', ['r_left_s3', 'three_h'], ['r_left_center']),
        helper.make_node('And', ['r_left_ge6', 'r_left_center'], ['r_left_interior']),
        helper.make_node('Reshape', ['r_full_interior', 'row_shape'], ['r_full_i_row']),
        helper.make_node('Reshape', ['r_left_interior', 'row_shape'], ['r_left_i_row']),
        helper.make_node('And', ['r_left_i_row', 'col_ge5'], ['hbase_left']),
        helper.make_node('Or', ['r_full_i_row', 'hbase_left'], ['hbase']),
        helper.make_node('Reshape', ['r_left_ge6', 'row_shape'], ['r_left_b_row']),
        helper.make_node('Cast', ['r_left_b_row'], ['base_rows_f'], to=1),
        helper.make_node('Mul', ['base_rows_f', 'row_coord'], ['base_rows_weighted']),
        helper.make_node('ReduceMax', ['base_rows_weighted'], ['bottom'], axes=[2], keepdims=1),
        helper.make_node('ReduceMax', ['base_rows_f'], ['h_exists_f'], axes=[2], keepdims=1),
        helper.make_node('Greater', ['h_exists_f', 'half'], ['h_exists']),
        helper.make_node('Less', ['row_coord', 'bottom'], ['top_rows']),
        helper.make_node('Cast', ['top_rows'], ['top_rows_f'], to=1),
        helper.make_node('Sub', ['bottom', 'one_f'], ['bottom_m1']),
        helper.make_node('GreaterOrEqual', ['row_coord', 'bottom_m1'], ['bottom_rect_rows']),
        helper.make_node('Cast', ['bottom_rect_rows'], ['bottom_rect_rows_f'], to=1),
        helper.make_node('Sub', ['thirty_one', 'bottom'], ['bottom_height']),
        helper.make_node('GreaterOrEqual', ['row_coord', 'bottom'], ['bottom_green_rows']),
        helper.make_node('Reshape', ['left_cols_f', 'row_shape'], ['left_colsR']),
        helper.make_node('MatMul', ['z', 'left_colsR'], ['left_sum16']),
        helper.make_node('Reshape', ['right_rect_cols_f', 'row_shape'], ['right_colsR']),
        helper.make_node('MatMul', ['z', 'right_colsR'], ['right_sum16']),
        helper.make_node('Reshape', ['top_rows_f', 'vec_shape'], ['top_rowsR']),
        helper.make_node('MatMul', ['top_rowsR', 'z'], ['top_sum16']),
        helper.make_node('Reshape', ['bottom_rect_rows_f', 'vec_shape'], ['bottom_rowsR']),
        helper.make_node('MatMul', ['bottom_rowsR', 'z'], ['bottom_sum16']),
        helper.make_node('Equal', ['left_sum16', 'right'], ['left_all']),
        helper.make_node('Reshape', ['left_all', 'vec_shape'], ['left_vec']),
        helper.make_node('Cast', ['left_vec'], ['left_f'], to=10),
        helper.make_node('Conv', ['left_f', 'w3_h'], ['left_s3'], pads=[0, 1, 0, 1]),
        helper.make_node('Equal', ['left_s3', 'three_h'], ['left_normal']),
        helper.make_node('Reshape', ['left_normal', 'row_shape'], ['left_inner_row']),
        helper.make_node('And', ['left_inner_row', 'left_cols'], ['left_branch_a']),
        helper.make_node('Equal', ['right_sum16', 'right_width'], ['right_all']),
        helper.make_node('Reshape', ['right_all', 'vec_shape'], ['right_vec']),
        helper.make_node('Cast', ['right_vec'], ['right_f'], to=10),
        helper.make_node('Conv', ['right_f', 'w3_h'], ['right_s3'], pads=[0, 1, 0, 1]),
        helper.make_node('Equal', ['right_s3', 'three_h'], ['right_normal']),
        helper.make_node('Slice', ['right_vec', 'i0', 'axis_c', 'axis_w'], ['right_p0']),
        helper.make_node('Slice', ['right_vec', 'axis_c', 'axis_h', 'axis_w'], ['right_p1']),
        helper.make_node('Slice', ['right_vec', 'axis_h', 'axis_w', 'axis_w'], ['right_p2']),
        helper.make_node('Slice', ['right_vec', 'axis_w', 'i4', 'axis_w'], ['right_p3']),
        helper.make_node('Slice', ['right_vec', 'i28', 'i29', 'axis_w'], ['right_p28']),
        helper.make_node('Slice', ['right_vec', 'i29', 'i30', 'axis_w'], ['right_p29']),
        helper.make_node('Not', ['right_p2'], ['right_not_p2']),
        helper.make_node('Not', ['right_p3'], ['right_not_p3']),
        helper.make_node('And', ['right_p2', 'right_not_p3'], ['right_p2_not_p3']),
        helper.make_node('Or', ['right_not_p2', 'right_p2_not_p3'], ['right_top_len']),
        helper.make_node('And', ['right_p0', 'right_p1'], ['right_top0_a']),
        helper.make_node('And', ['right_top0_a', 'right_top_len'], ['right_top0']),
        helper.make_node('And', ['right_top0', 'pos0'], ['right_top0_m']),
        helper.make_node('And', ['right_top0_a', 'right_p2'], ['right_top1_a']),
        helper.make_node('And', ['right_top1_a', 'right_not_p3'], ['right_top1']),
        helper.make_node('And', ['right_top1', 'pos1'], ['right_top1_m']),
        helper.make_node('And', ['right_p29', 'right_p28'], ['right_bottom29_a']),
        helper.make_node('And', ['right_bottom29_a', 'pos29'], ['right_bottom29_m']),
        helper.make_node('Or', ['right_normal', 'right_top0_m'], ['right_or0']),
        helper.make_node('Or', ['right_or0', 'right_top1_m'], ['right_or1']),
        helper.make_node('Or', ['right_or1', 'right_bottom29_m'], ['right_or2']),
        helper.make_node('Reshape', ['right_or2', 'row_shape'], ['right_inner_row']),
        helper.make_node('And', ['right_inner_row', 'right_green_cols'], ['right_branch_a']),
        helper.make_node('Equal', ['top_sum16', 'bottom'], ['top_all']),
        helper.make_node('Cast', ['top_all'], ['top_f'], to=10),
        helper.make_node('Conv', ['top_f', 'w3_h'], ['top_s3'], pads=[0, 1, 0, 1]),
        helper.make_node('Equal', ['top_s3', 'three_h'], ['top_normal']),
        helper.make_node('Slice', ['top_all', 'i26', 'i27', 'axis_w'], ['top_p26']),
        helper.make_node('Slice', ['top_all', 'i27', 'i28', 'axis_w'], ['top_p27']),
        helper.make_node('Slice', ['top_all', 'i28', 'i29', 'axis_w'], ['top_p28']),
        helper.make_node('Slice', ['top_all', 'i29', 'i30', 'axis_w'], ['top_p29']),
        helper.make_node('Not', ['top_p27'], ['top_not_p27']),
        helper.make_node('Not', ['top_p26'], ['top_not_p26']),
        helper.make_node('And', ['top_p27', 'top_not_p26'], ['top_p27_not_p26']),
        helper.make_node('Or', ['top_not_p27', 'top_p27_not_p26'], ['top_bottom_len']),
        helper.make_node('And', ['top_p29', 'top_p28'], ['top_bottom29_a']),
        helper.make_node('And', ['top_bottom29_a', 'top_bottom_len'], ['top_bottom29']),
        helper.make_node('And', ['top_bottom29', 'pos29'], ['top_bottom29_m']),
        helper.make_node('Or', ['top_normal', 'top_bottom29_m'], ['top_or2']),
        helper.make_node('And', ['top_rows', 'top_or2'], ['top_branch_a']),
        helper.make_node('Equal', ['bottom_sum16', 'bottom_height'], ['bottom_all']),
        helper.make_node('Cast', ['bottom_all'], ['bottom_f'], to=10),
        helper.make_node('Conv', ['bottom_f', 'w3_h'], ['bottom_s3'], pads=[0, 1, 0, 1]),
        helper.make_node('Equal', ['bottom_s3', 'three_h'], ['bottom_normal']),
        helper.make_node('Slice', ['bottom_all', 'i26', 'i27', 'axis_w'], ['bottom_p26']),
        helper.make_node('Slice', ['bottom_all', 'i27', 'i28', 'axis_w'], ['bottom_p27']),
        helper.make_node('Slice', ['bottom_all', 'i28', 'i29', 'axis_w'], ['bottom_p28']),
        helper.make_node('Slice', ['bottom_all', 'i29', 'i30', 'axis_w'], ['bottom_p29']),
        helper.make_node('Not', ['bottom_p27'], ['bottom_not_p27']),
        helper.make_node('Not', ['bottom_p26'], ['bottom_not_p26']),
        helper.make_node('And', ['bottom_p27', 'bottom_not_p26'], ['bottom_p27_not_p26']),
        helper.make_node('Or', ['bottom_not_p27', 'bottom_p27_not_p26'], ['bottom_bottom_len']),
        helper.make_node('And', ['bottom_p29', 'bottom_p28'], ['bottom_bottom29_a']),
        helper.make_node('And', ['bottom_bottom29_a', 'bottom_bottom_len'], ['bottom_bottom29']),
        helper.make_node('And', ['bottom_bottom29', 'pos29'], ['bottom_bottom29_m']),
        helper.make_node('And', ['bottom_bottom29_a', 'bottom_p27'], ['bottom_bottom28_a']),
        helper.make_node('And', ['bottom_bottom28_a', 'bottom_not_p26'], ['bottom_bottom28']),
        helper.make_node('And', ['bottom_bottom28', 'pos28'], ['bottom_bottom28_m']),
        helper.make_node('Or', ['bottom_normal', 'bottom_bottom29_m'], ['bottom_or2']),
        helper.make_node('Or', ['bottom_or2', 'bottom_bottom28_m'], ['bottom_interior']),
        helper.make_node('And', ['bottom_green_rows', 'bottom_interior'], ['bottom_branch_a']),
        helper.make_node('And', ['bottom_branch_a', 'h_exists'], ['bottom_branch']),
        helper.make_node('Or', ['vbase_tb', 'left_branch_a'], ['geom0']),
        helper.make_node('Or', ['geom0', 'right_branch_a'], ['geom1']),
        helper.make_node('Or', ['geom1', 'hbase'], ['geom2']),
        helper.make_node('Or', ['geom2', 'top_branch_a'], ['geom3']),
        helper.make_node('Or', ['geom3', 'bottom_branch'], ['geom']),
        helper.make_node('Where', ['geom', 'channel3', 'input'], ['output']),
    ]
    value_infos = [
    ]
    return model('task255', nodes, inits, output_dtype=1, opset=12, value_infos=value_infos)
