"""Task 355 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('safe_name_2', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAGBB')),
        tensor('safe_name_3', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAQBzG')),
        tensor('safe_name_4', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAEAAAAAAAAAAgAAAAAAAAADAAAAAAAAAAQAAAAAAAAABQAAAAAAAAAGAAAAAAAAAAcAAAAAAAAACAAAAAAAAAAJAAAAAAAAAA==')),
        tensor('safe_name_6', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdAAAAAAAAAB0AAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('ReduceSum', ['input'], ['safe_name_8'], keepdims=0, axes=[2, 3]),
        helper.make_node('ReduceMax', ['input'], ['safe_name_9'], axes=[3], keepdims=0),
        helper.make_node('ReduceMax', ['input'], ['safe_name_10'], axes=[2], keepdims=0),
        helper.make_node('ReduceSum', ['safe_name_9'], ['safe_name_11'], keepdims=0, axes=[2]),
        helper.make_node('ReduceSum', ['safe_name_10'], ['safe_name_12'], keepdims=0, axes=[2]),
        helper.make_node('Mul', ['safe_name_11', 'safe_name_12'], ['safe_name_13']),
        helper.make_node('Sub', ['safe_name_13', 'safe_name_8'], ['safe_name_14']),
        helper.make_node('Greater', ['safe_name_8', 'safe_name_2'], ['safe_name_15']),
        helper.make_node('Where', ['safe_name_15', 'safe_name_14', 'safe_name_3'], ['safe_name_16']),
        helper.make_node('ArgMax', ['safe_name_16'], ['safe_name_17'], axis=1, keepdims=0),
        helper.make_node('Equal', ['safe_name_4', 'safe_name_17'], ['safe_name_18']),
        helper.make_node('Cast', ['safe_name_18'], ['safe_name_19'], to=2),
        helper.make_node('Unsqueeze', ['safe_name_19'], ['safe_name_20'], axes=[0, 2, 3]),
        helper.make_node('Pad', ['safe_name_20', 'safe_name_6'], ['output'], mode='constant'),
    ]
    value_infos = [
        helper.make_tensor_value_info('safe_name_8', 1, [1, 10]),
        helper.make_tensor_value_info('safe_name_9', 1, [1, 10, 30]),
        helper.make_tensor_value_info('safe_name_10', 1, [1, 10, 30]),
        helper.make_tensor_value_info('safe_name_11', 1, [1, 10]),
        helper.make_tensor_value_info('safe_name_12', 1, [1, 10]),
        helper.make_tensor_value_info('safe_name_13', 1, [1, 10]),
        helper.make_tensor_value_info('safe_name_14', 1, [1, 10]),
        helper.make_tensor_value_info('safe_name_15', 9, [1, 10]),
        helper.make_tensor_value_info('safe_name_16', 1, [1, 10]),
        helper.make_tensor_value_info('safe_name_17', 7, [1]),
        helper.make_tensor_value_info('safe_name_18', 9, [10]),
        helper.make_tensor_value_info('safe_name_19', 2, [10]),
        helper.make_tensor_value_info('safe_name_20', 2, [1, 10, 1, 1]),
    ]
    return model('task355_live_exact', nodes, inits, output_dtype=2, opset=12, value_infos=value_infos)
