"""Task 137 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('col_w', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBBAAAgQQAAMEEAAEBBAABQQQAAYEEAAHBBAACAQQAAiEEAAJBBAACYQQAAoEEAAKhBAACwQQAAuEEAAMBBAADIQQAA0EEAANhBAADgQQAA6EEAAPBBAAD4QQAAAEI=')),
        tensor('row_idx_h', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDMwLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAA8AEAAQgBEAEUARgBHAEiASABJgEkASoBKAEuASwBMQEyATMBMAE1ATYBNwE0ATkBOgE7ATgBPQE8=')),
        tensor('col_idx_h', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDMwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAA8AEAAQgBEAEUARgBHAEiASABJgEkASoBKAEuASwBMQEyATMBMAE1ATYBNwE0ATkBOgE7ATgBPQE8=')),
        tensor('bad_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAof')),
        tensor('three_h', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAQg==')),
        tensor('three_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAEBA')),
    ]
    nodes = [
        helper.make_node('ReduceSum', ['input'], ['channel_counts'], axes=[2, 3], keepdims=1),
        helper.make_node('Equal', ['channel_counts', 'three_f'], ['color_is_three']),
        helper.make_node('Cast', ['color_is_three'], ['center_vec'], to=1),
        helper.make_node('ReduceSum', ['channel_counts'], ['total_count'], axes=[1], keepdims=1),
        helper.make_node('Cast', ['total_count'], ['total_count_h'], to=10),
        helper.make_node('Sqrt', ['total_count_h'], ['size_h']),
        helper.make_node('Einsum', ['input', 'center_vec', 'col_w'], ['row_code'], equation='nchw,ncij,w->nh'),
        helper.make_node('Cast', ['row_code'], ['row_pos'], to=9),
        helper.make_node('Cast', ['row_pos'], ['row_any_u8'], to=2),
        helper.make_node('ArgMax', ['row_any_u8'], ['row_min_i'], axis=1, keepdims=1, select_last_index=0),
        helper.make_node('ArgMax', ['row_any_u8'], ['row_max_i'], axis=1, keepdims=1, select_last_index=1),
        helper.make_node('Cast', ['row_min_i'], ['row_min_h'], to=10),
        helper.make_node('Cast', ['row_max_i'], ['row_max_h'], to=10),
        helper.make_node('Mean', ['row_min_h', 'row_max_h'], ['cr_h']),
        helper.make_node('Sub', ['row_max_h', 'cr_h'], ['step_h']),
        helper.make_node('ReduceSum', ['row_code'], ['col_sum_f'], axes=[1], keepdims=1),
        helper.make_node('Cast', ['col_sum_f'], ['col_sum_h'], to=10),
        helper.make_node('Div', ['col_sum_h', 'three_h'], ['col_plus3_h']),
        helper.make_node('Sub', ['col_plus3_h', 'three_h'], ['cc_h']),
        helper.make_node('Less', ['row_idx_h', 'size_h'], ['row_valid']),
        helper.make_node('Less', ['col_idx_h', 'size_h'], ['col_valid']),
        helper.make_node('Sub', ['row_idx_h', 'cr_h'], ['row_delta']),
        helper.make_node('Abs', ['row_delta'], ['dr']),
        helper.make_node('Sub', ['col_idx_h', 'cc_h'], ['col_delta']),
        helper.make_node('Abs', ['col_delta'], ['dc']),
        helper.make_node('Cast', ['dr'], ['dr_u8_raw'], to=2),
        helper.make_node('Cast', ['dc'], ['dc_u8_raw'], to=2),
        helper.make_node('Where', ['row_valid', 'dr_u8_raw', 'bad_u8'], ['dr_u8']),
        helper.make_node('Where', ['col_valid', 'dc_u8_raw', 'bad_u8'], ['dc_u8']),
        helper.make_node('Cast', ['step_h'], ['step_u8'], to=2),
        helper.make_node('Max', ['dr_u8', 'dc_u8'], ['cheb_u8']),
        helper.make_node('Mod', ['cheb_u8', 'step_u8'], ['cheb_rem_u8'], fmod=0),
        helper.make_node('Cast', ['cheb_rem_u8'], ['nonring_bool'], to=9),
        helper.make_node('Where', ['nonring_bool', 'input', 'center_vec'], ['output']),
    ]
    value_infos = [
    ]
    return model('task137_live_exact', nodes, inits, output_dtype=1, opset=12, value_infos=value_infos)
