"""Task 177 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('row_weights', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCA1KSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPw==')),
        tensor('col_weights', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCA1LCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPw==')),
        tensor('label_weights', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACIPwAAkD8AAJg/AACgPwAAqD8AALA/AAC4PwAAwD8AAMg/')),
        tensor('seven_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAOBA')),
        tensor('eight_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAABB')),
        tensor('batch_indices', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAA==')),
        tensor('class_ids', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDksIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIg/AACQPwAAmD8AAKA/AACoPwAAsD8AALg/AADAPwAAyD8=')),
        tensor('output_pad', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWAAAAAAAAABYAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Conv', ['input', 'row_weights'], ['row_score'], dilations=[1, 4], strides=[1, 30]),
        helper.make_node('ArgMax', ['row_score'], ['top'], axis=2, keepdims=0),
        helper.make_node('Cast', ['top'], ['top_f3'], to=1),
        helper.make_node('Flatten', ['top_f3'], ['top_f'], axis=1),
        helper.make_node('Add', ['top_f', 'eight_f'], ['bottom_f']),
        helper.make_node('Conv', ['input', 'col_weights'], ['col_score'], dilations=[4, 1], strides=[30, 1]),
        helper.make_node('ArgMax', ['col_score'], ['right'], axis=3, keepdims=0, select_last_index=1),
        helper.make_node('Cast', ['right'], ['right_f3'], to=1),
        helper.make_node('Flatten', ['right_f3'], ['right_f'], axis=1),
        helper.make_node('Sub', ['right_f', 'seven_f'], ['left_f']),
        helper.make_node('Add', ['left_f', 'eight_f'], ['after_right_f']),
        helper.make_node('Concat', ['after_right_f', 'top_f', 'left_f', 'bottom_f'], ['rois'], axis=1),
        helper.make_node('RoiAlign', ['input', 'rois', 'batch_indices'], ['crop_onehot'], coordinate_transformation_mode='half_pixel', mode='avg', output_height=8, output_width=8, sampling_ratio=1, spatial_scale=1.0),
        helper.make_node('Conv', ['crop_onehot', 'label_weights'], ['crop_f']),
        helper.make_node('Equal', ['crop_f', 'class_ids'], ['one_hot_crop']),
        helper.make_node('Pad', ['one_hot_crop', 'output_pad'], ['output'], mode='constant'),
    ]
    value_infos = [
    ]
    return model('task177_live_exact', nodes, inits, output_dtype=9, opset=16, value_infos=value_infos)
