"""Task 066 — exact source reconstruction of current live graph.

This builder owns the graph structure and constants in Python source and does
not load networks/task066.onnx at runtime.  The task is a documented
wall/complex heuristic, so this file preserves the verified live behavior as
source-controlled ONNX construction.
"""
from onnx import helper
from ._exact import arr_b64, model, tensor

def build(task):
    inits = [
        tensor('zero_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAA==')),
        tensor('zero32_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAA')),
        tensor('one_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAPA==')),
        tensor('hi_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAowVg==')),
        tensor('hundred_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIApAVg==')),
        tensor('half_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAOA==')),
        tensor('three_quarters_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAOg==')),
        tensor('row_weights', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDIwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAA8AEAAQgBEAEUARgBHAEiASABJgEkASoBKAEuASwBMQEyATMBM')),
        tensor('row_mat', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIwLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAA8AEAAQgBEAEUARgBHAEiASABJgEkASoBKAEuASwBMQEyATMBM')),
        tensor('col_grid', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDIwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAA8AEAAQgBEAEUARgBHAEiASABJgEkASoBKAEuASwBMQEyATMBM')),
        tensor('cumsum_axis', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
        tensor('cyan_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==')),
        tensor('cyan_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAkAAAAAAAAAFAAAAAAAAAAUAAAAAAAAAA==')),
        tensor('red_row_any_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAA=')),
        tensor('red_row_any_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAMAAAAAAAAAFAAAAAAAAAA=')),
        tensor('green_row_any_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAA=')),
        tensor('green_row_any_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAQAAAAAAAAAFAAAAAAAAAA=')),
        tensor('active_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAA==')),
        tensor('active_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoUAAAAAAAAAA==')),
        tensor('n_red_cyan_row_zero', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDIwLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA')),
        tensor('n_red_bad_pref_m_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoTAAAAAAAAAA==')),
        tensor('n_red_bad_pref_m_pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==')),
        tensor('n_red_bad_pref_m_zero', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAA==')),
        tensor('n_corner_t_plus_shifted_pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAA==')),
        tensor('green_paint', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA')),
        tensor('n_s_down_tie_score', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDIwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIApAVlBWYFZwVoBWkFagVrBWwFbQVuBW8FYAVxBXIFcwV0BXUFdgV3BX')),
        tensor('hidden_right', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGIxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDIwLCAxMCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==')),
        tensor('hidden_bottom', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGIxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEwLCAzMCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('where_mask_zero_f16', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAA==')),
        tensor('_v_351', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAA==')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'cyan_starts', 'cyan_ends'], ['cyan_4d']),
        helper.make_node('Cast', ['cyan_4d'], ['cyan_b4'], to=9),
        helper.make_node('Squeeze', ['cyan_b4', 'cumsum_axis'], ['cyan']),
        helper.make_node('ReduceMax', ['input'], ['row_channels'], axes=[3], keepdims=0),
        helper.make_node('ReduceMax', ['input'], ['col_channels'], axes=[2], keepdims=0),
        helper.make_node('Slice', ['row_channels', 'red_row_any_starts', 'red_row_any_ends'], ['red_row_any_slice']),
        helper.make_node('Squeeze', ['red_row_any_slice', 'cumsum_axis'], ['red_row_any_squeezed']),
        helper.make_node('Greater', ['red_row_any_squeezed', 'zero32_f'], ['red_row_any']),
        helper.make_node('Slice', ['col_channels', 'red_row_any_starts', 'red_row_any_ends'], ['red_col_any_slice']),
        helper.make_node('Squeeze', ['red_col_any_slice', 'cumsum_axis'], ['red_col_any_squeezed']),
        helper.make_node('Greater', ['red_col_any_squeezed', 'zero32_f'], ['red_col_any']),
        helper.make_node('Slice', ['row_channels', 'green_row_any_starts', 'green_row_any_ends'], ['green_row_any_slice']),
        helper.make_node('Squeeze', ['green_row_any_slice', 'cumsum_axis'], ['green_row_any_squeezed']),
        helper.make_node('Greater', ['green_row_any_squeezed', 'zero32_f'], ['green_row_any']),
        helper.make_node('Slice', ['col_channels', 'green_row_any_starts', 'green_row_any_ends'], ['green_col_any_slice']),
        helper.make_node('Squeeze', ['green_col_any_slice', 'cumsum_axis'], ['green_col_any_squeezed']),
        helper.make_node('Greater', ['green_col_any_squeezed', 'zero32_f'], ['green_col_any']),
        helper.make_node('ReduceMax', ['input'], ['active_row_any30_max'], axes=[1, 3], keepdims=0),
        helper.make_node('Greater', ['active_row_any30_max', 'zero32_f'], ['active_row_any30']),
        helper.make_node('Slice', ['active_row_any30', 'active_starts', 'active_ends', 'cumsum_axis'], ['active_row_any']),
        helper.make_node('Where', ['active_row_any', 'row_weights', 'where_mask_zero_f16'], ['active_row_weighted']),
        helper.make_node('ReduceMax', ['active_row_weighted'], ['active_row_max'], axes=[1], keepdims=1),
        helper.make_node('Add', ['active_row_max', 'one_f'], ['size']),
        helper.make_node('Where', ['red_col_any', 'row_weights', 'where_mask_zero_f16'], ['ori_red_col_weighted']),
        helper.make_node('ReduceMax', ['ori_red_col_weighted'], ['ori_red_col_max'], axes=[1], keepdims=1),
        helper.make_node('Where', ['red_col_any', 'row_weights', 'hi_f'], ['ori_red_col_masked_min']),
        helper.make_node('ReduceMin', ['ori_red_col_masked_min'], ['ori_red_col_min'], axes=[1], keepdims=1),
        helper.make_node('Equal', ['ori_red_col_min', 'ori_red_col_max'], ['use_native_orientation']),
        helper.make_node('Transpose', ['cyan'], ['cyan_t'], perm=[0, 2, 1]),
        helper.make_node('And', ['use_native_orientation', 'cyan'], ['cyan_norm_yes']),
        helper.make_node('Not', ['use_native_orientation'], ['cyan_norm_not_cond']),
        helper.make_node('And', ['cyan_norm_not_cond', 'cyan_t'], ['cyan_norm_no']),
        helper.make_node('Or', ['cyan_norm_yes', 'cyan_norm_no'], ['cyan_norm']),
        helper.make_node('And', ['use_native_orientation', 'red_row_any'], ['red_row_norm_yes']),
        helper.make_node('And', ['cyan_norm_not_cond', 'red_col_any'], ['red_row_norm_no']),
        helper.make_node('Or', ['red_row_norm_yes', 'red_row_norm_no'], ['red_row_norm']),
        helper.make_node('And', ['use_native_orientation', 'red_col_any'], ['red_col_norm_yes']),
        helper.make_node('And', ['cyan_norm_not_cond', 'red_row_any'], ['red_col_norm_no']),
        helper.make_node('Or', ['red_col_norm_yes', 'red_col_norm_no'], ['red_col_norm']),
        helper.make_node('And', ['use_native_orientation', 'green_row_any'], ['green_row_norm_yes']),
        helper.make_node('And', ['cyan_norm_not_cond', 'green_col_any'], ['green_row_norm_no']),
        helper.make_node('Or', ['green_row_norm_yes', 'green_row_norm_no'], ['green_row_norm']),
        helper.make_node('And', ['use_native_orientation', 'green_col_any'], ['green_col_norm_yes']),
        helper.make_node('And', ['cyan_norm_not_cond', 'green_row_any'], ['green_col_norm_no']),
        helper.make_node('Or', ['green_col_norm_yes', 'green_col_norm_no'], ['green_col_norm']),
        helper.make_node('Where', ['red_row_norm', 'row_weights', 'where_mask_zero_f16'], ['n_rr_weighted']),
        helper.make_node('ReduceMax', ['n_rr_weighted'], ['n_rr_max'], axes=[1], keepdims=1),
        helper.make_node('Where', ['red_row_norm', 'row_weights', 'hi_f'], ['n_rr_masked_min']),
        helper.make_node('ReduceMin', ['n_rr_masked_min'], ['n_rr_min'], axes=[1], keepdims=1),
        helper.make_node('Where', ['red_col_norm', 'row_weights', 'hi_f'], ['n_rc_masked_min']),
        helper.make_node('ReduceMin', ['n_rc_masked_min'], ['n_rc_min'], axes=[1], keepdims=1),
        helper.make_node('Where', ['green_row_norm', 'row_weights', 'where_mask_zero_f16'], ['n_gr_weighted']),
        helper.make_node('ReduceMax', ['n_gr_weighted'], ['n_gr_max'], axes=[1], keepdims=1),
        helper.make_node('Where', ['green_row_norm', 'row_weights', 'hi_f'], ['n_gr_masked_min']),
        helper.make_node('ReduceMin', ['n_gr_masked_min'], ['n_gr_min'], axes=[1], keepdims=1),
        helper.make_node('Where', ['green_col_norm', 'row_weights', 'where_mask_zero_f16'], ['n_gc_weighted']),
        helper.make_node('ReduceMax', ['n_gc_weighted'], ['n_gc_max'], axes=[1], keepdims=1),
        helper.make_node('Where', ['green_col_norm', 'row_weights', 'hi_f'], ['n_gc_masked_min']),
        helper.make_node('ReduceMin', ['n_gc_masked_min'], ['n_gc_min'], axes=[1], keepdims=1),
        helper.make_node('Equal', ['n_rc_min', 'n_rc_min'], ['n_red_vertical']),
        helper.make_node('Equal', ['n_gc_min', 'n_gc_max'], ['n_green_vertical']),
        helper.make_node('Greater', ['n_rc_min', 'n_gc_max'], ['n_red_right']),
        helper.make_node('Less', ['n_rc_min', 'n_gc_max'], ['n_red_left']),
        helper.make_node('And', ['n_red_vertical', 'n_green_vertical'], ['n_endpoint_base']),
        helper.make_node('Or', ['n_red_right', 'n_red_left'], ['n_endpoint_side']),
        helper.make_node('And', ['n_endpoint_base', 'n_endpoint_side'], ['n_endpoint_ok']),
        helper.make_node('Min', ['n_rc_min', 'n_gc_max'], ['n_c_low']),
        helper.make_node('Max', ['n_rc_min', 'n_gc_max'], ['n_c_high']),
        helper.make_node('Add', ['n_rc_min', 'one_f'], ['n_rc_plus']),
        helper.make_node('Sub', ['n_rc_min', 'one_f'], ['n_rc_minus']),
        helper.make_node('Where', ['n_red_right', 'n_rc_plus', 'n_rc_minus'], ['n_rc_out']),
        helper.make_node('Where', ['n_red_right', 'n_rc_minus', 'n_rc_plus'], ['n_rc_in']),
        helper.make_node('Cast', ['n_rc_min'], ['n_red_cyan_col_i'], to=7),
        helper.make_node('Unsqueeze', ['n_red_cyan_col_i', '_v_351'], ['n_red_cyan_col_i3']),
        helper.make_node('Add', ['n_red_cyan_row_zero', 'n_red_cyan_col_i3'], ['n_red_cyan_gather_i']),
        helper.make_node('GatherElements', ['cyan_norm', 'n_red_cyan_gather_i'], ['n_red_cyan_gathered'], axis=2),
        helper.make_node('Squeeze', ['n_red_cyan_gathered', '_v_351'], ['n_red_cyan']),
        helper.make_node('Cast', ['n_gc_max'], ['n_green_cyan_col_i'], to=7),
        helper.make_node('Unsqueeze', ['n_green_cyan_col_i', '_v_351'], ['n_green_cyan_col_i3']),
        helper.make_node('Add', ['n_red_cyan_row_zero', 'n_green_cyan_col_i3'], ['n_green_cyan_gather_i']),
        helper.make_node('GatherElements', ['cyan_norm', 'n_green_cyan_gather_i'], ['n_green_cyan_gathered'], axis=2),
        helper.make_node('Squeeze', ['n_green_cyan_gathered', '_v_351'], ['n_green_cyan']),
        helper.make_node('Cast', ['n_green_cyan'], ['n_green_bad_profile'], to=10),
        helper.make_node('Cast', ['n_rr_min'], ['n_rrmin_i'], to=7),
        helper.make_node('Cast', ['n_rr_max'], ['n_rrmax_i'], to=7),
        helper.make_node('Cast', ['n_gr_min'], ['n_grmin_i'], to=7),
        helper.make_node('Cast', ['n_gr_max'], ['n_grmax_i'], to=7),
        helper.make_node('Cast', ['n_red_cyan'], ['n_red_bad_profile32'], to=1),
        helper.make_node('CumSum', ['n_red_bad_profile32', 'cumsum_axis'], ['n_red_bad_pref32']),
        helper.make_node('Cast', ['n_red_bad_pref32'], ['n_red_bad_pref'], to=10),
        helper.make_node('Slice', ['n_red_bad_pref', 'active_starts', 'n_red_bad_pref_m_ends', 'cumsum_axis'], ['n_red_bad_pref_m_core']),
        helper.make_node('Pad', ['n_red_bad_pref_m_core', 'n_red_bad_pref_m_pads', 'n_red_bad_pref_m_zero'], ['n_red_bad_pref_m'], mode='constant'),
        helper.make_node('GatherElements', ['n_red_bad_pref', 'n_rrmax_i'], ['n_red_bad_rrmax'], axis=1),
        helper.make_node('GatherElements', ['n_red_bad_pref_m', 'n_rrmin_i'], ['n_red_bad_before_rrmin'], axis=1),
        helper.make_node('Cast', ['n_green_bad_profile'], ['n_green_bad_profile32'], to=1),
        helper.make_node('CumSum', ['n_green_bad_profile32', 'cumsum_axis'], ['n_green_bad_pref32']),
        helper.make_node('Cast', ['n_green_bad_pref32'], ['n_green_bad_pref'], to=10),
        helper.make_node('Slice', ['n_green_bad_pref', 'active_starts', 'n_red_bad_pref_m_ends', 'cumsum_axis'], ['n_green_bad_pref_m_core']),
        helper.make_node('Pad', ['n_green_bad_pref_m_core', 'n_red_bad_pref_m_pads', 'n_red_bad_pref_m_zero'], ['n_green_bad_pref_m'], mode='constant'),
        helper.make_node('GatherElements', ['n_green_bad_pref', 'n_grmax_i'], ['n_green_bad_grmax'], axis=1),
        helper.make_node('GatherElements', ['n_green_bad_pref_m', 'n_grmin_i'], ['n_green_bad_before_grmin'], axis=1),
        helper.make_node('Greater', ['col_grid', 'n_c_low'], ['n_h_c_ge_low_gt']),
        helper.make_node('Equal', ['col_grid', 'n_c_low'], ['n_h_c_ge_low_eq']),
        helper.make_node('Or', ['n_h_c_ge_low_gt', 'n_h_c_ge_low_eq'], ['n_h_c_ge_low_1']),
        helper.make_node('Less', ['col_grid', 'n_c_high'], ['n_h_c_le_high_lt']),
        helper.make_node('Equal', ['col_grid', 'n_c_high'], ['n_h_c_le_high_eq']),
        helper.make_node('Or', ['n_h_c_le_high_lt', 'n_h_c_le_high_eq'], ['n_h_c_le_high_1']),
        helper.make_node('And', ['n_h_c_ge_low_1', 'n_h_c_le_high_1'], ['n_h_c_between']),
        helper.make_node('Cast', ['cyan_norm'], ['n_h_nonblack_f'], to=10),
        helper.make_node('Cast', ['n_h_c_between'], ['n_h_c_between_f'], to=10),
        helper.make_node('Transpose', ['n_h_c_between_f'], ['n_h_c_between_col'], perm=[0, 2, 1]),
        helper.make_node('MatMul', ['n_h_nonblack_f', 'n_h_c_between_col'], ['n_h_bad_score']),
        helper.make_node('Squeeze', ['n_h_bad_score', '_v_351'], ['n_h_bad_score_2d']),
        helper.make_node('LessOrEqual', ['n_h_bad_score_2d', 'zero_f'], ['n_h_clear']),
        helper.make_node('Cast', ['n_rc_out'], ['n_marker_out_col_i'], to=7),
        helper.make_node('Unsqueeze', ['n_marker_out_col_i', '_v_351'], ['n_marker_out_col_i3']),
        helper.make_node('Add', ['n_red_cyan_row_zero', 'n_marker_out_col_i3'], ['n_marker_out_gather_i']),
        helper.make_node('GatherElements', ['cyan_norm', 'n_marker_out_gather_i'], ['n_marker_out_gathered'], axis=2),
        helper.make_node('Squeeze', ['n_marker_out_gathered', '_v_351'], ['n_marker_out']),
        helper.make_node('Slice', ['n_green_bad_profile', 'active_starts', 'n_red_bad_pref_m_ends', 'cumsum_axis'], ['n_corner_t_minus_shifted_core']),
        helper.make_node('Pad', ['n_corner_t_minus_shifted_core', 'n_red_bad_pref_m_pads', 'n_red_bad_pref_m_zero'], ['n_corner_t_minus_shifted'], mode='constant'),
        helper.make_node('Greater', ['n_corner_t_minus_shifted', 'zero_f'], ['n_corner_t_minus']),
        helper.make_node('Slice', ['n_green_bad_profile', 'cumsum_axis', 'active_ends', 'cumsum_axis'], ['n_corner_t_plus_shifted_core']),
        helper.make_node('Pad', ['n_corner_t_plus_shifted_core', 'n_corner_t_plus_shifted_pads', 'n_red_bad_pref_m_zero'], ['n_corner_t_plus_shifted'], mode='constant'),
        helper.make_node('Greater', ['n_corner_t_plus_shifted', 'zero_f'], ['n_corner_t_plus']),
        helper.make_node('Cast', ['n_rc_in'], ['n_red_inside_cyan_col_i'], to=7),
        helper.make_node('Unsqueeze', ['n_red_inside_cyan_col_i', '_v_351'], ['n_red_inside_cyan_col_i3']),
        helper.make_node('Add', ['n_red_cyan_row_zero', 'n_red_inside_cyan_col_i3'], ['n_red_inside_cyan_gather_i']),
        helper.make_node('GatherElements', ['cyan_norm', 'n_red_inside_cyan_gather_i'], ['n_red_inside_cyan_gathered'], axis=2),
        helper.make_node('Squeeze', ['n_red_inside_cyan_gathered', '_v_351'], ['n_red_inside_cyan']),
        helper.make_node('Equal', ['row_weights', 'n_rr_min'], ['n_extra_down_row']),
        helper.make_node('And', ['n_red_inside_cyan', 'n_extra_down_row'], ['n_extra_down_hit']),
        helper.make_node('Equal', ['row_weights', 'n_rr_max'], ['n_extra_up_row']),
        helper.make_node('And', ['n_red_inside_cyan', 'n_extra_up_row'], ['n_extra_up_hit']),
        helper.make_node('Cast', ['n_extra_down_hit'], ['n_extra_down_hit_any_f'], to=2),
        helper.make_node('ReduceMax', ['n_extra_down_hit_any_f'], ['n_extra_down_hit_any_max_u8'], axes=[1], keepdims=0),
        helper.make_node('Cast', ['n_extra_down_hit_any_max_u8'], ['n_extra_down_hit_any_max'], to=10),
        helper.make_node('Greater', ['n_extra_down_hit_any_max', 'zero_f'], ['n_extra_down_hit_any']),
        helper.make_node('Cast', ['n_extra_up_hit'], ['n_extra_up_hit_any_f'], to=2),
        helper.make_node('ReduceMax', ['n_extra_up_hit_any_f'], ['n_extra_up_hit_any_max_u8'], axes=[1], keepdims=0),
        helper.make_node('Cast', ['n_extra_up_hit_any_max_u8'], ['n_extra_up_hit_any_max'], to=10),
        helper.make_node('Greater', ['n_extra_up_hit_any_max', 'zero_f'], ['n_extra_up_hit_any']),
        helper.make_node('Not', ['n_red_right'], ['n_not_red_right']),
        helper.make_node('Or', ['n_not_red_right', 'n_extra_down_hit_any'], ['n_extra_down']),
        helper.make_node('Or', ['n_not_red_right', 'n_extra_up_hit_any'], ['n_extra_up']),
        helper.make_node('Greater', ['row_weights', 'n_rr_max'], ['n_s_down_t_gt_red']),
        helper.make_node('Less', ['row_weights', 'n_gr_min'], ['n_s_down_t_lt_green']),
        helper.make_node('And', ['n_s_down_t_gt_red', 'n_s_down_t_lt_green'], ['n_s_down_t_ok_1']),
        helper.make_node('Sub', ['n_red_bad_pref_m', 'n_red_bad_rrmax'], ['n_s_down_red_bad']),
        helper.make_node('Sub', ['n_green_bad_before_grmin', 'n_green_bad_pref'], ['n_s_down_green_bad']),
        helper.make_node('Equal', ['n_s_down_red_bad', 'zero_f'], ['n_s_down_red_clear']),
        helper.make_node('Equal', ['n_s_down_green_bad', 'zero_f'], ['n_s_down_green_clear']),
        helper.make_node('And', ['n_h_clear', 'n_s_down_red_clear'], ['n_s_down_no_bad_1']),
        helper.make_node('And', ['n_s_down_no_bad_1', 'n_s_down_green_clear'], ['n_s_down_no_bad_2']),
        helper.make_node('And', ['n_endpoint_ok', 'n_s_down_t_ok_1'], ['n_s_down_valid_1']),
        helper.make_node('And', ['n_s_down_valid_1', 'n_marker_out'], ['n_s_down_valid_2']),
        helper.make_node('And', ['n_s_down_valid_2', 'n_corner_t_minus'], ['n_s_down_valid_3']),
        helper.make_node('And', ['n_s_down_valid_3', 'n_s_down_no_bad_2'], ['n_s_down_valid_4']),
        helper.make_node('Where', ['n_s_down_valid_4', 'n_s_down_tie_score', 'zero_f'], ['n_s_down_score']),
        helper.make_node('Sub', ['active_row_max', 'row_weights'], ['n_s_up_edge']),
        helper.make_node('Less', ['row_weights', 'n_rr_min'], ['n_s_up_t_lt_red']),
        helper.make_node('Greater', ['row_weights', 'n_gr_max'], ['n_s_up_t_gt_green']),
        helper.make_node('And', ['n_s_up_t_lt_red', 'n_s_up_t_gt_green'], ['n_s_up_t_ok_1']),
        helper.make_node('Sub', ['n_red_bad_before_rrmin', 'n_red_bad_pref_m'], ['n_s_up_red_bad']),
        helper.make_node('Sub', ['n_green_bad_pref_m', 'n_green_bad_grmax'], ['n_s_up_green_bad']),
        helper.make_node('Equal', ['n_s_up_red_bad', 'zero_f'], ['n_s_up_red_clear']),
        helper.make_node('Equal', ['n_s_up_green_bad', 'zero_f'], ['n_s_up_green_clear']),
        helper.make_node('And', ['n_h_clear', 'n_s_up_red_clear'], ['n_s_up_no_bad_1']),
        helper.make_node('And', ['n_s_up_no_bad_1', 'n_s_up_green_clear'], ['n_s_up_no_bad_2']),
        helper.make_node('And', ['n_endpoint_ok', 'n_s_up_t_ok_1'], ['n_s_up_valid_1']),
        helper.make_node('And', ['n_s_up_valid_1', 'n_marker_out'], ['n_s_up_valid_2']),
        helper.make_node('And', ['n_s_up_valid_2', 'n_corner_t_plus'], ['n_s_up_valid_3']),
        helper.make_node('And', ['n_s_up_valid_3', 'n_s_up_no_bad_2'], ['n_s_up_valid_4']),
        helper.make_node('Add', ['n_s_up_edge', 'hundred_f'], ['n_s_up_tie_score']),
        helper.make_node('Where', ['n_s_up_valid_4', 'n_s_up_tie_score', 'zero_f'], ['n_s_up_score']),
        helper.make_node('Add', ['n_rr_max', 'one_f'], ['n_u_down_red_gap']),
        helper.make_node('Greater', ['row_weights', 'n_u_down_red_gap'], ['n_u_down_t_gt_red_gap']),
        helper.make_node('And', ['n_u_down_t_gt_red_gap', 'n_s_up_t_gt_green'], ['n_u_down_t_ok_1']),
        helper.make_node('Sub', ['n_red_bad_pref', 'n_red_bad_rrmax'], ['n_u_down_red_bad']),
        helper.make_node('Sub', ['n_green_bad_pref', 'n_green_bad_grmax'], ['n_u_down_green_bad']),
        helper.make_node('Equal', ['n_u_down_red_bad', 'zero_f'], ['n_u_down_red_clear']),
        helper.make_node('Equal', ['n_u_down_green_bad', 'zero_f'], ['n_u_down_green_clear']),
        helper.make_node('And', ['n_h_clear', 'n_u_down_red_clear'], ['n_u_down_no_bad_1']),
        helper.make_node('And', ['n_u_down_no_bad_1', 'n_u_down_green_clear'], ['n_u_down_no_bad_2']),
        helper.make_node('And', ['n_endpoint_ok', 'n_u_down_t_ok_1'], ['n_u_down_valid_1']),
        helper.make_node('And', ['n_u_down_valid_1', 'n_marker_out'], ['n_u_down_valid_2']),
        helper.make_node('And', ['n_u_down_valid_2', 'n_corner_t_plus'], ['n_u_down_valid_3']),
        helper.make_node('And', ['n_u_down_valid_3', 'n_u_down_no_bad_2'], ['n_u_down_valid_4']),
        helper.make_node('And', ['n_u_down_valid_4', 'n_extra_down'], ['n_u_down_valid_5']),
        helper.make_node('Where', ['n_u_down_valid_5', 'n_s_down_tie_score', 'zero_f'], ['n_u_down_score']),
        helper.make_node('Sub', ['n_rr_min', 'one_f'], ['n_u_up_red_gap']),
        helper.make_node('Less', ['row_weights', 'n_u_up_red_gap'], ['n_u_up_t_lt_red_gap']),
        helper.make_node('And', ['n_u_up_t_lt_red_gap', 'n_s_down_t_lt_green'], ['n_u_up_t_ok_1']),
        helper.make_node('Add', ['n_s_up_edge', 'one_f'], ['n_u_up_bottom_plus_one']),
        helper.make_node('Sub', ['active_row_max', 'n_rr_max'], ['n_u_up_red_orig']),
        helper.make_node('Sub', ['active_row_max', 'n_gr_max'], ['n_u_up_green_orig']),
        helper.make_node('Min', ['n_u_up_red_orig', 'n_u_up_green_orig'], ['n_u_up_row_limit']),
        helper.make_node('Mul', ['size', 'half_f'], ['n_u_up_min_u_height']),
        helper.make_node('Mul', ['size', 'three_quarters_f'], ['n_u_up_max_u_height']),
        helper.make_node('Sub', ['n_u_up_bottom_plus_one', 'n_u_up_min_u_height'], ['n_u_up_max_start']),
        helper.make_node('Sub', ['n_u_up_bottom_plus_one', 'n_u_up_max_u_height'], ['n_u_up_min_start']),
        helper.make_node('Greater', ['n_u_up_max_start', 'one_f'], ['n_u_up_height_has_margin_gt']),
        helper.make_node('Equal', ['n_u_up_max_start', 'one_f'], ['n_u_up_height_has_margin_eq']),
        helper.make_node('Or', ['n_u_up_height_has_margin_gt', 'n_u_up_height_has_margin_eq'], ['n_u_up_height_has_margin_1']),
        helper.make_node('Less', ['n_u_up_min_start', 'n_u_up_row_limit'], ['n_u_up_height_fits_top_lt']),
        helper.make_node('Equal', ['n_u_up_min_start', 'n_u_up_row_limit'], ['n_u_up_height_fits_top_eq']),
        helper.make_node('Or', ['n_u_up_height_fits_top_lt', 'n_u_up_height_fits_top_eq'], ['n_u_up_height_fits_top_1']),
        helper.make_node('And', ['n_u_up_height_has_margin_1', 'n_u_up_height_fits_top_1'], ['n_u_up_height_ok_1']),
        helper.make_node('Sub', ['n_green_bad_before_grmin', 'n_green_bad_pref_m'], ['n_u_up_green_bad']),
        helper.make_node('Equal', ['n_u_up_green_bad', 'zero_f'], ['n_u_up_green_clear']),
        helper.make_node('And', ['n_s_up_no_bad_1', 'n_u_up_green_clear'], ['n_u_up_no_bad_2']),
        helper.make_node('And', ['n_endpoint_ok', 'n_u_up_t_ok_1'], ['n_u_up_valid_1']),
        helper.make_node('And', ['n_u_up_valid_1', 'n_marker_out'], ['n_u_up_valid_2']),
        helper.make_node('And', ['n_u_up_valid_2', 'n_corner_t_minus'], ['n_u_up_valid_3']),
        helper.make_node('And', ['n_u_up_valid_3', 'n_u_up_no_bad_2'], ['n_u_up_valid_4']),
        helper.make_node('And', ['n_u_up_valid_4', 'n_extra_up'], ['n_u_up_valid_5']),
        helper.make_node('Where', ['n_u_up_height_ok_1', 'n_s_up_tie_score', 'one_f'], ['n_u_up_gated_score']),
        helper.make_node('Where', ['n_u_up_valid_5', 'n_u_up_gated_score', 'zero_f'], ['n_u_up_score']),
        helper.make_node('ReduceMax', ['n_s_down_score'], ['n_cand_max_0'], axes=[1], keepdims=1),
        helper.make_node('ReduceMax', ['n_s_up_score'], ['n_cand_max_1'], axes=[1], keepdims=1),
        helper.make_node('ReduceMax', ['n_u_down_score'], ['n_cand_max_2'], axes=[1], keepdims=1),
        helper.make_node('ReduceMax', ['n_u_up_score'], ['n_cand_max_3'], axes=[1], keepdims=1),
        helper.make_node('Max', ['n_cand_max_0', 'n_cand_max_1', 'n_cand_max_2', 'n_cand_max_3'], ['n_all_max']),
        helper.make_node('Greater', ['n_all_max', 'zero_f'], ['n_any_len']),
        helper.make_node('Equal', ['col_grid', 'n_rc_min'], ['n_out_c_rc']),
        helper.make_node('Equal', ['col_grid', 'n_gc_max'], ['n_out_c_gc']),
        helper.make_node('ArgMax', ['n_s_down_score'], ['n_arg_t_0'], axis=1, keepdims=1),
        helper.make_node('Cast', ['n_arg_t_0'], ['n_t_sel_0'], to=10),
        helper.make_node('Equal', ['n_cand_max_0', 'n_all_max'], ['n_best_0']),
        helper.make_node('And', ['n_best_0', 'n_any_len'], ['n_keep_0_1']),
        helper.make_node('Equal', ['row_mat', 'n_t_sel_0'], ['n_row_eq_t_0']),
        helper.make_node('And', ['n_row_eq_t_0', 'n_keep_0_1'], ['n_h_row_0']),
        helper.make_node('Greater', ['row_mat', 'n_rr_max'], ['n_draw_red_after_0']),
        helper.make_node('Less', ['row_mat', 'n_t_sel_0'], ['n_draw_red_before_t_0']),
        helper.make_node('Greater', ['row_mat', 'n_t_sel_0'], ['n_draw_green_after_t_0']),
        helper.make_node('Less', ['row_mat', 'n_gr_min'], ['n_draw_green_before_endpoint_0']),
        helper.make_node('And', ['n_draw_red_after_0', 'n_draw_red_before_t_0'], ['n_draw_red_rows_0']),
        helper.make_node('And', ['n_draw_green_after_t_0', 'n_draw_green_before_endpoint_0'], ['n_draw_green_rows_0']),
        helper.make_node('And', ['n_draw_red_rows_0', 'n_keep_0_1'], ['n_red_row_0']),
        helper.make_node('And', ['n_draw_green_rows_0', 'n_keep_0_1'], ['n_green_row_0']),
        helper.make_node('ArgMax', ['n_s_up_score'], ['n_arg_t_1'], axis=1, keepdims=1),
        helper.make_node('Cast', ['n_arg_t_1'], ['n_t_sel_1'], to=10),
        helper.make_node('Equal', ['n_cand_max_1', 'n_all_max'], ['n_best_1']),
        helper.make_node('And', ['n_best_1', 'n_any_len'], ['n_keep_1_1']),
        helper.make_node('Equal', ['row_mat', 'n_t_sel_1'], ['n_row_eq_t_1']),
        helper.make_node('And', ['n_row_eq_t_1', 'n_keep_1_1'], ['n_h_row_1']),
        helper.make_node('Less', ['row_mat', 'n_rr_min'], ['n_draw_red_before_1']),
        helper.make_node('Greater', ['row_mat', 'n_t_sel_1'], ['n_draw_red_from_t_1_gt']),
        helper.make_node('Or', ['n_draw_red_from_t_1_gt', 'n_row_eq_t_1'], ['n_draw_red_from_t_1_1']),
        helper.make_node('Less', ['row_mat', 'n_t_sel_1'], ['n_draw_green_before_t_1']),
        helper.make_node('Greater', ['row_mat', 'n_gr_max'], ['n_draw_green_after_endpoint_1']),
        helper.make_node('And', ['n_draw_red_before_1', 'n_draw_red_from_t_1_1'], ['n_draw_red_rows_1']),
        helper.make_node('And', ['n_draw_green_before_t_1', 'n_draw_green_after_endpoint_1'], ['n_draw_green_rows_1']),
        helper.make_node('And', ['n_draw_red_rows_1', 'n_keep_1_1'], ['n_red_row_1']),
        helper.make_node('And', ['n_draw_green_rows_1', 'n_keep_1_1'], ['n_green_row_1']),
        helper.make_node('ArgMax', ['n_u_down_score'], ['n_arg_t_2'], axis=1, keepdims=1),
        helper.make_node('Cast', ['n_arg_t_2'], ['n_t_sel_2'], to=10),
        helper.make_node('Equal', ['n_cand_max_2', 'n_all_max'], ['n_best_2']),
        helper.make_node('And', ['n_best_2', 'n_any_len'], ['n_keep_2_1']),
        helper.make_node('Equal', ['row_mat', 'n_t_sel_2'], ['n_row_eq_t_2']),
        helper.make_node('And', ['n_row_eq_t_2', 'n_keep_2_1'], ['n_h_row_2']),
        helper.make_node('Less', ['row_mat', 'n_t_sel_2'], ['n_draw_red_to_t_2_lt']),
        helper.make_node('Or', ['n_draw_red_to_t_2_lt', 'n_row_eq_t_2'], ['n_draw_red_to_t_2_1']),
        helper.make_node('And', ['n_draw_red_after_0', 'n_draw_red_to_t_2_1'], ['n_draw_red_rows_2']),
        helper.make_node('And', ['n_draw_green_after_endpoint_1', 'n_draw_red_to_t_2_1'], ['n_draw_green_rows_2']),
        helper.make_node('And', ['n_draw_red_rows_2', 'n_keep_2_1'], ['n_red_row_2']),
        helper.make_node('And', ['n_draw_green_rows_2', 'n_keep_2_1'], ['n_green_row_2']),
        helper.make_node('ArgMax', ['n_u_up_score'], ['n_arg_t_3'], axis=1, keepdims=1),
        helper.make_node('Cast', ['n_arg_t_3'], ['n_t_sel_3'], to=10),
        helper.make_node('Equal', ['n_cand_max_3', 'n_all_max'], ['n_best_3']),
        helper.make_node('And', ['n_best_3', 'n_any_len'], ['n_keep_3_1']),
        helper.make_node('Equal', ['row_mat', 'n_t_sel_3'], ['n_row_eq_t_3']),
        helper.make_node('And', ['n_row_eq_t_3', 'n_keep_3_1'], ['n_h_row_3']),
        helper.make_node('Greater', ['row_mat', 'n_t_sel_3'], ['n_draw_red_from_t_3_gt']),
        helper.make_node('Or', ['n_draw_red_from_t_3_gt', 'n_row_eq_t_3'], ['n_draw_red_from_t_3_1']),
        helper.make_node('And', ['n_draw_red_before_1', 'n_draw_red_from_t_3_1'], ['n_draw_red_rows_3']),
        helper.make_node('And', ['n_draw_green_before_endpoint_0', 'n_draw_red_from_t_3_1'], ['n_draw_green_rows_3']),
        helper.make_node('And', ['n_draw_red_rows_3', 'n_keep_3_1'], ['n_red_row_3']),
        helper.make_node('And', ['n_draw_green_rows_3', 'n_keep_3_1'], ['n_green_row_3']),
        helper.make_node('Or', ['n_h_row_0', 'n_h_row_1'], ['n_h_rows_1']),
        helper.make_node('Or', ['n_h_rows_1', 'n_h_row_2'], ['n_h_rows_2']),
        helper.make_node('Or', ['n_h_rows_2', 'n_h_row_3'], ['n_h_rows_3']),
        helper.make_node('Or', ['n_red_row_0', 'n_red_row_1'], ['n_red_rows_1']),
        helper.make_node('Or', ['n_red_rows_1', 'n_red_row_2'], ['n_red_rows_2']),
        helper.make_node('Or', ['n_red_rows_2', 'n_red_row_3'], ['n_red_rows_3']),
        helper.make_node('Or', ['n_green_row_0', 'n_green_row_1'], ['n_green_rows_1']),
        helper.make_node('Or', ['n_green_rows_1', 'n_green_row_2'], ['n_green_rows_2']),
        helper.make_node('Or', ['n_green_rows_2', 'n_green_row_3'], ['n_green_rows_3']),
        helper.make_node('And', ['n_h_rows_3', 'n_h_c_between'], ['n_horiz']),
        helper.make_node('And', ['n_red_rows_3', 'n_out_c_rc'], ['n_red_path']),
        helper.make_node('And', ['n_green_rows_3', 'n_out_c_gc'], ['n_green_path']),
        helper.make_node('Or', ['n_horiz', 'n_red_path'], ['n_selected_1']),
        helper.make_node('Or', ['n_selected_1', 'n_green_path'], ['n_selected_2']),
        helper.make_node('Transpose', ['n_selected_2'], ['norm_mask_t'], perm=[0, 2, 1]),
        helper.make_node('And', ['use_native_orientation', 'n_selected_2'], ['hidden_any_yes']),
        helper.make_node('And', ['cyan_norm_not_cond', 'norm_mask_t'], ['hidden_any_no']),
        helper.make_node('Or', ['hidden_any_yes', 'hidden_any_no'], ['hidden_any']),
        helper.make_node('Unsqueeze', ['hidden_any', 'cumsum_axis'], ['hidden4']),
        helper.make_node('Concat', ['hidden4', 'hidden_right'], ['hidden_wide'], axis=3),
        helper.make_node('Concat', ['hidden_wide', 'hidden_bottom'], ['hidden30'], axis=2),
        helper.make_node('Where', ['hidden30', 'green_paint', 'input'], ['output']),
    ]
    value_infos = [
    ]
    return model('task066', nodes, inits, output_dtype=1, opset=14, value_infos=value_infos)
