"""Task 002 — exact source reconstruction of current live graph.

This builder owns the graph structure and constants in Python source and does
not load networks/task002.onnx at runtime.  The task is a documented
wall/complex heuristic, so this file preserves the verified live behavior as
source-controlled ONNX construction.
"""
from onnx import helper
from ._exact import arr_b64, model, tensor

def build(task):
    inits = [
        tensor('axes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAA=')),
        tensor('ch0s', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('ch0e', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAABQAAAAAAAAAFAAAAAAAAAA=')),
        tensor('ch3s', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('ch3e', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoEAAAAAAAAABQAAAAAAAAAFAAAAAAAAAA=')),
        tensor('one_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('pad_hw1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAA')),
        tensor('pad_final', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQAAAAAAAAAKAAAAAAAAAAoAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'ch0s', 'ch0e', 'axes'], ['bg_f']),
        helper.make_node('Slice', ['input', 'ch3s', 'ch3e', 'axes'], ['c3_f']),
        helper.make_node('Cast', ['bg_f'], ['bg'], to=2),
        helper.make_node('Cast', ['c3_f'], ['c3ch'], to=2),
        helper.make_node('Max', ['bg', 'c3ch'], ['active']),
        helper.make_node('Sub', ['one_u8', 'active'], ['inactive']),
        helper.make_node('Pad', ['inactive', 'pad_hw1', 'one_u8'], ['inactive_pad'], mode='constant'),
        helper.make_node('MaxPool', ['inactive_pad'], ['miss'], kernel_shape=[3, 3], strides=[1, 1]),
        helper.make_node('Mul', ['bg', 'miss'], ['ext0']),
        helper.make_node('MaxPool', ['ext0'], ['h0'], kernel_shape=[1, 3], pads=[0, 1, 0, 1]),
        helper.make_node('Max', ['c3ch', 'h0'], ['g0']),
        helper.make_node('Mul', ['bg', 'g0'], ['e0']),
        helper.make_node('MaxPool', ['e0'], ['h1'], kernel_shape=[1, 3], pads=[0, 1, 0, 1]),
        helper.make_node('Max', ['c3ch', 'h1'], ['g1']),
        helper.make_node('Mul', ['bg', 'g1'], ['e1']),
        helper.make_node('MaxPool', ['e1'], ['v2'], kernel_shape=[3, 1], pads=[1, 0, 1, 0]),
        helper.make_node('MaxPool', ['e1'], ['h2'], kernel_shape=[1, 3], pads=[0, 1, 0, 1]),
        helper.make_node('Max', ['v2', 'h2'], ['g2']),
        helper.make_node('Mul', ['bg', 'g2'], ['e2']),
        helper.make_node('MaxPool', ['e2'], ['v3'], kernel_shape=[3, 1], pads=[1, 0, 1, 0]),
        helper.make_node('MaxPool', ['e2'], ['h3'], kernel_shape=[1, 3], pads=[0, 1, 0, 1]),
        helper.make_node('Max', ['v3', 'h3'], ['g3']),
        helper.make_node('Mul', ['bg', 'g3'], ['e3']),
        helper.make_node('MaxPool', ['e3'], ['v4'], kernel_shape=[3, 1], pads=[1, 0, 1, 0]),
        helper.make_node('MaxPool', ['e3'], ['h4'], kernel_shape=[1, 3], pads=[0, 1, 0, 1]),
        helper.make_node('Max', ['v4', 'h4'], ['g4']),
        helper.make_node('Mul', ['bg', 'g4'], ['e4']),
        helper.make_node('MaxPool', ['e4'], ['v5'], kernel_shape=[3, 1], pads=[1, 0, 1, 0]),
        helper.make_node('MaxPool', ['e4'], ['h5'], kernel_shape=[1, 3], pads=[0, 1, 0, 1]),
        helper.make_node('Max', ['v5', 'h5'], ['g5']),
        helper.make_node('Mul', ['bg', 'g5'], ['e5']),
        helper.make_node('MaxPool', ['e5'], ['v6'], kernel_shape=[3, 1], pads=[1, 0, 1, 0]),
        helper.make_node('MaxPool', ['e5'], ['h6'], kernel_shape=[1, 3], pads=[0, 1, 0, 1]),
        helper.make_node('Max', ['v6', 'h6'], ['g6']),
        helper.make_node('Mul', ['bg', 'g6'], ['e6']),
        helper.make_node('MaxPool', ['e6'], ['v7'], kernel_shape=[3, 1], pads=[1, 0, 1, 0]),
        helper.make_node('MaxPool', ['e6'], ['h7'], kernel_shape=[1, 3], pads=[0, 1, 0, 1]),
        helper.make_node('Max', ['v7', 'h7'], ['g7']),
        helper.make_node('Mul', ['bg', 'g7'], ['e7']),
        helper.make_node('MaxPool', ['e7'], ['v8'], kernel_shape=[3, 1], pads=[1, 0, 1, 0]),
        helper.make_node('MaxPool', ['e7'], ['h8'], kernel_shape=[1, 3], pads=[0, 1, 0, 1]),
        helper.make_node('Max', ['v8', 'h8'], ['g8']),
        helper.make_node('Mul', ['bg', 'g8'], ['e8']),
        helper.make_node('MaxPool', ['e8'], ['v9'], kernel_shape=[3, 1], pads=[1, 0, 1, 0]),
        helper.make_node('MaxPool', ['e8'], ['h9'], kernel_shape=[1, 3], pads=[0, 1, 0, 1]),
        helper.make_node('Max', ['v9', 'h9'], ['g9']),
        helper.make_node('Mul', ['bg', 'g9'], ['e9']),
        helper.make_node('MaxPool', ['e9'], ['v10'], kernel_shape=[3, 1], pads=[1, 0, 1, 0]),
        helper.make_node('MaxPool', ['e9'], ['h10'], kernel_shape=[1, 3], pads=[0, 1, 0, 1]),
        helper.make_node('Max', ['v10', 'h10'], ['g10']),
        helper.make_node('Mul', ['bg', 'g10'], ['e10']),
        helper.make_node('MaxPool', ['e10'], ['v11'], kernel_shape=[3, 1], pads=[1, 0, 1, 0]),
        helper.make_node('MaxPool', ['e10'], ['h11'], kernel_shape=[1, 3], pads=[0, 1, 0, 1]),
        helper.make_node('Max', ['v11', 'h11'], ['g11']),
        helper.make_node('Mul', ['bg', 'g11'], ['e11']),
        helper.make_node('MaxPool', ['e11'], ['v12'], kernel_shape=[3, 1], pads=[1, 0, 1, 0]),
        helper.make_node('MaxPool', ['e11'], ['h12'], kernel_shape=[1, 3], pads=[0, 1, 0, 1]),
        helper.make_node('Max', ['v12', 'h12'], ['g12']),
        helper.make_node('Mul', ['bg', 'g12'], ['e12']),
        helper.make_node('MaxPool', ['e12'], ['v13'], kernel_shape=[3, 1], pads=[1, 0, 1, 0]),
        helper.make_node('MaxPool', ['e12'], ['h13'], kernel_shape=[1, 3], pads=[0, 1, 0, 1]),
        helper.make_node('Max', ['v13', 'h13'], ['g13']),
        helper.make_node('Mul', ['bg', 'g13'], ['e13']),
        helper.make_node('MaxPool', ['e13'], ['v14'], kernel_shape=[3, 1], pads=[1, 0, 1, 0]),
        helper.make_node('MaxPool', ['e13'], ['h14'], kernel_shape=[1, 3], pads=[0, 1, 0, 1]),
        helper.make_node('Max', ['v14', 'h14'], ['g14']),
        helper.make_node('Mul', ['bg', 'g14'], ['e14']),
        helper.make_node('MaxPool', ['e14'], ['v15'], kernel_shape=[3, 1], pads=[1, 0, 1, 0]),
        helper.make_node('MaxPool', ['e14'], ['h15'], kernel_shape=[1, 3], pads=[0, 1, 0, 1]),
        helper.make_node('Max', ['v15', 'h15'], ['g15']),
        helper.make_node('Mul', ['bg', 'g15'], ['e15']),
        helper.make_node('MaxPool', ['e15'], ['v16'], kernel_shape=[3, 1], pads=[1, 0, 1, 0]),
        helper.make_node('MaxPool', ['e15'], ['h16'], kernel_shape=[1, 3], pads=[0, 1, 0, 1]),
        helper.make_node('Max', ['v16', 'h16'], ['g16']),
        helper.make_node('Mul', ['bg', 'g16'], ['e16']),
        helper.make_node('MaxPool', ['e16'], ['v17'], kernel_shape=[3, 1], pads=[1, 0, 1, 0]),
        helper.make_node('MaxPool', ['e16'], ['h17'], kernel_shape=[1, 3], pads=[0, 1, 0, 1]),
        helper.make_node('Max', ['v17', 'h17'], ['g17']),
        helper.make_node('Mul', ['bg', 'g17'], ['e17']),
        helper.make_node('MaxPool', ['e17'], ['v18'], kernel_shape=[3, 1], pads=[1, 0, 1, 0]),
        helper.make_node('MaxPool', ['e17'], ['h18'], kernel_shape=[1, 3], pads=[0, 1, 0, 1]),
        helper.make_node('Max', ['v18', 'h18'], ['g18']),
        helper.make_node('Mul', ['bg', 'g18'], ['e18']),
        helper.make_node('MaxPool', ['e18'], ['v19'], kernel_shape=[3, 1], pads=[1, 0, 1, 0]),
        helper.make_node('MaxPool', ['e18'], ['h19'], kernel_shape=[1, 3], pads=[0, 1, 0, 1]),
        helper.make_node('Max', ['v19', 'h19'], ['g19']),
        helper.make_node('Mul', ['bg', 'g19'], ['e19']),
        helper.make_node('Sub', ['bg', 'e19'], ['holes']),
        helper.make_node('Sub', ['bg', 'bg'], ['zero']),
        helper.make_node('Concat', ['e19', 'zero', 'zero', 'c3ch', 'holes'], ['out5'], axis=1),
        helper.make_node('Pad', ['out5', 'pad_final'], ['output'], mode='constant'),
    ]
    value_infos = [
    ]
    return model('task002', nodes, inits, output_dtype=2, opset=17, value_infos=value_infos)
