"""Task 342 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('coord_weights', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBBAAAgQQAAMEEAAEBBAABQQQAAYEEAAHBBAACAQQAAiEEAAJBBAACYQQAAoEEAAKhBAACwQQAAuEEAAMBBAADIQQAA0EEAANhBAADgQQAA6EE=')),
        tensor('ch8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoIAAAAAAAAAA==')),
        tensor('one_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/')),
        tensor('two_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAABA')),
        tensor('four_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIBA')),
        tensor('one_i', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
        tensor('zero16_1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDE2LCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==')),
        tensor('zero4_1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==')),
        tensor('eight4_1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoIAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAIAAAAAAAAAA==')),
        tensor('updates16', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDE2LCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAACAPwAAgD8AAIA/AACAPwAAAAAAAAAAAAAAAAAAAAAAAIA/AACAPwAAgD8AAIA/')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'coord_weights'], ['row_pos'], equation='nchw,h->nc'),
        helper.make_node('Einsum', ['input', 'coord_weights'], ['col_pos'], equation='nchw,w->nc'),
        helper.make_node('Einsum', ['input'], ['total'], equation='nchw->nc'),
        helper.make_node('Equal', ['total', 'one_f'], ['present']),
        helper.make_node('Gather', ['row_pos', 'ch8'], ['cyan_row_sum'], axis=1),
        helper.make_node('Gather', ['col_pos', 'ch8'], ['cyan_col_sum'], axis=1),
        helper.make_node('Sub', ['cyan_row_sum', 'two_f'], ['row_minus2']),
        helper.make_node('Sub', ['cyan_col_sum', 'two_f'], ['col_minus2']),
        helper.make_node('Div', ['row_minus2', 'four_f'], ['row_box_f']),
        helper.make_node('Div', ['col_minus2', 'four_f'], ['col_box_f']),
        helper.make_node('Cast', ['row_box_f'], ['row_idx'], to=7),
        helper.make_node('Cast', ['col_box_f'], ['col_idx'], to=7),
        helper.make_node('Add', ['row_idx', 'one_i'], ['rowp1']),
        helper.make_node('Add', ['col_idx', 'one_i'], ['colp1']),
        helper.make_node('Less', ['row_pos', 'row_box_f'], ['row_lt']),
        helper.make_node('Greater', ['row_pos', 'row_box_f'], ['row_gt']),
        helper.make_node('Less', ['col_pos', 'col_box_f'], ['col_lt']),
        helper.make_node('Greater', ['col_pos', 'col_box_f'], ['col_gt']),
        helper.make_node('And', ['row_lt', 'col_lt'], ['nw_rc']),
        helper.make_node('And', ['nw_rc', 'present'], ['nw_mask']),
        helper.make_node('Cast', ['nw_mask'], ['nw_mask_u8'], to=2),
        helper.make_node('ArgMax', ['nw_mask_u8'], ['color_nw'], axis=1, keepdims=1),
        helper.make_node('GatherElements', ['row_pos', 'color_nw'], ['mr_nw_f'], axis=1),
        helper.make_node('GatherElements', ['col_pos', 'color_nw'], ['mc_nw_f'], axis=1),
        helper.make_node('Cast', ['mr_nw_f'], ['mr_nw'], to=7),
        helper.make_node('Cast', ['mc_nw_f'], ['mc_nw'], to=7),
        helper.make_node('And', ['row_lt', 'col_gt'], ['ne_rc']),
        helper.make_node('Cast', ['ne_rc'], ['ne_mask_u8'], to=2),
        helper.make_node('ArgMax', ['ne_mask_u8'], ['color_ne'], axis=1, keepdims=1),
        helper.make_node('GatherElements', ['row_pos', 'color_ne'], ['mr_ne_f'], axis=1),
        helper.make_node('GatherElements', ['col_pos', 'color_ne'], ['mc_ne_f'], axis=1),
        helper.make_node('Cast', ['mr_ne_f'], ['mr_ne'], to=7),
        helper.make_node('Cast', ['mc_ne_f'], ['mc_ne'], to=7),
        helper.make_node('And', ['row_gt', 'col_lt'], ['sw_rc']),
        helper.make_node('Cast', ['sw_rc'], ['sw_mask_u8'], to=2),
        helper.make_node('ArgMax', ['sw_mask_u8'], ['color_sw'], axis=1, keepdims=1),
        helper.make_node('GatherElements', ['row_pos', 'color_sw'], ['mr_sw_f'], axis=1),
        helper.make_node('GatherElements', ['col_pos', 'color_sw'], ['mc_sw_f'], axis=1),
        helper.make_node('Cast', ['mr_sw_f'], ['mr_sw'], to=7),
        helper.make_node('Cast', ['mc_sw_f'], ['mc_sw'], to=7),
        helper.make_node('And', ['row_gt', 'col_gt'], ['se_rc']),
        helper.make_node('And', ['se_rc', 'present'], ['se_mask']),
        helper.make_node('Cast', ['se_mask'], ['se_mask_u8'], to=2),
        helper.make_node('ArgMax', ['se_mask_u8'], ['color_se'], axis=1, keepdims=1),
        helper.make_node('GatherElements', ['row_pos', 'color_se'], ['mr_se_f'], axis=1),
        helper.make_node('GatherElements', ['col_pos', 'color_se'], ['mc_se_f'], axis=1),
        helper.make_node('Cast', ['mr_se_f'], ['mr_se'], to=7),
        helper.make_node('Cast', ['mc_se_f'], ['mc_se'], to=7),
        helper.make_node('Concat', ['color_nw', 'color_ne', 'color_sw', 'color_se'], ['colors4'], axis=0),
        helper.make_node('Concat', ['mr_nw', 'mr_ne', 'mr_sw', 'mr_se'], ['marker_rows'], axis=0),
        helper.make_node('Concat', ['mc_nw', 'mc_ne', 'mc_sw', 'mc_se'], ['marker_cols'], axis=0),
        helper.make_node('Concat', ['row_idx', 'row_idx', 'rowp1', 'rowp1'], ['box_rows'], axis=0),
        helper.make_node('Concat', ['col_idx', 'colp1', 'col_idx', 'colp1'], ['box_cols'], axis=0),
        helper.make_node('Concat', ['colors4', 'zero4_1', 'eight4_1', 'colors4'], ['channels16'], axis=0),
        helper.make_node('Concat', ['marker_rows', 'marker_rows', 'box_rows', 'box_rows'], ['rows16'], axis=0),
        helper.make_node('Concat', ['marker_cols', 'marker_cols', 'box_cols', 'box_cols'], ['cols16'], axis=0),
        helper.make_node('Concat', ['zero16_1', 'channels16', 'rows16', 'cols16'], ['scatter_idx'], axis=1),
        helper.make_node('ScatterND', ['input', 'scatter_idx', 'updates16'], ['output']),
    ]
    value_infos = [
    ]
    return model('task342_live_exact', nodes, inits, output_dtype=1, opset=13, value_infos=value_infos)
