"""Task 246 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('sel', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsIDEwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAgD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==')),
        tensor('arange', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBBAAAgQQAAMEEAAEBBAABQQQAAYEEAAHBBAACAQQAAiEEAAJBBAACYQQAAoEEAAKhBAACwQQAAuEEAAMBBAADIQQAA0EEAANhBAADgQQAA6EE=')),
        tensor('shape_r', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAEAAAAAAAAAAgAAAAAAAAABAAAAAAAAAA==')),
        tensor('shape_c', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAACAAAAAAAAAA==')),
        tensor('s0', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAA==')),
        tensor('s1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
        tensor('e2', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAA==')),
        tensor('a3', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAA==')),
        tensor('row_coords', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDE3LCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAgMEBQYHCAkKCwwNDg8QEQ==')),
        tensor('col_coords', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDE3KSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAgMEBQYHCAkKCwwNDg8QEQ==')),
        tensor('pads_to_30', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAwAAAAAAAAA')),
        tensor('false_b', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGIxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('path_color', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgD8AAAAA')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'sel', 'arange'], ['rowvals'], equation='nchw,oc,h->no'),
        helper.make_node('Einsum', ['input', 'sel', 'arange'], ['colvals'], equation='nchw,oc,w->no'),
        helper.make_node('Cast', ['rowvals'], ['rowi'], to=3),
        helper.make_node('Cast', ['colvals'], ['coli'], to=3),
        helper.make_node('Reshape', ['rowi', 'shape_r'], ['rrow']),
        helper.make_node('Reshape', ['coli', 'shape_c'], ['ccol']),
        helper.make_node('Slice', ['rrow', 's0', 's1', 'e2'], ['r0']),
        helper.make_node('Slice', ['rrow', 's1', 'e2', 'e2'], ['r1']),
        helper.make_node('Slice', ['ccol', 's0', 's1', 'a3'], ['c0']),
        helper.make_node('Slice', ['ccol', 's1', 'e2', 'a3'], ['c1']),
        helper.make_node('Min', ['r0', 'r1'], ['minr']),
        helper.make_node('Max', ['r0', 'r1'], ['maxr']),
        helper.make_node('Min', ['c0', 'c1'], ['minc']),
        helper.make_node('Max', ['c0', 'c1'], ['maxc']),
        helper.make_node('Equal', ['row_coords', 'r0'], ['red_rows']),
        helper.make_node('Equal', ['col_coords', 'c1'], ['green_cols']),
        helper.make_node('Greater', ['col_coords', 'minc'], ['col_gt']),
        helper.make_node('Less', ['col_coords', 'maxc'], ['col_lt']),
        helper.make_node('And', ['col_gt', 'col_lt'], ['h_cols_strict']),
        helper.make_node('Or', ['h_cols_strict', 'green_cols'], ['h_cols']),
        helper.make_node('Greater', ['row_coords', 'minr'], ['row_gt']),
        helper.make_node('Less', ['row_coords', 'maxr'], ['row_lt']),
        helper.make_node('And', ['row_gt', 'row_lt'], ['v_rows']),
        helper.make_node('And', ['red_rows', 'h_cols'], ['h_part']),
        helper.make_node('And', ['v_rows', 'green_cols'], ['v_part']),
        helper.make_node('Or', ['h_part', 'v_part'], ['path18']),
        helper.make_node('Pad', ['path18', 'pads_to_30', 'false_b'], ['path30'], mode='constant'),
        helper.make_node('Where', ['path30', 'path_color', 'input'], ['output']),
    ]
    value_infos = [
        helper.make_tensor_value_info('rowvals', 1, [1, 2]),
        helper.make_tensor_value_info('colvals', 1, [1, 2]),
        helper.make_tensor_value_info('rowi', 3, [1, 2]),
        helper.make_tensor_value_info('coli', 3, [1, 2]),
        helper.make_tensor_value_info('rrow', 3, [1, 1, 2, 1]),
        helper.make_tensor_value_info('ccol', 3, [1, 1, 1, 2]),
        helper.make_tensor_value_info('r0', 3, [1, 1, 1, 1]),
        helper.make_tensor_value_info('r1', 3, [1, 1, 1, 1]),
        helper.make_tensor_value_info('c0', 3, [1, 1, 1, 1]),
        helper.make_tensor_value_info('c1', 3, [1, 1, 1, 1]),
        helper.make_tensor_value_info('minr', 3, [1, 1, 1, 1]),
        helper.make_tensor_value_info('maxr', 3, [1, 1, 1, 1]),
        helper.make_tensor_value_info('minc', 3, [1, 1, 1, 1]),
        helper.make_tensor_value_info('maxc', 3, [1, 1, 1, 1]),
        helper.make_tensor_value_info('red_rows', 9, [1, 1, 17, 1]),
        helper.make_tensor_value_info('green_cols', 9, [1, 1, 1, 17]),
        helper.make_tensor_value_info('col_gt', 9, [1, 1, 1, 17]),
        helper.make_tensor_value_info('col_lt', 9, [1, 1, 1, 17]),
        helper.make_tensor_value_info('h_cols_strict', 9, [1, 1, 1, 17]),
        helper.make_tensor_value_info('h_cols', 9, [1, 1, 1, 17]),
        helper.make_tensor_value_info('row_gt', 9, [1, 1, 17, 1]),
        helper.make_tensor_value_info('row_lt', 9, [1, 1, 17, 1]),
        helper.make_tensor_value_info('v_rows', 9, [1, 1, 17, 1]),
        helper.make_tensor_value_info('h_part', 9, [1, 1, 17, 17]),
        helper.make_tensor_value_info('v_part', 9, [1, 1, 17, 17]),
        helper.make_tensor_value_info('path18', 9, [1, 1, 17, 17]),
        helper.make_tensor_value_info('path30', 9, [1, 1, 30, 30]),
    ]
    return model('task246_live_exact', nodes, inits, output_dtype=1, opset=13, value_infos=value_infos)
