"""Task 285 — exact source reconstruction of current live graph.

This builder owns the graph structure and constants in Python source and does
not load networks/task285.onnx at runtime.  The task is a documented
wall/complex heuristic, so this file preserves the verified live behavior as
source-controlled ONNX construction.
"""
from onnx import helper
from ._exact import arr_b64, model, tensor

def build(task):
    inits = [
        tensor('color_kernel', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBB')),
        tensor('color_values', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJ')),
        tensor('bottom_zero_row', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('zero_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('zero_f32', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAA')),
        tensor('clear_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoK')),
        tensor('zero_f16', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAA==')),
        tensor('top_row_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==')),
        tensor('top_row_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAeAAAAAAAAAA==')),
        tensor('split3_i64', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAA=')),
        tensor('source_slice_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
        tensor('source_slice_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoZAAAAAAAAAA==')),
        tensor('max_cells_i32', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAohAAAA')),
        tensor('source_count_i32', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoYAAAA')),
        tensor('topk_cells_k', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAohAAAAAAAAAA==')),
        tensor('topk_pivots_k', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAA==')),
        tensor('topk_source_k', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoIAAAAAAAAAA==')),
        tensor('shape_flat900', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAqEAwAAAAAAAA==')),
        tensor('shape_grid900', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAEAAAAAAAAAHgAAAAAAAAAeAAAAAAAAAA==')),
        tensor('shape_cells_111', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAACEAAAAAAAAAAQAAAAAAAAA=')),
        tensor('shape_candidates_flat', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAqEAAAAAAAAAA==')),
        tensor('shape_pivots1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAAEAAAAAAAAA')),
        tensor('shape_pivots11', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAA=')),
        tensor('shape_pivot_presence4', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAA==')),
        tensor('shape_source_grid', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAAEAAAAAAAAABQAAAAAAAAAFAAAAAAAAAA==')),
        tensor('shape_conn_flat', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAABkAAAAAAAAA')),
        tensor('shape_marker_3d', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAAEAAAAAAAAAAwAAAAAAAAA=')),
        tensor('shape_source_live_3d', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAAgAAAAAAAAAAQAAAAAAAAA=')),
        tensor('shape_scatter_flat', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIApIAAAAAAAAAA==')),
        tensor('seed_src', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGIxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDUsIDUpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA')),
        tensor('source_flat_offsets', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsIDI1KSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAA//////7////9/////P///+L////h////4P///9/////e////xP///8P////C////wf///8D///+m////pf///6T///+j////ov///4j///+H////hv///4X///+E////AAAAAAEAAAACAAAAAwAAAAQAAADi////4////+T////l////5v///8T////F////xv///8f////I////pv///6f///+o////qf///6r///+I////if///4r///+L////jP///wAAAAD//////v////3////8////HgAAAB0AAAAcAAAAGwAAABoAAAA8AAAAOwAAADoAAAA5AAAAOAAAAFoAAABZAAAAWAAAAFcAAABWAAAAeAAAAHcAAAB2AAAAdQAAAHQAAAAAAAAAAQAAAAIAAAADAAAABAAAAB4AAAAfAAAAIAAAACEAAAAiAAAAPAAAAD0AAAA+AAAAPwAAAEAAAABaAAAAWwAAAFwAAABdAAAAXgAAAHgAAAB5AAAAegAAAHsAAAB8AAAA')),
        tensor('marker_flat_offsets', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsIDMpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAHgAAAB8AAAD/////HQAAAB4AAADi////4////wEAAADh////4v////////8=')),
        tensor('source_neighbor_flat_offsets', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsIDEsIDMpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAr/////4v///+H///8BAAAA4v///+P/////////HgAAAB0AAAABAAAAHgAAAB8AAAA=')),
        tensor('cand_marker_flat_offsets', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsIDEsIDMpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAHgAAAB8AAAD/////HQAAAB4AAADi////4////wEAAADh////4v////////8=')),
        tensor('dest_flat_offsets', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDk2LCAzKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAHQAAACAAAAADAAAAHAAAACEAAAAEAAAAGwAAACIAAAAFAAAAGgAAACMAAADj////PAAAAD0AAADk////OwAAAD4AAADl////OgAAAD8AAADm////OQAAAEAAAADn////OAAAAEEAAADF////WgAAAFsAAADG////WQAAAFwAAADH////WAAAAF0AAADI////VwAAAF4AAADJ////VgAAAF8AAACn////eAAAAHkAAACo////dwAAAHoAAACp////dgAAAHsAAACq////dQAAAHwAAACr////dAAAAH0AAACJ////lgAAAJcAAACK////lQAAAJgAAACL////lAAAAJkAAACM////kwAAAJoAAACN////kgAAAJsAAAD+////HAAAAB8AAAD9////GwAAACAAAAD8////GgAAACEAAAD7////GQAAACIAAADh////OwAAADwAAADg////OgAAAD0AAADf////OQAAAD4AAADe////OAAAAD8AAADd////NwAAAEAAAADD////WQAAAFoAAADC////WAAAAFsAAADB////VwAAAFwAAADA////VgAAAF0AAAC/////VQAAAF4AAACl////dwAAAHgAAACk////dgAAAHkAAACj////dQAAAHoAAACi////dAAAAHsAAACh////cwAAAHwAAACH////lQAAAJYAAACG////lAAAAJcAAACF////kwAAAJgAAACE////kgAAAJkAAACD////kQAAAJoAAADh////5P///wIAAADg////5f///wMAAADf////5v///wQAAADe////5////wUAAADE////xf///x8AAADD////xv///yAAAADC////x////yEAAADB////yP///yIAAADA////yf///yMAAACm////p////z0AAACl////qP///z4AAACk////qf///z8AAACj////qv///0AAAACi////q////0EAAACI////if///1sAAACH////iv///1wAAACG////i////10AAACF////jP///14AAACE////jf///18AAABq////a////3kAAABp////bP///3oAAABo////bf///3sAAABn////bv///3wAAABm////b////30AAADg////4/////7////f////5P////3////e////5f////z////d////5v////v////D////xP///x0AAADC////xf///xwAAADB////xv///xsAAADA////x////xoAAAC/////yP///xkAAACl////pv///zsAAACk////p////zoAAACj////qP///zkAAACi////qf///zgAAACh////qv///zcAAACH////iP///1kAAACG////if///1gAAACF////iv///1cAAACE////i////1YAAACD////jP///1UAAABp////av///3cAAABo////a////3YAAABn////bP///3UAAABm////bf///3QAAABl////bv///3MAAAA=')),
    ]
    nodes = [
        helper.make_node('Conv', ['input', 'color_kernel'], ['color_f']),
        helper.make_node('Cast', ['color_f'], ['color_idx'], to=2),
        helper.make_node('Slice', ['input', 'top_row_starts', 'top_row_ends'], ['top_row_black']),
        helper.make_node('Greater', ['top_row_black', 'zero_f32'], ['top_col_mask']),
        helper.make_node('Transpose', ['top_col_mask'], ['top_row_mask'], perm=[0, 1, 3, 2]),
        helper.make_node('And', ['top_col_mask', 'top_row_mask'], ['inside_mask']),
        helper.make_node('Reshape', ['color_idx', 'shape_flat900'], ['color_idx_flat']),
        helper.make_node('Concat', ['color_idx_flat', 'bottom_zero_row'], ['color_pad_flat'], axis=0),
        helper.make_node('Cast', ['color_idx_flat'], ['color_idx_flat_f'], to=10),
        helper.make_node('TopK', ['color_idx_flat_f', 'topk_cells_k'], ['cell_values', 'cell_indices_i64'], axis=0, largest=1, sorted=0),
        helper.make_node('Greater', ['cell_values', 'zero_f16'], ['cell_presence']),
        helper.make_node('Cast', ['cell_indices_i64'], ['cell_indices'], to=6),
        helper.make_node('Gather', ['color_idx_flat', 'cell_indices'], ['cell_colors'], axis=0),
        helper.make_node('Reshape', ['cell_indices', 'shape_cells_111'], ['cell_pad_flat_3d']),
        helper.make_node('Reshape', ['cell_colors', 'shape_cells_111'], ['cell_colors_3d']),
        helper.make_node('Reshape', ['cell_presence', 'shape_cells_111'], ['cell_presence_3d']),
        helper.make_node('Add', ['cell_pad_flat_3d', 'cand_marker_flat_offsets'], ['cand_marker_vals_indices']),
        helper.make_node('Gather', ['color_pad_flat', 'cand_marker_vals_indices'], ['cand_marker_vals'], axis=0),
        helper.make_node('Greater', ['cand_marker_vals', 'zero_u8'], ['cand_marker_nonzero']),
        helper.make_node('Equal', ['cand_marker_vals', 'cell_colors_3d'], ['cand_marker_same']),
        helper.make_node('Not', ['cand_marker_same'], ['cand_marker_diff']),
        helper.make_node('And', ['cand_marker_nonzero', 'cand_marker_diff'], ['cand_marker_valid']),
        helper.make_node('Split', ['cand_marker_valid', 'split3_i64'], ['cand_marker_0', 'cand_marker_1', 'cand_marker_2'], axis=2),
        helper.make_node('Or', ['cand_marker_0', 'cand_marker_1'], ['cand_marker_01_or']),
        helper.make_node('And', ['cand_marker_0', 'cand_marker_1'], ['cand_marker_01_and']),
        helper.make_node('And', ['cand_marker_2', 'cand_marker_01_or'], ['cand_marker_2_and_01or']),
        helper.make_node('Or', ['cand_marker_01_and', 'cand_marker_2_and_01or'], ['cand_marker_ge2']),
        helper.make_node('Add', ['cell_pad_flat_3d', 'source_neighbor_flat_offsets'], ['cand_source_vals_indices']),
        helper.make_node('Gather', ['color_pad_flat', 'cand_source_vals_indices'], ['cand_source_vals'], axis=0),
        helper.make_node('Equal', ['cand_source_vals', 'cell_colors_3d'], ['cand_source_same']),
        helper.make_node('Split', ['cand_source_same', 'split3_i64'], ['cand_source_0', 'cand_source_1', 'cand_source_2'], axis=2),
        helper.make_node('Or', ['cand_source_0', 'cand_source_1'], ['cand_source_head']),
        helper.make_node('Or', ['cand_source_head', 'cand_source_2'], ['cand_source_any']),
        helper.make_node('And', ['cand_marker_ge2', 'cand_source_any'], ['candidate_logic']),
        helper.make_node('And', ['candidate_logic', 'cell_presence_3d'], ['candidate_grid']),
        helper.make_node('Reshape', ['candidate_grid', 'shape_candidates_flat'], ['candidate_flat']),
        helper.make_node('Cast', ['candidate_flat'], ['candidate_flat_f'], to=10),
        helper.make_node('TopK', ['candidate_flat_f', 'topk_pivots_k'], ['pivot_values', 'pivot_indices_i64'], axis=0, largest=1, sorted=0),
        helper.make_node('Greater', ['pivot_values', 'zero_f16'], ['pivot_presence']),
        helper.make_node('Cast', ['pivot_indices_i64'], ['pivot_indices'], to=6),
        helper.make_node('Div', ['pivot_indices', 'max_cells_i32'], ['pivot_orient']),
        helper.make_node('Mod', ['pivot_indices', 'max_cells_i32'], ['pivot_cell']),
        helper.make_node('Gather', ['cell_indices', 'pivot_cell'], ['pivot_grid_flat'], axis=0),
        helper.make_node('Gather', ['cell_colors', 'pivot_cell'], ['pivot_colors'], axis=0),
        helper.make_node('Reshape', ['pivot_grid_flat', 'shape_pivots1'], ['pivot_grid_flat_2d']),
        helper.make_node('Reshape', ['pivot_grid_flat', 'shape_pivots11'], ['pivot_grid_flat_3d']),
        helper.make_node('Reshape', ['pivot_colors', 'shape_pivots1'], ['pivot_colors_2d']),
        helper.make_node('Reshape', ['pivot_presence', 'shape_pivots1'], ['pivot_presence_2d']),
        helper.make_node('Gather', ['source_flat_offsets', 'pivot_orient'], ['pivot_src_offsets'], axis=0),
        helper.make_node('Add', ['pivot_grid_flat_2d', 'pivot_src_offsets'], ['pivot_src_vals_indices']),
        helper.make_node('Gather', ['color_idx_flat', 'pivot_src_vals_indices'], ['pivot_src_vals'], axis=0),
        helper.make_node('Equal', ['pivot_src_vals', 'pivot_colors_2d'], ['pivot_src_same']),
        helper.make_node('And', ['pivot_src_same', 'pivot_presence_2d'], ['pivot_src_same_masked']),
        helper.make_node('Reshape', ['pivot_src_same_masked', 'shape_source_grid'], ['pivot_src_grid']),
        helper.make_node('Reshape', ['pivot_presence_2d', 'shape_pivot_presence4'], ['pivot_presence_b4d']),
        helper.make_node('And', ['seed_src', 'pivot_presence_b4d'], ['conn_b0']),
        helper.make_node('Cast', ['conn_b0'], ['conn_u0'], to=2),
        helper.make_node('MaxPool', ['conn_u0'], ['conn_nbr_sum_0'], kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]),
        helper.make_node('Greater', ['conn_nbr_sum_0', 'zero_u8'], ['conn_nbr_0']),
        helper.make_node('And', ['conn_nbr_0', 'pivot_src_grid'], ['conn_b_1']),
        helper.make_node('Cast', ['conn_b_1'], ['conn_u_1'], to=2),
        helper.make_node('MaxPool', ['conn_u_1'], ['conn_nbr_sum_1'], kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]),
        helper.make_node('Greater', ['conn_nbr_sum_1', 'zero_u8'], ['conn_nbr_1']),
        helper.make_node('And', ['conn_nbr_1', 'pivot_src_grid'], ['conn_b_2']),
        helper.make_node('Cast', ['conn_b_2'], ['conn_u_2'], to=2),
        helper.make_node('MaxPool', ['conn_u_2'], ['conn_nbr_sum_2'], kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]),
        helper.make_node('Greater', ['conn_nbr_sum_2', 'zero_u8'], ['conn_nbr_2']),
        helper.make_node('And', ['conn_nbr_2', 'pivot_src_grid'], ['conn_b_3']),
        helper.make_node('Cast', ['conn_b_3'], ['conn_u_3'], to=2),
        helper.make_node('MaxPool', ['conn_u_3'], ['conn_nbr_sum_3'], kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]),
        helper.make_node('Greater', ['conn_nbr_sum_3', 'zero_u8'], ['conn_nbr_3']),
        helper.make_node('And', ['conn_nbr_3', 'pivot_src_grid'], ['conn_b_4']),
        helper.make_node('Cast', ['conn_b_4'], ['conn_u_6'], to=2),
        helper.make_node('Gather', ['marker_flat_offsets', 'pivot_orient'], ['pivot_marker_offsets'], axis=0),
        helper.make_node('Add', ['pivot_grid_flat_2d', 'pivot_marker_offsets'], ['pivot_marker_vals_indices']),
        helper.make_node('Gather', ['color_idx_flat', 'pivot_marker_vals_indices'], ['pivot_marker_vals'], axis=0),
        helper.make_node('Reshape', ['conn_u_6', 'shape_conn_flat'], ['conn_flat_u8']),
        helper.make_node('Slice', ['conn_flat_u8', 'source_slice_starts', 'source_slice_ends', 'source_slice_starts'], ['conn_scatter_u8']),
        helper.make_node('Cast', ['conn_scatter_u8'], ['conn_scatter_f'], to=10),
        helper.make_node('TopK', ['conn_scatter_f', 'topk_source_k'], ['source_live_values', 'source_live_indices_i64'], axis=1, largest=1, sorted=0),
        helper.make_node('Greater', ['source_live_values', 'zero_f16'], ['source_live_mask']),
        helper.make_node('Cast', ['source_live_indices_i64'], ['source_live_indices'], to=6),
        helper.make_node('Reshape', ['source_live_mask', 'shape_source_live_3d'], ['source_live_mask_3d']),
        helper.make_node('Reshape', ['pivot_marker_vals', 'shape_marker_3d'], ['pivot_marker_vals_3d']),
        helper.make_node('Where', ['source_live_mask_3d', 'pivot_marker_vals_3d', 'zero_u8'], ['slot_updates']),
        helper.make_node('Mul', ['pivot_orient', 'source_count_i32'], ['pivot_dest_key_base']),
        helper.make_node('Reshape', ['pivot_dest_key_base', 'shape_pivots1'], ['pivot_dest_key_base_2d']),
        helper.make_node('Add', ['pivot_dest_key_base_2d', 'source_live_indices'], ['pivot_dest_keys']),
        helper.make_node('Gather', ['dest_flat_offsets', 'pivot_dest_keys'], ['pivot_dest_offsets_sel'], axis=0),
        helper.make_node('Add', ['pivot_dest_offsets_sel', 'pivot_grid_flat_3d'], ['pivot_dest_indices']),
        helper.make_node('Reshape', ['pivot_dest_indices', 'shape_scatter_flat'], ['all_dest_indices']),
        helper.make_node('Reshape', ['slot_updates', 'shape_scatter_flat'], ['all_updates']),
        helper.make_node('ScatterElements', ['color_idx_flat', 'all_dest_indices', 'all_updates'], ['color_flat_out'], axis=0, reduction='add'),
        helper.make_node('Reshape', ['color_flat_out', 'shape_grid900'], ['scatter_grid']),
        helper.make_node('Where', ['inside_mask', 'scatter_grid', 'clear_u8'], ['final_grid']),
        helper.make_node('Equal', ['final_grid', 'color_values'], ['output']),
    ]
    value_infos = [
    ]
    return model('task285', nodes, inits, output_dtype=9, opset=16, value_infos=value_infos)
