"""Task 121 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('axes23', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAwAAAA==')),
        tensor('axes123', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAgAAAAMAAAA=')),
        tensor('three1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAA')),
        tensor('zero1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAA')),
        tensor('one1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAA')),
        tensor('chan8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgD8AAAAA')),
        tensor('coord', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAgD8AAABAAABAQAAAgEAAAKBAAADAQAAA4EAAAABBAAAQQQAAIEEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('zero_selector1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAAA')),
        tensor('pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbAAAAAAAAABsAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'chan8', 'coord'], ['row_f'], equation='bcrs,c,r->b'),
        helper.make_node('Einsum', ['input', 'chan8', 'coord'], ['col_f'], equation='bcrs,c,s->b'),
        helper.make_node('Cast', ['row_f'], ['row_z'], to=6),
        helper.make_node('Cast', ['col_f'], ['col_z'], to=6),
        helper.make_node('Concat', ['row_z', 'col_z'], ['starts2'], axis=0),
        helper.make_node('Add', ['starts2', 'three1'], ['ends2']),
        helper.make_node('Concat', ['zero1', 'starts2'], ['bg_starts3'], axis=0),
        helper.make_node('Concat', ['one1', 'ends2'], ['bg_ends3'], axis=0),
        helper.make_node('Slice', ['input', 'bg_starts3', 'bg_ends3', 'axes123'], ['bg_patch']),
        helper.make_node('Cast', ['bg_patch'], ['patch_bg'], to=9),
        helper.make_node('Gather', ['patch_bg', 'zero1'], ['top_bg'], axis=2),
        helper.make_node('Gather', ['top_bg', 'zero1'], ['top_b0'], axis=3),
        helper.make_node('Gather', ['top_bg', 'one1'], ['top_b1'], axis=3),
        helper.make_node('And', ['top_b0', 'top_b1'], ['top_b0b1']),
        helper.make_node('Cast', ['top_b0'], ['top_b0_u8'], to=2),
        helper.make_node('Cast', ['top_b0b1'], ['top_b0b1_u8'], to=2),
        helper.make_node('Add', ['top_b0_u8', 'top_b0b1_u8'], ['top_col_offset_1111_u8']),
        helper.make_node('Squeeze', ['top_col_offset_1111_u8'], ['top_col_offset_u8']),
        helper.make_node('Cast', ['top_col_offset_u8'], ['top_col_offset'], to=6),
        helper.make_node('Add', ['col_z', 'top_col_offset'], ['color_col']),
        helper.make_node('Concat', ['row_z', 'color_col'], ['color_starts2'], axis=0),
        helper.make_node('Add', ['color_starts2', 'one1'], ['color_ends2']),
        helper.make_node('Slice', ['input', 'color_starts2', 'color_ends2', 'axes23'], ['color_pixel']),
        helper.make_node('Cast', ['color_pixel'], ['color_selector'], to=2),
        helper.make_node('Where', ['patch_bg', 'zero_selector1', 'color_selector'], ['small']),
        helper.make_node('Pad', ['small', 'pads'], ['output'], mode='constant'),
    ]
    value_infos = [
        helper.make_tensor_value_info('row_f', 1, [1]),
        helper.make_tensor_value_info('col_f', 1, [1]),
        helper.make_tensor_value_info('row_z', 6, [1]),
        helper.make_tensor_value_info('col_z', 6, [1]),
        helper.make_tensor_value_info('starts2', 6, [2]),
        helper.make_tensor_value_info('ends2', 6, [2]),
        helper.make_tensor_value_info('bg_starts3', 6, [3]),
        helper.make_tensor_value_info('bg_ends3', 6, [3]),
        helper.make_tensor_value_info('bg_patch', 1, [1, 1, 3, 3]),
        helper.make_tensor_value_info('patch_bg', 9, [1, 1, 3, 3]),
        helper.make_tensor_value_info('top_bg', 9, [1, 1, 1, 3]),
        helper.make_tensor_value_info('top_b0', 9, [1, 1, 1, 1]),
        helper.make_tensor_value_info('top_b1', 9, [1, 1, 1, 1]),
        helper.make_tensor_value_info('top_b0b1', 9, [1, 1, 1, 1]),
        helper.make_tensor_value_info('top_b0_u8', 2, [1, 1, 1, 1]),
        helper.make_tensor_value_info('top_b0b1_u8', 2, [1, 1, 1, 1]),
        helper.make_tensor_value_info('top_col_offset_1111_u8', 2, [1, 1, 1, 1]),
        helper.make_tensor_value_info('top_col_offset_u8', 2, []),
        helper.make_tensor_value_info('top_col_offset', 6, []),
        helper.make_tensor_value_info('color_col', 6, [1]),
        helper.make_tensor_value_info('color_starts2', 6, [2]),
        helper.make_tensor_value_info('color_ends2', 6, [2]),
        helper.make_tensor_value_info('color_pixel', 1, [1, 10, 1, 1]),
        helper.make_tensor_value_info('color_selector', 2, [1, 10, 1, 1]),
        helper.make_tensor_value_info('small', 2, [1, 10, 3, 3]),
    ]
    return model('task121_live_exact', nodes, inits, output_dtype=2, opset=14, value_infos=value_infos)
