"""Task 244 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('slice_axes_spatial', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAwAAAA==')),
        tensor('same_shape', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
        tensor('row_table', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsIDQsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAvFi6sbgAPAC8y7kstwA8ALxYurG4ErYAvD6597QAPAC8y7kst4SxALyxuISxADwAvD6597RqKAC8sbiEsbkz')),
        tensor('col_table', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsIDEsIDQsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAqxuFi6ALwAPCy3y7kAvAA8EraxuFi6ALz3tD65ALwAPISxLLfLuQC8hLGxuAC8ADxqKPe0PrkAvLkzhLGxuAC8')),
        tensor('pads4', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaAAAAAAAAABoAAAAAAAAA')),
        tensor('grid_shape', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAQAAAAAAAAABAAAAAAAAAABAAAAAAAAAA==')),
        tensor('cell_r8_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoIAAAAAAAAAA==')),
        tensor('cell_r8_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoJAAAAAQAAAA==')),
        tensor('cell_r11_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoLAAAAAAAAAA==')),
        tensor('cell_r11_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoMAAAAAQAAAA==')),
        tensor('cell_r14_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoOAAAAAAAAAA==')),
        tensor('cell_r14_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoPAAAAAQAAAA==')),
        tensor('cell_r15_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoPAAAAAAAAAA==')),
        tensor('cell_r15_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoQAAAAAQAAAA==')),
        tensor('cell_r17_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoRAAAAAAAAAA==')),
        tensor('cell_r17_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoSAAAAAQAAAA==')),
        tensor('probe_b_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoIAAAAAwAAAA==')),
        tensor('probe_b_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoJAAAABAAAAA==')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'cell_r8_starts', 'cell_r8_ends', 'slice_axes_spatial'], ['cell_r8']),
        helper.make_node('ReduceMax', ['cell_r8'], ['r8'], axes=[1, 2, 3], keepdims=0),
        helper.make_node('Slice', ['input', 'cell_r11_starts', 'cell_r11_ends', 'slice_axes_spatial'], ['cell_r11']),
        helper.make_node('ReduceMax', ['cell_r11'], ['r11'], axes=[1, 2, 3], keepdims=0),
        helper.make_node('Slice', ['input', 'cell_r14_starts', 'cell_r14_ends', 'slice_axes_spatial'], ['cell_r14']),
        helper.make_node('ReduceMax', ['cell_r14'], ['r14'], axes=[1, 2, 3], keepdims=0),
        helper.make_node('Slice', ['input', 'cell_r15_starts', 'cell_r15_ends', 'slice_axes_spatial'], ['cell_r15']),
        helper.make_node('ReduceMax', ['cell_r15'], ['r15'], axes=[1, 2, 3], keepdims=0),
        helper.make_node('Slice', ['input', 'cell_r17_starts', 'cell_r17_ends', 'slice_axes_spatial'], ['cell_r17']),
        helper.make_node('ReduceMax', ['cell_r17'], ['r17'], axes=[1, 2, 3], keepdims=0),
        helper.make_node('Slice', ['input', 'probe_b_starts', 'probe_b_ends', 'slice_axes_spatial'], ['probe_11_b']),
        helper.make_node('ArgMax', ['cell_r8'], ['probe_11_a_color'], axis=1, keepdims=0),
        helper.make_node('ArgMax', ['probe_11_b'], ['probe_11_b_color'], axis=1, keepdims=0),
        helper.make_node('Equal', ['probe_11_a_color', 'probe_11_b_color'], ['probe_11_same_color']),
        helper.make_node('Reshape', ['probe_11_same_color', 'same_shape'], ['probe_11_same_1d']),
        helper.make_node('Less', ['r11', 'r8'], ['is_height_11']),
        helper.make_node('And', ['is_height_11', 'probe_11_same_1d'], ['is_11_four_by_four_bool']),
        helper.make_node('Cast', ['is_11_four_by_four_bool'], ['h11_is_4'], to=1),
        helper.make_node('Sum', ['r8', 'r11', 'r14', 'r15', 'r17', 'r17', 'h11_is_4', 'r11'], ['geometry_float']),
        helper.make_node('Cast', ['geometry_float'], ['geometry_idx'], to=6),
        helper.make_node('Gather', ['row_table', 'geometry_idx'], ['row_reshaped'], axis=0),
        helper.make_node('Gather', ['col_table', 'geometry_idx'], ['col_reshaped'], axis=0),
        helper.make_node('Expand', ['row_reshaped', 'grid_shape'], ['row_grid']),
        helper.make_node('Expand', ['col_reshaped', 'grid_shape'], ['col_grid']),
        helper.make_node('Concat', ['col_grid', 'row_grid'], ['sample_grid'], axis=3),
        helper.make_node('GridSample', ['input', 'sample_grid'], ['sampled_grid'], align_corners=1, mode='nearest', padding_mode='zeros'),
        helper.make_node('Pad', ['sampled_grid', 'pads4'], ['output'], mode='constant'),
    ]
    value_infos = [
        helper.make_tensor_value_info('cell_r8', 1, [1, 10, 1, 1]),
        helper.make_tensor_value_info('r8', 1, [1]),
        helper.make_tensor_value_info('cell_r11', 1, [1, 10, 1, 1]),
        helper.make_tensor_value_info('r11', 1, [1]),
        helper.make_tensor_value_info('cell_r14', 1, [1, 10, 1, 1]),
        helper.make_tensor_value_info('r14', 1, [1]),
        helper.make_tensor_value_info('cell_r15', 1, [1, 10, 1, 1]),
        helper.make_tensor_value_info('r15', 1, [1]),
        helper.make_tensor_value_info('cell_r17', 1, [1, 10, 1, 1]),
        helper.make_tensor_value_info('r17', 1, [1]),
        helper.make_tensor_value_info('probe_11_b', 1, [1, 10, 1, 1]),
        helper.make_tensor_value_info('probe_11_a_color', 7, [1, 1, 1]),
        helper.make_tensor_value_info('probe_11_b_color', 7, [1, 1, 1]),
        helper.make_tensor_value_info('probe_11_same_color', 9, [1, 1, 1]),
        helper.make_tensor_value_info('probe_11_same_1d', 9, [1]),
        helper.make_tensor_value_info('is_height_11', 9, [1]),
        helper.make_tensor_value_info('is_11_four_by_four_bool', 9, [1]),
        helper.make_tensor_value_info('h11_is_4', 1, [1]),
        helper.make_tensor_value_info('geometry_float', 1, [1]),
        helper.make_tensor_value_info('geometry_idx', 6, [1]),
        helper.make_tensor_value_info('row_reshaped', 10, [1, 4, 1, 1]),
        helper.make_tensor_value_info('col_reshaped', 10, [1, 1, 4, 1]),
        helper.make_tensor_value_info('row_grid', 10, [1, 4, 4, 1]),
        helper.make_tensor_value_info('col_grid', 10, [1, 4, 4, 1]),
        helper.make_tensor_value_info('sample_grid', 10, [1, 4, 4, 2]),
        helper.make_tensor_value_info('sampled_grid', 1, [1, 10, 4, 4]),
    ]
    return model('task244_live_exact', nodes, inits, output_dtype=1, opset=16, value_infos=value_infos)
