"""Task 368 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('colW', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAyLCAyKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAACAPwAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAEBAAAAAAAAAAAAAAAAAAACAQAAAAAAAAAAAAAAAAAAAoEAAAAAAAAAAAAAAAAAAAMBAAAAAAAAAAAAAAAAAAADgQAAAAAAAAAAAAAAAAAAAAEEAAAAAAAAAAAAAAAAAABBBAAAAAAAAAAAAAAAA')),
        tensor('akw', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDIsIDIpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAADCAMIAPA==')),
        tensor('zero_f16', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAA==')),
        tensor('one_f16', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAPA==')),
        tensor('u5', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoF')),
        tensor('u0', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('off4', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAEAAAAAAAAAAgAAAAAAAAADAAAAAAAAAA==')),
        tensor('rowidx_c', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEwLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAQAAAAIAAAADAAAABAAAAAUAAAAGAAAABwAAAAgAAAAJAAAA')),
        tensor('colidx_r', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDEwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAQAAAAIAAAADAAAABAAAAAUAAAAGAAAABwAAAAgAAAAJAAAA')),
        tensor('big99', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIApjAAAA')),
        tensor('flipi', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAAIAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAA==')),
        tensor('colveci', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJ')),
        tensor('pad13', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAA')),
        tensor('padz', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('pad30', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUAAAAAAAAABQAAAAAAAAA')),
        tensor('pad255', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAr/')),
        tensor('one_i', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
    ]
    nodes = [
        helper.make_node('Conv', ['input', 'colW'], ['labc'], dilations=[20, 20], kernel_shape=[2, 2]),
        helper.make_node('Cast', ['labc'], ['labc16'], to=10),
        helper.make_node('Clip', ['labc16', 'zero_f16', 'one_f16'], ['occf']),
        helper.make_node('Conv', ['occf', 'akw'], ['aconv'], kernel_shape=[2, 2], pads=[1, 1, 0, 0]),
        helper.make_node('Clip', ['aconv', 'zero_f16', 'one_f16'], ['cornf']),
        helper.make_node('Cast', ['labc'], ['L'], to=2),
        helper.make_node('Greater', ['L', 'u0'], ['occb']),
        helper.make_node('Equal', ['L', 'u5'], ['is5']),
        helper.make_node('Not', ['is5'], ['not5']),
        helper.make_node('And', ['occb', 'not5'], ['colb']),
        helper.make_node('Cast', ['colb'], ['colu'], to=2),
        helper.make_node('ReduceMax', ['colu'], ['rowany'], axes=[3], keepdims=1),
        helper.make_node('ReduceMax', ['colu'], ['colany'], axes=[2], keepdims=1),
        helper.make_node('Greater', ['rowany', 'u0'], ['rmask']),
        helper.make_node('Greater', ['colany', 'u0'], ['cmask']),
        helper.make_node('Where', ['rmask', 'rowidx_c', 'big99'], ['rcand']),
        helper.make_node('Where', ['cmask', 'colidx_r', 'big99'], ['ccand']),
        helper.make_node('ReduceMin', ['rcand'], ['tr0'], keepdims=0),
        helper.make_node('ReduceMin', ['ccand'], ['tc0'], keepdims=0),
        helper.make_node('Cast', ['tr0'], ['tr0i'], to=7),
        helper.make_node('Cast', ['tc0'], ['tc0i'], to=7),
        helper.make_node('Reshape', ['tc0i', 'one_i'], ['tc1']),
        helper.make_node('Add', ['tr0i', 'off4'], ['r4']),
        helper.make_node('Add', ['tc1', 'off4'], ['c4']),
        helper.make_node('Pad', ['L', 'pad13', 'padz'], ['idx13']),
        helper.make_node('Gather', ['idx13', 'r4'], ['patchR'], axis=2),
        helper.make_node('Gather', ['patchR', 'c4'], ['patch'], axis=3),
        helper.make_node('Cast', ['patch'], ['patchf'], to=10),
        helper.make_node('Gather', ['patchf', 'flipi'], ['patchf2'], axis=2),
        helper.make_node('Gather', ['patchf2', 'flipi'], ['W'], axis=3),
        helper.make_node('Conv', ['cornf', 'W'], ['stampX'], kernel_shape=[4, 4], pads=[3, 3, 0, 0]),
        helper.make_node('Cast', ['stampX'], ['outU10'], to=2),
        helper.make_node('Pad', ['outU10', 'pad30', 'pad255'], ['padU']),
        helper.make_node('Equal', ['padU', 'colveci'], ['output']),
    ]
    value_infos = [
    ]
    return model('task368_live_exact', nodes, inits, output_dtype=9, opset=13, value_infos=value_infos)
