"""Task 065 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('coord30', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AAAAQAAAQEAAAIBAAACgQAAAwEAAAOBAAAAAQQAAEEEAACBBAAAwQQAAQEEAAFBBAABgQQAAcEEAAIBBAACIQQAAkEEAAJhBAACgQQAAqEEAALBBAAC4QQAAwEEAAMhBAADQQQAA2EEAAOBBAADoQQAA8EE=')),
        tensor('pos_r7', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDcsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AAAAQAAAQEAAAIBAAACgQAAAwEAAAOBA')),
        tensor('pos_c7', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDcsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AAAAQAAAQEAAAIBAAACgQAAAwEAAAOBA')),
        tensor('one_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/')),
        tensor('half_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAA/')),
        tensor('zero_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('two_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoC')),
        tensor('three_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoD')),
        tensor('five_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoF')),
        tensor('six_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoG')),
        tensor('axes_23', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAMAAAAAAAAA')),
        tensor('pads_r', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAFwAAAAAAAAAAAAAAAAAAAA==')),
        tensor('pads_c', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAABcAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'one_f'], ['counts'], equation='bchw,z->bc'),
        helper.make_node('Einsum', ['counts', 'one_f'], ['total_count'], equation='bc,z->b'),
        helper.make_node('Sqrt', ['total_count'], ['side_f']),
        helper.make_node('Add', ['side_f', 'one_f'], ['side_p1_f']),
        helper.make_node('Mul', ['side_p1_f', 'half_f'], ['period_f']),
        helper.make_node('Equal', ['counts', 'one_f'], ['dot_mask']),
        helper.make_node('Cast', ['dot_mask'], ['dot_mask_u8_arg'], to=2),
        helper.make_node('Cast', ['dot_mask'], ['dot_mask_f'], to=1),
        helper.make_node('Einsum', ['input', 'coord30', 'dot_mask_f', 'one_f'], ['dot_row'], equation='bchw,h,bc,z->bz'),
        helper.make_node('Einsum', ['input', 'coord30', 'dot_mask_f'], ['dot_col'], equation='bchw,w,bc->b'),
        helper.make_node('Mod', ['dot_row', 'period_f'], ['dot_rn'], fmod=1),
        helper.make_node('Mod', ['dot_col', 'period_f'], ['dot_cn'], fmod=1),
        helper.make_node('ReduceMax', ['counts'], ['max_count'], keepdims=0),
        helper.make_node('Equal', ['counts', 'max_count'], ['bg_mask']),
        helper.make_node('Where', ['bg_mask', 'six_u8', 'dot_mask_u8_arg'], ['chan_bits2']),
        helper.make_node('Unsqueeze', ['chan_bits2', 'axes_23'], ['chan_bits']),
        helper.make_node('Less', ['pos_r7', 'period_f'], ['valid_r7']),
        helper.make_node('Equal', ['pos_r7', 'dot_rn'], ['row_hot7']),
        helper.make_node('Where', ['valid_r7', 'six_u8', 'zero_u8'], ['row_base7']),
        helper.make_node('Where', ['row_hot7', 'three_u8', 'row_base7'], ['row_bits7']),
        helper.make_node('Pad', ['row_bits7', 'pads_r'], ['row_bits'], mode='constant'),
        helper.make_node('Less', ['pos_c7', 'period_f'], ['valid_c7']),
        helper.make_node('Equal', ['pos_c7', 'dot_cn'], ['col_hot7']),
        helper.make_node('Where', ['valid_c7', 'two_u8', 'zero_u8'], ['col_base7']),
        helper.make_node('Where', ['col_hot7', 'five_u8', 'col_base7'], ['col_bits7']),
        helper.make_node('Pad', ['col_bits7', 'pads_c'], ['col_bits'], mode='constant'),
        helper.make_node('BitwiseAnd', ['chan_bits', 'row_bits'], ['chan_row_bits']),
        helper.make_node('BitwiseAnd', ['chan_row_bits', 'col_bits'], ['output']),
    ]
    value_infos = [
    ]
    return model('task065_live_exact', nodes, inits, output_dtype=2, opset=18, value_infos=value_infos)
