"""Task 044 — exact source reconstruction of current live graph.

This builder owns the graph structure and constants in Python source and does
not load networks/task044.onnx at runtime.  The task is a documented
wall/complex heuristic, so this file preserves the verified live behavior as
source-controlled ONNX construction.
"""
from onnx import helper
from ._exact import arr_b64, model, tensor

def build(task):
    inits = [
        tensor('clip_min', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAA==')),
        tensor('clip_max', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAPA==')),
        tensor('crop_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAA')),
        tensor('crop_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoKAAAAAAAAAAoAAAAAAAAA')),
        tensor('crop_axes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAMAAAAAAAAA')),
        tensor('output_pad', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUAAAAAAAAABQAAAAAAAAA')),
        tensor('axes1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
        tensor('axes2', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAA==')),
        tensor('axes3', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAA==')),
        tensor('squeeze_axes01', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAEAAAAAAAAA')),
        tensor('zero_index', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAA==')),
        tensor('five_index', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoFAAAAAAAAAA==')),
        tensor('bottom_border_row', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoJAAAAAAAAAA==')),
        tensor('coord', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAA8AEAAQgBEAEUARgBHAEiASA==')),
        tensor('coord_3d', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAA8AEAAQgBEAEUARgBHAEiASA==')),
        tensor('two_scalar', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAQA==')),
        tensor('seven_scalar', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoARw==')),
        tensor('half_scalar', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAOA==')),
        tensor('movable_values_2d', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAA8AEAAQgBEAEUARgBHAEiASA==')),
        tensor('movable_values_4d', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAA8AEAAQgBEAEUARgBHAEiASA==')),
        tensor('pad_value_bool', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGIxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'crop_starts', 'crop_ends', 'crop_axes'], ['crop_f32']),
        helper.make_node('Cast', ['crop_f32'], ['crop'], to=10),
        helper.make_node('Gather', ['crop', 'zero_index'], ['zero'], axis=1),
        helper.make_node('Gather', ['crop', 'five_index'], ['five'], axis=1),
        helper.make_node('ReduceSum', ['five', 'axes3'], ['gray_row_sum_all'], keepdims=0),
        helper.make_node('Clip', ['gray_row_sum_all', 'clip_min', 'clip_max'], ['gray_row_active_all']),
        helper.make_node('Sub', ['clip_max', 'gray_row_active_all'], ['gray_row_inactive']),
        helper.make_node('Mul', ['gray_row_inactive', 'coord_3d'], ['gray_gap_weighted']),
        helper.make_node('ArgMax', ['gray_row_active_all'], ['top_box_row_i64'], axis=2, keepdims=0),
        helper.make_node('ReduceMax', ['gray_gap_weighted'], ['gap_row_unsqueezed'], axes=[2], keepdims=0),
        helper.make_node('Squeeze', ['top_box_row_i64', 'squeeze_axes01'], ['top_box_row_scalar_i64']),
        helper.make_node('Squeeze', ['gap_row_unsqueezed', 'squeeze_axes01'], ['gap_row']),
        helper.make_node('Cast', ['top_box_row_scalar_i64'], ['top_box_row'], to=10),
        helper.make_node('Sub', ['gap_row', 'top_box_row'], ['top_box_h_full']),
        helper.make_node('Sub', ['top_box_h_full', 'two_scalar'], ['top_inner_h']),
        helper.make_node('Add', ['top_box_row', 'clip_max'], ['top_inner_row0']),
        helper.make_node('Sub', ['seven_scalar', 'gap_row'], ['bottom_inner_h']),
        helper.make_node('Add', ['gap_row', 'two_scalar'], ['bottom_inner_row0']),
        helper.make_node('Gather', ['five', 'top_box_row_scalar_i64'], ['top_gray_col_active'], axis=2),
        helper.make_node('Gather', ['five', 'bottom_border_row'], ['bottom_gray_col_active'], axis=2),
        helper.make_node('ArgMax', ['top_gray_col_active'], ['top_box_col_i64'], axis=2, keepdims=0),
        helper.make_node('Cast', ['top_box_col_i64'], ['top_box_col'], to=10),
        helper.make_node('ReduceSum', ['top_gray_col_active', 'axes2'], ['top_box_w_full'], keepdims=0),
        helper.make_node('Sub', ['top_box_w_full', 'two_scalar'], ['top_inner_w']),
        helper.make_node('Add', ['top_box_col', 'clip_max'], ['top_inner_col0']),
        helper.make_node('ArgMax', ['bottom_gray_col_active'], ['bottom_box_col_i64'], axis=2, keepdims=0),
        helper.make_node('Cast', ['bottom_box_col_i64'], ['bottom_box_col'], to=10),
        helper.make_node('ReduceSum', ['bottom_gray_col_active', 'axes2'], ['bottom_box_w_full'], keepdims=0),
        helper.make_node('Sub', ['bottom_box_w_full', 'two_scalar'], ['bottom_inner_w']),
        helper.make_node('Add', ['bottom_box_col', 'clip_max'], ['bottom_inner_col0']),
        helper.make_node('Sub', ['top_inner_row0', 'half_scalar'], ['top_inner_row_start']),
        helper.make_node('Add', ['top_inner_row0', 'top_inner_h'], ['top_inner_row_end_raw']),
        helper.make_node('Sub', ['top_inner_row_end_raw', 'half_scalar'], ['top_inner_row_end']),
        helper.make_node('Greater', ['coord', 'top_inner_row_start'], ['top_inner_row_ge']),
        helper.make_node('Less', ['coord', 'top_inner_row_end'], ['top_inner_row_lt']),
        helper.make_node('And', ['top_inner_row_ge', 'top_inner_row_lt'], ['top_inner_row_bool']),
        helper.make_node('Cast', ['top_inner_row_bool'], ['top_inner_row'], to=10),
        helper.make_node('Unsqueeze', ['top_inner_row', 'axes1'], ['top_inner_row_col']),
        helper.make_node('Sub', ['top_inner_col0', 'half_scalar'], ['top_inner_col_start']),
        helper.make_node('Add', ['top_inner_col0', 'top_inner_w'], ['top_inner_col_end_raw']),
        helper.make_node('Sub', ['top_inner_col_end_raw', 'half_scalar'], ['top_inner_col_end']),
        helper.make_node('Greater', ['coord', 'top_inner_col_start'], ['top_inner_col_ge']),
        helper.make_node('Less', ['coord', 'top_inner_col_end'], ['top_inner_col_lt']),
        helper.make_node('And', ['top_inner_col_ge', 'top_inner_col_lt'], ['top_inner_col_bool']),
        helper.make_node('Cast', ['top_inner_col_bool'], ['top_inner_col'], to=10),
        helper.make_node('Mul', ['top_inner_row_col', 'top_inner_col'], ['top_inner_area']),
        helper.make_node('Mul', ['zero', 'top_inner_area'], ['hole_top']),
        helper.make_node('Sub', ['bottom_inner_row0', 'half_scalar'], ['bottom_inner_row_start']),
        helper.make_node('Add', ['bottom_inner_row0', 'bottom_inner_h'], ['bottom_inner_row_end_raw']),
        helper.make_node('Sub', ['bottom_inner_row_end_raw', 'half_scalar'], ['bottom_inner_row_end']),
        helper.make_node('Greater', ['coord', 'bottom_inner_row_start'], ['bottom_inner_row_ge']),
        helper.make_node('Less', ['coord', 'bottom_inner_row_end'], ['bottom_inner_row_lt']),
        helper.make_node('And', ['bottom_inner_row_ge', 'bottom_inner_row_lt'], ['bottom_inner_row_bool']),
        helper.make_node('Cast', ['bottom_inner_row_bool'], ['bottom_inner_row'], to=10),
        helper.make_node('Unsqueeze', ['bottom_inner_row', 'axes1'], ['bottom_inner_row_col']),
        helper.make_node('Sub', ['bottom_inner_col0', 'half_scalar'], ['bottom_inner_col_start']),
        helper.make_node('Add', ['bottom_inner_col0', 'bottom_inner_w'], ['bottom_inner_col_end_raw']),
        helper.make_node('Sub', ['bottom_inner_col_end_raw', 'half_scalar'], ['bottom_inner_col_end']),
        helper.make_node('Greater', ['coord', 'bottom_inner_col_start'], ['bottom_inner_col_ge']),
        helper.make_node('Less', ['coord', 'bottom_inner_col_end'], ['bottom_inner_col_lt']),
        helper.make_node('And', ['bottom_inner_col_ge', 'bottom_inner_col_lt'], ['bottom_inner_col_bool']),
        helper.make_node('Cast', ['bottom_inner_col_bool'], ['bottom_inner_col'], to=10),
        helper.make_node('Mul', ['bottom_inner_row_col', 'bottom_inner_col'], ['bottom_inner_area']),
        helper.make_node('Mul', ['zero', 'bottom_inner_area'], ['hole_bottom']),
        helper.make_node('ReduceSum', ['hole_top', 'axes3'], ['hole_top_row_sum'], keepdims=0),
        helper.make_node('ReduceSum', ['hole_top', 'axes2'], ['hole_top_col_sum'], keepdims=0),
        helper.make_node('Clip', ['hole_top_row_sum', 'clip_min', 'clip_max'], ['hole_top_row_active']),
        helper.make_node('ArgMax', ['hole_top_row_active'], ['hole_top_row_index_i64'], axis=2, keepdims=0),
        helper.make_node('Cast', ['hole_top_row_index_i64'], ['hole_top_row_index'], to=10),
        helper.make_node('ReduceSum', ['hole_top_row_sum', 'axes2'], ['hole_top_area'], keepdims=0),
        helper.make_node('MatMul', ['hole_top_row_sum', 'coord'], ['hole_top_row_raw_1']),
        helper.make_node('MatMul', ['hole_top_col_sum', 'coord'], ['hole_top_col_raw_1']),
        helper.make_node('Mul', ['hole_top_row_index', 'hole_top_area'], ['hole_top_row_shift_1']),
        helper.make_node('Mul', ['top_inner_col0', 'hole_top_area'], ['hole_top_col_shift_1']),
        helper.make_node('Sub', ['hole_top_row_raw_1', 'hole_top_row_shift_1'], ['hole_top_row_m1']),
        helper.make_node('Sub', ['hole_top_col_raw_1', 'hole_top_col_shift_1'], ['hole_top_col_m1']),
        helper.make_node('ReduceSum', ['hole_bottom', 'axes3'], ['hole_bottom_row_sum'], keepdims=0),
        helper.make_node('ReduceSum', ['hole_bottom', 'axes2'], ['hole_bottom_col_sum'], keepdims=0),
        helper.make_node('Clip', ['hole_bottom_row_sum', 'clip_min', 'clip_max'], ['hole_bottom_row_active']),
        helper.make_node('Clip', ['hole_bottom_col_sum', 'clip_min', 'clip_max'], ['hole_bottom_col_active']),
        helper.make_node('ArgMax', ['hole_bottom_row_active'], ['hole_bottom_row_index_i64'], axis=2, keepdims=0),
        helper.make_node('ArgMax', ['hole_bottom_col_active'], ['hole_bottom_col_index_i64'], axis=2, keepdims=0),
        helper.make_node('Cast', ['hole_bottom_row_index_i64'], ['hole_bottom_row_index'], to=10),
        helper.make_node('Cast', ['hole_bottom_col_index_i64'], ['hole_bottom_col_index'], to=10),
        helper.make_node('ReduceSum', ['hole_bottom_row_sum', 'axes2'], ['hole_bottom_area'], keepdims=0),
        helper.make_node('MatMul', ['hole_bottom_row_sum', 'coord'], ['hole_bottom_row_raw_1']),
        helper.make_node('MatMul', ['hole_bottom_col_sum', 'coord'], ['hole_bottom_col_raw_1']),
        helper.make_node('Mul', ['hole_bottom_row_index', 'hole_bottom_area'], ['hole_bottom_row_shift_1']),
        helper.make_node('Mul', ['hole_bottom_col_index', 'hole_bottom_area'], ['hole_bottom_col_shift_1']),
        helper.make_node('Sub', ['hole_bottom_row_raw_1', 'hole_bottom_row_shift_1'], ['hole_bottom_row_m1']),
        helper.make_node('Sub', ['hole_bottom_col_raw_1', 'hole_bottom_col_shift_1'], ['hole_bottom_col_m1']),
        helper.make_node('ReduceSum', ['crop', 'axes3'], ['movable_row_sum'], keepdims=0),
        helper.make_node('ReduceSum', ['crop', 'axes2'], ['movable_col_sum'], keepdims=0),
        helper.make_node('Clip', ['movable_row_sum', 'clip_min', 'clip_max'], ['movable_row_active']),
        helper.make_node('Clip', ['movable_col_sum', 'clip_min', 'clip_max'], ['movable_col_active']),
        helper.make_node('ArgMax', ['movable_row_active'], ['movable_row_index_i64'], axis=2, keepdims=0),
        helper.make_node('ArgMax', ['movable_col_active'], ['movable_col_index_i64'], axis=2, keepdims=0),
        helper.make_node('Cast', ['movable_row_index_i64'], ['movable_row_index'], to=10),
        helper.make_node('Cast', ['movable_col_index_i64'], ['movable_col_index'], to=10),
        helper.make_node('ReduceSum', ['movable_row_sum', 'axes2'], ['movable_area'], keepdims=0),
        helper.make_node('MatMul', ['movable_row_sum', 'coord'], ['movable_row_raw_1']),
        helper.make_node('MatMul', ['movable_col_sum', 'coord'], ['movable_col_raw_1']),
        helper.make_node('Mul', ['movable_row_index', 'movable_area'], ['movable_row_shift_1']),
        helper.make_node('Mul', ['movable_col_index', 'movable_area'], ['movable_col_shift_1']),
        helper.make_node('Sub', ['movable_row_raw_1', 'movable_row_shift_1'], ['movable_row_m1']),
        helper.make_node('Sub', ['movable_col_raw_1', 'movable_col_shift_1'], ['movable_col_m1']),
        helper.make_node('Equal', ['movable_row_m1', 'hole_top_row_m1'], ['top_row_match']),
        helper.make_node('Equal', ['movable_col_m1', 'hole_top_col_m1'], ['top_col_match']),
        helper.make_node('And', ['top_row_match', 'top_col_match'], ['top_m2_match_bool']),
        helper.make_node('Cast', ['top_m2_match_bool'], ['top_match'], to=10),
        helper.make_node('Mul', ['top_match', 'movable_values_2d'], ['top_color_parts']),
        helper.make_node('ReduceMax', ['top_color_parts'], ['top_color'], axes=[1], keepdims=0),
        helper.make_node('Equal', ['movable_row_m1', 'hole_bottom_row_m1'], ['bottom_row_match']),
        helper.make_node('Equal', ['movable_col_m1', 'hole_bottom_col_m1'], ['bottom_col_match']),
        helper.make_node('Equal', ['movable_area', 'hole_bottom_area'], ['bottom_area_match']),
        helper.make_node('And', ['bottom_row_match', 'bottom_col_match'], ['bottom_m2_match_bool']),
        helper.make_node('And', ['bottom_m2_match_bool', 'bottom_area_match'], ['bottom_match_bool']),
        helper.make_node('Cast', ['bottom_match_bool'], ['bottom_match'], to=10),
        helper.make_node('Mul', ['bottom_match', 'movable_values_2d'], ['bottom_color_parts']),
        helper.make_node('ReduceMax', ['bottom_color_parts'], ['bottom_color'], axes=[1], keepdims=0),
        helper.make_node('Or', ['top_m2_match_bool', 'bottom_match_bool'], ['task044_bool_union_or']),
        helper.make_node('Cast', ['task044_bool_union_or'], ['matched'], to=10),
        helper.make_node('Unsqueeze', ['matched', 'crop_axes'], ['matched_4d']),
        helper.make_node('Mul', ['matched_4d', 'movable_values_4d'], ['matched_values_4d']),
        helper.make_node('Conv', ['crop', 'matched_values_4d'], ['all_removed_values']),
        helper.make_node('Conv', ['crop', 'movable_values_4d'], ['grid_in']),
        helper.make_node('Mul', ['hole_top', 'top_color'], ['top_fill']),
        helper.make_node('Mul', ['hole_bottom', 'bottom_color'], ['bottom_fill']),
        helper.make_node('Add', ['top_fill', 'bottom_fill'], ['all_fill']),
        helper.make_node('Sub', ['grid_in', 'all_removed_values'], ['grid_without_sources']),
        helper.make_node('Add', ['grid_without_sources', 'all_fill'], ['grid_out']),
        helper.make_node('Equal', ['grid_out', 'movable_values_4d'], ['output_cropped_bool']),
        helper.make_node('Pad', ['output_cropped_bool', 'output_pad', 'pad_value_bool'], ['output'], mode='constant'),
    ]
    value_infos = [
    ]
    return model('task044', nodes, inits, output_dtype=9, opset=13, value_infos=value_infos)
