"""Task 030 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('sel124', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsIDEwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('wcol', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBBAAAgQQAAMEEAAEBBAABQQQAAYEEAAHBBAACAQQAAiEEAAJBBAACYQQAAoEEAAKhBAACwQQAAuEEAAMBBAADIQQAA0EEAANhBAADgQQAA6EE=')),
        tensor('base_idx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJ')),
        tensor('row_mod', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoK')),
        tensor('zero_ch', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEwLCAxMCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA')),
        tensor('one_cell', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('ax123', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAA=')),
        tensor('x1_s', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('x1_e', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAoAAAAAAAAACgAAAAAAAAA=')),
        tensor('h10_s', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAkAAAAAAAAAAAAAAAAAAAA=')),
        tensor('h10_e', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAoAAAAAAAAAAQAAAAAAAAA=')),
        tensor('ax0', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAA==')),
        tensor('s2_s', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
        tensor('s2_e', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAA==')),
        tensor('s4_e', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAA==')),
        tensor('out_pad', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQAAAAAAAAAUAAAAAAAAABQAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'sel124', 'wcol'], ['sumcol'], equation='nchw,vc,w->nv'),
        helper.make_node('Einsum', ['input', 'sel124'], ['cnt'], equation='nchw,vc->nv'),
        helper.make_node('Slice', ['sumcol', 'ax0', 's2_s', 's2_s'], ['sum1']),
        helper.make_node('Sub', ['sumcol', 'sum1'], ['dsum']),
        helper.make_node('Div', ['dsum', 'cnt'], ['sflt']),
        helper.make_node('Reshape', ['sflt', 's4_e'], ['s3f']),
        helper.make_node('Cast', ['s3f'], ['s3'], to=3),
        helper.make_node('Slice', ['s3', 's2_s', 's2_e', 'ax0'], ['s2']),
        helper.make_node('Slice', ['s3', 's2_e', 's4_e', 'ax0'], ['s4']),
        helper.make_node('Slice', ['input', 'x1_s', 'x1_e', 'ax123'], ['x1f']),
        helper.make_node('Cast', ['x1f'], ['x1'], to=3),
        helper.make_node('Slice', ['input', 'h10_s', 'h10_e', 'ax123'], ['h10f']),
        helper.make_node('Cast', ['h10f'], ['h10'], to=3),
        helper.make_node('Sub', ['base_idx', 's2'], ['ci_x2s']),
        helper.make_node('Mod', ['ci_x2s', 'row_mod'], ['ci_x2sm'], fmod=0),
        helper.make_node('Cast', ['ci_x2sm'], ['ci_x2si'], to=6),
        helper.make_node('Gather', ['x1', 'ci_x2si'], ['x2s'], axis=3),
        helper.make_node('Sub', ['base_idx', 's4'], ['ci_x4s']),
        helper.make_node('Mod', ['ci_x4s', 'row_mod'], ['ci_x4sm'], fmod=0),
        helper.make_node('Cast', ['ci_x4sm'], ['ci_x4si'], to=6),
        helper.make_node('Gather', ['x1', 'ci_x4si'], ['x4s'], axis=3),
        helper.make_node('Concat', ['one_cell', 'one_cell', 'one_cell', 'one_cell', 'one_cell', 'h10', 'h10', 'h10', 'h10', 'h10'], ['inside'], axis=2),
        helper.make_node('Max', ['x1', 'x2s', 'x4s'], ['fg']),
        helper.make_node('Sub', ['inside', 'fg'], ['bg']),
        helper.make_node('Concat', ['bg', 'x1', 'x2s', 'zero_ch', 'x4s'], ['crop'], axis=1),
        helper.make_node('Pad', ['crop', 'out_pad'], ['output'], mode='constant'),
    ]
    value_infos = [
        helper.make_tensor_value_info('sumcol', 1, [1, 3]),
        helper.make_tensor_value_info('cnt', 1, [1, 3]),
        helper.make_tensor_value_info('sum1', 1, [1, 1]),
        helper.make_tensor_value_info('dsum', 1, [1, 3]),
        helper.make_tensor_value_info('sflt', 1, [1, 3]),
        helper.make_tensor_value_info('s3f', 1, [3]),
        helper.make_tensor_value_info('s3', 3, [3]),
        helper.make_tensor_value_info('s2', 3, [1]),
        helper.make_tensor_value_info('s4', 3, [1]),
        helper.make_tensor_value_info('x1f', 1, [1, 1, 10, 10]),
        helper.make_tensor_value_info('x1', 3, [1, 1, 10, 10]),
        helper.make_tensor_value_info('h10f', 1, [1, 1, 1, 1]),
        helper.make_tensor_value_info('h10', 3, [1, 1, 1, 1]),
        helper.make_tensor_value_info('ci_x2s', 3, [10]),
        helper.make_tensor_value_info('ci_x2sm', 3, [10]),
        helper.make_tensor_value_info('ci_x2si', 6, [10]),
        helper.make_tensor_value_info('x2s', 3, [1, 1, 10, 10]),
        helper.make_tensor_value_info('ci_x4s', 3, [10]),
        helper.make_tensor_value_info('ci_x4sm', 3, [10]),
        helper.make_tensor_value_info('ci_x4si', 6, [10]),
        helper.make_tensor_value_info('x4s', 3, [1, 1, 10, 10]),
        helper.make_tensor_value_info('inside', 3, [1, 1, 10, 1]),
        helper.make_tensor_value_info('fg', 3, [1, 1, 10, 10]),
        helper.make_tensor_value_info('bg', 3, [1, 1, 10, 10]),
        helper.make_tensor_value_info('crop', 3, [1, 5, 10, 10]),
    ]
    return model('task030_live_exact', nodes, inits, output_dtype=3, opset=14, value_infos=value_infos)
