"""Task 074 (3631a71a): full-canvas D4-symmetric reconstruction under maroon cutouts.

Rule (from ARC-GEN generator): a 32x32 region (trisize=16, n=2*trisize=32) carries a
pattern with full D4 dihedral symmetry -- the 8-element orbit
  {(r,c),(c,r),(r,n-1-c),(c,n-1-r),(n-1-r,c),(n-1-c,r),(n-1-r,n-1-c),(n-1-c,n-1-r)}
with n=32 all share one colour.  Several maroon (colour 9) rectangles are stamped
over the pattern, occluding it.  The generator guarantees every occluded (maroon)
cell still has at least one NON-maroon orbit member inside the 30x30 grid.  The
output is the ENTIRE 30x30 grid with every maroon cell reconstructed from symmetry
(non-maroon cells are copied unchanged); no maroon remains in the output.

Reconstruction = elementwise MAX over the 8 D4 transforms with maroon dropped to 0:
  * The colour-index plane is a 1x1 Conv  val[i,j] = sum_k w_k * input_k  with
    w_k = k EXCEPT w_9 = 0, so maroon cells map straight to 0 (no mask/Where needed;
    0 loses every max, and a genuinely-background cell still has a 0-showing orbit
    member, so the max recovers it).  Cast that fp32 plane to uint8 (colours 0..8).
  * The 8 D4 images are generated by 3 maxes (a 2-max set is insufficient because the
    flip axis sits at index n-1=31, not the array centre -- verified the orbit needs
    {flipC, flipR, transpose}).  Flips about 31 are a Pad-by-2 (end) then a Gather
    with index vector gi = [31-i for i in 0..29]; transpose is a 0-param Transpose.
  * uint8 elementwise-max = Where(Greater(a,b), a, b)  (ORT has no uint8 Max but does
    have uint8 Greater/Where) -- keeps every working plane at 900B (vs 1800B fp16).
  * output = Equal(P_uint8, arange[0..9])  ([1,10,30,30] BOOL) routed into the FREE
    output; no 10-channel intermediate is ever materialised.

Dominant intermediate: the 3600B fp32 colour-index plane from the Conv (input is
fp32 so the Conv output dtype is forced fp32; the 10->1 reduction is irreducible).
Everything after it is uint8 (900B) or bool (900B).

Verified exact: numpy reference 0 failures over 300 fresh instances; ONNX stored
267/267, isolated fresh 200/200.
"""

import numpy as np
from onnx import helper, numpy_helper, TensorProto

from ..harness import IR_VERSION

U8 = TensorProto.UINT8


def build(task):
    inits, nodes = [], []

    def init(name, arr, dtype):
        inits.append(numpy_helper.from_array(
            np.ascontiguousarray(arr, dtype=dtype), name))
        return name

    def n(op, ins, out, **attrs):
        nodes.append(helper.make_node(op, ins, [out], **attrs))
        return out

    def umax(a, b, tag):
        # uint8 elementwise max (ORT lacks uint8 Max, has uint8 Greater/Where)
        n("Greater", [a, b], tag + "g")
        return n("Where", [tag + "g", a, b], tag)

    # ---------- colour-index plane (maroon folded to 0 via the kernel) ----------
    kwv = np.arange(10, dtype=np.float32)
    kwv[9] = 0.0                                   # maroon channel weight 0 -> 0
    init("kw", kwv.reshape(1, 10, 1, 1), np.float32)
    init("zero", np.array(0, np.uint8), np.uint8)
    n("Conv", ["input", "kw"], "colf32")           # [1,1,30,30] fp32
    n("Cast", ["colf32"], "val", to=U8)            # [1,1,30,30] uint8 (maroon already 0)

    # flip index vector: output i in 0..29 reads source 31-i (flip about axis index 31)
    init("gi", np.array([31 - i for i in range(30)], np.int64), np.int64)

    # ---------- column flip: A = max(val, flipC(val)) ----------
    init("padC", np.array([0, 0, 0, 0, 0, 0, 0, 2], np.int64), np.int64)  # pad axis3 end +2
    n("Pad", ["val", "padC", "zero"], "valC")      # [1,1,30,32] uint8
    n("Gather", ["valC", "gi"], "FC", axis=3)      # [1,1,30,30] val[i,31-j]
    A = umax("val", "FC", "A")

    # ---------- row flip: M = max(A, flipR(A)) ----------
    init("padR", np.array([0, 0, 0, 0, 0, 0, 2, 0], np.int64), np.int64)  # pad axis2 end +2
    n("Pad", [A, "padR", "zero"], "valR")          # [1,1,32,30] uint8
    n("Gather", ["valR", "gi"], "fRA", axis=2)     # [1,1,30,30] A[31-i,j]
    M = umax(A, "fRA", "M")

    # ---------- diagonal (transpose): P = max(M, M^T) ----------
    n("Transpose", [M], "MT", perm=[0, 1, 3, 2])   # [1,1,30,30]
    P = umax(M, "MT", "P")

    # ---------- one-hot into the FREE output ----------
    init("k10u", np.arange(10, dtype=np.uint8).reshape(1, 10, 1, 1), np.uint8)
    n("Equal", [P, "k10u"], "output")              # [1,10,30,30] BOOL

    x = helper.make_tensor_value_info("input", TensorProto.FLOAT, [1, 10, 30, 30])
    y = helper.make_tensor_value_info("output", TensorProto.BOOL, [1, 10, 30, 30])
    graph = helper.make_graph(nodes, "task074", [x], [y], inits)
    return helper.make_model(
        graph, ir_version=IR_VERSION,
        opset_imports=[helper.make_opsetid("", 11)])
