"""Task 190 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('bg_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('bg_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAoAAAAAAAAACgAAAAAAAAA=')),
        tensor('axes123', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAA=')),
        tensor('scale1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/')),
        tensor('scale4', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIBA')),
        tensor('zp0_u', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('wzp1_u', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('marker_w', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsIDEsIDYsIDYpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAgEBAQEBAAIBAQEBAgABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAgEBAQECAAEBAQEAAgEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAgABAQEBAAIBAQEBAgEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAgEBAQECAAEBAQEBAgE=')),
        tensor('nw_ray_w', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDYsIDYpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAE=')),
        tensor('ne_ray_w', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDYsIDYpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAEAAAAAAQAAAAABAAAAAAEAAAAAAQAAAAABAAAAAAA=')),
        tensor('pad_pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUAAAAAAAAABQAAAAAAAAA')),
        tensor('color_mask', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'bg_starts', 'bg_ends', 'axes123'], ['bg10_f']),
        helper.make_node('Cast', ['bg10_f'], ['bg10_u'], to=2),
        helper.make_node('QLinearConv', ['bg10_u', 'scale1', 'zp0_u', 'marker_w', 'scale1', 'wzp1_u', 'scale4', 'zp0_u'], ['marker_u']),
        helper.make_node('Split', ['marker_u'], ['nw5_u', 'ne5_u', 'sw5_u', 'se5_u'], axis=1),
        helper.make_node('QLinearConv', ['nw5_u', 'scale1', 'zp0_u', 'nw_ray_w', 'scale1', 'zp0_u', 'scale1', 'zp0_u'], ['nw_ray_u'], pads=[1, 1, 9, 9]),
        helper.make_node('QLinearConv', ['ne5_u', 'scale1', 'zp0_u', 'ne_ray_w', 'scale1', 'zp0_u', 'scale1', 'zp0_u'], ['ne_ray_u'], pads=[1, 9, 9, 1]),
        helper.make_node('QLinearConv', ['sw5_u', 'scale1', 'zp0_u', 'ne_ray_w', 'scale1', 'zp0_u', 'scale1', 'zp0_u'], ['sw_ray_u'], pads=[9, 1, 1, 9]),
        helper.make_node('QLinearConv', ['se5_u', 'scale1', 'zp0_u', 'nw_ray_w', 'scale1', 'zp0_u', 'scale1', 'zp0_u'], ['se_ray_u'], pads=[9, 9, 1, 1]),
        helper.make_node('Max', ['nw_ray_u', 'ne_ray_u'], ['ray_a_u']),
        helper.make_node('Max', ['sw_ray_u', 'se_ray_u'], ['ray_b_u']),
        helper.make_node('Max', ['ray_a_u', 'ray_b_u'], ['ray_u']),
        helper.make_node('Cast', ['ray_u'], ['ray10'], to=9),
        helper.make_node('Pad', ['ray10', 'pad_pads'], ['ray30'], mode='constant'),
        helper.make_node('MaxPool', ['input'], ['pooled_color'], kernel_shape=[30, 30]),
        helper.make_node('Mul', ['pooled_color', 'color_mask'], ['color10_f']),
        helper.make_node('Where', ['ray30', 'color10_f', 'input'], ['output']),
    ]
    value_infos = [
        helper.make_tensor_value_info('bg10_f', 1, [1, 1, 10, 10]),
        helper.make_tensor_value_info('bg10_u', 2, [1, 1, 10, 10]),
        helper.make_tensor_value_info('marker_u', 2, [1, 4, 5, 5]),
        helper.make_tensor_value_info('nw5_u', 2, [1, 1, 5, 5]),
        helper.make_tensor_value_info('ne5_u', 2, [1, 1, 5, 5]),
        helper.make_tensor_value_info('sw5_u', 2, [1, 1, 5, 5]),
        helper.make_tensor_value_info('se5_u', 2, [1, 1, 5, 5]),
        helper.make_tensor_value_info('nw_ray_u', 2, [1, 1, 10, 10]),
        helper.make_tensor_value_info('ne_ray_u', 2, [1, 1, 10, 10]),
        helper.make_tensor_value_info('sw_ray_u', 2, [1, 1, 10, 10]),
        helper.make_tensor_value_info('se_ray_u', 2, [1, 1, 10, 10]),
        helper.make_tensor_value_info('ray_a_u', 2, [1, 1, 10, 10]),
        helper.make_tensor_value_info('ray_b_u', 2, [1, 1, 10, 10]),
        helper.make_tensor_value_info('ray_u', 2, [1, 1, 10, 10]),
        helper.make_tensor_value_info('ray10', 9, [1, 1, 10, 10]),
        helper.make_tensor_value_info('ray30', 9, [1, 1, 30, 30]),
        helper.make_tensor_value_info('pooled_color', 1, [1, 10, 1, 1]),
        helper.make_tensor_value_info('color10_f', 1, [1, 10, 1, 1]),
    ]
    return model('task190_live_exact', nodes, inits, output_dtype=1, opset=13, value_infos=value_infos)
