"""Task 374 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('in_s', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==')),
        tensor('in_e', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAYAAAAAAAAACgAAAAAAAAAKAAAAAAAAAA==')),
        tensor('c0s', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAA==')),
        tensor('c9e', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoJAAAAAAAAAA==')),
        tensor('c1s', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
        tensor('c10e', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoKAAAAAAAAAA==')),
        tensor('ax3', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAA==')),
        tensor('ax2', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAA==')),
        tensor('onesW_row', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDEwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAQEBAQEBAQEB')),
        tensor('onesW_col', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEwLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAQEBAQEBAQEB')),
        tensor('zu8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('C1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('C2', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoC')),
        tensor('C4', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoE')),
        tensor('zi', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAA')),
        tensor('BIG', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIArnAwAA')),
        tensor('cids', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDUsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBA==')),
        tensor('padf', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQAAAAAAAAAUAAAAAAAAABQAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'in_s', 'in_e'], ['gray_f']),
        helper.make_node('Cast', ['gray_f'], ['occ'], to=9),
        helper.make_node('Slice', ['occ', 'c0s', 'c9e', 'ax3'], ['c08']),
        helper.make_node('Slice', ['occ', 'c1s', 'c10e', 'ax3'], ['c19']),
        helper.make_node('And', ['c08', 'c19'], ['hpair']),
        helper.make_node('Cast', ['hpair'], ['hpair_u8'], to=2),
        helper.make_node('MaxPool', ['hpair_u8'], ['horiz_u8'], kernel_shape=[1, 2], pads=[0, 1, 0, 1], strides=[1, 1]),
        helper.make_node('Cast', ['horiz_u8'], ['horizontal'], to=9),
        helper.make_node('ConvInteger', ['horiz_u8', 'onesW_row', 'zu8', 'zu8'], ['row_len']),
        helper.make_node('ConvInteger', ['horiz_u8', 'onesW_col', 'zu8', 'zu8'], ['horiz_col']),
        helper.make_node('ReduceSum', ['gray_f', 'ax2'], ['occ_col_f'], keepdims=1),
        helper.make_node('Cast', ['occ_col_f'], ['occ_col'], to=6),
        helper.make_node('Sub', ['occ_col', 'horiz_col'], ['col_len']),
        helper.make_node('ReduceMax', ['row_len', 'ax2'], ['row_mx'], keepdims=1),
        helper.make_node('ReduceMax', ['col_len', 'ax3'], ['col_mx'], keepdims=1),
        helper.make_node('Max', ['row_mx', 'col_mx'], ['gmax']),
        helper.make_node('Greater', ['row_len', 'zi'], ['row_pres']),
        helper.make_node('Greater', ['col_len', 'zi'], ['col_pres']),
        helper.make_node('Where', ['row_pres', 'row_len', 'BIG'], ['row_mr']),
        helper.make_node('Where', ['col_pres', 'col_len', 'BIG'], ['col_mr']),
        helper.make_node('ReduceMin', ['row_mr', 'ax2'], ['row_mn'], keepdims=1),
        helper.make_node('ReduceMin', ['col_mr', 'ax3'], ['col_mn'], keepdims=1),
        helper.make_node('Min', ['row_mn', 'col_mn'], ['gmin']),
        helper.make_node('Equal', ['row_len', 'gmax'], ['row_ismax']),
        helper.make_node('Equal', ['row_len', 'gmin'], ['row_ismin']),
        helper.make_node('Equal', ['col_len', 'gmax'], ['col_ismax']),
        helper.make_node('Equal', ['col_len', 'gmin'], ['col_ismin']),
        helper.make_node('Where', ['row_ismax', 'C1', 'C4'], ['row_l']),
        helper.make_node('Where', ['row_ismin', 'C2', 'row_l'], ['row_color']),
        helper.make_node('Where', ['col_ismax', 'C1', 'C4'], ['col_l']),
        helper.make_node('Where', ['col_ismin', 'C2', 'col_l'], ['col_color']),
        helper.make_node('Where', ['horizontal', 'row_color', 'col_color'], ['cell_color']),
        helper.make_node('Where', ['occ', 'cell_color', 'zu8'], ['color_grid']),
        helper.make_node('Equal', ['color_grid', 'cids'], ['out5']),
        helper.make_node('Pad', ['out5', 'padf'], ['output'], mode='constant'),
    ]
    value_infos = [
    ]
    return model('task374_live_exact', nodes, inits, output_dtype=9, opset=18, value_infos=value_infos)
