"""Task 156 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('starts_c4', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('ends_c4', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoFAAAAAAAAAAoAAAAAAAAACgAAAAAAAAA=')),
        tensor('axes_chw', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAA=')),
        tensor('idx3', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAA==')),
        tensor('idx4', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoEAAAAAAAAAA==')),
        tensor('idx5', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoFAAAAAAAAAA==')),
        tensor('idx6', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoGAAAAAAAAAA==')),
        tensor('pads_inner', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAA')),
        tensor('pads_output', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQAAAAAAAAAUAAAAAAAAABQAAAAAAAAA')),
        tensor('top_half', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGIxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEwLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAQEBAQAAAAAA')),
        tensor('almost_one', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAp3vn8/')),
        tensor('one_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('two_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoC')),
        tensor('label_values', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDUsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBA==')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'starts_c4', 'ends_c4', 'axes_chw'], ['c4_f']),
        helper.make_node('Cast', ['c4_f'], ['c4_u8'], to=2),
        helper.make_node('AveragePool', ['c4_f'], ['avg3'], kernel_shape=[3, 3], strides=[1, 1]),
        helper.make_node('Greater', ['avg3', 'almost_one'], ['interior_core']),
        helper.make_node('Einsum', ['c4_f'], ['row_sum'], equation='abcd->ac'),
        helper.make_node('Gather', ['row_sum', 'idx3'], ['row3'], axis=1),
        helper.make_node('Gather', ['row_sum', 'idx4'], ['row4'], axis=1),
        helper.make_node('Gather', ['row_sum', 'idx5'], ['row5'], axis=1),
        helper.make_node('Gather', ['row_sum', 'idx6'], ['row6'], axis=1),
        helper.make_node('Less', ['row3', 'almost_one'], ['sep3_top_small']),
        helper.make_node('Less', ['row4', 'almost_one'], ['sep4']),
        helper.make_node('Less', ['row5', 'almost_one'], ['sep5']),
        helper.make_node('LessOrEqual', ['row3', 'row5'], ['row3_le_row5']),
        helper.make_node('And', ['sep4', 'row3_le_row5'], ['sep4_top_small']),
        helper.make_node('Less', ['row4', 'row6'], ['row4_lt_row6']),
        helper.make_node('And', ['sep5', 'row4_lt_row6'], ['sep5_top_small']),
        helper.make_node('Or', ['sep3_top_small', 'sep4_top_small'], ['top_small_a']),
        helper.make_node('Or', ['top_small_a', 'sep5_top_small'], ['top_small']),
        helper.make_node('Pad', ['interior_core', 'pads_inner'], ['interior'], mode='constant'),
        helper.make_node('BitShift', ['c4_u8', 'two_u8'], ['yellow_label'], direction='LEFT'),
        helper.make_node('Where', ['top_small', 'one_u8', 'two_u8'], ['top_label']),
        helper.make_node('Where', ['top_small', 'two_u8', 'one_u8'], ['bottom_label']),
        helper.make_node('Where', ['top_half', 'top_label', 'bottom_label'], ['interior_label']),
        helper.make_node('Where', ['interior', 'interior_label', 'yellow_label'], ['label']),
        helper.make_node('Equal', ['label', 'label_values'], ['out5']),
        helper.make_node('Pad', ['out5', 'pads_output'], ['output'], mode='constant'),
    ]
    value_infos = [
    ]
    return model('task156_live_exact', nodes, inits, output_dtype=9, opset=13, value_infos=value_infos)
