"""Task 199 — exact source reconstruction of current live graph.

Generated by tools/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('ar', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDMwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBBAAAgQQAAMEEAAEBBAABQQQAAYEEAAHBBAACAQQAAiEEAAJBBAACYQQAAoEEAAKhBAACwQQAAuEEAAMBBAADIQQAA0EEAANhBAADgQQAA6EE=')),
        tensor('odd', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDMwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAAAAAIA/AAAAAAAAgD8AAAAAAACAPwAAAAAAAIA/AAAAAAAAgD8AAAAAAACAPwAAAAAAAIA/AAAAAAAAgD8AAAAAAACAPwAAAAAAAIA/AAAAAAAAgD8AAAAAAACAPwAAAAAAAIA/AAAAAAAAgD8=')),
        tensor('kar', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBB')),
        tensor('two', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAABA')),
        tensor('kp', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AAAAQA==')),
        tensor('e0', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAPAAAAAAAAAAAAAAAAAAAAAAAAA==')),
        tensor('e4', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAA8AAAAAAAAAAAAAA==')),
        tensor('D', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsIDEsIDMpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAPAC8ALwAAAA8AAAAAAC8ADw=')),
        tensor('sh11', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAEAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('ReduceL2', ['input'], ['H'], name='H', keepdims=0),
        helper.make_node('Einsum', ['input', 'kar'], ['K'], name='K', equation='nkij,ak->n'),
        helper.make_node('Einsum', ['input', 'kar', 'ar'], ['RK'], name='RK', equation='nkij,ak,xi->n'),
        helper.make_node('Einsum', ['input', 'kar', 'ar'], ['CK'], name='CK', equation='nkij,ak,xj->n'),
        helper.make_node('Div', ['RK', 'K'], ['R'], name='R'),
        helper.make_node('Div', ['CK', 'K'], ['C'], name='C'),
        helper.make_node('Mod', ['C', 'two'], ['Cm'], name='Cm', fmod=1),
        helper.make_node('Add', ['R', 'kp'], ['RR'], name='RR'),
        helper.make_node('Reshape', ['H', 'sh11'], ['Hr'], name='Hr'),
        helper.make_node('Concat', ['Hr', 'RR'], ['thrU'], name='thrU', axis=0),
        helper.make_node('Less', ['ar', 'thrU'], ['Ub'], name='Ub'),
        helper.make_node('Cast', ['Ub'], ['U'], name='U', to=10),
        helper.make_node('Less', ['ar', 'H'], ['ingrid'], name='ingrid'),
        helper.make_node('Equal', ['odd', 'Cm'], ['parity'], name='parity'),
        helper.make_node('And', ['parity', 'ingrid'], ['colpat'], name='colpat'),
        helper.make_node('Equal', ['ar', 'C'], ['cvec'], name='cvec'),
        helper.make_node('Concat', ['ingrid', 'colpat', 'cvec'], ['Vb'], name='Vb', axis=0),
        helper.make_node('Cast', ['Vb'], ['V'], name='V', to=10),
        helper.make_node('Equal', ['kar', 'K'], ['cv1'], name='cv1'),
        helper.make_node('Cast', ['cv1'], ['Kv'], name='Kv', to=10),
        helper.make_node('Concat', ['e0', 'e4', 'Kv'], ['B'], name='B', axis=0),
        helper.make_node('Einsum', ['B', 'D', 'U', 'V'], ['output'], name='output', equation='qk,qnm,mI,mJ->nkIJ'),
    ]
    value_infos = [
    ]
    return model('task199_live_exact', nodes, inits, output_dtype=10, opset=13, value_infos=value_infos)
