"""Task 354 — exact source reconstruction of current live graph.

Generated by tools/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('s_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAUAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAA==')),
        tensor('s_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAYAAAAAAAAACgAAAAAAAAAKAAAAAAAAAA==')),
        tensor('key_w', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAAAAAAMBAAADgQAAAAEEAABBB')),
        tensor('c_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAA==')),
        tensor('c_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoKAAAAAAAAAA==')),
        tensor('c_axes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAA==')),
        tensor('zero_row', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDEwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAA')),
        tensor('gmask', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDMsIDgpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoEBAQAAAAAAAAAAAQEAAAAAAAAAAAEBAQ=')),
        tensor('qzero', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('scales', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAqrqipA')),
        tensor('pads_hw', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAFAAAAAAAAAAUAAAAAAAAAA==')),
        tensor('axes_hw', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAMAAAAAAAAA')),
        tensor('padv', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoK')),
        tensor('ar', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJ')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 's_starts', 's_ends'], ['Sraw']),
        helper.make_node('Einsum', ['input', 'key_w'], ['Mfull_f'], equation='ncrs,qcxy->nqys'),
        helper.make_node('Cast', ['Mfull_f'], ['Mfull'], to=2),
        helper.make_node('Slice', ['Mfull', 'c_starts', 'c_ends', 'c_axes'], ['M']),
        helper.make_node('Cast', ['Sraw'], ['S8'], to=2),
        helper.make_node('QLinearMatMul', ['gmask', 'scales', 'qzero', 'S8', 'scales', 'qzero', 'scales', 'qzero'], ['Uraw']),
        helper.make_node('Min', ['M', 'Uraw'], ['x0']),
        helper.make_node('MaxPool', ['x0'], ['mp0'], kernel_shape=[1, 3], pads=[0, 1, 0, 1], strides=[1, 1]),
        helper.make_node('Min', ['mp0', 'Uraw'], ['x1']),
        helper.make_node('MaxPool', ['x1'], ['mp1'], kernel_shape=[1, 3], pads=[0, 1, 0, 1], strides=[1, 1]),
        helper.make_node('Min', ['mp1', 'Uraw'], ['x2']),
        helper.make_node('MaxPool', ['x2'], ['mp2'], kernel_shape=[1, 3], pads=[0, 1, 0, 1], strides=[1, 1]),
        helper.make_node('Min', ['mp2', 'Uraw'], ['x3']),
        helper.make_node('MaxPool', ['x3'], ['Fb'], kernel_shape=[1, 3], pads=[0, 1, 0, 1], strides=[1, 1]),
        helper.make_node('Resize', ['Fb', '', 'scales'], ['Fb8'], axes=[2], coordinate_transformation_mode='half_pixel', mode='nearest', nearest_mode='round_prefer_floor'),
        helper.make_node('Mul', ['S8', 'Fb8'], ['Gb']),
        helper.make_node('Concat', ['M', 'zero_row', 'Gb'], ['G'], axis=2),
        helper.make_node('Pad', ['G', 'pads_hw', 'padv', 'axes_hw'], ['Gp'], mode='constant'),
        helper.make_node('Equal', ['Gp', 'ar'], ['output']),
    ]
    value_infos = [
    ]
    return model('task354_live_exact', nodes, inits, output_dtype=9, opset=18, value_infos=value_infos)
