"""Task 303 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('black_selector', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA')),
        tensor('two_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoC')),
        tensor('zero_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('red_onehot', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAgD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'black_selector'], ['row_sum'], equation='nchw,ca->nha'),
        helper.make_node('Einsum', ['input', 'black_selector'], ['col_sum'], equation='nchw,ca->naw'),
        helper.make_node('Sign', ['row_sum'], ['row_active_f']),
        helper.make_node('Sign', ['col_sum'], ['col_active_f']),
        helper.make_node('ReduceSum', ['row_active_f'], ['height'], keepdims=0),
        helper.make_node('ReduceSum', ['col_active_f'], ['width'], keepdims=0),
        helper.make_node('Equal', ['row_sum', 'width'], ['marker_rows']),
        helper.make_node('Equal', ['col_sum', 'height'], ['marker_cols']),
        helper.make_node('Cast', ['row_active_f'], ['row_active_u8'], to=2),
        helper.make_node('Cast', ['col_active_f'], ['col_active_u8'], to=2),
        helper.make_node('Where', ['marker_rows', 'two_u8', 'row_active_u8'], ['row_code']),
        helper.make_node('Sub', ['two_u8', 'col_active_u8'], ['col_nonmarker_code']),
        helper.make_node('Where', ['marker_cols', 'zero_u8', 'col_nonmarker_code'], ['col_code']),
        helper.make_node('Greater', ['row_code', 'col_code'], ['red_mask']),
        helper.make_node('Where', ['red_mask', 'red_onehot', 'input'], ['output']),
    ]
    value_infos = [
    ]
    return model('task303_live_exact', nodes, inits, output_dtype=1, opset=14, value_infos=value_infos)
