"""Task 100 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('idx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBBAAAgQQAAMEEAAEBBAABQQQAAYEEAAHBBAACAQQAAiEEAAJBBAACYQQAAoEEAAKhBAACwQQAAuEEAAMBBAADIQQAA0EEAANhBAADgQQAA6EE=')),
        tensor('idx2', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAgEAAABBBAACAQQAAyEEAABBCAABEQgAAgEIAAKJCAADIQgAA8kIAABBDAAApQwAAREMAAGFDAACAQwCAkEMAAKJDAIC0QwAAyEMAgNxDAADyQwBABEQAABBEAEAcRAAAKUQAQDZEAABERABAUkQ=')),
        tensor('one', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAPA==')),
        tensor('inv48', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIApVJQ==')),
        tensor('score_start', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
        tensor('score_end', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoKAAAAAAAAAA==')),
        tensor('channel_ids', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAEAAAAAAAAAAgAAAAAAAAADAAAAAAAAAAQAAAAAAAAABQAAAAAAAAAGAAAAAAAAAAcAAAAAAAAACAAAAAAAAAAJAAAAAAAAAA==')),
        tensor('reduce_axes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAA=')),
        tensor('patch_shape', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAoAAAAAAAAAAgAAAAAAAAACAAAAAAAAAA==')),
        tensor('pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAAAAAAAABwAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('ReduceSum', ['input', 'reduce_axes'], ['count'], keepdims=0),
        helper.make_node('Einsum', ['input', 'idx'], ['row_sum'], equation='bchw,h->c'),
        helper.make_node('Einsum', ['input', 'idx2'], ['row2_sum'], equation='bchw,h->c'),
        helper.make_node('Cast', ['count'], ['count_h'], to=10),
        helper.make_node('Cast', ['row_sum'], ['row_sum_h'], to=10),
        helper.make_node('Cast', ['row2_sum'], ['row2_sum_h'], to=10),
        helper.make_node('Max', ['count_h', 'one'], ['safe_count']),
        helper.make_node('Mul', ['row_sum_h', 'row_sum_h'], ['row_sum_sq']),
        helper.make_node('Div', ['row_sum_sq', 'safe_count'], ['row_center_term']),
        helper.make_node('Sub', ['row2_sum_h', 'row_center_term'], ['row_moment']),
        helper.make_node('Mul', ['count_h', 'count_h'], ['count_sq']),
        helper.make_node('Mul', ['count_h', 'count_sq'], ['count_central_num']),
        helper.make_node('Mul', ['count_central_num', 'inv48'], ['central_sum']),
        helper.make_node('Sub', ['central_sum', 'row_moment'], ['other_moment']),
        helper.make_node('Mul', ['row_moment', 'other_moment'], ['area_key']),
        helper.make_node('Slice', ['area_key', 'score_start', 'score_end'], ['color_area_key']),
        helper.make_node('ArgMax', ['color_area_key'], ['winner_rel_i64'], axis=0, keepdims=1),
        helper.make_node('Add', ['winner_rel_i64', 'score_start'], ['winner_i64']),
        helper.make_node('Equal', ['channel_ids', 'winner_i64'], ['winner_bool']),
        helper.make_node('Unsqueeze', ['winner_bool', 'reduce_axes'], ['winner_4d']),
        helper.make_node('Expand', ['winner_4d', 'patch_shape'], ['patch']),
        helper.make_node('Pad', ['patch', 'pads'], ['output'], mode='constant'),
    ]
    value_infos = [
        helper.make_tensor_value_info('count', 1, [10]),
        helper.make_tensor_value_info('row_sum', 1, [10]),
        helper.make_tensor_value_info('row2_sum', 1, [10]),
        helper.make_tensor_value_info('count_h', 10, [10]),
        helper.make_tensor_value_info('row_sum_h', 10, [10]),
        helper.make_tensor_value_info('row2_sum_h', 10, [10]),
        helper.make_tensor_value_info('safe_count', 10, [10]),
        helper.make_tensor_value_info('row_sum_sq', 10, [10]),
        helper.make_tensor_value_info('row_center_term', 10, [10]),
        helper.make_tensor_value_info('row_moment', 10, [10]),
        helper.make_tensor_value_info('count_sq', 10, [10]),
        helper.make_tensor_value_info('count_central_num', 10, [10]),
        helper.make_tensor_value_info('central_sum', 10, [10]),
        helper.make_tensor_value_info('other_moment', 10, [10]),
        helper.make_tensor_value_info('area_key', 10, [10]),
        helper.make_tensor_value_info('color_area_key', 10, [9]),
        helper.make_tensor_value_info('winner_rel_i64', 7, [1]),
        helper.make_tensor_value_info('winner_i64', 7, [1]),
        helper.make_tensor_value_info('winner_bool', 9, [10]),
        helper.make_tensor_value_info('winner_4d', 9, [1, 10, 1, 1]),
        helper.make_tensor_value_info('patch', 9, [1, 10, 2, 2]),
    ]
    return model('task100_live_exact', nodes, inits, output_dtype=9, opset=13, value_infos=value_infos)
