"""Task 355 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('ax23', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAMAAAAAAAAA')),
        tensor('ax2', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAA==')),
        tensor('thr', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAGBB')),
        tensor('neg', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAQBzG')),
        tensor('arange10_i', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAEAAAAAAAAAAgAAAAAAAAADAAAAAAAAAAQAAAAAAAAABQAAAAAAAAAGAAAAAAAAAAcAAAAAAAAACAAAAAAAAAAJAAAAAAAAAA==')),
        tensor('unsq_ax', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAA=')),
        tensor('pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdAAAAAAAAAB0AAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('ReduceSum', ['input', 'ax23'], ['counts'], keepdims=0),
        helper.make_node('ReduceMax', ['input'], ['row_mx'], axes=[3], keepdims=0),
        helper.make_node('ReduceMax', ['input'], ['col_mx'], axes=[2], keepdims=0),
        helper.make_node('ReduceSum', ['row_mx', 'ax2'], ['row_cnt'], keepdims=0),
        helper.make_node('ReduceSum', ['col_mx', 'ax2'], ['col_cnt'], keepdims=0),
        helper.make_node('Mul', ['row_cnt', 'col_cnt'], ['bbox']),
        helper.make_node('Sub', ['bbox', 'counts'], ['missing']),
        helper.make_node('Greater', ['counts', 'thr'], ['valid_b']),
        helper.make_node('Where', ['valid_b', 'missing', 'neg'], ['score10']),
        helper.make_node('ArgMax', ['score10'], ['color_idx'], axis=1, keepdims=0),
        helper.make_node('Equal', ['arange10_i', 'color_idx'], ['sel_b']),
        helper.make_node('Unsqueeze', ['sel_b', 'unsq_ax'], ['sel_u8']),
        helper.make_node('Pad', ['sel_u8', 'pads'], ['output'], mode='constant'),
    ]
    value_infos = [
        helper.make_tensor_value_info('counts', 1, [1, 10]),
        helper.make_tensor_value_info('row_mx', 1, [1, 10, 30]),
        helper.make_tensor_value_info('col_mx', 1, [1, 10, 30]),
        helper.make_tensor_value_info('row_cnt', 1, [1, 10]),
        helper.make_tensor_value_info('col_cnt', 1, [1, 10]),
        helper.make_tensor_value_info('bbox', 1, [1, 10]),
        helper.make_tensor_value_info('missing', 1, [1, 10]),
        helper.make_tensor_value_info('valid_b', 9, [1, 10]),
        helper.make_tensor_value_info('score10', 1, [1, 10]),
        helper.make_tensor_value_info('color_idx', 7, [1]),
        helper.make_tensor_value_info('sel_b', 9, [10]),
    ]
    return model('task355_live_exact', nodes, inits, output_dtype=9, opset=17, value_infos=value_infos)
