"""Task 216 — exact source reconstruction of current live graph.

This builder owns the graph structure and constants in Python source and does
not load networks/task216.onnx at runtime.  The task is a documented
wall/complex heuristic, so this file preserves the verified live behavior as
source-controlled ONNX construction.
"""
from onnx import helper
from ._exact import arr_b64, model, tensor

def build(task):
    inits = [
        tensor('starts_c12', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('ends_c12', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAABQAAAAAAAAAFAAAAAAAAAA=')),
        tensor('axes_c12', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAA=')),
        tensor('twenty', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoUAAAA')),
        tensor('coords20p1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAgAAAAMAAAAEAAAABQAAAAYAAAAHAAAACAAAAAkAAAAKAAAACwAAAAwAAAANAAAADgAAAA8AAAAQAAAAEQAAABIAAAATAAAAFAAAAA==')),
        tensor('one_i', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAA')),
        tensor('thirty64', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoeAAAAAAAAAA==')),
        tensor('zero_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('one_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('q_scale', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/')),
        tensor('corner_w', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDIsIDIsIDIpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAACAQAAAg==')),
        tensor('scatter_zero', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDIpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAA==')),
        tensor('crop_start_prefix', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAA==')),
        tensor('crop_end_prefix', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAgAAAA==')),
        tensor('diag_idx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsIDMpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAwAAAAAAAAA=')),
        tensor('pad_output_prefix', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDYsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAAA=')),
        tensor('coords20p1_col', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIwLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAgAAAAMAAAAEAAAABQAAAAYAAAAHAAAACAAAAAkAAAAKAAAACwAAAAwAAAANAAAADgAAAA8AAAAQAAAAEQAAABIAAAATAAAAFAAAAA==')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'starts_c12', 'ends_c12', 'axes_c12'], ['c12_f32']),
        helper.make_node('Cast', ['c12_f32'], ['c12'], to=2),
        helper.make_node('QLinearConv', ['c12', 'q_scale', 'zero_u8', 'corner_w', 'q_scale', 'one_u8', 'q_scale', 'zero_u8'], ['tl'], kernel_shape=[2, 2], pads=[1, 1, 0, 0]),
        helper.make_node('Flatten', ['tl'], ['tl_flat'], axis=0),
        helper.make_node('ArgMax', ['tl_flat'], ['arg0_2d'], axis=1, keepdims=1),
        helper.make_node('ArgMax', ['tl_flat'], ['arg1_2d'], axis=1, keepdims=1, select_last_index=1),
        helper.make_node('Concat', ['arg0_2d', 'arg1_2d'], ['edge_idx_2d'], axis=1),
        helper.make_node('ScatterElements', ['tl_flat', 'edge_idx_2d', 'scatter_zero'], ['tl_flat_mid'], axis=1),
        helper.make_node('ArgMax', ['tl_flat_mid'], ['arg2_2d'], axis=1, keepdims=1),
        helper.make_node('ArgMax', ['tl_flat_mid'], ['arg3_2d'], axis=1, keepdims=1, select_last_index=1),
        helper.make_node('Cast', ['arg0_2d'], ['arg0_i'], to=6),
        helper.make_node('Cast', ['arg1_2d'], ['arg1_i'], to=6),
        helper.make_node('Cast', ['arg2_2d'], ['arg2_i'], to=6),
        helper.make_node('Cast', ['arg3_2d'], ['arg3_i'], to=6),
        helper.make_node('Concat', ['arg0_i', 'arg1_i', 'arg2_i', 'arg3_i'], ['top_idx_i_2d'], axis=1),
        helper.make_node('Squeeze', ['top_idx_i_2d'], ['top_idx_i'], axes=[0]),
        helper.make_node('Div', ['top_idx_i', 'twenty'], ['rows']),
        helper.make_node('Mod', ['top_idx_i', 'twenty'], ['cols'], fmod=0),
        helper.make_node('Gather', ['c12', 'rows'], ['row_cands'], axis=2),
        helper.make_node('ReduceMax', ['row_cands'], ['row_vecs'], axes=[0, 1], keepdims=0),
        helper.make_node('Equal', ['row_vecs', 'zero_u8'], ['row_zero']),
        helper.make_node('Unsqueeze', ['cols'], ['cols_col'], axes=[1]),
        helper.make_node('Less', ['cols_col', 'coords20p1'], ['after_col']),
        helper.make_node('And', ['after_col', 'row_zero'], ['row_zero_after']),
        helper.make_node('Cast', ['row_zero_after'], ['row_zero_after_u8'], to=2),
        helper.make_node('ArgMax', ['row_zero_after_u8'], ['width_end_raw'], axis=1, keepdims=0),
        helper.make_node('Cast', ['width_end_raw'], ['width_end_raw_i'], to=6),
        helper.make_node('ReduceMax', ['row_zero_after_u8'], ['width_has_zero_u8'], axes=[1], keepdims=0),
        helper.make_node('Cast', ['width_has_zero_u8'], ['width_has_zero'], to=9),
        helper.make_node('Where', ['width_has_zero', 'width_end_raw_i', 'twenty'], ['width_end_i']),
        helper.make_node('Sub', ['width_end_i', 'cols'], ['widths']),
        helper.make_node('Gather', ['c12', 'cols'], ['col_cands'], axis=3),
        helper.make_node('ReduceMax', ['col_cands'], ['col_vecs'], axes=[0, 1], keepdims=0),
        helper.make_node('Equal', ['col_vecs', 'zero_u8'], ['col_zero']),
        helper.make_node('Unsqueeze', ['rows'], ['rows_row'], axes=[0]),
        helper.make_node('Less', ['rows_row', 'coords20p1_col'], ['after_row']),
        helper.make_node('And', ['after_row', 'col_zero'], ['col_zero_after']),
        helper.make_node('Cast', ['col_zero_after'], ['col_zero_after_u8'], to=2),
        helper.make_node('ArgMax', ['col_zero_after_u8'], ['height_end_raw'], axis=0, keepdims=0),
        helper.make_node('Cast', ['height_end_raw'], ['height_end_raw_i'], to=6),
        helper.make_node('ReduceMax', ['col_zero_after_u8'], ['height_has_zero_u8'], axes=[0], keepdims=0),
        helper.make_node('Cast', ['height_has_zero_u8'], ['height_has_zero'], to=9),
        helper.make_node('Where', ['height_has_zero', 'height_end_raw_i', 'twenty'], ['height_end_i']),
        helper.make_node('Sub', ['height_end_i', 'rows'], ['heights']),
        helper.make_node('Gather', ['c12', 'one_i'], ['red_3d'], axis=1),
        helper.make_node('Unsqueeze', ['width_end_i'], ['col_end_col'], axes=[1]),
        helper.make_node('LessOrEqual', ['coords20p1', 'col_end_col'], ['col_lt_end']),
        helper.make_node('And', ['after_col', 'col_lt_end'], ['col_in']),
        helper.make_node('Unsqueeze', ['height_end_i'], ['row_end_row'], axes=[0]),
        helper.make_node('LessOrEqual', ['coords20p1_col', 'row_end_row'], ['row_lt']),
        helper.make_node('And', ['after_row', 'row_lt'], ['row_in']),
        helper.make_node('Cast', ['row_in'], ['row_mask_u8'], to=2),
        helper.make_node('Transpose', ['row_mask_u8'], ['row_mask_t_u8'], perm=[1, 0]),
        helper.make_node('Cast', ['col_in'], ['col_mask_u8'], to=2),
        helper.make_node('Transpose', ['col_mask_u8'], ['col_mask_t_u8'], perm=[1, 0]),
        helper.make_node('MatMulInteger', ['row_mask_t_u8', 'red_3d'], ['row_red_i']),
        helper.make_node('Cast', ['row_red_i'], ['row_red_u8'], to=2),
        helper.make_node('MatMulInteger', ['row_red_u8', 'col_mask_t_u8'], ['count_matrix']),
        helper.make_node('GatherND', ['count_matrix', 'diag_idx'], ['counts']),
        helper.make_node('ArgMax', ['counts'], ['winner_idx'], axis=0, keepdims=0),
        helper.make_node('Gather', ['rows', 'winner_idx'], ['winner_row'], axis=0),
        helper.make_node('Gather', ['cols', 'winner_idx'], ['winner_col'], axis=0),
        helper.make_node('Gather', ['heights', 'winner_idx'], ['winner_height'], axis=0),
        helper.make_node('Gather', ['widths', 'winner_idx'], ['winner_width'], axis=0),
        helper.make_node('Add', ['winner_row', 'winner_height'], ['crop_row_end']),
        helper.make_node('Add', ['winner_col', 'winner_width'], ['crop_col_end']),
        helper.make_node('Unsqueeze', ['winner_row'], ['winner_row_v'], axes=[0]),
        helper.make_node('Unsqueeze', ['winner_col'], ['winner_col_v'], axes=[0]),
        helper.make_node('Unsqueeze', ['crop_row_end'], ['crop_row_end_v'], axes=[0]),
        helper.make_node('Unsqueeze', ['crop_col_end'], ['crop_col_end_v'], axes=[0]),
        helper.make_node('Concat', ['crop_start_prefix', 'winner_row_v', 'winner_col_v'], ['crop_starts'], axis=0),
        helper.make_node('Concat', ['crop_end_prefix', 'crop_row_end_v', 'crop_col_end_v'], ['crop_ends'], axis=0),
        helper.make_node('Slice', ['c12', 'crop_starts', 'crop_ends'], ['crop']),
        helper.make_node('Cast', ['winner_height'], ['winner_height64'], to=7),
        helper.make_node('Cast', ['winner_width'], ['winner_width64'], to=7),
        helper.make_node('Unsqueeze', ['winner_height64'], ['winner_height64_v'], axes=[0]),
        helper.make_node('Unsqueeze', ['winner_width64'], ['winner_width64_v'], axes=[0]),
        helper.make_node('Sub', ['thirty64', 'winner_height64_v'], ['pad_h_tail']),
        helper.make_node('Sub', ['thirty64', 'winner_width64_v'], ['pad_w_tail']),
        helper.make_node('Concat', ['pad_output_prefix', 'pad_h_tail', 'pad_w_tail'], ['dynamic_pad_output'], axis=0),
        helper.make_node('Pad', ['crop', 'dynamic_pad_output'], ['output'], mode='constant'),
    ]
    value_infos = [
        helper.make_tensor_value_info('c12_f32', 1, [1, 2, 20, 20]),
        helper.make_tensor_value_info('c12', 2, [1, 2, 20, 20]),
        helper.make_tensor_value_info('tl', 2, [1, 1, 20, 20]),
        helper.make_tensor_value_info('tl_flat', 2, [1, 400]),
        helper.make_tensor_value_info('arg0_2d', 7, [1, 1]),
        helper.make_tensor_value_info('arg1_2d', 7, [1, 1]),
        helper.make_tensor_value_info('edge_idx_2d', 7, [1, 2]),
        helper.make_tensor_value_info('tl_flat_mid', 2, [1, 400]),
        helper.make_tensor_value_info('arg2_2d', 7, [1, 1]),
        helper.make_tensor_value_info('arg3_2d', 7, [1, 1]),
        helper.make_tensor_value_info('arg0_i', 6, [1, 1]),
        helper.make_tensor_value_info('arg1_i', 6, [1, 1]),
        helper.make_tensor_value_info('arg2_i', 6, [1, 1]),
        helper.make_tensor_value_info('arg3_i', 6, [1, 1]),
        helper.make_tensor_value_info('top_idx_i_2d', 6, [1, 4]),
        helper.make_tensor_value_info('top_idx_i', 6, [4]),
        helper.make_tensor_value_info('rows', 6, [4]),
        helper.make_tensor_value_info('cols', 6, [4]),
        helper.make_tensor_value_info('row_cands', 2, [1, 2, 4, 20]),
        helper.make_tensor_value_info('row_vecs', 2, [4, 20]),
        helper.make_tensor_value_info('row_zero', 9, [4, 20]),
        helper.make_tensor_value_info('cols_col', 6, [4, 1]),
        helper.make_tensor_value_info('after_col', 9, [4, 20]),
        helper.make_tensor_value_info('row_zero_after', 9, [4, 20]),
        helper.make_tensor_value_info('row_zero_after_u8', 2, [4, 20]),
        helper.make_tensor_value_info('width_end_raw', 7, [4]),
        helper.make_tensor_value_info('width_end_raw_i', 6, [4]),
        helper.make_tensor_value_info('width_has_zero_u8', 2, [4]),
        helper.make_tensor_value_info('width_has_zero', 9, [4]),
        helper.make_tensor_value_info('width_end_i', 6, [4]),
        helper.make_tensor_value_info('widths', 6, [4]),
        helper.make_tensor_value_info('col_cands', 2, [1, 2, 20, 4]),
        helper.make_tensor_value_info('col_vecs', 2, [20, 4]),
        helper.make_tensor_value_info('col_zero', 9, [20, 4]),
        helper.make_tensor_value_info('rows_row', 6, [1, 4]),
        helper.make_tensor_value_info('after_row', 9, [20, 4]),
        helper.make_tensor_value_info('col_zero_after', 9, [20, 4]),
        helper.make_tensor_value_info('col_zero_after_u8', 2, [20, 4]),
        helper.make_tensor_value_info('height_end_raw', 7, [4]),
        helper.make_tensor_value_info('height_end_raw_i', 6, [4]),
        helper.make_tensor_value_info('height_has_zero_u8', 2, [4]),
        helper.make_tensor_value_info('height_has_zero', 9, [4]),
        helper.make_tensor_value_info('height_end_i', 6, [4]),
        helper.make_tensor_value_info('heights', 6, [4]),
        helper.make_tensor_value_info('red_3d', 2, [1, 20, 20]),
        helper.make_tensor_value_info('col_end_col', 6, [4, 1]),
        helper.make_tensor_value_info('col_lt_end', 9, [4, 20]),
        helper.make_tensor_value_info('col_in', 9, [4, 20]),
        helper.make_tensor_value_info('row_end_row', 6, [1, 4]),
        helper.make_tensor_value_info('row_lt', 9, [20, 4]),
        helper.make_tensor_value_info('row_in', 9, [20, 4]),
        helper.make_tensor_value_info('row_mask_u8', 2, [20, 4]),
        helper.make_tensor_value_info('row_mask_t_u8', 2, [4, 20]),
        helper.make_tensor_value_info('col_mask_u8', 2, [4, 20]),
        helper.make_tensor_value_info('col_mask_t_u8', 2, [20, 4]),
        helper.make_tensor_value_info('row_red_i', 6, [1, 4, 20]),
        helper.make_tensor_value_info('row_red_u8', 2, [1, 4, 20]),
        helper.make_tensor_value_info('count_matrix', 6, [1, 4, 4]),
        helper.make_tensor_value_info('counts', 6, [4]),
        helper.make_tensor_value_info('winner_idx', 7, []),
        helper.make_tensor_value_info('winner_row', 6, []),
        helper.make_tensor_value_info('winner_col', 6, []),
        helper.make_tensor_value_info('winner_height', 6, []),
        helper.make_tensor_value_info('winner_width', 6, []),
        helper.make_tensor_value_info('crop_row_end', 6, []),
        helper.make_tensor_value_info('crop_col_end', 6, []),
        helper.make_tensor_value_info('winner_row_v', 6, [1]),
        helper.make_tensor_value_info('winner_col_v', 6, [1]),
        helper.make_tensor_value_info('crop_row_end_v', 6, [1]),
        helper.make_tensor_value_info('crop_col_end_v', 6, [1]),
        helper.make_tensor_value_info('crop_starts', 6, [4]),
        helper.make_tensor_value_info('crop_ends', 6, [4]),
        helper.make_tensor_value_info('crop', 2, [1, 2, 18, 18]),
        helper.make_tensor_value_info('winner_height64', 7, []),
        helper.make_tensor_value_info('winner_width64', 7, []),
        helper.make_tensor_value_info('winner_height64_v', 7, [1]),
        helper.make_tensor_value_info('winner_width64_v', 7, [1]),
        helper.make_tensor_value_info('pad_h_tail', 7, [1]),
        helper.make_tensor_value_info('pad_w_tail', 7, [1]),
        helper.make_tensor_value_info('dynamic_pad_output', 7, [8]),
    ]
    return model('task216', nodes, inits, output_dtype=2, opset=12, value_infos=value_infos)
