"""Task 219 — exact source reconstruction of current live graph.

This builder owns the graph structure and constants in Python source and does
not load networks/task219.onnx at runtime.  The task is a documented
wall/complex heuristic, so this file preserves the verified live behavior as
source-controlled ONNX construction.
"""
from onnx import helper
from ._exact import arr_b64, model, tensor

def build(task):
    inits = [
        tensor('k_1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoIAAAAAAAAAA==')),
        tensor('k_3', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==')),
        tensor('k_4', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAEAAAAAAAAADwAAAAAAAAAKAAAAAAAAAA==')),
        tensor('k_6', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoPAAAAAAAAAAoAAAAAAAAA')),
        tensor('k_8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAA==')),
        tensor('k_11', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
        tensor('k_13', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAA==')),
        tensor('k_14', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoPAAAAAAAAAA==')),
        tensor('k_16', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAA==')),
        tensor('k_18', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoOAAAAAAAAAA==')),
        tensor('k_21', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAPA==')),
        tensor('k_24', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAA==')),
        tensor('k_31', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAEAAAAAAAAAAgAAAAAAAAA=')),
        tensor('k_39', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAA==')),
        tensor('k_56', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAA=')),
        tensor('k_57', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsIDIpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAA=')),
        tensor('k_64', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoJAAAAAAAAAA==')),
        tensor('k_69', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoKAAAAAAAAAA==')),
        tensor('k_122', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAA==')),
        tensor('k_126', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAA==')),
        tensor('k_140', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAAAAAAAAAAAADwAAAAAAAAAAAAAAAAAAAA==')),
        tensor('k_142', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDE1LCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAEAAAAAAAAAAgAAAAAAAAADAAAAAAAAAAQAAAAAAAAABQAAAAAAAAAGAAAAAAAAAAcAAAAAAAAACAAAAAAAAAAJAAAAAAAAAAoAAAAAAAAACwAAAAAAAAAMAAAAAAAAAA0AAAAAAAAADgAAAAAAAAA=')),
        tensor('k_143', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAA==')),
        tensor('k_308', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoEAAAAAAAAAA==')),
        tensor('k_384', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoFAAAAAAAAAA==')),
        tensor('k_460', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoGAAAAAAAAAA==')),
        tensor('k_545', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAEAAAAAAAAA')),
        tensor('c_eight_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoI')),
        tensor('arange_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJ')),
        tensor('pad_out', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAAAAAAABQAAAAAAAAA')),
        tensor('false_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGIxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
    ]
    nodes = [
        helper.make_node('Gather', ['input', 'k_1'], ['gat_2'], axis=1),
        helper.make_node('Slice', ['gat_2', 'k_3', 'k_4'], ['gat_2_c']),
        helper.make_node('Cast', ['gat_2_c'], ['gat_2__h16'], to=10),
        helper.make_node('Reshape', ['gat_2__h16', 'k_6'], ['res_7']),
        helper.make_node('Pad', ['res_7', 'k_8'], ['pad_9'], mode='constant'),
        helper.make_node('ReduceMax', ['pad_9'], ['red_10'], axes=[1], keepdims=1),
        helper.make_node('Squeeze', ['red_10', 'k_11'], ['squ_12']),
        helper.make_node('Slice', ['squ_12', 'k_13', 'k_14'], ['sli_15']),
        helper.make_node('Slice', ['sli_15', 'k_13', 'k_18'], ['sli_19']),
        helper.make_node('Concat', ['k_16', 'sli_19'], ['con_20'], axis=0),
        helper.make_node('Sub', ['k_21', 'con_20'], ['sub_22']),
        helper.make_node('Mul', ['sli_15', 'sub_22'], ['mul_23']),
        helper.make_node('CumSum', ['mul_23', 'k_24'], ['cum_25']),
        helper.make_node('Cast', ['cum_25'], ['cas_26'], to=7),
        helper.make_node('ArgMax', ['mul_23'], ['arg_28'], axis=0, keepdims=0),
        helper.make_node('Unsqueeze', ['arg_28', 'k_13'], ['uns_30']),
        helper.make_node('Add', ['uns_30', 'k_31'], ['add_32']),
        helper.make_node('Gather', ['pad_9', 'add_32'], ['gat_33'], axis=0),
        helper.make_node('Gather', ['squ_12', 'add_32'], ['gat_36'], axis=0),
        helper.make_node('Gather', ['gat_36', 'k_11'], ['gat_41']),
        helper.make_node('Gather', ['gat_36', 'k_39'], ['gat_42']),
        helper.make_node('Min', ['gat_41', 'gat_42'], ['min_44']),
        helper.make_node('Concat', ['k_21', 'gat_41', 'min_44'], ['con_45'], axis=0),
        helper.make_node('Unsqueeze', ['con_45', 'k_11'], ['uns_47']),
        helper.make_node('Mul', ['gat_33', 'uns_47'], ['mul_48']),
        helper.make_node('ReduceMax', ['mul_48'], ['red_49'], axes=[0], keepdims=0),
        helper.make_node('ArgMax', ['red_49'], ['arg_50'], axis=0, keepdims=0),
        helper.make_node('Unsqueeze', ['arg_50', 'k_13'], ['uns_51']),
        helper.make_node('Gather', ['mul_48', 'uns_51'], ['gat_52'], axis=1),
        helper.make_node('Squeeze', ['gat_52', 'k_11'], ['squ_54']),
        helper.make_node('ArgMax', ['squ_54'], ['arg_55'], axis=0, keepdims=0),
        helper.make_node('Slice', ['mul_48', 'k_13', 'k_1', 'k_11'], ['sli_61']),
        helper.make_node('Concat', ['k_57', 'sli_61'], ['con_62'], axis=1),
        helper.make_node('Slice', ['mul_48', 'k_13', 'k_64', 'k_11'], ['sli_66']),
        helper.make_node('Concat', ['k_56', 'sli_66'], ['con_67'], axis=1),
        helper.make_node('Slice', ['mul_48', 'k_11', 'k_69', 'k_11'], ['sli_71']),
        helper.make_node('Concat', ['sli_71', 'k_56'], ['con_72'], axis=1),
        helper.make_node('Unsqueeze', ['con_62', 'k_13'], ['uns_74']),
        helper.make_node('Unsqueeze', ['con_67', 'k_13'], ['uns_75']),
        helper.make_node('Unsqueeze', ['mul_48', 'k_13'], ['uns_76']),
        helper.make_node('Unsqueeze', ['con_72', 'k_13'], ['uns_77']),
        helper.make_node('Concat', ['uns_74', 'uns_75', 'uns_76', 'uns_77'], ['con_78'], axis=0),
        helper.make_node('Pad', ['mul_48', 'k_140'], ['pad_141'], mode='constant'),
        helper.make_node('Sub', ['k_143', 'uns_30'], ['sub_144']),
        helper.make_node('Add', ['sub_144', 'k_142'], ['add_145']),
        helper.make_node('Gather', ['pad_141', 'add_145'], ['gat_151'], axis=0),
        helper.make_node('Equal', ['cas_26', 'k_122'], ['equ_157']),
        helper.make_node('Cast', ['equ_157'], ['cas_158'], to=10),
        helper.make_node('Mul', ['cas_158', 'mul_23'], ['mul_159']),
        helper.make_node('ArgMax', ['mul_159'], ['arg_161'], axis=0, keepdims=0),
        helper.make_node('Unsqueeze', ['arg_161', 'k_13'], ['uns_162']),
        helper.make_node('Add', ['uns_162', 'k_31'], ['add_163']),
        helper.make_node('Gather', ['pad_9', 'add_163'], ['gat_164'], axis=0),
        helper.make_node('Gather', ['squ_12', 'add_163'], ['gat_165'], axis=0),
        helper.make_node('Gather', ['gat_165', 'k_39'], ['gat_168']),
        helper.make_node('Min', ['gat_41', 'gat_168'], ['min_170']),
        helper.make_node('Concat', ['k_21', 'gat_41', 'min_170'], ['con_171'], axis=0),
        helper.make_node('Unsqueeze', ['con_171', 'k_11'], ['uns_173']),
        helper.make_node('Mul', ['gat_164', 'uns_173'], ['mul_174']),
        helper.make_node('Gather', ['mul_174', 'uns_51'], ['gat_178'], axis=1),
        helper.make_node('Squeeze', ['gat_178', 'k_11'], ['squ_179']),
        helper.make_node('ArgMax', ['squ_179'], ['arg_180'], axis=0, keepdims=0),
        helper.make_node('Sub', ['arg_180', 'arg_55'], ['sub_181']),
        helper.make_node('Add', ['arg_161', 'sub_181'], ['add_182']),
        helper.make_node('Unsqueeze', ['add_182', 'k_13'], ['uns_183']),
        helper.make_node('Add', ['uns_183', 'k_31'], ['add_188']),
        helper.make_node('Gather', ['pad_9', 'add_188'], ['gat_189'], axis=0),
        helper.make_node('Mul', ['con_62', 'gat_189'], ['mul_192']),
        helper.make_node('ReduceSum', ['mul_192'], ['red_193'], keepdims=0),
        helper.make_node('Mul', ['con_67', 'gat_189'], ['mul_196']),
        helper.make_node('ReduceSum', ['mul_196'], ['red_197'], keepdims=0),
        helper.make_node('Mul', ['mul_48', 'gat_189'], ['mul_200']),
        helper.make_node('ReduceSum', ['mul_200'], ['red_201'], keepdims=0),
        helper.make_node('Mul', ['con_72', 'gat_189'], ['mul_204']),
        helper.make_node('ReduceSum', ['mul_204'], ['red_205'], keepdims=0),
        helper.make_node('Unsqueeze', ['red_193', 'k_13'], ['uns_206']),
        helper.make_node('Unsqueeze', ['red_197', 'k_13'], ['uns_207']),
        helper.make_node('Unsqueeze', ['red_201', 'k_13'], ['uns_208']),
        helper.make_node('Unsqueeze', ['red_205', 'k_13'], ['uns_209']),
        helper.make_node('Concat', ['uns_206', 'uns_207', 'uns_208', 'uns_209'], ['con_210'], axis=0),
        helper.make_node('ArgMax', ['con_210'], ['arg_211'], axis=0, keepdims=0),
        helper.make_node('Unsqueeze', ['arg_211', 'k_13'], ['uns_212']),
        helper.make_node('Gather', ['con_78', 'uns_212'], ['gat_213'], axis=0),
        helper.make_node('Squeeze', ['gat_213', 'k_13'], ['squ_215']),
        helper.make_node('Pad', ['squ_215', 'k_140'], ['pad_217'], mode='constant'),
        helper.make_node('Sub', ['k_143', 'uns_183'], ['sub_220']),
        helper.make_node('Add', ['sub_220', 'k_142'], ['add_221']),
        helper.make_node('Max', ['add_221', 'k_13'], ['max_224']),
        helper.make_node('Gather', ['pad_217', 'max_224'], ['gat_227'], axis=0),
        helper.make_node('Max', ['gat_151', 'gat_227'], ['max_231']),
        helper.make_node('Equal', ['cas_26', 'k_126'], ['equ_233']),
        helper.make_node('Cast', ['equ_233'], ['cas_234'], to=10),
        helper.make_node('Mul', ['cas_234', 'mul_23'], ['mul_235']),
        helper.make_node('ReduceMax', ['mul_235'], ['red_236'], axes=[0], keepdims=1),
        helper.make_node('ArgMax', ['mul_235'], ['arg_237'], axis=0, keepdims=0),
        helper.make_node('Unsqueeze', ['arg_237', 'k_13'], ['uns_238']),
        helper.make_node('Add', ['uns_238', 'k_31'], ['add_239']),
        helper.make_node('Gather', ['pad_9', 'add_239'], ['gat_240'], axis=0),
        helper.make_node('Gather', ['squ_12', 'add_239'], ['gat_241'], axis=0),
        helper.make_node('Gather', ['gat_241', 'k_11'], ['gat_243']),
        helper.make_node('Gather', ['gat_241', 'k_39'], ['gat_244']),
        helper.make_node('Min', ['red_236', 'gat_243'], ['min_245']),
        helper.make_node('Min', ['min_245', 'gat_244'], ['min_246']),
        helper.make_node('Concat', ['red_236', 'min_245', 'min_246'], ['con_247'], axis=0),
        helper.make_node('Unsqueeze', ['con_247', 'k_11'], ['uns_249']),
        helper.make_node('Mul', ['gat_240', 'uns_249'], ['mul_250']),
        helper.make_node('ReduceMax', ['mul_250'], ['red_251'], axes=[0], keepdims=0),
        helper.make_node('ArgMax', ['red_251'], ['arg_252'], axis=0, keepdims=0),
        helper.make_node('Unsqueeze', ['arg_252', 'k_13'], ['uns_253']),
        helper.make_node('Gather', ['mul_250', 'uns_253'], ['gat_254'], axis=1),
        helper.make_node('Squeeze', ['gat_254', 'k_11'], ['squ_255']),
        helper.make_node('ArgMax', ['squ_255'], ['arg_256'], axis=0, keepdims=0),
        helper.make_node('Sub', ['arg_256', 'arg_55'], ['sub_257']),
        helper.make_node('Add', ['arg_237', 'sub_257'], ['add_258']),
        helper.make_node('Unsqueeze', ['add_258', 'k_13'], ['uns_259']),
        helper.make_node('Max', ['uns_259', 'k_13'], ['max_262']),
        helper.make_node('Add', ['max_262', 'k_31'], ['add_264']),
        helper.make_node('Gather', ['pad_9', 'add_264'], ['gat_265'], axis=0),
        helper.make_node('Mul', ['con_62', 'gat_265'], ['mul_268']),
        helper.make_node('ReduceSum', ['mul_268'], ['red_269'], keepdims=0),
        helper.make_node('Mul', ['con_67', 'gat_265'], ['mul_272']),
        helper.make_node('ReduceSum', ['mul_272'], ['red_273'], keepdims=0),
        helper.make_node('Mul', ['mul_48', 'gat_265'], ['mul_276']),
        helper.make_node('ReduceSum', ['mul_276'], ['red_277'], keepdims=0),
        helper.make_node('Mul', ['con_72', 'gat_265'], ['mul_280']),
        helper.make_node('ReduceSum', ['mul_280'], ['red_281'], keepdims=0),
        helper.make_node('Unsqueeze', ['red_269', 'k_13'], ['uns_282']),
        helper.make_node('Unsqueeze', ['red_273', 'k_13'], ['uns_283']),
        helper.make_node('Unsqueeze', ['red_277', 'k_13'], ['uns_284']),
        helper.make_node('Unsqueeze', ['red_281', 'k_13'], ['uns_285']),
        helper.make_node('Concat', ['uns_282', 'uns_283', 'uns_284', 'uns_285'], ['con_286'], axis=0),
        helper.make_node('ArgMax', ['con_286'], ['arg_287'], axis=0, keepdims=0),
        helper.make_node('Unsqueeze', ['arg_287', 'k_13'], ['uns_288']),
        helper.make_node('Gather', ['con_78', 'uns_288'], ['gat_289'], axis=0),
        helper.make_node('Squeeze', ['gat_289', 'k_13'], ['squ_291']),
        helper.make_node('Pad', ['squ_291', 'k_140'], ['pad_293'], mode='constant'),
        helper.make_node('Sub', ['k_143', 'max_262'], ['sub_296']),
        helper.make_node('Add', ['sub_296', 'k_142'], ['add_297']),
        helper.make_node('Max', ['add_297', 'k_13'], ['max_300']),
        helper.make_node('Gather', ['pad_293', 'max_300'], ['gat_303'], axis=0),
        helper.make_node('Unsqueeze', ['red_236', 'k_13'], ['uns_305']),
        helper.make_node('Mul', ['gat_303', 'uns_305'], ['mul_306']),
        helper.make_node('Max', ['max_231', 'mul_306'], ['max_307']),
        helper.make_node('Equal', ['cas_26', 'k_308'], ['equ_309']),
        helper.make_node('Cast', ['equ_309'], ['cas_310'], to=10),
        helper.make_node('Mul', ['cas_310', 'mul_23'], ['mul_311']),
        helper.make_node('ReduceMax', ['mul_311'], ['red_312'], axes=[0], keepdims=1),
        helper.make_node('ArgMax', ['mul_311'], ['arg_313'], axis=0, keepdims=0),
        helper.make_node('Unsqueeze', ['arg_313', 'k_13'], ['uns_314']),
        helper.make_node('Add', ['uns_314', 'k_31'], ['add_315']),
        helper.make_node('Gather', ['pad_9', 'add_315'], ['gat_316'], axis=0),
        helper.make_node('Mul', ['con_62', 'gat_316'], ['mul_344']),
        helper.make_node('ReduceSum', ['mul_344'], ['red_345'], keepdims=0),
        helper.make_node('Mul', ['con_67', 'gat_316'], ['mul_348']),
        helper.make_node('ReduceSum', ['mul_348'], ['red_349'], keepdims=0),
        helper.make_node('Mul', ['mul_48', 'gat_316'], ['mul_352']),
        helper.make_node('ReduceSum', ['mul_352'], ['red_353'], keepdims=0),
        helper.make_node('Mul', ['con_72', 'gat_316'], ['mul_356']),
        helper.make_node('ReduceSum', ['mul_356'], ['red_357'], keepdims=0),
        helper.make_node('Unsqueeze', ['red_345', 'k_13'], ['uns_358']),
        helper.make_node('Unsqueeze', ['red_349', 'k_13'], ['uns_359']),
        helper.make_node('Unsqueeze', ['red_353', 'k_13'], ['uns_360']),
        helper.make_node('Unsqueeze', ['red_357', 'k_13'], ['uns_361']),
        helper.make_node('Concat', ['uns_358', 'uns_359', 'uns_360', 'uns_361'], ['con_362'], axis=0),
        helper.make_node('ArgMax', ['con_362'], ['arg_363'], axis=0, keepdims=0),
        helper.make_node('Unsqueeze', ['arg_363', 'k_13'], ['uns_364']),
        helper.make_node('Gather', ['con_78', 'uns_364'], ['gat_365'], axis=0),
        helper.make_node('Squeeze', ['gat_365', 'k_13'], ['squ_367']),
        helper.make_node('Pad', ['squ_367', 'k_140'], ['pad_369'], mode='constant'),
        helper.make_node('Sub', ['k_143', 'uns_314'], ['sub_372']),
        helper.make_node('Add', ['sub_372', 'k_142'], ['add_373']),
        helper.make_node('Max', ['add_373', 'k_13'], ['max_376']),
        helper.make_node('Gather', ['pad_369', 'max_376'], ['gat_379'], axis=0),
        helper.make_node('Unsqueeze', ['red_312', 'k_13'], ['uns_381']),
        helper.make_node('Mul', ['gat_379', 'uns_381'], ['mul_382']),
        helper.make_node('Max', ['max_307', 'mul_382'], ['max_383']),
        helper.make_node('Equal', ['cas_26', 'k_384'], ['equ_385']),
        helper.make_node('Cast', ['equ_385'], ['cas_386'], to=10),
        helper.make_node('Mul', ['cas_386', 'mul_23'], ['mul_387']),
        helper.make_node('ReduceMax', ['mul_387'], ['red_388'], axes=[0], keepdims=1),
        helper.make_node('ArgMax', ['mul_387'], ['arg_389'], axis=0, keepdims=0),
        helper.make_node('Unsqueeze', ['arg_389', 'k_13'], ['uns_390']),
        helper.make_node('Add', ['uns_390', 'k_31'], ['add_391']),
        helper.make_node('Gather', ['pad_9', 'add_391'], ['gat_392'], axis=0),
        helper.make_node('Mul', ['con_62', 'gat_392'], ['mul_420']),
        helper.make_node('ReduceSum', ['mul_420'], ['red_421'], keepdims=0),
        helper.make_node('Mul', ['con_67', 'gat_392'], ['mul_424']),
        helper.make_node('ReduceSum', ['mul_424'], ['red_425'], keepdims=0),
        helper.make_node('Mul', ['mul_48', 'gat_392'], ['mul_428']),
        helper.make_node('ReduceSum', ['mul_428'], ['red_429'], keepdims=0),
        helper.make_node('Mul', ['con_72', 'gat_392'], ['mul_432']),
        helper.make_node('ReduceSum', ['mul_432'], ['red_433'], keepdims=0),
        helper.make_node('Unsqueeze', ['red_421', 'k_13'], ['uns_434']),
        helper.make_node('Unsqueeze', ['red_425', 'k_13'], ['uns_435']),
        helper.make_node('Unsqueeze', ['red_429', 'k_13'], ['uns_436']),
        helper.make_node('Unsqueeze', ['red_433', 'k_13'], ['uns_437']),
        helper.make_node('Concat', ['uns_434', 'uns_435', 'uns_436', 'uns_437'], ['con_438'], axis=0),
        helper.make_node('ArgMax', ['con_438'], ['arg_439'], axis=0, keepdims=0),
        helper.make_node('Unsqueeze', ['arg_439', 'k_13'], ['uns_440']),
        helper.make_node('Gather', ['con_78', 'uns_440'], ['gat_441'], axis=0),
        helper.make_node('Squeeze', ['gat_441', 'k_13'], ['squ_443']),
        helper.make_node('Pad', ['squ_443', 'k_140'], ['pad_445'], mode='constant'),
        helper.make_node('Sub', ['k_143', 'uns_390'], ['sub_448']),
        helper.make_node('Add', ['sub_448', 'k_142'], ['add_449']),
        helper.make_node('Max', ['add_449', 'k_13'], ['max_452']),
        helper.make_node('Gather', ['pad_445', 'max_452'], ['gat_455'], axis=0),
        helper.make_node('Unsqueeze', ['red_388', 'k_13'], ['uns_457']),
        helper.make_node('Mul', ['gat_455', 'uns_457'], ['mul_458']),
        helper.make_node('Max', ['max_383', 'mul_458'], ['max_459']),
        helper.make_node('Equal', ['cas_26', 'k_460'], ['equ_461']),
        helper.make_node('Cast', ['equ_461'], ['cas_462'], to=10),
        helper.make_node('Mul', ['cas_462', 'mul_23'], ['mul_463']),
        helper.make_node('ReduceMax', ['mul_463'], ['red_464'], axes=[0], keepdims=1),
        helper.make_node('ArgMax', ['mul_463'], ['arg_465'], axis=0, keepdims=0),
        helper.make_node('Unsqueeze', ['arg_465', 'k_13'], ['uns_466']),
        helper.make_node('Add', ['uns_466', 'k_31'], ['add_467']),
        helper.make_node('Gather', ['pad_9', 'add_467'], ['gat_468'], axis=0),
        helper.make_node('Mul', ['con_62', 'gat_468'], ['mul_496']),
        helper.make_node('ReduceSum', ['mul_496'], ['red_497'], keepdims=0),
        helper.make_node('Mul', ['con_67', 'gat_468'], ['mul_500']),
        helper.make_node('ReduceSum', ['mul_500'], ['red_501'], keepdims=0),
        helper.make_node('Mul', ['mul_48', 'gat_468'], ['mul_504']),
        helper.make_node('ReduceSum', ['mul_504'], ['red_505'], keepdims=0),
        helper.make_node('Mul', ['con_72', 'gat_468'], ['mul_508']),
        helper.make_node('ReduceSum', ['mul_508'], ['red_509'], keepdims=0),
        helper.make_node('Unsqueeze', ['red_497', 'k_13'], ['uns_510']),
        helper.make_node('Unsqueeze', ['red_501', 'k_13'], ['uns_511']),
        helper.make_node('Unsqueeze', ['red_505', 'k_13'], ['uns_512']),
        helper.make_node('Unsqueeze', ['red_509', 'k_13'], ['uns_513']),
        helper.make_node('Concat', ['uns_510', 'uns_511', 'uns_512', 'uns_513'], ['con_514'], axis=0),
        helper.make_node('ArgMax', ['con_514'], ['arg_515'], axis=0, keepdims=0),
        helper.make_node('Unsqueeze', ['arg_515', 'k_13'], ['uns_516']),
        helper.make_node('Gather', ['con_78', 'uns_516'], ['gat_517'], axis=0),
        helper.make_node('Squeeze', ['gat_517', 'k_13'], ['squ_519']),
        helper.make_node('Pad', ['squ_519', 'k_140'], ['pad_521'], mode='constant'),
        helper.make_node('Sub', ['k_143', 'uns_466'], ['sub_524']),
        helper.make_node('Add', ['sub_524', 'k_142'], ['add_525']),
        helper.make_node('Max', ['add_525', 'k_13'], ['max_528']),
        helper.make_node('Gather', ['pad_521', 'max_528'], ['gat_531'], axis=0),
        helper.make_node('Unsqueeze', ['red_464', 'k_13'], ['uns_533']),
        helper.make_node('Mul', ['gat_531', 'uns_533'], ['mul_534']),
        helper.make_node('Max', ['max_459', 'mul_534'], ['max_535']),
        helper.make_node('Gather', ['input', 'k_13'], ['gat_537'], axis=1),
        helper.make_node('Slice', ['gat_537', 'k_3', 'k_4'], ['gat_537_c']),
        helper.make_node('Cast', ['gat_537_c'], ['gat_537__h16'], to=10),
        helper.make_node('Slice', ['gat_537__h16', 'k_3', 'k_4'], ['sli_540']),
        helper.make_node('Reshape', ['sli_540', 'k_6'], ['res_541']),
        helper.make_node('Mul', ['max_535', 'res_541'], ['mul_542']),
        helper.make_node('Cast', ['gat_2_c'], ['cyan_c'], to=2),
        helper.make_node('Unsqueeze', ['mul_542', 'k_545'], ['mask_4d']),
        helper.make_node('Cast', ['mask_4d'], ['mask_c'], to=2),
        helper.make_node('Mul', ['cyan_c', 'c_eight_u8'], ['cyan8_c']),
        helper.make_node('Add', ['cyan8_c', 'mask_c'], ['colour15']),
        helper.make_node('Equal', ['colour15', 'arange_u8'], ['out15']),
        helper.make_node('Pad', ['out15', 'pad_out', 'false_u8'], ['output'], mode='constant'),
    ]
    value_infos = [
    ]
    return model('task219', nodes, inits, output_dtype=9, opset=17, value_infos=value_infos)
