"""Task 155 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('row_ids_1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAgAAAAMAAAAEAAAABQAAAAYAAAAHAAAACAAAAAkAAAAKAAAACwAAAAwAAAANAAAADgAAAA8AAAAQAAAAEQAAABIAAAATAAAAFAAAABUAAAAWAAAAFwAAABgAAAAZAAAAGgAAABsAAAAcAAAAHQAAAB4AAAA=')),
    ]
    nodes = [
        helper.make_node('ReduceL2', ['input'], ['side_f'], axes=[0, 1, 2, 3], keepdims=0),
        helper.make_node('Cast', ['side_f'], ['side'], to=6),
        helper.make_node('Sub', ['side', 'row_ids_1'], ['src_rows']),
        helper.make_node('Gather', ['input', 'src_rows'], ['output'], axis=2),
    ]
    value_infos = [
    ]
    return model('task155_live_exact', nodes, inits, output_dtype=1, opset=11, value_infos=value_infos)
