"""Task 293 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('top_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('top_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAEAAAAAAAAADwAAAAAAAAA=')),
        tensor('top_axes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAA=')),
        tensor('left_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAABAAAAAAAAAAAQAAAAAAAAA=')),
        tensor('one_1111', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
        tensor('zero_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAA')),
        tensor('true_1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGIxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('two_1111', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAA==')),
        tensor('shape111', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAA=')),
        tensor('shape_1_10_1_1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAoAAAAAAAAAAQAAAAAAAAABAAAAAAAAAA==')),
        tensor('batch0_2111', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsIDEsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAA')),
        tensor('offset_const', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDMsIDIsIDQpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAQAAAAAAAAA=')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'top_starts', 'top_ends', 'top_axes'], ['top_slice']),
        helper.make_node('Slice', ['input', 'top_starts', 'left_ends', 'top_axes'], ['left_slice']),
        helper.make_node('ArgMin', ['top_slice'], ['col0_k'], axis=3, keepdims=1),
        helper.make_node('ArgMin', ['left_slice'], ['row0_k'], axis=2, keepdims=1),
        helper.make_node('Add', ['col0_k', 'one_1111'], ['col0p1_k']),
        helper.make_node('Add', ['row0_k', 'one_1111'], ['row0p1_k']),
        helper.make_node('Add', ['row0_k', 'two_1111'], ['row0p2_k']),
        helper.make_node('GatherElements', ['top_slice', 'col0p1_k'], ['col0p1_val'], axis=3),
        helper.make_node('GatherElements', ['left_slice', 'row0p1_k'], ['row0p1_val'], axis=2),
        helper.make_node('GatherElements', ['left_slice', 'row0p2_k'], ['row0p2_val'], axis=2),
        helper.make_node('Equal', ['col0p1_val', 'zero_f'], ['col_valid1_raw']),
        helper.make_node('Equal', ['row0p1_val', 'zero_f'], ['row_valid1_raw']),
        helper.make_node('Equal', ['row0p2_val', 'zero_f'], ['row_valid2_raw0']),
        helper.make_node('And', ['row_valid1_raw', 'row_valid2_raw0'], ['row_valid2_raw']),
        helper.make_node('Reshape', ['col_valid1_raw', 'shape111'], ['col_valid1']),
        helper.make_node('Reshape', ['row_valid1_raw', 'shape111'], ['row_valid1']),
        helper.make_node('Reshape', ['row_valid2_raw', 'shape111'], ['row_valid2']),
        helper.make_node('Concat', ['true_1', 'col_valid1'], ['col_valid'], axis=2),
        helper.make_node('Concat', ['true_1', 'row_valid1', 'row_valid2'], ['row_valid'], axis=1),
        helper.make_node('Cast', ['col0_k'], ['col0_i32'], to=6),
        helper.make_node('Cast', ['row0_k'], ['row0_i32'], to=6),
        helper.make_node('Expand', ['col0_i32', 'shape_1_10_1_1'], ['col0_idx4']),
        helper.make_node('Expand', ['row0_i32', 'shape_1_10_1_1'], ['row0_idx4']),
        helper.make_node('GatherElements', ['input', 'col0_idx4'], ['colorA_slice'], axis=3),
        helper.make_node('GatherElements', ['input', 'row0_idx4'], ['colorB_slice'], axis=2),
        helper.make_node('ArgMax', ['colorA_slice'], ['colorA_ch'], axis=1, keepdims=1),
        helper.make_node('ArgMax', ['colorB_slice'], ['colorB_ch'], axis=1, keepdims=1),
        helper.make_node('Concat', ['colorA_ch', 'colorB_ch'], ['colors_r'], axis=0),
        helper.make_node('And', ['row_valid', 'col_valid'], ['valid']),
        helper.make_node('Concat', ['row0_k', 'row0_k'], ['row0_exp'], axis=0),
        helper.make_node('Concat', ['col0_k', 'col0_k'], ['col0_exp'], axis=0),
        helper.make_node('Concat', ['batch0_2111', 'colors_r', 'row0_exp', 'col0_exp'], ['part1'], axis=3),
        helper.make_node('Add', ['part1', 'offset_const'], ['scatter_idx']),
        helper.make_node('GatherND', ['input', 'scatter_idx'], ['orig']),
        helper.make_node('Cast', ['orig'], ['orig_b'], to=9),
        helper.make_node('Xor', ['valid', 'orig_b'], ['updates_b']),
        helper.make_node('Cast', ['updates_b'], ['updates'], to=1),
        helper.make_node('ScatterND', ['input', 'scatter_idx', 'updates'], ['output']),
    ]
    value_infos = [
    ]
    return model('task293_live_exact', nodes, inits, output_dtype=1, opset=17, value_infos=value_infos)
