"""Task 334 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('out_pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbAAAAAAAAABsAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('ReduceMax', ['input'], ['present_f'], axes=[2, 3], keepdims=1),
        helper.make_node('Cast', ['present_f'], ['present'], to=2),
        helper.make_node('Split', ['present'], ['c0', 'c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9'], axis=1),
        helper.make_node('Max', ['c1', 'c2'], ['c12']),
        helper.make_node('Max', ['c2', 'c3'], ['c23']),
        helper.make_node('Max', ['c1', 'c3'], ['c13']),
        helper.make_node('Concat', ['c2', 'c12', 'c23'], ['row0'], axis=3),
        helper.make_node('Concat', ['c1', 'c12', 'c13'], ['row1'], axis=3),
        helper.make_node('Concat', ['c3', 'c0', 'c3'], ['row2'], axis=3),
        helper.make_node('Concat', ['row0', 'row1', 'row2'], ['gray'], axis=2),
        helper.make_node('Sub', ['c0', 'gray'], ['black']),
        helper.make_node('Sub', ['gray', 'gray'], ['zero']),
        helper.make_node('Concat', ['black', 'zero', 'zero', 'zero', 'zero', 'gray', 'zero', 'zero', 'zero', 'zero'], ['patch'], axis=1),
        helper.make_node('Pad', ['patch', 'out_pads'], ['output'], mode='constant'),
    ]
    value_infos = [
        helper.make_tensor_value_info('present_f', 1, [1, 10, 1, 1]),
        helper.make_tensor_value_info('present', 2, [1, 10, 1, 1]),
        helper.make_tensor_value_info('c0', 2, [1, 1, 1, 1]),
        helper.make_tensor_value_info('c1', 2, [1, 1, 1, 1]),
        helper.make_tensor_value_info('c2', 2, [1, 1, 1, 1]),
        helper.make_tensor_value_info('c3', 2, [1, 1, 1, 1]),
        helper.make_tensor_value_info('c4', 2, [1, 1, 1, 1]),
        helper.make_tensor_value_info('c5', 2, [1, 1, 1, 1]),
        helper.make_tensor_value_info('c6', 2, [1, 1, 1, 1]),
        helper.make_tensor_value_info('c7', 2, [1, 1, 1, 1]),
        helper.make_tensor_value_info('c8', 2, [1, 1, 1, 1]),
        helper.make_tensor_value_info('c9', 2, [1, 1, 1, 1]),
        helper.make_tensor_value_info('c12', 2, [1, 1, 1, 1]),
        helper.make_tensor_value_info('c23', 2, [1, 1, 1, 1]),
        helper.make_tensor_value_info('c13', 2, [1, 1, 1, 1]),
        helper.make_tensor_value_info('row0', 2, [1, 1, 1, 3]),
        helper.make_tensor_value_info('row1', 2, [1, 1, 1, 3]),
        helper.make_tensor_value_info('row2', 2, [1, 1, 1, 3]),
        helper.make_tensor_value_info('gray', 2, [1, 1, 3, 3]),
        helper.make_tensor_value_info('black', 2, [1, 1, 3, 3]),
        helper.make_tensor_value_info('zero', 2, [1, 1, 3, 3]),
        helper.make_tensor_value_info('patch', 2, [1, 10, 3, 3]),
    ]
    return model('task334_live_exact', nodes, inits, output_dtype=2, opset=14, value_infos=value_infos)
