"""Task 004 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('Wc', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAyLCAyKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAH/DAAAAAAAAAAAAAAAAAAB+wwAAAAAAAAAAAAAAAAAAfcMAAAAAAAAAAAAAAAAAAHzDAAAAAAAAAAAAAAAAAAB7wwAAAAAAAAAAAAAAAAAAesMAAAAAAAAAAAAAAAAAAHnDAAAAAAAAAAAAAAAAAAB4wwAAAAAAAAAAAAAAAAAAd8MAAAAAAAAAAAAAAAAAAHbDAAAAAAAAAAAAAAAA')),
        tensor('bc', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAH9D')),
        tensor('u255', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAr/')),
        tensor('u0', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('bidx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDE2LCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAAEAAAAAAAAAAUAAAAAAAAABgAAAAAAAAAHAAAAAAAAAAgAAAAAAAAACQAAAAAAAAAKAAAAAAAAAAsAAAAAAAAADAAAAAAAAAANAAAAAAAAAA4AAAAAAAAADwAAAAAAAAAAAAAAAAAAAA==')),
        tensor('sidx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDE2LCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoPAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAACAAAAAAAAAAMAAAAAAAAABAAAAAAAAAAFAAAAAAAAAAYAAAAAAAAABwAAAAAAAAAIAAAAAAAAAAkAAAAAAAAACgAAAAAAAAALAAAAAAAAAAwAAAAAAAAADQAAAAAAAAAOAAAAAAAAAA==')),
        tensor('pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAAAAAAAA4AAAAAAAAA')),
        tensor('palette', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJ')),
    ]
    nodes = [
        helper.make_node('Conv', ['input', 'Wc', 'bc'], ['code_f'], dilations=[14, 14], kernel_shape=[2, 2], pads=[0, 0, 0, 0]),
        helper.make_node('Cast', ['code_f'], ['code'], to=2),
        helper.make_node('Less', ['code', 'u255'], ['valid']),
        helper.make_node('Where', ['valid', 'code', 'u0'], ['vals']),
        helper.make_node('Gather', ['vals', 'bidx'], ['below_any'], axis=2),
        helper.make_node('Gather', ['vals', 'bidx'], ['right_any'], axis=3),
        helper.make_node('ReduceMax', ['below_any'], ['row_next_u8'], axes=[3], keepdims=1),
        helper.make_node('Cast', ['row_next_u8'], ['row_next'], to=9),
        helper.make_node('Greater', ['below_any', 'right_any'], ['endpoint']),
        helper.make_node('Xor', ['row_next', 'endpoint'], ['move_cond']),
        helper.make_node('Where', ['move_cond', 'vals', 'u0'], ['move_vals']),
        helper.make_node('Where', ['move_cond', 'u0', 'vals'], ['stay_vals']),
        helper.make_node('Gather', ['move_vals', 'sidx'], ['shifted'], axis=3),
        helper.make_node('Max', ['stay_vals', 'shifted'], ['scalar_out']),
        helper.make_node('Where', ['valid', 'scalar_out', 'u255'], ['scalar_valid']),
        helper.make_node('Pad', ['scalar_valid', 'pads', 'u255'], ['scalar_full'], mode='constant'),
        helper.make_node('Equal', ['scalar_full', 'palette'], ['output']),
    ]
    value_infos = [
        helper.make_tensor_value_info('code_f', 1, [1, 1, 16, 16]),
        helper.make_tensor_value_info('code', 2, [1, 1, 16, 16]),
        helper.make_tensor_value_info('valid', 9, [1, 1, 16, 16]),
        helper.make_tensor_value_info('vals', 2, [1, 1, 16, 16]),
        helper.make_tensor_value_info('below_any', 2, [1, 1, 16, 16]),
        helper.make_tensor_value_info('right_any', 2, [1, 1, 16, 16]),
        helper.make_tensor_value_info('row_next_u8', 2, [1, 1, 16, 1]),
        helper.make_tensor_value_info('row_next', 9, [1, 1, 16, 1]),
        helper.make_tensor_value_info('endpoint', 9, [1, 1, 16, 16]),
        helper.make_tensor_value_info('move_cond', 9, [1, 1, 16, 16]),
        helper.make_tensor_value_info('move_vals', 2, [1, 1, 16, 16]),
        helper.make_tensor_value_info('stay_vals', 2, [1, 1, 16, 16]),
        helper.make_tensor_value_info('shifted', 2, [1, 1, 16, 16]),
        helper.make_tensor_value_info('scalar_out', 2, [1, 1, 16, 16]),
        helper.make_tensor_value_info('scalar_valid', 2, [1, 1, 16, 16]),
        helper.make_tensor_value_info('scalar_full', 2, [1, 1, 30, 30]),
    ]
    return model('task004_live_exact', nodes, inits, output_dtype=9, opset=17, value_infos=value_infos)
