"""Task 290 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('outer_counts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAABBAABAQQAAwEEAAABC')),
        tensor('topk_k', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAA==')),
        tensor('outer_col', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
        tensor('color_cols', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAEAAAAAAAAA')),
        tensor('depth10', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoKAAAAAAAAAA==')),
        tensor('onehot_values', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAvAA8')),
        tensor('spatial_table', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsIDIsIDYpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAPAA8ADwAAAAAAAAAAABAAAAAAAAAAAAAPAA8ADwAPAAAAAAAAABAAEAAAAAAAAAAPAA8ADwAPAA8AAAAAAAAAEAAAAAAAAAAPAA8ADwAPAA8ADwAAAAAAEAAQAAAAAA=')),
        tensor('spatial_pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAA==')),
    ]
    nodes = [
        helper.make_node('ReduceSum', ['input'], ['color_counts'], axes=[2, 3], keepdims=0),
        helper.make_node('TopK', ['color_counts', 'topk_k'], ['top_values', 'top_indices'], axis=1, largest=1, sorted=1),
        helper.make_node('Gather', ['top_values', 'outer_col'], ['outer_count'], axis=1),
        helper.make_node('Equal', ['outer_count', 'outer_counts'], ['size_match']),
        helper.make_node('Cast', ['size_match'], ['size_f16'], to=10),
        helper.make_node('Gather', ['top_indices', 'color_cols'], ['color_indices'], axis=1),
        helper.make_node('OneHot', ['color_indices', 'depth10', 'onehot_values'], ['color_basis'], axis=-1),
        helper.make_node('Einsum', ['size_f16', 'spatial_table'], ['spatial6'], equation='z,zkr->kr'),
        helper.make_node('Pad', ['spatial6', 'spatial_pads'], ['spatial_terms'], mode='constant'),
        helper.make_node('Einsum', ['color_basis', 'spatial_terms', 'spatial_terms'], ['output'], equation='bkc,kr,ks->bcrs'),
    ]
    value_infos = [
        helper.make_tensor_value_info('color_counts', 1, [1, 10]),
        helper.make_tensor_value_info('top_values', 1, [1, 3]),
        helper.make_tensor_value_info('top_indices', 7, [1, 3]),
        helper.make_tensor_value_info('outer_count', 1, [1]),
        helper.make_tensor_value_info('size_match', 9, [4]),
        helper.make_tensor_value_info('size_f16', 10, [4]),
        helper.make_tensor_value_info('color_indices', 7, [1, 2]),
        helper.make_tensor_value_info('color_basis', 10, [1, 2, 10]),
        helper.make_tensor_value_info('spatial6', 10, [2, 6]),
        helper.make_tensor_value_info('spatial_terms', 10, [2, 30]),
    ]
    return model('task290_live_exact', nodes, inits, output_dtype=10, opset=12, value_infos=value_infos)
