"""Task 109 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('slice_axes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAgAAAAMAAAA=')),
        tensor('bg_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAA=')),
        tensor('bg_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAABgAAAAYAAAA=')),
        tensor('one_i32', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAA')),
        tensor('line_start_post', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAA')),
        tensor('line_end_pre', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoKAAAA')),
        tensor('mirror_table', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsIDEyKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAQAAAAIAAAACAAAAAQAAAAAAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAAAAAAAAQAAAAIAAAADAAAAAwAAAAIAAAABAAAAAAAAAAQAAAAEAAAABAAAAAQAAAAAAAAAAQAAAAIAAAADAAAABAAAAAQAAAADAAAAAgAAAAEAAAAAAAAABQAAAAUAAAAAAAAAAQAAAAIAAAADAAAABAAAAAUAAAAFAAAABAAAAAMAAAACAAAAAQAAAAAAAAA=')),
        tensor('four_i32', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoEAAAA')),
        tensor('diag_coords', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsIDQpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAABwAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJAAAAAAAAAAkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsAAAAAAAAACwAAAAAAAAA=')),
        tensor('bg_class_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoJ')),
        tensor('invalid_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoK')),
        tensor('class_to_channel_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoJAAECAwQFBgcI')),
        tensor('pads12_to_30', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASAAAAAAAAABIAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'bg_starts', 'bg_ends', 'slice_axes'], ['bg6_f']),
        helper.make_node('Cast', ['bg6_f'], ['bg6'], to=9),
        helper.make_node('GatherND', ['input', 'diag_coords'], ['diag_f']),
        helper.make_node('ReduceSum', ['diag_f'], ['active_case_f'], axes=[0], keepdims=0),
        helper.make_node('Cast', ['active_case_f'], ['active_case'], to=6),
        helper.make_node('Gather', ['mirror_table', 'active_case'], ['mirror_idx'], axis=0),
        helper.make_node('Add', ['active_case', 'four_i32'], ['line_end_idx_vec']),
        helper.make_node('Sub', ['line_end_idx_vec', 'one_i32'], ['center_idx_vec']),
        helper.make_node('Less', ['mirror_idx', 'center_idx_vec'], ['valid_idx']),
        helper.make_node('Greater', ['center_idx_vec', 'four_i32'], ['center_gt4']),
        helper.make_node('Where', ['center_gt4', 'four_i32', 'line_end_idx_vec'], ['invalid_col']),
        helper.make_node('Where', ['valid_idx', 'mirror_idx', 'invalid_col'], ['mirror_col_idx']),
        helper.make_node('Gather', ['bg6', 'mirror_idx'], ['bg_rows'], axis=2),
        helper.make_node('Gather', ['bg_rows', 'mirror_col_idx'], ['bg_mask'], axis=3),
        helper.make_node('Unsqueeze', ['valid_idx'], ['valid_rows'], axes=[0, 1, 3]),
        helper.make_node('Concat', ['one_i32', 'center_idx_vec', 'line_start_post'], ['line_starts'], axis=0),
        helper.make_node('Concat', ['line_end_pre', 'line_end_idx_vec', 'one_i32'], ['line_ends'], axis=0),
        helper.make_node('Slice', ['input', 'line_starts', 'line_ends', 'slice_axes'], ['line_candidates']),
        helper.make_node('ArgMax', ['line_candidates'], ['line_args_all'], axis=1, keepdims=1),
        helper.make_node('Cast', ['line_args_all'], ['line_arg0_u8'], to=2),
        helper.make_node('Where', ['valid_idx', 'bg_class_u8', 'invalid_u8'], ['base_cols']),
        helper.make_node('Where', ['valid_rows', 'line_arg0_u8', 'invalid_u8'], ['line_rows']),
        helper.make_node('Where', ['bg_mask', 'base_cols', 'line_rows'], ['class_idx']),
        helper.make_node('Pad', ['class_idx', 'pads12_to_30', 'invalid_u8'], ['class_idx30'], mode='constant'),
        helper.make_node('Equal', ['class_to_channel_u8', 'class_idx30'], ['output']),
    ]
    value_infos = [
        helper.make_tensor_value_info('line_candidates', 1, [1, 9, 1, 1]),
    ]
    return model('task109_live_exact', nodes, inits, output_dtype=9, opset=12, value_infos=value_infos)
