"""Task 030 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('axes123', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAA=')),
        tensor('slice_color_1_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('slice_color_1_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAoAAAAAAAAACgAAAAAAAAA=')),
        tensor('slice_probe_2_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('slice_probe_2_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAAkAAAAAAAAACAAAAAAAAAA=')),
        tensor('slice_probe_4_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('slice_probe_4_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoFAAAAAAAAAAkAAAAAAAAACAAAAAAAAAA=')),
        tensor('slice_h10_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAkAAAAAAAAAAAAAAAAAAAA=')),
        tensor('slice_h10_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAoAAAAAAAAAAQAAAAAAAAA=')),
        tensor('one_col_i8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('base_idx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJ')),
        tensor('row_mod', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoK')),
        tensor('one_cell', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('zero', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEwLCAxMCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA')),
        tensor('out_pad', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQAAAAAAAAAUAAAAAAAAABQAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'slice_color_1_starts', 'slice_color_1_ends', 'axes123'], ['x1f']),
        helper.make_node('Cast', ['x1f'], ['x1'], to=3),
        helper.make_node('Slice', ['input', 'slice_probe_2_starts', 'slice_probe_2_ends', 'axes123'], ['probe2f']),
        helper.make_node('Slice', ['input', 'slice_probe_4_starts', 'slice_probe_4_ends', 'axes123'], ['probe4f']),
        helper.make_node('Slice', ['input', 'slice_h10_starts', 'slice_h10_ends', 'axes123'], ['h10f']),
        helper.make_node('Cast', ['h10f'], ['h10'], to=3),
        helper.make_node('ReduceMax', ['x1'], ['col_has_1'], axes=[1, 2], keepdims=0),
        helper.make_node('ArgMax', ['col_has_1'], ['left1_i64'], axis=1, keepdims=0),
        helper.make_node('Cast', ['left1_i64'], ['left1'], to=3),
        helper.make_node('ReduceMax', ['probe2f'], ['col_has_2f'], axes=[1, 2], keepdims=0),
        helper.make_node('Cast', ['col_has_2f'], ['col_has_2'], to=3),
        helper.make_node('Concat', ['col_has_2', 'one_col_i8'], ['col_scan_2'], axis=1),
        helper.make_node('ArgMax', ['col_scan_2'], ['left2_i64'], axis=1, keepdims=0),
        helper.make_node('Cast', ['left2_i64'], ['left2'], to=3),
        helper.make_node('ReduceMax', ['probe4f'], ['col_has_4f'], axes=[1, 2], keepdims=0),
        helper.make_node('Cast', ['col_has_4f'], ['col_has_4'], to=3),
        helper.make_node('Concat', ['col_has_4', 'one_col_i8'], ['col_scan_4'], axis=1),
        helper.make_node('ArgMax', ['col_scan_4'], ['left4_i64'], axis=1, keepdims=0),
        helper.make_node('Cast', ['left4_i64'], ['left4'], to=3),
        helper.make_node('Sub', ['left2', 'left1'], ['shift2']),
        helper.make_node('Sub', ['base_idx', 'shift2'], ['col_idx2']),
        helper.make_node('Mod', ['col_idx2', 'row_mod'], ['col_idx2_safe'], fmod=0),
        helper.make_node('Cast', ['col_idx2_safe'], ['col_idx2_i32'], to=6),
        helper.make_node('Gather', ['x1', 'col_idx2_i32'], ['x2_shift'], axis=3),
        helper.make_node('Sub', ['left4', 'left1'], ['shift4']),
        helper.make_node('Sub', ['base_idx', 'shift4'], ['col_idx4']),
        helper.make_node('Mod', ['col_idx4', 'row_mod'], ['col_idx4_safe'], fmod=0),
        helper.make_node('Cast', ['col_idx4_safe'], ['col_idx4_i32'], to=6),
        helper.make_node('Gather', ['x1', 'col_idx4_i32'], ['x4_shift'], axis=3),
        helper.make_node('Concat', ['one_cell', 'one_cell', 'one_cell', 'one_cell', 'one_cell', 'h10', 'h10', 'h10', 'h10', 'h10'], ['inside_col'], axis=2),
        helper.make_node('Max', ['x1', 'x2_shift', 'x4_shift'], ['fg']),
        helper.make_node('Sub', ['inside_col', 'fg'], ['bg']),
        helper.make_node('Concat', ['bg', 'x1', 'x2_shift', 'zero', 'x4_shift'], ['crop_output'], axis=1),
        helper.make_node('Pad', ['crop_output', 'out_pad'], ['output'], mode='constant'),
    ]
    value_infos = [
    ]
    return model('task030_live_exact', nodes, inits, output_dtype=3, opset=14, value_infos=value_infos)
