"""Task 101 candidate — counting-model rebuild of the incumbent algorithm.

Same algorithm as src/custom/task101.py (blue-bbox origin + near probes,
scan-order TopK red candidates, 3 sequential copy claims with scale probes and
coverage subtraction, slot-enumerated blue paint), with cheaper plumbing:

1. Output = Where(blue_mask30, e1, input): passthrough replaces the whole
   inside-rect + ch0/out1/crop3 epilogue (input is exact one-hot; only the
   hidden blue cells change, ch0 1->0 and ch1 0->1, which Where does in one
   free-output node).
2. c1 (blue) fp32 slice chain replaced by free-input Einsums:
   row/col blue counts 'bchw,c->h' / 'bchw,c->w' for the bbox origin, and a
   4-operand Einsum with OneHot row/col selectors for the 4x4 patch reads
   (OneHot rows out of range read zeros == old patch_ok masking).
3. nzc eliminated: all six near probes are at rows above / cols left of the
   first blue row/col, so nzc == c2 there; probe c2_flat directly.
4. Blue paint: flat = (rbase*21) + dre*21 + c0 fusion (dre*21 baked as
   initializer), Where-safe index applied on fp16 before the int32 cast.
"""
import numpy as np
from onnx import TensorProto, helper

from ._exact import model, tensor


def build(task):
    f16 = np.float16
    i32 = np.int32
    i64 = np.int64
    inits = [
        tensor('four_f16', np.array([4], f16)),
        tensor('nine_f16', np.array([9], f16)),
        tensor('zero_i', np.array([0], i32)),
        tensor('one_i64', np.array([1], i32)),
        tensor('two_i64', np.array([2], i32)),
        tensor('three_i', np.array([3], i32)),
        tensor('twentyone_i', np.array([21], i32)),
        tensor('work_wm1_i', np.array([20], i32)),
        tensor('zero_f16', np.array([0], f16)),
        tensor('work_w_f16', np.array([21], f16)),
        tensor('axes_ch_hw', np.array([1, 2, 3], i64)),
        tensor('axes0', np.array([0], i64)),
        tensor('h17cs', np.array([0, 16, 0], i64)),
        tensor('h17ce', np.array([3, 17, 1], i64)),
        tensor('c2cs', np.array([2, 0, 0], i64)),
        tensor('c2ce', np.array([3, 17, 21], i64)),
        tensor('shape16', np.array([16], i64)),
        tensor('patch_offsets', np.array([0, 1, 2, 3], i32)),
        tensor('off16_f', -np.arange(16, dtype=f16)),
        tensor('offwork_f', -np.arange(357, dtype=f16)),
        tensor('patch_i', np.array([4], i32)),
        tensor('k_p1', np.array([8], i64)),
        tensor('k_p2', np.array([2], i64)),
        tensor('k_raw', np.array([29], i64)),
        tensor('sq_dr_i32', np.array([0, 0, 0, 1, 1, 1, 2, 2, 2], i32)),
        tensor('sq_dc_i32', np.array([0, 1, 2, 0, 1, 2, 0, 1, 2], i32)),
        tensor('sq2_i', np.array([1, 1, 0, 1, 1, 0, 0, 0, 0], bool)),
        tensor('false_work_flat', np.zeros(357, bool)),
        tensor('zero_bool', np.array(False)),
        tensor('false_score_f', np.array(-1000.0, f16)),
        tensor('present_score_f', np.array(-999.0, f16)),
        tensor('nzc_flat_shape', np.array([357], i64)),
        tensor('p1re_shape', np.array([1, 8, 1], i64)),
        tensor('blue_base_cre_shape', np.array([3, 1, 1], i64)),
        tensor('blue_base_dre_shape', np.array([1, 1, 1], i64)),
        tensor('blue_base_active_shape', np.array([24], i64)),
        tensor('blue_x2_active_shape', np.array([72], i64)),
        tensor('blue_x3_active_shape', np.array([40], i64)),
        tensor('blue_mask_shape', np.array([1, 1, 17, 21], i64)),
        tensor('blue_x2_dre21', np.array([0, 21, 21], f16).reshape(1, 1, 3)),
        tensor('blue_x2_dce', np.array([1, 0, 1], f16).reshape(1, 1, 3)),
        tensor('blue_x3_dre21', np.array([0, 21, 42, 42, 42], f16).reshape(1, 1, 5)),
        tensor('blue_x3_dce', np.array([2, 2, 0, 1, 2], f16).reshape(1, 1, 5)),
        tensor('fill_f16', np.array([356], f16)),
        tensor('mask_pads', np.array([0, 0, 0, 0, 0, 0, 13, 9], i64)),
        tensor('c2pad_pads', np.array([0, 44], i64)),
        tensor('pad_idx_i', np.array([400], i32)),
        tensor('sel_blue', np.eye(10, dtype=np.float32)[1]),
        tensor('sel_red', np.eye(10, dtype=np.float32)[2]),
        tensor('half_f', np.array([0.5], np.float32)),
        tensor('oh_depth', np.array([30], i32)),
        tensor('oh_vals', np.array([0.0, 1.0], np.float32)),
        tensor('e1_vals', np.eye(10, dtype=np.float32)[1].reshape(1, 10, 1, 1)),
    ]
    nodes = [
        # --- grid-height flag (17 rows <=> 4 sprites <=> 3rd copy slot live) ---
        helper.make_node('Slice', ['input', 'h17cs', 'h17ce', 'axes_ch_hw'], ['h17_cell']),
        helper.make_node('ReduceSum', ['h17_cell', 'axes_ch_hw'], ['h17_sum'], keepdims=0),
        helper.make_node('Cast', ['h17_sum'], ['h17'], to=9),
        # --- red plane (only counted full-plane read left) ---
        helper.make_node('Slice', ['input', 'c2cs', 'c2ce', 'axes_ch_hw'], ['c2cf']),
        helper.make_node('Cast', ['c2cf'], ['c2c'], to=9),
        helper.make_node('Reshape', ['c2c', 'nzc_flat_shape'], ['c2_flat']),
        # padded red vector: OOB scale probes (idx<=400) read False == "not seen"
        helper.make_node('Pad', ['c2_flat', 'c2pad_pads', 'zero_bool'], ['c2_pad'], mode='constant'),
        # --- blue bbox origin via free-input einsum counts ---
        helper.make_node('Einsum', ['input', 'sel_blue'], ['row_cnt'], equation='bchw,c->h'),
        helper.make_node('Greater', ['row_cnt', 'half_f'], ['row_pos']),
        helper.make_node('Cast', ['row_pos'], ['row_pos_u8'], to=2),
        helper.make_node('ArgMax', ['row_pos_u8'], ['blue_row0_i64'], axis=0, keepdims=1),
        helper.make_node('Cast', ['blue_row0_i64'], ['blue_row0'], to=6),
        helper.make_node('Einsum', ['input', 'sel_blue'], ['col_cnt'], equation='bchw,c->w'),
        helper.make_node('Greater', ['col_cnt', 'half_f'], ['col_pos']),
        helper.make_node('Cast', ['col_pos'], ['col_pos_u8'], to=2),
        helper.make_node('ArgMax', ['col_pos_u8'], ['blue_col0_i64'], axis=0, keepdims=1),
        helper.make_node('Cast', ['blue_col0_i64'], ['blue_col0'], to=6),
        # --- near probes (above/left of first blue row/col => red-only cells) ---
        helper.make_node('Sub', ['blue_row0', 'one_i64'], ['near_u1_r']),
        helper.make_node('Mul', ['near_u1_r', 'twentyone_i'], ['near_u1_rw']),
        helper.make_node('Add', ['near_u1_rw', 'blue_col0'], ['near_u1_flat']),
        helper.make_node('Gather', ['c2_flat', 'near_u1_flat'], ['near_u1_val'], axis=0),
        helper.make_node('GreaterOrEqual', ['blue_row0', 'one_i64'], ['near_u1_rok']),
        helper.make_node('And', ['near_u1_val', 'near_u1_rok'], ['near_u1']),
        helper.make_node('Sub', ['blue_row0', 'two_i64'], ['near_u2_r']),
        helper.make_node('Mul', ['near_u2_r', 'twentyone_i'], ['near_u2_rw']),
        helper.make_node('Add', ['near_u2_rw', 'blue_col0'], ['near_u2_flat']),
        helper.make_node('Gather', ['c2_flat', 'near_u2_flat'], ['near_u2_val'], axis=0),
        helper.make_node('GreaterOrEqual', ['blue_row0', 'two_i64'], ['near_u2_rok']),
        helper.make_node('And', ['near_u2_val', 'near_u2_rok'], ['near_u2']),
        helper.make_node('Sub', ['blue_col0', 'one_i64'], ['near_l1_c']),
        helper.make_node('Mul', ['blue_row0', 'twentyone_i'], ['near_l1_rw']),
        helper.make_node('Add', ['near_l1_rw', 'near_l1_c'], ['near_l1_flat']),
        helper.make_node('Gather', ['c2_flat', 'near_l1_flat'], ['near_l1_val'], axis=0),
        helper.make_node('GreaterOrEqual', ['blue_col0', 'one_i64'], ['near_l1_cok']),
        helper.make_node('And', ['near_l1_val', 'near_l1_cok'], ['near_l1']),
        helper.make_node('Sub', ['blue_col0', 'two_i64'], ['near_l2_c']),
        helper.make_node('Add', ['near_l1_rw', 'near_l2_c'], ['near_l2_flat']),
        helper.make_node('Gather', ['c2_flat', 'near_l2_flat'], ['near_l2_val'], axis=0),
        helper.make_node('GreaterOrEqual', ['blue_col0', 'two_i64'], ['near_l2_cok']),
        helper.make_node('And', ['near_l2_val', 'near_l2_cok'], ['near_l2']),
        helper.make_node('Add', ['near_u1_rw', 'near_l1_c'], ['near_ul_flat']),
        helper.make_node('Gather', ['c2_flat', 'near_ul_flat'], ['near_ul_val'], axis=0),
        helper.make_node('And', ['near_u1_rok', 'near_l1_cok'], ['near_ul_ib']),
        helper.make_node('And', ['near_ul_val', 'near_ul_ib'], ['near_ul']),
        helper.make_node('Add', ['blue_col0', 'one_i64'], ['near_ur_c']),
        helper.make_node('Add', ['near_u1_rw', 'near_ur_c'], ['near_ur_flat']),
        helper.make_node('Gather', ['c2_flat', 'near_ur_flat'], ['near_ur_val'], axis=0),
        helper.make_node('Less', ['blue_col0', 'work_wm1_i'], ['near_ur_cok']),
        helper.make_node('And', ['near_u1_rok', 'near_ur_cok'], ['near_ur_ib']),
        helper.make_node('And', ['near_ur_val', 'near_ur_ib'], ['near_ur']),
        helper.make_node('And', ['near_u1', 'near_u2'], ['off2r']),
        helper.make_node('And', ['near_l1', 'near_l2'], ['off2c']),
        helper.make_node('Or', ['near_u1', 'near_l1'], ['u_or_l']),
        helper.make_node('And', ['near_ul', 'u_or_l'], ['off11']),
        helper.make_node('Or', ['off11', 'near_u1'], ['row1_base']),
        helper.make_node('Or', ['row1_base', 'near_ur'], ['row1']),
        helper.make_node('Or', ['off11', 'near_l1'], ['col1']),
        helper.make_node('Where', ['row1', 'one_i64', 'zero_i'], ['row_off1']),
        helper.make_node('Where', ['col1', 'one_i64', 'zero_i'], ['col_off1']),
        helper.make_node('Where', ['off2r', 'two_i64', 'row_off1'], ['row_off']),
        helper.make_node('Where', ['off2c', 'two_i64', 'col_off1'], ['col_off']),
        helper.make_node('Sub', ['blue_row0', 'row_off'], ['row0']),
        helper.make_node('Sub', ['blue_col0', 'col_off'], ['col0']),
        # --- 4x4 reference patch via OneHot selectors + free-input einsum ---
        helper.make_node('Add', ['row0', 'patch_offsets'], ['row_idx_raw']),
        helper.make_node('Add', ['col0', 'patch_offsets'], ['col_idx_raw']),
        helper.make_node('OneHot', ['row_idx_raw', 'oh_depth', 'oh_vals'], ['row_sel']),
        helper.make_node('OneHot', ['col_idx_raw', 'oh_depth', 'oh_vals'], ['col_sel']),
        helper.make_node('Einsum', ['input', 'sel_blue', 'row_sel', 'col_sel'],
                         ['p1_patch_f'], equation='bchw,c,uh,vw->uv'),
        helper.make_node('Greater', ['p1_patch_f', 'half_f'], ['p1_bool4']),
        helper.make_node('Reshape', ['p1_bool4', 'shape16'], ['p1_vec']),
        helper.make_node('Einsum', ['input', 'sel_red', 'row_sel', 'col_sel'],
                         ['p2_patch_f'], equation='bchw,c,uh,vw->uv'),
        helper.make_node('Greater', ['p2_patch_f', 'half_f'], ['p2_bool4']),
        helper.make_node('Reshape', ['p2_bool4', 'shape16'], ['p2_vec']),
        # --- patch blue / red position lists ---
        helper.make_node('Where', ['p1_vec', 'off16_f', 'false_score_f'], ['p1pos_score']),
        helper.make_node('TopK', ['p1pos_score', 'k_p1'], ['p1pos_vals', 'p1pos_idx'], axis=0, largest=1, sorted=1),
        helper.make_node('Greater', ['p1pos_vals', 'present_score_f'], ['p1pos_present']),
        helper.make_node('Cast', ['p1pos_idx'], ['p1pos_idx32'], to=6),
        helper.make_node('Div', ['p1pos_idx32', 'patch_i'], ['p1pos_rows']),
        helper.make_node('Mod', ['p1pos_idx32', 'patch_i'], ['p1pos_cols'], fmod=0),
        helper.make_node('Where', ['p2_vec', 'off16_f', 'false_score_f'], ['p2pos_score']),
        helper.make_node('TopK', ['p2pos_score', 'k_p2'], ['p2pos_vals', 'p2pos_idx'], axis=0, largest=1, sorted=1),
        helper.make_node('Greater', ['p2pos_vals', 'present_score_f'], ['p2pos_present']),
        helper.make_node('Cast', ['p2pos_idx'], ['p2pos_idx32'], to=6),
        helper.make_node('Div', ['p2pos_idx32', 'patch_i'], ['p2pos_rows']),
        helper.make_node('Mod', ['p2pos_idx32', 'patch_i'], ['p2pos_cols'], fmod=0),
        helper.make_node('Gather', ['p2pos_rows', 'zero_i'], ['p2r0'], axis=0),
        helper.make_node('Gather', ['p2pos_cols', 'zero_i'], ['p2c0'], axis=0),
        # --- raw red candidate list (scan order, k=29) ---
        helper.make_node('Where', ['c2_flat', 'offwork_f', 'false_score_f'], ['rawpos_score']),
        helper.make_node('TopK', ['rawpos_score', 'k_raw'], ['rawpos_vals', 'rawpos_idx'], axis=0, largest=1, sorted=1),
        helper.make_node('Greater', ['rawpos_vals', 'present_score_f'], ['rawpos_present']),
        helper.make_node('Cast', ['rawpos_idx'], ['rawpos_idx32'], to=6),
        helper.make_node('Div', ['rawpos_idx32', 'twentyone_i'], ['rawpos_rows']),
        helper.make_node('Mod', ['rawpos_idx32', 'twentyone_i'], ['rawpos_cols'], fmod=0),
        helper.make_node('Add', ['row0', 'patch_i'], ['row4_i32']),
        helper.make_node('Add', ['col0', 'patch_i'], ['col4_i32']),
        helper.make_node('GreaterOrEqual', ['rawpos_rows', 'row0'], ['raw_rge']),
        helper.make_node('Less', ['rawpos_rows', 'row4_i32'], ['raw_rlt4']),
        helper.make_node('GreaterOrEqual', ['rawpos_cols', 'col0'], ['raw_cge']),
        helper.make_node('Less', ['rawpos_cols', 'col4_i32'], ['raw_clt4']),
        helper.make_node('And', ['raw_rge', 'raw_rlt4'], ['raw_rin']),
        helper.make_node('And', ['raw_cge', 'raw_clt4'], ['raw_cin']),
        helper.make_node('And', ['raw_rin', 'raw_cin'], ['raw_in_ref']),
        helper.make_node('Not', ['raw_in_ref'], ['raw_not_ref']),
        helper.make_node('And', ['rawpos_present', 'raw_not_ref'], ['raw_present']),
        # --- copy 1 claim ---
        helper.make_node('Cast', ['raw_present'], ['copy1_target_u8'], to=2),
        helper.make_node('ArgMax', ['copy1_target_u8'], ['copy1_target_idx_i64'], axis=0, keepdims=1),
        helper.make_node('Cast', ['copy1_target_idx_i64'], ['copy1_target_idx'], to=6),
        helper.make_node('Gather', ['rawpos_rows', 'copy1_target_idx'], ['copy1_target_r'], axis=0),
        helper.make_node('Gather', ['rawpos_cols', 'copy1_target_idx'], ['copy1_target_c'], axis=0),
        helper.make_node('Gather', ['raw_present', 'copy1_target_idx'], ['copy1_target_active'], axis=0),
        helper.make_node('Add', ['copy1_target_r', 'sq_dr_i32'], ['copy1_scale_rr']),
        helper.make_node('Add', ['copy1_target_c', 'sq_dc_i32'], ['copy1_scale_cc']),
        helper.make_node('Mul', ['copy1_scale_rr', 'twentyone_i'], ['copy1_scale_idx_rw']),
        helper.make_node('Add', ['copy1_scale_idx_rw', 'copy1_scale_cc'], ['copy1_scale_idx_raw']),
        helper.make_node('Greater', ['copy1_scale_cc', 'work_wm1_i'], ['copy1_scale_cof']),
        helper.make_node('Where', ['copy1_scale_cof', 'pad_idx_i', 'copy1_scale_idx_raw'], ['copy1_scale_idx_flat']),
        helper.make_node('Gather', ['c2_pad', 'copy1_scale_idx_flat'], ['copy1_scale_seen'], axis=0),
        helper.make_node('Cast', ['copy1_scale_seen'], ['copy1_scale_seen_f'], to=10),
        helper.make_node('ReduceSum', ['copy1_scale_seen_f', 'axes0'], ['copy1_scale_cnt3'], keepdims=1),
        helper.make_node('And', ['copy1_scale_seen', 'sq2_i'], ['copy1_scale_seen2']),
        helper.make_node('Cast', ['copy1_scale_seen2'], ['copy1_scale_seen2_f'], to=10),
        helper.make_node('ReduceSum', ['copy1_scale_seen2_f', 'axes0'], ['copy1_scale_cnt2'], keepdims=1),
        helper.make_node('Equal', ['copy1_scale_cnt3', 'nine_f16'], ['copy1_scale_is3']),
        helper.make_node('Equal', ['copy1_scale_cnt2', 'four_f16'], ['copy1_scale_is2']),
        helper.make_node('Where', ['copy1_scale_is2', 'two_i64', 'one_i64'], ['copy1_scale_s2']),
        helper.make_node('Where', ['copy1_scale_is3', 'three_i', 'copy1_scale_s2'], ['copy1_scale_scale']),
        helper.make_node('Mul', ['p2r0', 'copy1_scale_scale'], ['copy1_rdelta']),
        helper.make_node('Sub', ['copy1_target_r', 'copy1_rdelta'], ['copy1_sr']),
        helper.make_node('Mul', ['p2c0', 'copy1_scale_scale'], ['copy1_cdelta']),
        helper.make_node('Sub', ['copy1_target_c', 'copy1_cdelta'], ['copy1_sc']),
        helper.make_node('Add', ['copy1_sr', 'copy1_rdelta'], ['copy1_cov_rs0']),
        helper.make_node('Add', ['copy1_sc', 'copy1_cdelta'], ['copy1_cov_cs0']),
        helper.make_node('Add', ['copy1_cov_rs0', 'copy1_scale_scale'], ['copy1_cov_re0']),
        helper.make_node('Add', ['copy1_cov_cs0', 'copy1_scale_scale'], ['copy1_cov_ce0']),
        helper.make_node('GreaterOrEqual', ['rawpos_rows', 'copy1_cov_rs0'], ['copy1_cov_rge0']),
        helper.make_node('Less', ['rawpos_rows', 'copy1_cov_re0'], ['copy1_cov_rltend0']),
        helper.make_node('GreaterOrEqual', ['rawpos_cols', 'copy1_cov_cs0'], ['copy1_cov_cge0']),
        helper.make_node('Less', ['rawpos_cols', 'copy1_cov_ce0'], ['copy1_cov_cltend0']),
        helper.make_node('And', ['copy1_cov_rge0', 'copy1_cov_rltend0'], ['copy1_cov_rm0']),
        helper.make_node('And', ['copy1_cov_cge0', 'copy1_cov_cltend0'], ['copy1_cov_cm0']),
        helper.make_node('And', ['copy1_cov_rm0', 'copy1_cov_cm0'], ['copy1_cov_rc0']),
        helper.make_node('Gather', ['p2pos_rows', 'one_i64'], ['copy1_cov_pr1'], axis=0),
        helper.make_node('Gather', ['p2pos_cols', 'one_i64'], ['copy1_cov_pc1'], axis=0),
        helper.make_node('Gather', ['p2pos_present', 'one_i64'], ['copy1_cov_pp1'], axis=0),
        helper.make_node('Mul', ['copy1_cov_pr1', 'copy1_scale_scale'], ['copy1_cov_rsd1']),
        helper.make_node('Add', ['copy1_sr', 'copy1_cov_rsd1'], ['copy1_cov_rs1']),
        helper.make_node('Mul', ['copy1_cov_pc1', 'copy1_scale_scale'], ['copy1_cov_csd1']),
        helper.make_node('Add', ['copy1_sc', 'copy1_cov_csd1'], ['copy1_cov_cs1']),
        helper.make_node('Add', ['copy1_cov_rs1', 'copy1_scale_scale'], ['copy1_cov_re1']),
        helper.make_node('Add', ['copy1_cov_cs1', 'copy1_scale_scale'], ['copy1_cov_ce1']),
        helper.make_node('GreaterOrEqual', ['rawpos_rows', 'copy1_cov_rs1'], ['copy1_cov_rge1']),
        helper.make_node('Less', ['rawpos_rows', 'copy1_cov_re1'], ['copy1_cov_rltend1']),
        helper.make_node('GreaterOrEqual', ['rawpos_cols', 'copy1_cov_cs1'], ['copy1_cov_cge1']),
        helper.make_node('Less', ['rawpos_cols', 'copy1_cov_ce1'], ['copy1_cov_cltend1']),
        helper.make_node('And', ['copy1_cov_rge1', 'copy1_cov_rltend1'], ['copy1_cov_rm1']),
        helper.make_node('And', ['copy1_cov_cge1', 'copy1_cov_cltend1'], ['copy1_cov_cm1']),
        helper.make_node('And', ['copy1_cov_rm1', 'copy1_cov_cm1'], ['copy1_cov_rc1']),
        helper.make_node('And', ['copy1_cov_rc1', 'copy1_cov_pp1'], ['copy1_cov_slot1']),
        helper.make_node('Or', ['copy1_cov_rc0', 'copy1_cov_slot1'], ['copy1_cov_covered']),
        helper.make_node('Not', ['copy1_cov_covered'], ['copy1_cov_not']),
        helper.make_node('And', ['raw_present', 'copy1_cov_not'], ['copy1_next_present']),
        # --- copy 2 claim ---
        helper.make_node('Cast', ['copy1_next_present'], ['copy2_target_u8'], to=2),
        helper.make_node('ArgMax', ['copy2_target_u8'], ['copy2_target_idx_i64'], axis=0, keepdims=1),
        helper.make_node('Cast', ['copy2_target_idx_i64'], ['copy2_target_idx'], to=6),
        helper.make_node('Gather', ['rawpos_rows', 'copy2_target_idx'], ['copy2_target_r'], axis=0),
        helper.make_node('Gather', ['rawpos_cols', 'copy2_target_idx'], ['copy2_target_c'], axis=0),
        helper.make_node('Gather', ['copy1_next_present', 'copy2_target_idx'], ['copy2_target_active'], axis=0),
        helper.make_node('Add', ['copy2_target_r', 'sq_dr_i32'], ['copy2_scale_rr']),
        helper.make_node('Add', ['copy2_target_c', 'sq_dc_i32'], ['copy2_scale_cc']),
        helper.make_node('Mul', ['copy2_scale_rr', 'twentyone_i'], ['copy2_scale_idx_rw']),
        helper.make_node('Add', ['copy2_scale_idx_rw', 'copy2_scale_cc'], ['copy2_scale_idx_raw']),
        helper.make_node('Greater', ['copy2_scale_cc', 'work_wm1_i'], ['copy2_scale_cof']),
        helper.make_node('Where', ['copy2_scale_cof', 'pad_idx_i', 'copy2_scale_idx_raw'], ['copy2_scale_idx_flat']),
        helper.make_node('Gather', ['c2_pad', 'copy2_scale_idx_flat'], ['copy2_scale_seen'], axis=0),
        helper.make_node('Cast', ['copy2_scale_seen'], ['copy2_scale_seen_f'], to=10),
        helper.make_node('ReduceSum', ['copy2_scale_seen_f', 'axes0'], ['copy2_scale_cnt3'], keepdims=1),
        helper.make_node('And', ['copy2_scale_seen', 'sq2_i'], ['copy2_scale_seen2']),
        helper.make_node('Cast', ['copy2_scale_seen2'], ['copy2_scale_seen2_f'], to=10),
        helper.make_node('ReduceSum', ['copy2_scale_seen2_f', 'axes0'], ['copy2_scale_cnt2'], keepdims=1),
        helper.make_node('Equal', ['copy2_scale_cnt3', 'nine_f16'], ['copy2_scale_is3']),
        helper.make_node('Equal', ['copy2_scale_cnt2', 'four_f16'], ['copy2_scale_is2']),
        helper.make_node('Where', ['copy2_scale_is2', 'two_i64', 'one_i64'], ['copy2_scale_s2']),
        helper.make_node('Where', ['copy2_scale_is3', 'three_i', 'copy2_scale_s2'], ['copy2_scale_scale']),
        helper.make_node('Mul', ['p2r0', 'copy2_scale_scale'], ['copy2_rdelta']),
        helper.make_node('Sub', ['copy2_target_r', 'copy2_rdelta'], ['copy2_sr']),
        helper.make_node('Mul', ['p2c0', 'copy2_scale_scale'], ['copy2_cdelta']),
        helper.make_node('Sub', ['copy2_target_c', 'copy2_cdelta'], ['copy2_sc']),
        helper.make_node('Add', ['copy2_sr', 'copy2_rdelta'], ['copy2_cov_rs0']),
        helper.make_node('Add', ['copy2_sc', 'copy2_cdelta'], ['copy2_cov_cs0']),
        helper.make_node('Add', ['copy2_cov_rs0', 'copy2_scale_scale'], ['copy2_cov_re0']),
        helper.make_node('Add', ['copy2_cov_cs0', 'copy2_scale_scale'], ['copy2_cov_ce0']),
        helper.make_node('GreaterOrEqual', ['rawpos_rows', 'copy2_cov_rs0'], ['copy2_cov_rge0']),
        helper.make_node('Less', ['rawpos_rows', 'copy2_cov_re0'], ['copy2_cov_rltend0']),
        helper.make_node('GreaterOrEqual', ['rawpos_cols', 'copy2_cov_cs0'], ['copy2_cov_cge0']),
        helper.make_node('Less', ['rawpos_cols', 'copy2_cov_ce0'], ['copy2_cov_cltend0']),
        helper.make_node('And', ['copy2_cov_rge0', 'copy2_cov_rltend0'], ['copy2_cov_rm0']),
        helper.make_node('And', ['copy2_cov_cge0', 'copy2_cov_cltend0'], ['copy2_cov_cm0']),
        helper.make_node('And', ['copy2_cov_rm0', 'copy2_cov_cm0'], ['copy2_cov_rc0']),
        helper.make_node('And', ['copy2_cov_rc0', 'copy2_target_active'], ['copy2_cov_active0']),
        helper.make_node('Mul', ['copy1_cov_pr1', 'copy2_scale_scale'], ['copy2_cov_rsd1']),
        helper.make_node('Add', ['copy2_sr', 'copy2_cov_rsd1'], ['copy2_cov_rs1']),
        helper.make_node('Mul', ['copy1_cov_pc1', 'copy2_scale_scale'], ['copy2_cov_csd1']),
        helper.make_node('Add', ['copy2_sc', 'copy2_cov_csd1'], ['copy2_cov_cs1']),
        helper.make_node('Add', ['copy2_cov_rs1', 'copy2_scale_scale'], ['copy2_cov_re1']),
        helper.make_node('Add', ['copy2_cov_cs1', 'copy2_scale_scale'], ['copy2_cov_ce1']),
        helper.make_node('GreaterOrEqual', ['rawpos_rows', 'copy2_cov_rs1'], ['copy2_cov_rge1']),
        helper.make_node('Less', ['rawpos_rows', 'copy2_cov_re1'], ['copy2_cov_rltend1']),
        helper.make_node('GreaterOrEqual', ['rawpos_cols', 'copy2_cov_cs1'], ['copy2_cov_cge1']),
        helper.make_node('Less', ['rawpos_cols', 'copy2_cov_ce1'], ['copy2_cov_cltend1']),
        helper.make_node('And', ['copy2_cov_rge1', 'copy2_cov_rltend1'], ['copy2_cov_rm1']),
        helper.make_node('And', ['copy2_cov_cge1', 'copy2_cov_cltend1'], ['copy2_cov_cm1']),
        helper.make_node('And', ['copy2_cov_rm1', 'copy2_cov_cm1'], ['copy2_cov_rc1']),
        helper.make_node('And', ['copy2_cov_rc1', 'copy1_cov_pp1'], ['copy2_cov_slot1']),
        helper.make_node('And', ['copy2_cov_slot1', 'copy2_target_active'], ['copy2_cov_active1']),
        helper.make_node('Or', ['copy2_cov_active0', 'copy2_cov_active1'], ['copy2_cov_covered']),
        helper.make_node('Not', ['copy2_cov_covered'], ['copy2_cov_not']),
        helper.make_node('And', ['copy1_next_present', 'copy2_cov_not'], ['copy2_next_present']),
        # --- copy 3 claim (row-clamped scale probe) ---
        helper.make_node('Cast', ['copy2_next_present'], ['copy3_target_u8'], to=2),
        helper.make_node('ArgMax', ['copy3_target_u8'], ['copy3_target_idx_i64'], axis=0, keepdims=1),
        helper.make_node('Cast', ['copy3_target_idx_i64'], ['copy3_target_idx'], to=6),
        helper.make_node('Gather', ['rawpos_rows', 'copy3_target_idx'], ['copy3_target_r'], axis=0),
        helper.make_node('Gather', ['rawpos_cols', 'copy3_target_idx'], ['copy3_target_c'], axis=0),
        helper.make_node('Add', ['copy3_target_r', 'sq_dr_i32'], ['copy3_scale_rr']),
        helper.make_node('Add', ['copy3_target_c', 'sq_dc_i32'], ['copy3_scale_cc']),
        helper.make_node('Mul', ['copy3_scale_rr', 'twentyone_i'], ['copy3_scale_idx_rw']),
        helper.make_node('Add', ['copy3_scale_idx_rw', 'copy3_scale_cc'], ['copy3_scale_idx_raw']),
        helper.make_node('Greater', ['copy3_scale_cc', 'work_wm1_i'], ['copy3_scale_cof']),
        helper.make_node('Where', ['copy3_scale_cof', 'pad_idx_i', 'copy3_scale_idx_raw'], ['copy3_scale_idx_flat']),
        helper.make_node('Gather', ['c2_pad', 'copy3_scale_idx_flat'], ['copy3_scale_seenib'], axis=0),
        helper.make_node('Cast', ['copy3_scale_seenib'], ['copy3_scale_seen_f'], to=10),
        helper.make_node('ReduceSum', ['copy3_scale_seen_f', 'axes0'], ['copy3_scale_cnt3'], keepdims=1),
        helper.make_node('And', ['copy3_scale_seenib', 'sq2_i'], ['copy3_scale_seen2']),
        helper.make_node('Cast', ['copy3_scale_seen2'], ['copy3_scale_seen2_f'], to=10),
        helper.make_node('ReduceSum', ['copy3_scale_seen2_f', 'axes0'], ['copy3_scale_cnt2'], keepdims=1),
        helper.make_node('Equal', ['copy3_scale_cnt3', 'nine_f16'], ['copy3_scale_is3']),
        helper.make_node('Equal', ['copy3_scale_cnt2', 'four_f16'], ['copy3_scale_is2']),
        helper.make_node('Where', ['copy3_scale_is2', 'two_i64', 'one_i64'], ['copy3_scale_s2']),
        helper.make_node('Where', ['copy3_scale_is3', 'three_i', 'copy3_scale_s2'], ['copy3_scale_scale']),
        helper.make_node('Mul', ['p2r0', 'copy3_scale_scale'], ['copy3_rdelta']),
        helper.make_node('Sub', ['copy3_target_r', 'copy3_rdelta'], ['copy3_sr']),
        helper.make_node('Mul', ['p2c0', 'copy3_scale_scale'], ['copy3_cdelta']),
        helper.make_node('Sub', ['copy3_target_c', 'copy3_cdelta'], ['copy3_sc']),
        # --- gather claims ---
        helper.make_node('Concat', ['copy1_sr', 'copy2_sr', 'copy3_sr'], ['copy_r'], axis=0),
        helper.make_node('Concat', ['copy1_sc', 'copy2_sc', 'copy3_sc'], ['copy_c'], axis=0),
        helper.make_node('Concat', ['copy1_scale_scale', 'copy2_scale_scale', 'copy3_scale_scale'], ['copy_s'], axis=0),
        helper.make_node('Concat', ['copy1_target_active', 'copy2_target_active', 'h17'], ['copy_a'], axis=0),
        helper.make_node('Cast', ['copy_r'], ['copy_rf'], to=10),
        helper.make_node('Cast', ['copy_c'], ['copy_cf'], to=10),
        helper.make_node('Cast', ['copy_s'], ['copy_sf'], to=10),
        helper.make_node('Cast', ['p1pos_rows'], ['p1rf'], to=10),
        helper.make_node('Cast', ['p1pos_cols'], ['p1cf'], to=10),
        helper.make_node('Reshape', ['p1rf', 'p1re_shape'], ['p1re']),
        helper.make_node('Reshape', ['p1cf', 'p1re_shape'], ['p1ce']),
        helper.make_node('Reshape', ['p1pos_present', 'p1re_shape'], ['p1pe']),
        helper.make_node('Greater', ['copy_s', 'one_i64'], ['copy_s_gt1']),
        helper.make_node('And', ['copy_a', 'copy_s_gt1'], ['copy_ge2']),
        helper.make_node('Equal', ['copy_s', 'three_i'], ['copy_s_eq3']),
        helper.make_node('And', ['copy_a', 'copy_s_eq3'], ['copy_eq3']),
        helper.make_node('Cast', ['copy_eq3'], ['copy_eq3_u8'], to=2),
        helper.make_node('ArgMax', ['copy_eq3_u8'], ['copy_eq3_idx_i64'], axis=0, keepdims=1),
        helper.make_node('Cast', ['copy_eq3_idx_i64'], ['copy_eq3_idx'], to=6),
        helper.make_node('Gather', ['copy_r', 'copy_eq3_idx'], ['copy_r3'], axis=0),
        helper.make_node('Gather', ['copy_c', 'copy_eq3_idx'], ['copy_c3'], axis=0),
        helper.make_node('Gather', ['copy_s', 'copy_eq3_idx'], ['copy_s3'], axis=0),
        helper.make_node('Gather', ['copy_eq3', 'copy_eq3_idx'], ['copy_a3'], axis=0),
        helper.make_node('Cast', ['copy_r3'], ['copy_r3f'], to=10),
        helper.make_node('Cast', ['copy_c3'], ['copy_c3f'], to=10),
        helper.make_node('Cast', ['copy_s3'], ['copy_s3f'], to=10),
        # --- blue paint: base cells (offset (0,0)) ---
        helper.make_node('Reshape', ['copy_rf', 'blue_base_cre_shape'], ['blue_base_cre']),
        helper.make_node('Reshape', ['copy_cf', 'blue_base_cre_shape'], ['blue_base_cce']),
        helper.make_node('Reshape', ['copy_sf', 'blue_base_cre_shape'], ['blue_base_cse']),
        helper.make_node('Reshape', ['copy_a', 'blue_base_cre_shape'], ['blue_base_ae']),
        helper.make_node('Mul', ['p1re', 'blue_base_cse'], ['blue_base_prs']),
        helper.make_node('Add', ['blue_base_cre', 'blue_base_prs'], ['blue_base_rbase']),
        helper.make_node('Mul', ['p1ce', 'blue_base_cse'], ['blue_base_pcs']),
        helper.make_node('Add', ['blue_base_cce', 'blue_base_pcs'], ['blue_base_cbase']),
        helper.make_node('And', ['p1pe', 'blue_base_ae'], ['blue_base_slot_live']),
        helper.make_node('Less', ['blue_base_cbase', 'zero_f16'], ['blue_base_clt0']),
        helper.make_node('Where', ['blue_base_clt0', 'zero_f16', 'blue_base_cbase'], ['blue_base_c0']),
        helper.make_node('Equal', ['blue_base_cbase', 'blue_base_c0'], ['blue_base_cok']),
        helper.make_node('And', ['blue_base_slot_live', 'blue_base_cok'], ['blue_base_live']),
        helper.make_node('Mul', ['blue_base_rbase', 'work_w_f16'], ['blue_base_rw']),
        helper.make_node('Add', ['blue_base_rw', 'blue_base_c0'], ['blue_base_flat3']),
        helper.make_node('Reshape', ['blue_base_live', 'blue_base_active_shape'], ['blue_base_active']),
        helper.make_node('Reshape', ['blue_base_flat3', 'blue_base_active_shape'], ['blue_base_flat_f']),
        # --- blue paint: scale>=2 extra offsets (0,1),(1,0),(1,1) ---
        helper.make_node('Reshape', ['copy_ge2', 'blue_base_cre_shape'], ['blue_x2_ae']),
        helper.make_node('Add', ['blue_base_cbase', 'blue_x2_dce'], ['blue_x2_cc']),
        helper.make_node('And', ['p1pe', 'blue_x2_ae'], ['blue_x2_slot_live']),
        helper.make_node('Less', ['blue_x2_cc', 'zero_f16'], ['blue_x2_clt0']),
        helper.make_node('Where', ['blue_x2_clt0', 'zero_f16', 'blue_x2_cc'], ['blue_x2_c0']),
        helper.make_node('Equal', ['blue_x2_cc', 'blue_x2_c0'], ['blue_x2_cok']),
        helper.make_node('And', ['blue_x2_slot_live', 'blue_x2_cok'], ['blue_x2_live']),
        helper.make_node('Add', ['blue_base_rw', 'blue_x2_dre21'], ['blue_x2_rw2']),
        helper.make_node('Add', ['blue_x2_rw2', 'blue_x2_c0'], ['blue_x2_flat3']),
        helper.make_node('Reshape', ['blue_x2_live', 'blue_x2_active_shape'], ['blue_x2_active']),
        helper.make_node('Reshape', ['blue_x2_flat3', 'blue_x2_active_shape'], ['blue_x2_flat_f']),
        # --- blue paint: scale==3 extra offsets (single eq3 copy) ---
        helper.make_node('Reshape', ['copy_r3f', 'blue_base_dre_shape'], ['blue_x3_cre']),
        helper.make_node('Reshape', ['copy_c3f', 'blue_base_dre_shape'], ['blue_x3_cce']),
        helper.make_node('Reshape', ['copy_s3f', 'blue_base_dre_shape'], ['blue_x3_cse']),
        helper.make_node('Reshape', ['copy_a3', 'blue_base_dre_shape'], ['blue_x3_ae']),
        helper.make_node('Mul', ['p1re', 'blue_x3_cse'], ['blue_x3_prs']),
        helper.make_node('Add', ['blue_x3_cre', 'blue_x3_prs'], ['blue_x3_rbase']),
        helper.make_node('Mul', ['p1ce', 'blue_x3_cse'], ['blue_x3_pcs']),
        helper.make_node('Add', ['blue_x3_cce', 'blue_x3_pcs'], ['blue_x3_cbase']),
        helper.make_node('Mul', ['blue_x3_rbase', 'work_w_f16'], ['blue_x3_rw1']),
        helper.make_node('Add', ['blue_x3_rw1', 'blue_x3_dre21'], ['blue_x3_rw2']),
        helper.make_node('Add', ['blue_x3_cbase', 'blue_x3_dce'], ['blue_x3_cc']),
        helper.make_node('And', ['p1pe', 'blue_x3_ae'], ['blue_x3_slot_live']),
        helper.make_node('Less', ['blue_x3_cc', 'zero_f16'], ['blue_x3_clt0']),
        helper.make_node('Where', ['blue_x3_clt0', 'zero_f16', 'blue_x3_cc'], ['blue_x3_c0']),
        helper.make_node('Equal', ['blue_x3_cc', 'blue_x3_c0'], ['blue_x3_cok']),
        helper.make_node('And', ['blue_x3_slot_live', 'blue_x3_cok'], ['blue_x3_live']),
        helper.make_node('Add', ['blue_x3_rw2', 'blue_x3_c0'], ['blue_x3_flat3']),
        helper.make_node('Reshape', ['blue_x3_live', 'blue_x3_active_shape'], ['blue_x3_active']),
        helper.make_node('Reshape', ['blue_x3_flat3', 'blue_x3_active_shape'], ['blue_x3_flat_f']),
        # --- scatter blue mask, pad to 30x30, passthrough output ---
        helper.make_node('Concat', ['blue_base_active', 'blue_x2_active', 'blue_x3_active'], ['blue_active'], axis=0),
        helper.make_node('Concat', ['blue_base_flat_f', 'blue_x2_flat_f', 'blue_x3_flat_f'], ['blue_flat_f'], axis=0),
        helper.make_node('Where', ['blue_active', 'blue_flat_f', 'fill_f16'], ['blue_safe_f']),
        helper.make_node('Cast', ['blue_safe_f'], ['blue_safe32'], to=6),
        helper.make_node('ScatterElements', ['false_work_flat', 'blue_safe32', 'blue_active'], ['blue_flat_mask'], axis=0),
        helper.make_node('Reshape', ['blue_flat_mask', 'blue_mask_shape'], ['blue_mask']),
        helper.make_node('Pad', ['blue_mask', 'mask_pads', 'zero_bool'], ['blue_mask30'], mode='constant'),
        helper.make_node('Where', ['blue_mask30', 'e1_vals', 'input'], ['output']),
    ]
    return model('task101_rebuild', nodes, inits, output_dtype=TensorProto.FLOAT, opset=13)
