"""Task 251 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('s0', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('e0', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAwAAAAAAAAADAAAAAAAAAA=')),
        tensor('s2', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('e2', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAAwAAAAAAAAADAAAAAAAAAA=')),
        tensor('ax', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAA=')),
        tensor('one', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('frame', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEyLCAxMiksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAQEBAQEBAQEBAQEBAAAAAAAAAAAAAAEBAAAAAAAAAAAAAAEBAAAAAAAAAAAAAAEBAAAAAAAAAAAAAAEBAAAAAAAAAAAAAAEBAAAAAAAAAAAAAAEBAAAAAAAAAAAAAAEBAAAAAAAAAAAAAAEBAAAAAAAAAAAAAAEBAAAAAAAAAAAAAAEBAQEBAQEBAQEBAQE=')),
        tensor('padv', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAAASAAAAAAAAABIAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 's0', 'e0', 'ax'], ['blk_f']),
        helper.make_node('Slice', ['input', 's2', 'e2', 'ax'], ['red_f']),
        helper.make_node('Cast', ['blk_f'], ['blk'], to=2),
        helper.make_node('Cast', ['red_f'], ['red'], to=2),
        helper.make_node('Sub', ['one', 'red'], ['nonred']),
        helper.make_node('Mul', ['frame', 'nonred'], ['ext0']),
        helper.make_node('MaxPool', ['ext0'], ['mp0'], kernel_shape=[3, 3], pads=[1, 1, 1, 1]),
        helper.make_node('Mul', ['mp0', 'nonred'], ['ext1']),
        helper.make_node('MaxPool', ['ext1'], ['mp1'], kernel_shape=[3, 3], pads=[1, 1, 1, 1]),
        helper.make_node('Mul', ['mp1', 'nonred'], ['ext2']),
        helper.make_node('MaxPool', ['ext2'], ['mp2'], kernel_shape=[3, 3], pads=[1, 1, 1, 1]),
        helper.make_node('Mul', ['mp2', 'nonred'], ['ext3']),
        helper.make_node('MaxPool', ['ext3'], ['mp3'], kernel_shape=[3, 3], pads=[1, 1, 1, 1]),
        helper.make_node('Mul', ['mp3', 'nonred'], ['ext4']),
        helper.make_node('MaxPool', ['ext4'], ['mp4'], kernel_shape=[3, 3], pads=[1, 1, 1, 1]),
        helper.make_node('Mul', ['mp4', 'nonred'], ['ext5']),
        helper.make_node('MaxPool', ['ext5'], ['mp5'], kernel_shape=[3, 3], pads=[1, 1, 1, 1]),
        helper.make_node('Mul', ['mp5', 'nonred'], ['ext6']),
        helper.make_node('MaxPool', ['ext6'], ['mp6'], kernel_shape=[3, 3], pads=[1, 1, 1, 1]),
        helper.make_node('Mul', ['mp6', 'nonred'], ['ext7']),
        helper.make_node('MaxPool', ['ext7'], ['mp7'], kernel_shape=[3, 3], pads=[1, 1, 1, 1]),
        helper.make_node('Sub', ['one', 'mp7'], ['notmp']),
        helper.make_node('Mul', ['nonred', 'notmp'], ['interior']),
        helper.make_node('Mul', ['blk', 'mp7'], ['out_blk']),
        helper.make_node('Concat', ['out_blk', 'interior', 'red'], ['small'], axis=1),
        helper.make_node('Pad', ['small', 'padv'], ['output'], mode='constant'),
    ]
    value_infos = [
    ]
    return model('task251_live_exact', nodes, inits, output_dtype=2, opset=17, value_infos=value_infos)
