"""Task 025 — exact source reconstruction of current live graph.

Generated by tools/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, node, tensor


def build(task):
    inits = [
        tensor('zero_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAA')),
        tensor('topk_k', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoEAAAAAAAAAA==')),
        tensor('onehot_depth', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoeAAAAAAAAAA==')),
        tensor('onehot_values', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPw==')),
        tensor('adj_onehot_values', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAA8')),
        tensor('one_i64', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
        tensor('color0_selector', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA')),
        tensor('map_bg', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAPAAAAAAAAAAAAAAAAAAAAAAAAA==')),
        tensor('map_bg_neg', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAwAAAAAAAAAAAAAAAAAAAAAAAAA==')),
        tensor('slot_projector', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEzLCA1KSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAPAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAPAAAADwAAAAAAAAAAAAAADwAAAAAAAAAAAAAADwAAAAAAAAAAAAAADwAAAA8AAAAAAAAAAAAAAA8AAAAAAAAAAAAAAA8AAAAAAAAAAAAAAA8')),
        tensor('arange30', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDMwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBBAAAgQQAAMEEAAEBBAABQQQAAYEEAAHBBAACAQQAAiEEAAJBBAACYQQAAoEEAAKhBAACwQQAAuEEAAMBBAADIQQAA0EEAANhBAADgQQAA6EE=')),
    ]
    nodes = [
        node('ReduceSum', ['input'], ['valid_col_count'], attrs=[('axes', [1, 2]), ('keepdims', 0)]),
        node('ReduceSum', ['input'], ['valid_row_count'], attrs=[('axes', [1, 3]), ('keepdims', 0)]),
        node('Greater', ['valid_col_count', 'zero_f'], ['valid_col_b']),
        node('Greater', ['valid_row_count', 'zero_f'], ['valid_row_b']),
        node('Unsqueeze', ['valid_col_b'], ['valid_col_b_u'], attrs=[('axes', [1])]),
        node('Unsqueeze', ['valid_row_b'], ['valid_row_b_u'], attrs=[('axes', [1])]),
        node('Cast', ['valid_col_b_u'], ['valid_col'], attrs=[('to', 10)]),
        node('Cast', ['valid_row_b_u'], ['valid_row'], attrs=[('to', 10)]),
        node('Einsum', ['input', 'color0_selector'], ['col_bg_count'], attrs=[('equation', 'bcrw,c->bw')]),
        node('Einsum', ['input', 'color0_selector'], ['row_bg_count'], attrs=[('equation', 'bcrw,c->br')]),
        node('Equal', ['col_bg_count', 'zero_f'], ['v_empty']),
        node('Equal', ['row_bg_count', 'zero_f'], ['h_empty']),
        node('And', ['v_empty', 'valid_col_b'], ['v_pos_b']),
        node('And', ['h_empty', 'valid_row_b'], ['h_pos_b']),
        node('Or', ['v_pos_b', 'h_pos_b'], ['line_pos_b']),
        node('Cast', ['line_pos_b'], ['line_pos_f'], attrs=[('to', 10)]),
        node('Cast', ['v_pos_b'], ['v_pos_u8'], attrs=[('to', 2)]),
        node('ReduceMax', ['v_pos_u8'], ['vertical_u8'], attrs=[('axes', [1]), ('keepdims', 1)]),
        node('Cast', ['vertical_u8'], ['vertical_orientation'], attrs=[('to', 9)]),
        node('Not', ['vertical_orientation'], ['horizontal_orientation']),
        node('Cast', ['vertical_orientation'], ['v_any'], attrs=[('to', 10)]),
        node('Cast', ['horizontal_orientation'], ['h_any'], attrs=[('to', 10)]),
        node('TopK', ['line_pos_f', 'topk_k'], ['top_values_3d', 'top_indices_3d'], attrs=[('axis', 1), ('largest', 1), ('sorted', 0)]),
        node('OneHot', ['top_indices_3d', 'onehot_depth', 'onehot_values'], ['pos_onehot'], attrs=[('axis', -1)]),
        node('Einsum', ['input', 'pos_onehot'], ['v_color_counts'], attrs=[('equation', 'bcrw,bsw->bcs')]),
        node('Einsum', ['input', 'pos_onehot'], ['h_color_counts'], attrs=[('equation', 'bcrw,bsr->bcs')]),
        node('Mul', ['top_values_3d', 'v_any'], ['v_active_color']),
        node('Cast', ['v_active_color'], ['v_active_color_f32'], attrs=[('to', 1)]),
        node('Mul', ['top_values_3d', 'h_any'], ['h_active_color']),
        node('Cast', ['h_active_color'], ['h_active_color_f32'], attrs=[('to', 1)]),
        node('Mul', ['v_color_counts', 'v_active_color_f32'], ['v_line_color_counts']),
        node('Mul', ['h_color_counts', 'h_active_color_f32'], ['h_line_color_counts']),
        node('Add', ['v_line_color_counts', 'h_line_color_counts'], ['line_color_counts']),
        node('Cast', ['top_indices_3d'], ['pos_f'], attrs=[('to', 1)]),
        node('Unsqueeze', ['pos_f'], ['pos_u'], attrs=[('axes', [2])]),
        node('Sub', ['arange30', 'pos_u'], ['pos_diff']),
        node('Sign', ['pos_diff'], ['signed_mask']),
        node('Cast', ['pos_onehot'], ['line16'], attrs=[('to', 10)]),
        node('Sub', ['top_indices_3d', 'one_i64'], ['idx_left']),
        node('Add', ['top_indices_3d', 'one_i64'], ['idx_right']),
        node('OneHot', ['idx_left', 'onehot_depth', 'adj_onehot_values'], ['adj_left'], attrs=[('axis', -1)]),
        node('OneHot', ['idx_right', 'onehot_depth', 'adj_onehot_values'], ['adj_right'], attrs=[('axis', -1)]),
        node('Cast', ['line_color_counts'], ['line_color16'], attrs=[('to', 10)]),
        node('Mul', ['top_values_3d', 'map_bg_neg'], ['bg_neg']),
        node('Add', ['line_color16', 'bg_neg'], ['map_terms']),
        node('Concat', ['map_bg', 'map_terms'], ['dyn_channel'], attrs=[('axis', 2)]),
        node('Einsum', ['input', 'signed_mask', 'v_line_color_counts'], ['signed_v_desc'], attrs=[('equation', 'bcrw,bsw,bcs->bsr')]),
        node('Cast', ['signed_v_desc'], ['signed_v'], attrs=[('to', 10)]),
        node('Einsum', ['input', 'signed_mask', 'h_line_color_counts'], ['signed_h_desc'], attrs=[('equation', 'bcrw,bsr,bcs->bsw')]),
        node('Cast', ['signed_h_desc'], ['signed_h'], attrs=[('to', 10)]),
        node('Sub', ['adj_right', 'adj_left'], ['signedadj']),
        node('Where', ['vertical_orientation', 'valid_row', 'line16'], ['line_row']),
        node('Where', ['vertical_orientation', 'line16', 'valid_col'], ['line_col']),
        node('Where', ['vertical_orientation', 'valid_col', 'valid_row'], ['adjacency_valid_axis']),
        node('Mul', ['adjacency_valid_axis', 'signedadj'], ['signedadj_axis']),
        node('Concat', ['valid_row', 'line_row', 'signed_v', 'signedadj_axis'], ['row_feat'], attrs=[('axis', 1)]),
        node('Concat', ['valid_col', 'line_col', 'signedadj_axis', 'signed_h'], ['col_feat'], attrs=[('axis', 1)]),
        node('Einsum', ['row_feat', 'col_feat', 'dyn_channel', 'slot_projector'], ['output'], attrs=[('equation', 'bpr,bpw,bos,ps->borw')]),
    ]
    value_infos = [
    ]
    return model('task025_line_position_fusion_u8', nodes, inits, output_dtype=10, opset=12, value_infos=value_infos, ir_version=10)
