"""Task 362 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('foreground_channels', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAgD8AAIA/AACAPwAAAAAAAIA/AACAPwAAgD8AAIA/')),
        tensor('coordinate_weight', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAqQOYa+AqwavpiTI71uxJE9U6k6Pjc4lj7GG88+qv8DP3FxID844zw//1RZP8XGdT9HHIk/KlWXPw6OpT/xxrM/1f/BP7k40D+ccd4/gKrsP2Pj+j8jjgRAlaoLQAbHEkB44xlA6v8gQFwcKEDOOC9AP1U2QLFxPUA=')),
        tensor('gray_index', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoFAAAA')),
        tensor('nineteen', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAJhB')),
        tensor('channel0_term', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAPAAAAAAAAAAAAAAAAAAAAAAAAA==')),
        tensor('term_base', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsIDMwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAPAA8ADwAPAA8ADwAPAA8ADwAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAA8ADwAPAA8ADwAPAA8ADwAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('zero_update', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAA==')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'foreground_channels', 'coordinate_weight'], ['row_float'], equation='nchw,c,h->n'),
        helper.make_node('Einsum', ['input', 'foreground_channels', 'coordinate_weight'], ['col_float'], equation='nchw,c,w->n'),
        helper.make_node('ReduceSum', ['input'], ['channel_counts'], axes=[2, 3], keepdims=0),
        helper.make_node('Gather', ['channel_counts', 'gray_index'], ['offset_f'], axis=1),
        helper.make_node('Add', ['row_float', 'offset_f'], ['target_row_float']),
        helper.make_node('Sub', ['col_float', 'offset_f'], ['target_col_float']),
        helper.make_node('Cast', ['target_row_float'], ['target_row'], to=6),
        helper.make_node('Cast', ['target_col_float'], ['target_col'], to=6),
        helper.make_node('ScatterElements', ['term_base', 'target_row', 'zero_update'], ['row_terms'], axis=1),
        helper.make_node('ScatterElements', ['term_base', 'target_col', 'zero_update'], ['col_terms'], axis=1),
        helper.make_node('Equal', ['channel_counts', 'nineteen'], ['color_channel']),
        helper.make_node('Unsqueeze', ['color_channel'], ['color_channel_3d'], axes=[1]),
        helper.make_node('Cast', ['color_channel_3d'], ['color_f16'], to=10),
        helper.make_node('Sub', ['channel0_term', 'color_f16'], ['background_channel']),
        helper.make_node('Concat', ['background_channel', 'color_f16'], ['channel_terms'], axis=1),
        helper.make_node('Einsum', ['channel_terms', 'row_terms', 'col_terms'], ['output'], equation='ntc,tr,tw->ncrw'),
    ]
    value_infos = [
    ]
    return model('task362_live_exact', nodes, inits, output_dtype=10, opset=12, value_infos=value_infos)
