"""Task 141 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('coord_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBBAAAgQQAAMEEAAEBBAABQQQAAYEEAAHBBAACAQQAAiEEAAJBBAACYQQAAoEEAAKhBAACwQQAAuEEAAMBBAADIQQAA0EEAANhBAADgQQAA6EE=')),
        tensor('row_idx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDMwLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAA8AEAAQgBEAEUARgBHAEiASABJgEkASoBKAEuASwBMQEyATMBMAE1ATYBNwE0ATkBOgE7ATgBPQE8=')),
        tensor('col_idx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDMwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAA8AEAAQgBEAEUARgBHAEiASABJgEkASoBKAEuASwBMQEyATMBMAE1ATYBNwE0ATkBOgE7ATgBPQE8=')),
        tensor('bad', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAfg==')),
        tensor('color_idx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBB')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input'], ['area_f'], equation='bchw->'),
        helper.make_node('Sqrt', ['area_f'], ['size_f']),
        helper.make_node('Cast', ['size_f'], ['size_h'], to=10),
        helper.make_node('Less', ['row_idx', 'size_h'], ['row_valid']),
        helper.make_node('Less', ['col_idx', 'size_h'], ['col_valid']),
        helper.make_node('Einsum', ['input', 'color_idx'], ['seed_color'], equation='bchw,qcyx->byx'),
        helper.make_node('Einsum', ['input', 'color_idx', 'coord_f'], ['seed_row_num'], equation='bchw,qcyx,h->byx'),
        helper.make_node('Einsum', ['input', 'color_idx', 'coord_f'], ['seed_col_num'], equation='bchw,qcyx,w->byx'),
        helper.make_node('Div', ['seed_row_num', 'seed_color'], ['seed_row_f']),
        helper.make_node('Div', ['seed_col_num', 'seed_color'], ['seed_col_f']),
        helper.make_node('Cast', ['seed_row_f'], ['seed_row'], to=10),
        helper.make_node('Cast', ['seed_col_f'], ['seed_col'], to=10),
        helper.make_node('Sub', ['row_idx', 'seed_row'], ['row_delta']),
        helper.make_node('Abs', ['row_delta'], ['dr']),
        helper.make_node('Sub', ['col_idx', 'seed_col'], ['col_delta']),
        helper.make_node('Abs', ['col_delta'], ['dc']),
        helper.make_node('Where', ['row_valid', 'dr', 'bad'], ['dr_in']),
        helper.make_node('Where', ['col_valid', 'dc', 'bad'], ['dc_in']),
        helper.make_node('Equal', ['dr_in', 'dc_in'], ['diag30']),
        helper.make_node('Equal', ['color_idx', 'seed_color'], ['color_hit']),
        helper.make_node('Cast', ['color_hit'], ['color_vec'], to=1),
        helper.make_node('Where', ['diag30', 'color_vec', 'input'], ['output']),
    ]
    value_infos = [
    ]
    return model('task141_live_exact', nodes, inits, output_dtype=1, opset=12, value_infos=value_infos)
