"""Task 271 — exact source reconstruction of current live graph.

Generated by tools/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, node, tensor


def build(task):
    inits = [
        tensor('hash_channel', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAALBBAACIQQAAAEEAALhBAADIQQAAIEEAACBBAAAAQgAAQEAAALBB')),
        tensor('hash_row', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAGBBAACAQQAA2EEAAPhBAACwQQAA6EEAAMBBAACoQQAAiEEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('hash_col', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAMBBAABQQQAAQEEAAMBAAAAQQQAAuEEAAMhBAABQQQAA+EEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('bucket_count_i32', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogAAAA')),
        tensor('slot_count_i32', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAphAQAA')),
        tensor('seven_i32', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoHAAAA')),
        tensor('displacement_i32', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMyLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIApSAAAAaAAAAC0AAAABAAAAEQAAAEMBAAAZAAAACwAAACQAAAA9AAAAZAAAAAgAAAAJAAAA8AAAAGsAAAAhAQAAAwAAAJkAAAApAAAANgEAADkAAAAUAAAAAAAAAFUAAAA0AAAAaAAAAAAAAAAEAAAABgAAACIAAADzAAAAbgAAAA==')),
        tensor('lane_divisors_i64', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDcsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAACAAAAAAAAAAAEAAAAAAAAAAAIAAAAAAAAAAAQAAAAAAAAAAAgAAAAAAAAAABAAA==')),
        tensor('packed_payloads_i64', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDUxLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA/n4HUB+Ad3/sA9gLoPt+AADc3//q1y/v97vz+5saAAB8A/jr/+9f3gDkB/APwHf+d1ZfD8AUAO4BvO/vGsArALz+BQDAPwDfAbzffnfnfb4///zXHwAA3e90bL///mf85d6o8esvAADy798PAAAAvlTfB/DG/2v9v3b/t7tuf/P+dYwPAAAAALzfB9Dz934Avrv9/f19N+693gbQ8X1f7zG5+gTAPwDkAfi/7+bffgD6ez4PYOkt3gHsB/Bv/zffe//F97f/fgDeAwBwvzsA7791BwCg30pH/hkHUBHAQgAAPP3bbu973wH0B/AXwB8A9t8HAECTRv/uAyD37DsA758CAPBs817PAfQG8A8AAPb/3d8PAMB9s879A9D6dz7fAPy9/vsLAADuf/b/93d1v2/3O/P4uz+z7//t//cvALP9uwKwHUB/97/z27/7PgC+//XaB+APAFYB9L9/DsBvAPo9BPD3PQD/+qvVvd//Xy7+/b7/vX9j4np92qfG6z/7f08HsMM9OvR6fv/+2/g/+q1rBQAAAAA=')),
        tensor('payload_masks', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPHUyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDMsIDMpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAIABAAIABAAIABAAIAAAAE=')),
        tensor('two_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoC')),
        tensor('zero_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('one_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('render_weight_signed', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCAxLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQAAAAAAAP8A')),
    ]
    nodes = [
        node('Einsum', ['input', 'hash_channel', 'hash_row', 'hash_col'], ['hash_f32'], attrs=[('equation', 'bcrs,c,r,s->b')]),
        node('Cast', ['hash_f32'], ['hash_i32'], attrs=[('to', 6)]),
        node('Mod', ['hash_i32', 'bucket_count_i32'], ['bucket_i32']),
        node('Div', ['hash_i32', 'bucket_count_i32'], ['secondary_i32']),
        node('Gather', ['displacement_i32', 'bucket_i32'], ['displacement_value_i32']),
        node('Add', ['secondary_i32', 'displacement_value_i32'], ['slot_pre_i32']),
        node('Mod', ['slot_pre_i32', 'slot_count_i32'], ['slot_i32']),
        node('Div', ['slot_i32', 'seven_i32'], ['word_index_i32']),
        node('Mod', ['slot_i32', 'seven_i32'], ['lane_i32']),
        node('Gather', ['lane_divisors_i64', 'lane_i32'], ['lane_divisor_i64']),
        node('Gather', ['packed_payloads_i64', 'word_index_i32'], ['packed_word_i64']),
        node('Div', ['packed_word_i64', 'lane_divisor_i64'], ['quotient_i64']),
        node('Cast', ['quotient_i64'], ['encoded_u16'], attrs=[('to', 4)]),
        node('BitwiseAnd', ['encoded_u16', 'payload_masks'], ['masked_u16']),
        node('Cast', ['masked_u16'], ['payload_bits'], attrs=[('to', 9)]),
        node('Where', ['payload_bits', 'two_u8', 'zero_u8'], ['blue2']),
        node('ConvInteger', ['blue2', 'render_weight_signed', 'one_u8'], ['output'], attrs=[('kernel_shape', [1, 1]), ('pads', [0, 0, 27, 27])]),
    ]
    value_infos = [
        helper.make_tensor_value_info('hash_f32', 1, [1]),
        helper.make_tensor_value_info('hash_i32', 6, [1]),
        helper.make_tensor_value_info('bucket_i32', 6, [1]),
        helper.make_tensor_value_info('secondary_i32', 6, [1]),
        helper.make_tensor_value_info('displacement_value_i32', 6, [1]),
        helper.make_tensor_value_info('slot_pre_i32', 6, [1]),
        helper.make_tensor_value_info('slot_i32', 6, [1]),
        helper.make_tensor_value_info('word_index_i32', 6, [1]),
        helper.make_tensor_value_info('lane_i32', 6, [1]),
        helper.make_tensor_value_info('lane_divisor_i64', 7, [1]),
        helper.make_tensor_value_info('packed_word_i64', 7, [1]),
        helper.make_tensor_value_info('quotient_i64', 7, [1]),
        helper.make_tensor_value_info('encoded_u16', 4, [1]),
        helper.make_tensor_value_info('masked_u16', 4, [1, 1, 3, 3]),
        helper.make_tensor_value_info('payload_bits', 9, [1, 1, 3, 3]),
        helper.make_tensor_value_info('blue2', 2, [1, 1, 3, 3]),
    ]
    return model('task271_hash_chd_payload', nodes, inits, output_dtype=6, opset=18, value_infos=value_infos, ir_version=10)
