#!/usr/bin/env python3
"""Generate source-owned exact builders from current live ONNX graphs.

This is a control-recovery tool.  It does not optimize a graph; it converts the
current deployed `submission/overfit_nets/taskNNN.onnx` graph (or `--net-dir`)
into Python source that owns the nodes and initializers via `src.custom._exact`,
so later semantic rewrites can be compared against a source-controlled live
baseline instead of an opaque ONNX artifact.

Default output goes to `candidates/generated_exact_sources/taskNNN.py`.  Use
`--write-src` only when intentionally replacing `src/custom/taskNNN.py`.
"""

from __future__ import annotations

import argparse
import base64
from pathlib import Path
from typing import Any

import onnx
from onnx import TensorProto


ROOT = Path(__file__).resolve().parents[1]
DEPLOYED = ROOT / "submission" / "overfit_nets"
GENERATED = ROOT / "candidates" / "generated_exact_sources"
CUSTOM = ROOT / "src" / "custom"
NET_DIR = DEPLOYED  # overridden by --net-dir


def tensor_b64(tensor: onnx.TensorProto) -> str:
    return base64.b64encode(tensor.SerializeToString()).decode("ascii")


def attr_value(attr: onnx.AttributeProto) -> Any:
    value = onnx.helper.get_attribute_value(attr)
    if isinstance(value, bytes):
        return value.decode("utf-8")
    if isinstance(value, tuple):
        return list(value)
    return value


def format_node_kwargs(node: onnx.NodeProto) -> str:
    pieces = []
    if node.name:
        pieces.append(f"name={node.name!r}")
    if node.domain:
        pieces.append(f"domain={node.domain!r}")
    attrs = []
    for attr in node.attribute:
        value = attr_value(attr)
        if isinstance(value, onnx.TensorProto):
            raise ValueError(f"tensor attribute is not supported yet: {node.name or node.op_type}.{attr.name}")
        if isinstance(value, onnx.GraphProto):
            raise ValueError(f"graph attribute is not supported yet: {node.name or node.op_type}.{attr.name}")
        attrs.append((attr.name, value))
    if attrs:
        pieces.append(f"attrs={attrs!r}")
    return (", " + ", ".join(pieces)) if pieces else ""


def output_dtype(model: onnx.ModelProto) -> int:
    if not model.graph.output:
        return TensorProto.FLOAT
    tt = model.graph.output[0].type.tensor_type
    return tt.elem_type if tt.elem_type else TensorProto.FLOAT


def default_opset(model: onnx.ModelProto) -> int:
    for opset in model.opset_import:
        if opset.domain in ("", "ai.onnx"):
            return int(opset.version)
    return 11


def model_kwargs(model: onnx.ModelProto) -> str:
    """Preserve populated model-level fields supported by ``src.custom._exact``."""

    pieces = [f"ir_version={int(model.ir_version)}"]
    if model.producer_name:
        pieces.append(f"producer_name={model.producer_name!r}")
    return ", ".join(pieces)


def vi_expr(vi: onnx.ValueInfoProto) -> str | None:
    """Return Python source for a tensor value_info, or None if unsupported."""

    if not vi.type.HasField("tensor_type"):
        return None
    tt = vi.type.tensor_type
    if not tt.elem_type or not tt.HasField("shape"):
        return None
    dims: list[int] = []
    for dim in tt.shape.dim:
        if not dim.HasField("dim_value") or dim.dim_value <= 0:
            return None
        dims.append(int(dim.dim_value))
    return f"helper.make_tensor_value_info({vi.name!r}, {int(tt.elem_type)}, {dims!r})"


def generate(task_num: int, *, package_relative: bool) -> str:
    model = onnx.load(NET_DIR / f"task{task_num:03d}.onnx")
    exact_import = "from ._exact import model, node, tensor_b64" if package_relative else "from src.custom._exact import model, node, tensor_b64"
    lines: list[str] = [
        f'"""Task {task_num:03d} — exact source reconstruction of current live graph.',
        "",
        "Generated by tools/live_to_exact_source.py.",
        "This owns the live ONNX graph in Python source; it is a control baseline,",
        "not a semantic optimization.",
        '"""',
        "from onnx import TensorProto, helper",
        exact_import,
        "",
        "",
        "def build(task):",
        "    inits = [",
    ]
    for init in model.graph.initializer:
        lines.append(f"        tensor_b64({tensor_b64(init)!r}),")
    lines.extend(["    ]", "    nodes = ["])
    for graph_node in model.graph.node:
        kwargs = format_node_kwargs(graph_node)
        lines.append(
            f"        node({graph_node.op_type!r}, {list(graph_node.input)!r}, {list(graph_node.output)!r}{kwargs}),"
        )
    lines.extend(["    ]", "    value_infos = ["])
    for vi in model.graph.value_info:
        expr = vi_expr(vi)
        if expr is not None:
            lines.append(f"        {expr},")
    lines.extend(
        [
            "    ]",
            f"    return model({model.graph.name!r}, nodes, inits, output_dtype={output_dtype(model)}, opset={default_opset(model)}, value_infos=value_infos, {model_kwargs(model)})",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    global NET_DIR
    parser = argparse.ArgumentParser()
    parser.add_argument("tasks", nargs="+", type=int)
    parser.add_argument("--write-src", action="store_true", help="write to src/custom/taskNNN.py instead of candidates/generated_exact_sources")
    parser.add_argument("--net-dir", type=Path, default=DEPLOYED, help="directory of taskNNN.onnx graphs to convert (default: deployed submission/overfit_nets)")
    args = parser.parse_args()
    NET_DIR = args.net_dir

    out_dir = CUSTOM if args.write_src else GENERATED
    out_dir.mkdir(parents=True, exist_ok=True)
    for task_num in args.tasks:
        out = out_dir / f"task{task_num:03d}.py"
        out.write_text(generate(task_num, package_relative=args.write_src))
        print(out)


if __name__ == "__main__":
    main()
